import write_bracket_html

_WEIGHTS = {
    "bantam": (43, 46, 49, 52, 55, 58, 62, 66, 70, 76, 84, 95, 120),
    "intermediate": (55, 59, 64, 69, 74, 79, 84, 90, 98, 108, 122, 148, 177),
    "novice": (60, 64, 69, 74, 80, 86, 93, 100, 108, 116, 125, 134, 154, 178, 215),
    "senior": (
        74,
        79,
        84,
        90,
        96,
        103,
        110,
        118,
        126,
        135,
        144,
        154,
        164,
        176,
        188,
        215,
        275,
    ),
    "bantam_girls": (45, 50, 55, 61, 67, 74, 85, 95, 115),
    "intermediate_girls": (53, 57, 62, 67, 72, 77, 82, 88, 95, 115, 135),
    "novice_girls": (63, 68, 74, 80, 85, 90, 96, 102, 108, 115, 125, 140, 185),
    "senior_girls": (
        75,
        80,
        85,
        90,
        95,
        100,
        105,
        110,
        115,
        120,
        125,
        130,
        135,
        145,
        185,
        240,
    ),
}


def main() -> None:
    static_root = write_bracket_html.HERE.parent / "static" / "static"
    match_data_rows: list[write_bracket_html.MatchData] = [
        write_bracket_html.MatchData(
            match_slot_id=1,
            match_slot="championship_r32_01",
            top_name="Wrestler 1",
            top_team="Team 1",
            bottom_name=None,
            bottom_team=None,
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=True,
            result="Bye",
        ),
        write_bracket_html.MatchData(
            match_slot_id=2,
            match_slot="championship_r32_02",
            top_name="Wrestler 2",
            top_team="Team 2",
            bottom_name="Wrestler 3",
            bottom_team="Team 3",
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=None,
            result="",
        ),
        write_bracket_html.MatchData(
            match_slot_id=3,
            match_slot="championship_r32_03",
            top_name="Wrestler 4",
            top_team="Team 4",
            bottom_name=None,
            bottom_team=None,
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=True,
            result="Bye",
        ),
        write_bracket_html.MatchData(
            match_slot_id=4,
            match_slot="championship_r32_04",
            top_name="Wrestler 5",
            top_team="Team 5",
            bottom_name="Wrestler 6",
            bottom_team="Team 6",
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=None,
            result="",
        ),
        write_bracket_html.MatchData(
            match_slot_id=5,
            match_slot="championship_r32_05",
            top_name="Wrestler 7",
            top_team="Team 7",
            bottom_name=None,
            bottom_team=None,
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=True,
            result="Bye",
        ),
        write_bracket_html.MatchData(
            match_slot_id=6,
            match_slot="championship_r32_06",
            top_name="Wrestler 8",
            top_team="Team 8",
            bottom_name="Wrestler 9",
            bottom_team="Team 9",
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=None,
            result="",
        ),
        write_bracket_html.MatchData(
            match_slot_id=7,
            match_slot="championship_r32_07",
            top_name="Wrestler 10",
            top_team="Team 10",
            bottom_name=None,
            bottom_team=None,
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=True,
            result="Bye",
        ),
        write_bracket_html.MatchData(
            match_slot_id=8,
            match_slot="championship_r32_08",
            top_name="Wrestler 11",
            top_team="Team 11",
            bottom_name="Wrestler 12",
            bottom_team="Team 12",
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=None,
            result="",
        ),
        write_bracket_html.MatchData(
            match_slot_id=9,
            match_slot="championship_r32_09",
            top_name="Wrestler 13",
            top_team="Team 13",
            bottom_name=None,
            bottom_team=None,
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=True,
            result="Bye",
        ),
        write_bracket_html.MatchData(
            match_slot_id=10,
            match_slot="championship_r32_10",
            top_name="Wrestler 14",
            top_team="Team 14",
            bottom_name="Wrestler 15",
            bottom_team="Team 15",
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=None,
            result="",
        ),
        write_bracket_html.MatchData(
            match_slot_id=11,
            match_slot="championship_r32_11",
            top_name="Wrestler 16",
            top_team="Team 16",
            bottom_name=None,
            bottom_team=None,
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=True,
            result="Bye",
        ),
        write_bracket_html.MatchData(
            match_slot_id=12,
            match_slot="championship_r32_12",
            top_name="Wrestler 17",
            top_team="Team 17",
            bottom_name="Wrestler 18",
            bottom_team="Team 18",
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=None,
            result="",
        ),
        write_bracket_html.MatchData(
            match_slot_id=13,
            match_slot="championship_r32_13",
            top_name="Wrestler 19",
            top_team="Team 19",
            bottom_name=None,
            bottom_team=None,
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=True,
            result="Bye",
        ),
        write_bracket_html.MatchData(
            match_slot_id=14,
            match_slot="championship_r32_14",
            top_name="Wrestler 20",
            top_team="Team 20",
            bottom_name="Wrestler 21",
            bottom_team="Team 21",
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=None,
            result="",
        ),
        write_bracket_html.MatchData(
            match_slot_id=15,
            match_slot="championship_r32_15",
            top_name="Wrestler 22",
            top_team="Team 22",
            bottom_name=None,
            bottom_team=None,
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=True,
            result="Bye",
        ),
        write_bracket_html.MatchData(
            match_slot_id=16,
            match_slot="championship_r32_16",
            top_name="Wrestler 23",
            top_team="Team 23",
            bottom_name="Wrestler 24",
            bottom_team="Team 24",
            bout_number=None,
            top_score=None,
            bottom_score=None,
            top_win=None,
            result="",
        ),
    ]
    for division, weights in _WEIGHTS.items():
        for weight in weights:
            config = write_bracket_html.TournamentConfig(
                id=54, year=2026, wrestleback_type="full", medalist_count=8
            )
            write_bracket_html._render_bracket_html(
                static_root,
                config,
                division,
                weight,
                match_data_rows,
                _hazmat_skip_backside=True,
            )

    write_bracket_html._render_brackets_year_html(static_root, 2026, _WEIGHTS)


if __name__ == "__main__":
    main()
