[project]
name = "ikwf-history"
version = "0.0.1"
description = "IKWF History: collecting old brackets and building website"
readme = "README.md"
requires-python = "== 3.13.3"
dependencies = ["beautifulsoup4", "chardet", "ipython", "pydantic", "selenium"]
