# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
TEAM_ACRONYM_MAPPING = {
    "ABC": "TODO",
    "ACE": "TODO",
    "AGO": "TODO",
    "AJP": "TODO",
    "ANI": "TODO",
    "ARL": "TODO",
    "BAT": "TODO",
    "BB": "TODO",
    "BDGR": "TODO",
    "BELV": "TODO",
    "BEN": "TODO",
    "BHK": "TODO",
    "BIS": "TODO",
    "BLD": "TODO",
    "BLM": "TODO",
    "BMH": "TODO",
    "BRL": "TODO",
    "CARY": "TODO",
    "CCR": "TODO",
    "CENT": "TODO",
    "CHAR": "TODO",
    "CKW": "TODO",
    "CLD": "TODO",
    "CLW": "TODO",
    "CMB": "TODO",
    "CMW": "TODO",
    "COL": "TODO",
    "CRB": "TODO",
    "CRST": "TODO",
    "CWD": "TODO",
    "DAK": "TODO",
    "DEK": "TODO",
    "DGC": "TODO",
    "DIX": "TODO",
    "DUN": "TODO",
    "EDW": "TODO",
    "EFF": "TODO",
    "ELM": "TODO",
    "EPG": "TODO",
    "ERIE": "TODO",
    "FEN": "TODO",
    "FISH": "TODO",
    "FOX": "TODO",
    "FRR": "TODO",
    "FTT": "TODO",
    "FWC": "TODO",
    "FYW": "TODO",
    "GCW": "TODO",
    "GE": "TODO",
    "GED": "TODO",
    "GEJR": "TODO",
    "GEN": "TODO",
    "GLD": "TODO",
    "GOM": "TODO",
    "GPD": "TODO",
    "HBD": "TODO",
    "HBG": "TODO",
    "HCX": "TODO",
    "HILL": "TODO",
    "HOF": "TODO",
    "HON": "TODO",
    "HPDT": "TODO",
    "HPLG": "TODO",
    "HPN": "TODO",
    "HRD": "TODO",
    "HRL": "TODO",
    "HRR": "TODO",
    "HUR": "TODO",
    "IMP": "TODO",
    "IRN": "TODO",
    "JJS": "TODO",
    "JRC": "TODO",
    "JRG": "TODO",
    "JRV": "TODO",
    "KNGT": "TODO",
    "LAN": "TODO",
    "LEM": "TODO",
    "LIM": "TODO",
    "LION": "TODO",
    "LIT": "TODO",
    "LIW": "TODO",
    "LJP": "TODO",
    "LKP": "TODO",
    "LLC": "TODO",
    "LLF": "TODO",
    "LLH": "TODO",
    "LLRB": "TODO",
    "LLRS": "TODO",
    "LPC": "TODO",
    "LWW": "TODO",
    "MAT": "TODO",
    "MCC": "TODO",
    "MDWA": "TODO",
    "MEN": "TODO",
    "MET": "TODO",
    "MFV": "TODO",
    "MIN": "TODO",
    "MIY": "TODO",
    "MLB": "TODO",
    "MLM": "TODO",
    "MNE": "TODO",
    "MOL": "TODO",
    "MRS": "TODO",
    "MSK": "TODO",
    "MST": "TODO",
    "MTP": "TODO",
    "MTV": "TODO",
    "MTZ": "TODO",
    "MUR": "TODO",
    "MWC": "TODO",
    "MYW": "TODO",
    "NAP": "TODO",
    "NDW": "TODO",
    "OFW": "TODO",
    "OKW": "TODO",
    "OLP": "TODO",
    "OLW": "TODO",
    "OPP": "TODO",
    "OSW": "TODO",
    "PAL": "TODO",
    "PCCH": "TODO",
    "PCUB": "TODO",
    "PLNF": "TODO",
    "PNP": "TODO",
    "PNRD": "TODO",
    "POLO": "TODO",
    "PON": "TODO",
    "PRY": "TODO",
    "PVP": "TODO",
    "QUI": "TODO",
    "RCH": "TODO",
    "RCK": "TODO",
    "RDW": "TODO",
    "REN": "TODO",
    "RJR": "TODO",
    "RKFD": "TODO",
    "RKI": "TODO",
    "ROC": "TODO",
    "ROM": "TODO",
    "RRDG": "TODO",
    "RRT": "TODO",
    "RVB": "TODO",
    "SAU": "TODO",
    "SCE": "TODO",
    "SCN": "TODO",
    "SEN": "TODO",
    "SHM": "TODO",
    "SHR": "TODO",
    "SIUT": "TODO",
    "SJO": "TODO",
    "SKV": "TODO",
    "SLB": "TODO",
    "SOT": "TODO",
    "SPI": "TODO",
    "SPR": "TODO",
    "SRN": "TODO",
    "SV": "TODO",
    "SYC": "TODO",
    "TAY": "TODO",
    "TIG": "TODO",
    "TLK": "TODO",
    "TOM": "TODO",
    "TPB": "TODO",
    "TRI": "TODO",
    "TRV": "TODO",
    "TTT": "TODO",
    "TWW": "TODO",
    "UNI": "TODO",
    "VAN": "TODO",
    "VER": "TODO",
    "VIT": "TODO",
    "VLC": "TODO",
    "VPYW": "TODO",
    "WAR": "TODO",
    "WAS": "TODO",
    "WAUB": "TODO",
    "WAUK": "TODO",
    "WES": "TODO",
    "WHT": "TODO",
    "WLP": "TODO",
    "WRF": "TODO",
    "WTG": "TODO",
    "XTR": "TODO",
    "YKV": "TODO",
}
TEAM_NAME_MAPPING = {
    "ACES WC": -90501,
    "ALEDO BEAR COUNTRY WC": -90501,
    "ALLEMAN JR PIONEERS": -90501,
    "ARGENTA/OREANA KIDS CLUB": -90501,
    "ARLINGTON CARDINALS": -90501,
    "BADGER WC": -90501,
    "BATAVIA": -90501,
    "BATAVIA PINNERS": -90501,
    "BELLEVILLE LITTLE DEVILS": -90501,
    "BELVIDERE BANDITS": -90501,
    "BENTON JR WC": -90501,
    "BETHALTO BULLS WC": -90501,
    "BISMARCK HENNING WRESTLING CLUB": -90501,
    "BISON WC": -90501,
    "BLACKHAWK WC": -90501,
    "BLOOMINGTON RAIDER WC": -90501,
    "BRAWLERS WC": -90501,
    "CALUMET MEMORIAL PD WOLVERINES": -90501,
    "CARBONDALE WC": -90501,
    "CARY JR TROJAN MATMEN": -90501,
    "CENTRAL WRESTLING CLUB": -90501,
    "CHAMPAIGN KIDS WRESTLING": -90501,
    "CHICAGO CRUSADERS": -90501,
    "CHICAGO WOLVES DEN": -90501,
    "CLIPPER WC": -90501,
    "COLLINSVILLE RAIDERS": -90501,
    "CROSSTOWN CRUSHERS": -90501,
    "CRYSTAL LAKE WIZARDS": -90501,
    "CUMBERLAND YOUTH WC": -90501,
    "DAKOTA WC": -90501,
    "DEKALB WC": -90501,
    "DIXON WC": -90501,
    "DOWNERS GROVE COUGARS": -90501,
    "DUNDEE HIGHLANDERS": -90501,
    "EDWARDSVILLE WC": -90501,
    "EFFINGHAM JUNIOR WRESTLING TEAM": -90501,
    "EL PASO/GRIDLEY WC": -90501,
    "ELMHURST JR. DUKES": -90501,
    "ERIE MIDDLE SCHOOL WC": -90501,
    "FAIRMONT ROUGH RIDERS": -90501,
    "FALCON WRESTLING CLUB": -90501,
    "FALCON YOUTH WC": -90501,
    "FENWICK FALCONS WC": -90501,
    "FIGHTIN TITAN WC": -90501,
    "FISHER WC": -90501,
    "FOX VALLEY WC": -90501,
    "GC JR WARRIORS": -90501,
    "GENESEO SPIDER WC": -90501,
    "GLADIATORS": -90501,
    "GLEN ELLYN DUNGEON WC": -90501,
    "GLENBARD EAST JR RAMS": -90501,
    "GOLDEN EAGLES": -90501,
    "GOMEZ WRESTLING ACADEMY": -90501,
    "GRAPPLIN' DEVILS WRESTLING CLUB": -90501,
    "HARLEM COUGARS": -90501,
    "HARVEY PARK DIST TWISTERS": -90501,
    "HECOX TEAM BENAIAH": -90501,
    "HERRIN JUNIOR WC": -90501,
    "HIGHLAND BULLDOG JR WC": -90501,
    "HIGHLAND PARK LITTLE GIANTS": -90501,
    "HILLTOPPERS WC": -90501,
    "HINSDALE RED DEVIL WC": -90501,
    "HOFFMAN ESTATES WC": -90501,
    "HONONEGAH KIDS WC": -90501,
    "HOOPESTON AREA WC": -90501,
    "IMPACT WC": -90501,
    "IRON MAN": -90501,
    "JOLIET JUNIOR STEELMEN": -90501,
    "JUNIOR GATORS WC": -90501,
    "JUNIOR VIKINGS": -90501,
    "KNIGHTS WRESTLING": -90501,
    "L-P CRUNCHING CAVS": -90501,
    "LAKELAND PREDATORS": -90501,
    "LANCER WC": -90501,
    "LEMONT BEARS WC": -90501,
    "LIMESTONE YOUTH WC": -90501,
    "LINCOLN-WAY WC": -90501,
    "LIONHEART INTENSE WRESTLING": -90501,
    "LITCHFIELD KIDS WRESTLING": -90501,
    "LITTLE CELTIC WC": -90501,
    "LITTLE FALCONS WC": -90501,
    "LITTLE HUSKIE WC": -90501,
    "LITTLE REDBIRD WC": -90501,
    "LITTLE REDSKINS WC": -90501,
    "LOCKPORT JR PORTERS WC": -90501,
    "M-S KIDS CLUB": -90501,
    "MACOMB LITTLE BOMBERS": -90501,
    "MAD DOG WRESTLING ACADEMY": -90501,
    "MAINE EAGLES WC": -90501,
    "MARENGO INDIANS YOUTH WRESTLING": -90501,
    "MARTINEZ FOX VALLEY ELITE": -90501,
    "MATTOON YOUTH WC": -90501,
    "MCLEAN COUNTY WC": -90501,
    "METAMORA KIDS WC": -90501,
    "MIDWEST CENTRAL YOUTH": -90501,
    "MINOOKA LITTLE INDIANS": -90501,
    "MOLINE WC": -90501,
    "MORRISON STALLIONS WC": -90501,
    "MORTON LITTLE MUSTANGS": -90501,
    "MORTON YOUTH WRESTLING": -90501,
    "MT. PULASKI WC": -90501,
    "MT. VERNON LIONS": -90501,
    "MT. ZION WC": -90501,
    "MURPHYSBORO WRESTLING": -90501,
    "MUSTANG WC": -90501,
    "NAPERVILLE WC": -90501,
    "NOTRE DAME WRESTLING": -90501,
    "O'FALLON LITTLE PANTHERS": -90501,
    "OAK FOREST WARRIORS": -90501,
    "OAK LAWN P.D. WILDCATS": -90501,
    "OAKWOOD WC": -90501,
    "ORLAND PARK PIONEERS": -90501,
    "OSWEGO PANTHERS": -90501,
    "PANTHER CUB WRESTLING CLUB": -90501,
    "PANTHER POWERHOUSE WC": -90501,
    "PANTHER/REDHAWK WC": -90501,
    "PEORIA RAZORBACKS YOUTH WC": -90501,
    "PLAINFIELD WC": -90501,
    "POLO WC": -90501,
    "PONTIAC PYTHONS": -90501,
    "PRAIRIE CENTRAL-CHENOA HAWKS": -90501,
    "PROVISO POWERHOUSE WC": -90501,
    "QUINCY WC": -90501,
    "RICH RATTLERS WC": -90501,
    "RICHMOND WRESTLING CLUB": -90501,
    "RIVERBEND WC": -90501,
    "RIVERDALE JR. RAMS WC": -90501,
    "ROAD WARRIORS": -90501,
    "ROCHESTER WC": -90501,
    "ROCK ISLAND WC": -90501,
    "ROMEOVILLE WC": -90501,
    "SAUK VALLEY WRESTLING CLUB": -90501,
    "SAUKEE YOUTH WC": -90501,
    "SCN YOUTH WC": -90501,
    "SENECA IRISH CADETS": -90501,
    "SHAMROCK WC": -90501,
    "SHARKS WC": -90501,
    "SHELBYVILLE JR RAMS WRESTLING": -90501,
    "SJO SPARTAN YOUTH WC": -90501,
    "SONS OF THUNDER": -90501,
    "SPIDER WC": -90501,
    "SPRINGFIELD CAPITAL KIDS WRESTLING": -90501,
    "ST. CHARLES EAST WC": -90501,
    "STILLMAN VALLEY WC": -90501,
    "STOCKTON RENEGADES": -90501,
    "SYCAMORE WC": -90501,
    "TAYLORVILLE WC": -90501,
    "TEAM WEST WOLVES": -90501,
    "TIGER WC": -90501,
    "TIGERTOWN TANGLERS": -90501,
    "TINLEY PARK BULLDOGS": -90501,
    "TOMCAT WC": -90501,
    "TREVIAN WC": -90501,
    "TRIAD LITTLE KNIGHTS": -90501,
    "UNITY WC": -90501,
    "VANDALIA JR WRESTLING": -90501,
    "VERMILION VALLEY ELITE": -90501,
    "VILLA LOMBARD COUGARS": -90501,
    "VILLA PARK YOUNG WARRIORS": -90501,
    "VITTUM CATS": -90501,
    "WARRENSBURG WC": -90501,
    "WASHINGTON JR PANTHERS": -90501,
    "WAUKEGAN YOUTH WC": -90501,
    "WESTVILLE YOUTH WC": -90501,
    "WHEATON TIGER WC": -90501,
    "WOLFPAK WC": -90501,
    "WRESTLING FACTORY": -90501,
    "XTREME WRESTLING": -90501,
    "YORKVILLE WRESTLING CLUB": -90501,
}


def main():
    with open(HERE / "extracted.2006.json") as file_obj:
        extracted = json.load(file_obj)

    all_teams = set()
    for weight in extracted:
        for match in weight["matches"]:
            top_competitor = match["top_competitor"]
            if top_competitor is not None:
                all_teams.add(top_competitor["team"])

            bottom_competitor = match["bottom_competitor"]
            if bottom_competitor is not None:
                all_teams.add(bottom_competitor["team"])

    print({team: "TODO" for team in sorted(all_teams)})

    raise NotImplementedError(len(extracted))


if __name__ == "__main__":
    main()
