# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
TEAM_ACRONYM_MAPPING = {
    "ACE": "ACES WRESTLING",
    "AJJ": "TODO",
    "ARG": "TODO",
    "ARL": "TODO",
    "BAD": "BADGER WC",
    "BAR": "TODO",
    "BAT": "BATAVIA PINNERS",
    "BEL": "TODO",
    "BEN": "TODO",
    "BET": "TODO",
    "BEV": "TODO",
    "BIO": "TODO",
    "BIS": "TODO",
    "BLA": "TODO",
    "BLO": "TODO",
    "BOY": "TODO",
    "BRA": "TODO",
    "BRO": "BRONCO WRESTLING",
    "CAL": "TODO",
    "CAM": "TODO",
    "CAR": "TODO",
    "CAY": "TODO",
    "CEN": "CENTRALIA WC",
    "CHA": "CHARLESTON WC",
    "CHE": "CHENOA MAT CATS",
    "CHI": "TODO",
    "CHL": "CHILLICOTHE WC",
    "CHR": "CHARLESTON WC",
    "CRO": "TODO",
    "CRY": "TODO",
    "CUM": "TODO",
    "DAK": "DAKOTA WC",
    "DEK": "TODO",
    "DIX": "DIXON WC",
    "DOW": "TODO",
    "DUN": "TODO",
    "DUR": "TODO",
    "EAS": "TODO",
    "EDW": "TODO",
    "EFF": "TODO",
    "ELM": "TODO",
    "EUR": "EUREKA KIDS WC",
    "FAC": "TODO",
    "FAL": "TODO",
    "FIS": "FISHER WC",
    "FOR": "TODO",
    "FOX": "TODO",
    "GAL": "GALESBURG JR STREAKS",
    "GEE": "TODO",
    "GEN": "GENERALS",
    "GEV": "TODO",
    "GLA": "TODO",
    "GLE": "TODO",
    "GLN": "TODO",
    "GRA": "TODO",
    "HAE": "TODO",
    "HAR": "TODO",
    "HIG": "TODO",
    "HIL": "HILLSBORO JR TOPPERS WRESTLING CLUB",
    "HIN": "TODO",
    "HIT": "TODO",
    "HOM": "TODO",
    "HON": "HONONEGAH KIDS WC",
    "HOO": "TODO",
    "HUS": "HUSKIES WC",
    "ILL": "TODO",
    "JAC": "JACKSONVILLE WC",
    "JOL": "TODO",
    "JRC": "TODO",
    "JRG": "TODO",
    "JRM": "JR MAROON WC",
    "JRP": "TODO",
    "JRR": "TODO",
    "JRS": "JR SENTINELS",
    "JUP": "TODO",
    "KNI": "TODO",
    "LAE": "TODO",
    "LAO": "TODO",
    "LAR": "TODO",
    "LAW": "TODO",
    "LEM": "TODO",
    "LIB": "TODO",
    "LIC": "TODO",
    "LIL": "TODO",
    "LIN": "LITTLE INDIANS",
    "LIO": "TODO",
    "LIR": "TODO",
    "LIS": "TODO",
    "LOC": "TODO",
    "LPC": "L-P CRUNCHING CAVS",
    "MAC": "TODO",
    "MAF": "TODO",
    "MAI": "TODO",
    "MAR": "MARENGO WC",
    "MAT": "MATTOON YOUTH WC",
    "MET": "METAMORA KIDS WC",
    "MID": "TODO",
    "MOL": "TODO",
    "MOT": "TODO",
    "MTV": "MT VERNON LIONS",
    "MTZ": "MT ZION WC",
    "MUR": "MURPHYSBORO WRESTLIN",
    "MUS": "TODO",
    "NAP": "NAPERVILLE WC",
    "NOR": "TODO",
    "NOT": "TODO",
    "OAK": "OAKWOOD WC",
    "OAL": "TODO",
    "OAW": "TODO",
    "OPR": "TODO",
    "ORL": "TODO",
    "OSW": "TODO",
    "PAL": "TODO",
    "PAN": "TODO",
    "PAT": "TODO",
    "PLA": "TODO",
    "PLT": "PLT PROPHETS WC",
    "POL": "POLO WC",
    "PON": "PONY EXPRESS WC",
    "POY": "TODO",
    "RAI": "TODO",
    "RAM": "RAMS WC",
    "RIC": "RICHMOND WC",
    "RIV": "RIVERBEND WC",
    "ROF": "TODO",
    "ROK": "TODO",
    "ROU": "TODO",
    "ROX": "ROXANA KIDS WC",
    "SAU": "TODO",
    "SAV": "SAVANNA REDHAWKS",
    "SCH": "TODO",
    "SHP": "TODO",
    "SHR": "TODO",
    "SJO": "SJO YOUTH WRESTLING",
    "SOU": "TODO",
    "SPR": "TODO",
    "STC": "TODO",
    "STE": "TODO",
    "STI": "TODO",
    "SYC": "TODO",
    "TAY": "TAYLORVILLE WC",
    "TAZ": "TODO",
    "TBI": "TODO",
    "TEX": "TODO",
    "TIE": "TODO",
    "TIG": "TODO",
    "TIN": "TODO",
    "TOM": "TODO",
    "TRI": "TRIAD KNIGHTS WRESTLING CLUB",
    "UNI": "UNITY WRESTLING CLUB",
    "VAN": "VANDALIA JR WRESTLIN",
    "VIL": "TODO",
    "VIT": "TODO",
    "WAK": "TODO",
    "WAR": "WARRENSBURG WC",
    "WAU": "WAUBONSIE TRAILBLAZE",
    "WES": "WESTVILLE YOUTH WC",
    "WET": "TODO",
    "WHE": "WHEATON BULLDOGS",
    "WHF": "TODO",
    "WHM": "TODO",
    "WOL": "TODO",
    "WRE": "TODO",
    "YOR": "TODO",
}
TEAM_NAME_MAPPING = {
    "HILLSBORO JR TOPPERS WRESTLING CLUB": 170,
}


def main():
    with open(HERE / "extracted.2002.json") as file_obj:
        extracted = json.load(file_obj)

    S = set()
    for weight in extracted:
        for match in weight["matches"]:
            top_competitor = match["top_competitor"]
            if top_competitor is not None:
                S.add(top_competitor["team"])

            bottom_competitor = match["bottom_competitor"]
            if bottom_competitor is not None:
                S.add(bottom_competitor["team"])

    print({k: "TODO" for k in S})

    raise NotImplementedError(len(extracted))


if __name__ == "__main__":
    main()
