# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
TEAM_ACRONYM_MAPPING = {
    "ABC": "TODO",
    "ACE": "TODO",
    "AJP": "TODO",
    "AJW": "TODO",
    "ANI": "TODO",
    "ARG": "TODO",
    "ARL": "TODO",
    "BAT": "TODO",
    "BDG": "TODO",
    "BJH": "TODO",
    "BKH": "TODO",
    "BKT": "TODO",
    "BLD": "TODO",
    "BLM": "TODO",
    "BLV": "TODO",
    "BMH": "TODO",
    "BRL": "TODO",
    "BRR": "TODO",
    "BSN": "TODO",
    "BTB": "TODO",
    "BTN": "TODO",
    "CHM": "TODO",
    "CHR": "TODO",
    "CJS": "TODO",
    "CJT": "TODO",
    "CLA": "TODO",
    "CLD": "TODO",
    "CLP": "TODO",
    "CLW": "TODO",
    "CMB": "TODO",
    "CMW": "TODO",
    "CNT": "TODO",
    "CRL": "TODO",
    "CTC": "TODO",
    "CVR": "TODO",
    "DAK": "TODO",
    "DDH": "TODO",
    "DGC": "TODO",
    "DIX": "TODO",
    "EDW": "TODO",
    "EFF": "TODO",
    "EJD": "TODO",
    "EMS": "TODO",
    "EPG": "TODO",
    "ERV": "TODO",
    "FCY": "TODO",
    "FEN": "TODO",
    "FIS": "TODO",
    "FLC": "TODO",
    "FOX": "TODO",
    "FRR": "TODO",
    "FTT": "TODO",
    "GCW": "TODO",
    "GEN": "TODO",
    "GER": "TODO",
    "GLA": "TODO",
    "GLD": "TODO",
    "GRM": "TODO",
    "GRY": "TODO",
    "HBJ": "TODO",
    "HER": "TODO",
    "HJT": "TODO",
    "HOF": "TODO",
    "HON": "TODO",
    "HPG": "TODO",
    "HPN": "TODO",
    "HRD": "TODO",
    "HRL": "TODO",
    "HTW": "TODO",
    "HUR": "TODO",
    "IMP": "TODO",
    "JBC": "TODO",
    "JCG": "TODO",
    "JMS": "TODO",
    "JVK": "TODO",
    "KGT": "TODO",
    "LAK": "TODO",
    "LAN": "TODO",
    "LEM": "TODO",
    "LHI": "TODO",
    "LJP": "TODO",
    "LLB": "TODO",
    "LLC": "TODO",
    "LLF": "TODO",
    "LLH": "TODO",
    "LLS": "TODO",
    "LNS": "TODO",
    "LNW": "TODO",
    "LPC": "TODO",
    "LRB": "TODO",
    "LRS": "TODO",
    "MAT": "TODO",
    "MDW": "TODO",
    "MED": "TODO",
    "MEN": "TODO",
    "MFV": "TODO",
    "MIY": "TODO",
    "MLB": "TODO",
    "MLI": "TODO",
    "MLM": "TODO",
    "MNE": "TODO",
    "MOL": "TODO",
    "MRB": "TODO",
    "MRS": "TODO",
    "MRT": "TODO",
    "MST": "TODO",
    "MTP": "TODO",
    "MTV": "TODO",
    "MTZ": "TODO",
    "MWC": "TODO",
    "NDW": "TODO",
    "NPV": "TODO",
    "OFW": "TODO",
    "OKW": "TODO",
    "OLP": "TODO",
    "OLW": "TODO",
    "OPP": "TODO",
    "OSW": "TODO",
    "PAN": "TODO",
    "PCC": "TODO",
    "PEK": "TODO",
    "PLF": "TODO",
    "PLP": "TODO",
    "PLT": "TODO",
    "PLW": "TODO",
    "PNP": "TODO",
    "PON": "TODO",
    "PRP": "TODO",
    "PRZ": "TODO",
    "RAM": "TODO",
    "RCL": "TODO",
    "RCT": "TODO",
    "RDW": "TODO",
    "RJR": "TODO",
    "RKF": "TODO",
    "RKI": "TODO",
    "RKR": "TODO",
    "RMD": "TODO",
    "ROX": "TODO",
    "RRT": "TODO",
    "RVB": "TODO",
    "SAV": "TODO",
    "SCE": "TODO",
    "SCN": "TODO",
    "SHM": "TODO",
    "SIC": "TODO",
    "SJO": "TODO",
    "SJR": "TODO",
    "SKE": "TODO",
    "SKV": "TODO",
    "SOT": "TODO",
    "SPD": "TODO",
    "SPR": "TODO",
    "SRD": "TODO",
    "STT": "TODO",
    "STV": "TODO",
    "SYC": "TODO",
    "TAK": "TODO",
    "TAY": "TODO",
    "TIG": "TODO",
    "TLK": "TODO",
    "TOM": "TODO",
    "TPB": "TODO",
    "TRV": "TODO",
    "TTT": "TODO",
    "TVN": "TODO",
    "TWW": "TODO",
    "UNT": "TODO",
    "UNY": "TODO",
    "VAN": "TODO",
    "VIT": "TODO",
    "VLC": "TODO",
    "WBN": "TODO",
    "WHN": "TODO",
    "WHT": "TODO",
    "WJP": "TODO",
    "WPK": "TODO",
    "WRB": "TODO",
    "WRC": "TODO",
    "WRF": "TODO",
    "WSV": "TODO",
    "XTR": "TODO",
    "YNG": "TODO",
    "YRK": "TODO",
}
TEAM_NAME_MAPPING = {
    "A-J JUNIOR WILDCATS": -30303,
    "ACES WC": -30303,
    "ALEDO BEAR COUNTRY": -30303,
    "ALLEMAN JR. PIONEERS": -30303,
    "ANIMALS WC": -30303,
    "ARGENTA-OREANA KIDS CLUB": -30303,
    "ARLINGTON CARDNALS": -30303,
    "BADGERS WC": -30303,
    "BARRINGTON BRONCOS": -30303,
    "BARTLETT JR. HAWKS": -30303,
    "BATAVIA PINNERS": -30303,
    "BELLEVILLE LITTLE DEVILS": -30303,
    "BELVIDERE BANDITS": -30303,
    "BENTON JR. WC": -30303,
    "BETHALTO BULLS WC": -30303,
    "BISMARK-HENNING WC": -30303,
    "BISON WC": -30303,
    "BLACK KATS WC": -30303,
    "BLACKHAWK WC": -30303,
    "BLOOMINGTON RAIDERS WC": -30303,
    "BRAWLERS": -30303,
    "CALUMET MEMORIAL PD WOLVERINES": -30303,
    "CARBONDALE JUNIOR SPIRITS": -30303,
    "CARLINVILLE KIDS WC": -30303,
    "CARY JR. TROJAN MATMEN": -30303,
    "CENTRAILIA": -30303,
    "CENTRAL": -30303,
    "CHAMPAIGN KIDS WC": -30303,
    "CHARLESTON WC": -30303,
    "CHILLI DAWGS": -30303,
    "CHILLI DAWGS WC": -30303,
    "CLIPPER WC": -30303,
    "COLLINSVILLE RAIDERS": -30303,
    "CROSSTOWN CRUSHERS": -30303,
    "CRYSTAL LAKE WIZARDS": -30303,
    "CUMBERLAND YOUTH WC": -30303,
    "DAKOTA WC": -30303,
    "DIXON WC": -30303,
    "DOWNERS GROVE COUGARS": -30303,
    "DUNDEE HIGHLANDERS": -30303,
    "EDWARDSVILLE WC": -30303,
    "EFFINGHAM JUNIOR WC": -30303,
    "EL PASO/GRIDLEY WC": -30303,
    "ELMHUSRT JR. DUKES": -30303,
    "ERIE MIDDLE SCHOOL": -30303,
    "ERVIN WC": -30303,
    "FAIRMONT ROUGH RIDERS": -30303,
    "FALCON WC": -30303,
    "FALCON YOUTH WC": -30303,
    "FENWICK FALCONS WC": -30303,
    "FIGHTIN' TITANS": -30303,
    "FISHER WC": -30303,
    "FOX VALLEY WC": -30303,
    "GC JR. WARRIORS": -30303,
    "GENESEO WC": -30303,
    "GEORGETOWN RUDE DOGS YOUTH WC": -30303,
    "GERMANTOWN WC": -30303,
    "GLADIATORS": -30303,
    "GLENBARD EAST JR. RAMS": -30303,
    "GOLDEN EAGLES": -30303,
    "GRANITE CITY JR. WARRIORS": -30303,
    "HARLEM COUGARS": -30303,
    "HARVARD WC": -30303,
    "HARVEY PARK DISTRICT TWISTERS": -30303,
    "HERRIN WC": -30303,
    "HIGHLAND BULLDOGS JR. WC": -30303,
    "HIGHLAND PARK LITTLE GIANTS": -30303,
    "HILLSBORO JR. TOPPERS": -30303,
    "HINSDALE RED DEVILS": -30303,
    "HOFFMAN ESTATES WC": -30303,
    "HONONEGAH KIDS WC": -30303,
    "HOOPSTON AREA WC": -30303,
    "HURRICANES": -30303,
    "IMPACT WC": -30303,
    "JOLIET BOYS CLUB COBRAS": -30303,
    "JR. COUGARS": -30303,
    "JR. MUSTANGS": -30303,
    "JR. VIKINGS": -30303,
    "KNIGHTS WC": -30303,
    "L-P CRUNCHING CAVS": -30303,
    "LAKELAND PREDATORS": -30303,
    "LANCER WC": -30303,
    "LAWRENCE COUNTY WC": -30303,
    "LEMONT BEARS WC": -30303,
    "LIL' STORM YOUTH WC": -30303,
    "LINCOLN-WAY WC": -30303,
    "LIONHEART INTENSE WC": -30303,
    "LIONS WC": -30303,
    "LITTLE BOILERS WC": -30303,
    "LITTLE CELTICS": -30303,
    "LITTLE FALCONS WC": -30303,
    "LITTLE HUSKIES WC": -30303,
    "LITTLE REDBIRD WC": -30303,
    "LITTLE REDSKIN WC": -30303,
    "LOCKPORT JR PORTERS": -30303,
    "MACOMB LITTLE BOMBERS": -30303,
    "MAD DOG WRESTLING ACADEMY": -30303,
    "MAINE EAGLES": -30303,
    "MARENGO INDIANS YOUTH WC": -30303,
    "MARTINEZ FOX VALLEY ELITE": -30303,
    "MATTOON YOUTH WC": -30303,
    "MEDALIST WC": -30303,
    "MENDOTA WC": -30303,
    "METAMORA KIDS WC": -30303,
    "MIDWEST CENTRAL YOUTH WC": -30303,
    "MINOOKA LITTLE INDIANS": -30303,
    "MOLINE WC": -30303,
    "MORRISON STALLIONS WC": -30303,
    "MORTON LITTLE MUSTANGS": -30303,
    "MORTON YOUTH WC": -30303,
    "MT. PULASKI": -30303,
    "MT. VERNON LIONS": -30303,
    "MT. ZION WC": -30303,
    "MURPHYSBORO WC": -30303,
    "MUSTANG WC": -30303,
    "NAPERVILLE WC": -30303,
    "NOTRE DAME WC": -30303,
    "O'FALLION LITTLE PANTHERS": -30303,
    "OAK FOREST WARRIORS": -30303,
    "OAK LAWN PARK DISTRICT WILDCATS": -30303,
    "OAKWOOD WC": -30303,
    "ORLAND PARK PIONEERS": -30303,
    "OSWEGO PANTERS": -30303,
    "PALATINE PANTHERS WC": -30303,
    "PANTHER CUB WC": -30303,
    "PANTHER POWERHOUSE WC": -30303,
    "PANTHER WC": -30303,
    "PEKIN BOY AND GIRLS CLUB": -30303,
    "PEKIN BOYS AND GIRLS CLUB": -30303,
    "PEORIA RAZORBACKS": -30303,
    "PLAINFIELD TORNADOES WC": -30303,
    "PLAINFIELD WC": -30303,
    "PONTIAC PYTHONS": -30303,
    "PRAIRIE CENTRAL-CHENOA HAWKS": -30303,
    "PROVISO POWERHOUSE": -30303,
    "RAMS WC": -30303,
    "RICH RATTLERS WC": -30303,
    "RICHMOND WC": -30303,
    "RIVERBEND WC": -30303,
    "RIVERDALE JR RAMS WC": -30303,
    "ROAD WARRIORS": -30303,
    "ROCHELLE": -30303,
    "ROCHESTER WC": -30303,
    "ROCK ISLAND WC": -30303,
    "ROCKFORD WC": -30303,
    "ROCKRIDGE WC": -30303,
    "ROXANA KIDS WC": -30303,
    "SAUK VALLEY WC": -30303,
    "SAUKEE YOUTH WC": -30303,
    "SAVANNA REDHAWKS": -30303,
    "SCN YOUTH WC": -30303,
    "SENECA IRISH CADETS": -30303,
    "SHAMROCK WC": -30303,
    "SHELBYVILLE JR. RAMS WC": -30303,
    "SHERRARD WC": -30303,
    "SJO SPRATAN YOUTH": -30303,
    "SONS OF THUNDER": -30303,
    "SPIDER WC": -30303,
    "SPRINGFIELD CAPITAL KIDS WRESTLING": -30303,
    "ST. CHARLES EAST WC": -30303,
    "ST. TARCISSUS": -30303,
    "STILLMAN VALLEY WC": -30303,
    "SYCAMORE": -30303,
    "TAKEDOWN WC": -30303,
    "TAYLORVILLE WC": -30303,
    "TEAM WEST WOLVES": -30303,
    "TIGER WC": -30303,
    "TIGERTOWN TANGLERS": -30303,
    "TINLEY PARK BULLDOGS": -30303,
    "TOMCAT WC": -30303,
    "TREVIAN": -30303,
    "TRI-VALLEY WC": -30303,
    "TRIAD LITTLE KNIGHTS": -30303,
    "UNITED TOWNSHIP WC": -30303,
    "UNITY WC": -30303,
    "VANDALIA JR. WRESLTING": -30303,
    "VILLA LOMBARD COUGARS": -30303,
    "VITTUM CATS": -30303,
    "WARREN COUNTY WC": -30303,
    "WARRENSBURG WC": -30303,
    "WASHINGTON JR. PANTHERS": -30303,
    "WAUBONSIE WC": -30303,
    "WEST HANCOCK WC": -30303,
    "WESTVILLE YOUTH WC": -30303,
    "WHEATON TIGERS": -30303,
    "WOLFPAK WC": -30303,
    "WRESTLING FACTORY": -30303,
    "XTREME WC": -30303,
    "YORKVILLE WC": -30303,
    "YOUNG CHAMPIONS": -30303,
    "ZEE-BEE STINGERS": -30303,
}


def main():
    with open(HERE / "extracted.2005.json") as file_obj:
        extracted = json.load(file_obj)

    all_teams = set()
    for weight in extracted:
        for match in weight["matches"]:
            top_competitor = match["top_competitor"]
            if top_competitor is not None:
                all_teams.add(top_competitor["team"])

            bottom_competitor = match["bottom_competitor"]
            if bottom_competitor is not None:
                all_teams.add(bottom_competitor["team"])

    print({team: "TODO" for team in sorted(all_teams)})

    raise NotImplementedError(len(extracted))


if __name__ == "__main__":
    main()
