# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
TEAM_ACRONYM_MAPPING = {
    "ACE": "ACES WRESTLING",
    "AJJ": "TODO",
    "ARG": "TODO",
    "ARL": "TODO",
    "BAD": "BADGER WC",
    "BAR": "TODO",
    "BAT": "BATAVIA PINNERS",
    "BEL": "TODO",
    "BEN": "TODO",
    "BET": "TODO",
    "BEV": "TODO",
    "BIO": "TODO",
    "BIS": "TODO",
    "BLA": "TODO",
    "BLO": "TODO",
    "BOY": "TODO",
    "BRA": "TODO",
    "BRO": "BRONCO WRESTLING",
    "CAL": "TODO",
    "CAM": "TODO",
    "CAR": "TODO",
    "CAY": "TODO",
    "CEN": "CENTRALIA WC",
    "CHA": "CHARLESTON WC",
    "CHE": "CHENOA MAT CATS",
    "CHI": "TODO",
    "CHL": "CHILLICOTHE WC",
    "CHR": "CHARLESTON WC",
    "CRO": "TODO",
    "CRY": "TODO",
    "CUM": "TODO",
    "DAK": "DAKOTA WC",
    "DEK": "TODO",
    "DIX": "DIXON WC",
    "DOW": "TODO",
    "DUN": "TODO",
    "DUR": "TODO",
    "EAS": "TODO",
    "EDW": "TODO",
    "EFF": "TODO",
    "ELM": "TODO",
    "EUR": "EUREKA KIDS WC",
    "FAC": "TODO",
    "FAL": "TODO",
    "FIS": "FISHER WC",
    "FOR": "TODO",
    "FOX": "TODO",
    "GAL": "GALESBURG JR STREAKS",
    "GEE": "TODO",
    "GEN": "GENERALS",
    "GEV": "TODO",
    "GLA": "TODO",
    "GLE": "TODO",
    "GLN": "TODO",
    "GRA": "TODO",
    "HAE": "TODO",
    "HAR": "TODO",
    "HIG": "TODO",
    "HIL": "HILLSBORO JR TOPPERS",
    "HIN": "TODO",
    "HIT": "TODO",
    "HOM": "TODO",
    "HON": "HONONEGAH KIDS WC",
    "HOO": "TODO",
    "HUS": "HUSKIES WC",
    "ILL": "TODO",
    "JAC": "JACKSONVILLE WC",
    "JOL": "TODO",
    "JRC": "TODO",
    "JRG": "TODO",
    "JRM": "JR MAROON WC",
    "JRP": "TODO",
    "JRR": "TODO",
    "JRS": "JR SENTINELS",
    "JUP": "TODO",
    "KNI": "TODO",
    "LAE": "TODO",
    "LAO": "TODO",
    "LAR": "TODO",
    "LAW": "TODO",
    "LEM": "TODO",
    "LIB": "TODO",
    "LIC": "TODO",
    "LIL": "TODO",
    "LIN": "LITTLE INDIANS",
    "LIO": "TODO",
    "LIR": "TODO",
    "LIS": "TODO",
    "LOC": "TODO",
    "LPC": "L-P CRUNCHING CAVS",
    "MAC": "TODO",
    "MAF": "TODO",
    "MAI": "TODO",
    "MAR": "MARENGO WC",
    "MAT": "MATTOON YOUTH WC",
    "MET": "METAMORA KIDS WC",
    "MID": "TODO",
    "MOL": "TODO",
    "MOT": "TODO",
    "MTV": "MT VERNON LIONS",
    "MTZ": "MT ZION WC",
    "MUR": "MURPHYSBORO WRESTLIN",
    "MUS": "TODO",
    "NAP": "NAPERVILLE WC",
    "NOR": "TODO",
    "NOT": "TODO",
    "OAK": "OAKWOOD WC",
    "OAL": "TODO",
    "OAW": "TODO",
    "OPR": "TODO",
    "ORL": "TODO",
    "OSW": "TODO",
    "PAL": "TODO",
    "PAN": "TODO",
    "PAT": "TODO",
    "PLA": "TODO",
    "PLT": "PLT PROPHETS WC",
    "POL": "POLO WC",
    "PON": "PONY EXPRESS WC",
    "POY": "TODO",
    "RAI": "TODO",
    "RAM": "RAMS WC",
    "RIC": "RICHMOND WC",
    "RIV": "RIVERBEND WC",
    "ROF": "TODO",
    "ROK": "TODO",
    "ROU": "TODO",
    "ROX": "ROXANA KIDS WC",
    "SAU": "TODO",
    "SAV": "SAVANNA REDHAWKS",
    "SCH": "TODO",
    "SHP": "TODO",
    "SHR": "TODO",
    "SJO": "SJO YOUTH WRESTLING",
    "SOU": "TODO",
    "SPR": "TODO",
    "STC": "TODO",
    "STE": "TODO",
    "STI": "TODO",
    "SYC": "TODO",
    "TAY": "TAYLORVILLE WC",
    "TAZ": "TODO",
    "TBI": "TODO",
    "TEX": "TODO",
    "TIE": "TODO",
    "TIG": "TODO",
    "TIN": "TODO",
    "TOM": "TODO",
    "TRI": "TRIAD KNIGHTS WRESTLING CLUB",
    "UNI": "UNITY WRESTLING CLUB",
    "VAN": "VANDALIA JR WRESTLIN",
    "VIL": "TODO",
    "VIT": "TODO",
    "WAK": "TODO",
    "WAR": "WARRENSBURG WC",
    "WAU": "WAUBONSIE TRAILBLAZE",
    "WES": "WESTVILLE YOUTH WC",
    "WET": "TODO",
    "WHE": "WHEATON BULLDOGS",
    "WHF": "TODO",
    "WHM": "TODO",
    "WOL": "TODO",
    "WRE": "TODO",
    "YOR": "TODO",
}
TEAM_NAME_MAPPING = {
    "A-J JR. WILDCATS": -90105,
    "ACES WC": -90105,
    "ARGENTA/OREANA KIDS CLUB": -90105,
    "ARLINGTON CARDINALS": -90105,
    "BADGER WC": -90105,
    "BARTLETT HAWK WC": -90105,
    "BATAVIA PINNERS": -90105,
    "BELLEVILLE LITTLE DEVILS": -90105,
    "BELVIDERE BANDITS": -90105,
    "BENTON JR. WC": -90105,
    "BETHALTO BULLS WC": -90105,
    "BISMARCK-HENNING WC": -90105,
    "BISON WC": -90105,
    "BLACKHAWK WC": -90105,
    "BLOOMINGTON RAIDER WC": -90105,
    "BOYS & GIRLS CLUB OF PEKIN": -90105,
    "BRAWLERS WC": -90105,
    "BRONCO WRESTLING": -90105,
    "CAMP POINT CENTRAL": -90105,
    "CARBONDALE WC": -90105,
    "CARLINVILLE KIDS WC": -90105,
    "CARY JR TROJAN MATMEN": -90105,
    "CENTRAL WC": -90105,
    "CHAMPAIGN KIDS WRESTLING": -90105,
    "CHARLESTON WC": -90105,
    "CHENOA MAT CATS": -90105,
    "CHILLICOTHE WC": -90105,
    "CROSSFACE WRESTLING": -90105,
    "CRYSTAL LAKE WIZARDS": -90105,
    "CUMBERLAND YOUTH WC": -90105,
    "DAKOTA WC": -90105,
    "DEKALB WC": -90105,
    "DIXON WC": -90105,
    "DOWNERS GROVE COUGARS": -90105,
    "DUNDEE HIGHLANDERS": -90105,
    "DURAND-PECATONICA CARNIVORES": -90105,
    "EAST MOLINE PANTHER PINNERS": -90105,
    "EDWARDSVILLE WC": -90105,
    "EFFINGHAM YOUTH WC": -90105,
    "ELMHURST JR. DUKES": -90105,
    "EUREKA KIDS WC": -90105,
    "FALCON WC": -90105,
    "FALCON YOUTH WC": -90105,
    "FISHER WC": -90105,
    "FORD HEIGHTS FALCONS": -90105,
    "FOX VALLEY WC": -90105,
    "GALESBURG JR STREAKS": -90105,
    "GENERALS": -90105,
    "GENESEO WC": -90105,
    "GENEVA WC": -90105,
    "GLADIATORS": -90105,
    "GLEN ELLYN DUNGEON WC": -90105,
    "GLENBARD EAST JR RAMS": -90105,
    "GRANITE CITY JR WARRIORS": -90105,
    "HARLEM COUGARS": -90105,
    "HARVEY TWISTERS": -90105,
    "HIGHLAND BULLDOG JR WC": -90105,
    "HILLSBORO JR TOPPERS": 170,
    "HILLTOPPERS WC": -90105,
    "HINSDALE RED DEVIL WC": -90105,
    "HOMEWOOD-FLOSSMOOR CATS": -90105,
    "HONONEGAH KIDS WC": -90105,
    "HOOPESTON AREA WC": -90105,
    "HUSKIES WC": -90105,
    "ILLINI BLUFFS WC": -90105,
    "JACKSONVILLE WC": -90105,
    "JOLIET BOYS CLUB COBRAS": -90105,
    "JR. COUGAR WC": -90105,
    "JR. GOLDEN EAGLES": -90105,
    "JR. MAROON WC": -90105,
    "JR. PANTHERS WRESTLING": -90105,
    "JR. ROCKET WRESTLING": -90105,
    "JR. SENTINELS": -90105,
    "JUNIOR PIRATE WC": -90105,
    "KISHWAUKEE WC": -90105,
    "KNIGHTS WRESTLING": -90105,
    "L-P CRUNCHING CAVS": -90105,
    "LAKE VIEW JR WILDCATS": -90105,
    "LAKELAND PREDATORS": -90105,
    "LAN-OAK P.D. LITTLE REBELS": -90105,
    "LANCER WC": -90105,
    "LARKIN JR. ROYALS WC": -90105,
    "LAWRENCE COUNTY WC": -90105,
    "LEMONT BEARS WC": -90105,
    "LIL' ROUGHNECKS": -90105,
    "LIL' STORM YOUTH WRESTLING": -90105,
    "LINCOLN-WAY WC": -90105,
    "LIONS WC": -90105,
    "LITTLE BOILER WC": -90105,
    "LITTLE CELTIC WC": -90105,
    "LITTLE REDBIRD WC": -90105,
    "LOCKPORT GATORS WC": -90105,
    "MACOMB LITTLE BOMBERS": -90105,
    "MAINE EAGLES WC": -90105,
    "MANTENO JR PANTHERS": -90105,
    "MARENGO WC": -90105,
    "MARTINEZ FOX VALLEY ELITE WC": -90105,
    "MATTOON YOUTH WC": -90105,
    "METAMORA KIDS WC": -90105,
    "MIDWEST CENTRAL YOUTH": -90105,
    "MOLINE WC": -90105,
    "MORTON LITTLE MUSTANGS": -90105,
    "MT. VERNON LIONS": -90105,
    "MT. ZION WC": -90105,
    "MURPHYSBORO WRESTLING": -90105,
    "MUSTANG WC": -90105,
    "NAPERVILLE WC": -90105,
    "NORTHSHORE GATORS": -90105,
    "NOTRE DAME": -90105,
    "OAK FOREST WARRIORS": -90105,
    "OAK LAWN P.D. WILDCATS": -90105,
    "OAKWOOD WC": -90105,
    "OPRF LITTLE HUSKIE WC": -90105,
    "ORLAND PARK PIONEERS": -90105,
    "OSWEGO PANTHERS": -90105,
    "PALATINE PANTHERS WC": -90105,
    "PANTHER CUB WC": -90105,
    "PANTHER WC": -90105,
    "PLAINFIELD WC": -90105,
    "PLT PROPHETS WC": -90105,
    "POLO WC": -90105,
    "PONTIAC PYTHONS": -90105,
    "PONY EXPRESS WC": -90105,
    "RAIDER WC": -90105,
    "RAMS WC": -90105,
    "RICH RATTLERS WC": -90105,
    "RIVERBEND WC": -90105,
    "ROCK ISLAND JR. ROCKS": -90105,
    "ROCKFORD WC": -90105,
    "ROUND LAKE BAD BOYZ": -90105,
    "ROXANA KIDS WRESTING CLUB": -90105,
    "SAUKEE YOUTH WC": -90105,
    "SAVANNA REDHAWKS": -90105,
    "SCHAUMBURG JR. SAXONS": -90105,
    "SHARKS WC": -90105,
    "SHEPARD WRESTLING": -90105,
    "SJO SPARTAN WC": -90105,
    "SOUTHERN ILLINOIS EAGLES": -90105,
    "SPRINGFIELD CAPITALS": -90105,
    "ST. CHARLES WC": -90105,
    "STERLING NEWMAN JR COMETS": -90105,
    "STILLMAN VALLEY WC": -90105,
    "SYCAMORE WC": -90105,
    "T-BIRD/RAIDER WRESTLING": -90105,
    "TAYLORVILLE WC": -90105,
    "TAZEWELL COUNTY KIDZ WC": -90105,
    "TEAM WEST WOLVES": -90105,
    "TEAM XPRESS": -90105,
    "TIGER WC": -90105,
    "TIGERTOWN TANGLERS": -90105,
    "TINLEY PARK BULLDOGS": -90105,
    "TOMCAT WC": -90105,
    "TRIAD KNIGHTS": -90105,
    "UNITY WC": -90105,
    "VANDALIA JR WRESTLING": -90105,
    "VILLA LOMBARD COUGARS": -90105,
    "VITTUM CATS": -90105,
    "WARRENSBURG WC": -90105,
    "WAUBONSIE WC": -90105,
    "WAUKEGAN TAKEDOWN": -90105,
    "WEST FRANKFORT JR. WC": -90105,
    "WESTVILLE YOUTH WC": -90105,
    "WHEATON BULLDOGS": -90105,
    "WHEATON FRANKLIN WC": -90105,
    "WHEATON MONROE EAGLES": -90105,
    "WOLFPAK WC": -90105,
    "WRESTLING FACTORY": -90105,
    "YORKVILLE WC": -90105,
}


def main():
    with open(HERE / "extracted.2002.json") as file_obj:
        extracted = json.load(file_obj)

    S = set()
    for weight in extracted:
        for match in weight["matches"]:
            top_competitor = match["top_competitor"]
            if top_competitor is not None:
                S.add(top_competitor["team"])

            bottom_competitor = match["bottom_competitor"]
            if bottom_competitor is not None:
                S.add(bottom_competitor["team"])

    print({k: "TODO" for k in S})

    raise NotImplementedError(len(extracted))


if __name__ == "__main__":
    main()
