# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils

HERE = pathlib.Path(__file__).resolve().parent
TEAM_ACRONYM_MAPPING = {
    "ABC": "ALEDO BEAR COUNTRY W",
    "AC": "ARLINGTON CARDINALS",
    "ACE": "ACES WRESTLING",
    "ADA": "ADDISON ANIMALS",  # Duplicate
    "AOK": "A-O KIDS WC",
    "BAD": "BADGER WC",
    "BAT": "BATAVIA PINNERS",
    "BB": "BELVIDERE BANDITS",
    "BGP": "BOYS & GIRLS CLUB",  # ... of Pekin
    "BH": "BISMARK-HENNING WC",
    "BJH": "BETHALTO JR HIGH",
    "BJW": "BENTON JR. WC",
    "BLD": "BELLEVILLE LITTLE DE",
    "BRL": "BRAWLERS WC",  # Duplicate (team name shows up twice in Senior Team Scores)
    "BRO": "BRONCO WRESTLING",
    "BWC": "BRAWLERS WC",  # Duplicate
    "CEN": "CENTRALIA WC",
    "CHA": "CHARLESTON WC",  # Duplicate (team name shows up twice in Senior Team Scores)
    "CHE": "CHENOA MAT CATS",
    "CHL": "CHILLICOTHE WC",
    "CHR": "CHARLESTON WC",  # Duplicate
    "CJT": "CARY JR TROJAN MATME",
    "CKW": "CARLINVILLE KIDS WC",
    "CPC": "CAMP POINT CENTRAL",
    "CWC": "CARBONDALE WC",
    "CYW": "CUMBERLAND YOUTH WC",
    "DAK": "DAKOTA WC",
    "DC": "DUNDEE CARPETERVILL",
    "DEC": "DECATUR WC",
    "DH": "DUNDEE HIGHLANDERS",
    "DIX": "DIXON WC",
    "DPC": "DURAND-PECATONICA",
    "EMP": "EAST MOLINE PANTHER",
    "EMS": "ERIE MIDDLE SCHOOL W",  # Duplicate
    "EP": "EDISON PANTHERS",
    "EUR": "EUREKA KIDS WC",
    "EWC": "EDWARDSVILLE WC",
    "FIS": "FISHER WC",
    "FPR": "FRANKLIN PARK RAIDER",
    "FVC": "FOX VALLEY CRONE WC",
    "FVW": "FOX VALLEY WC",
    "FWC": "FISHER WC",
    "FYW": "FALCON YOUTH WC",
    "GED": "GLEN ELLYN DUNGEON W",
    "GEN": "GENERALS",
    "GJS": "GALESBURG JR STRK 2",
    "GWC": "GENESEO WC",
    "HAW": "HOOPESTON AREA WC",
    "HBJ": "HIGHLAND BULLDOG JR",
    "HC": "HARLEM COUGARS",
    "HJT": "HILLSBORO JR TOPPERS",
    "HON": "HONONEGAH KIDS WC",
    "HUS": "HUSKIES WC",
    "IB": "ILLINI BLUFFS WC",
    "JAC": "JACKSONVILLE WC",
    "JFW": "JACOBS FALCONS",
    "JGE": "JR GOLDEN EAGLES",
    "JRK": "JUNIOR ROCKS WRESTLI",
    "JRM": "JR MAROON WC",
    "JRS": "JR SENTINELS",
    "JRW": "JR ROCKET WRESTLING",
    "JUN": "JUNIOR PIRATE WC",
    "LB": "LEMONT BEARS WC",
    "LC": "LITTLE CELTIC WC",
    "LCW": "LAWRENCE COUNTY WC",
    "LIN": "LITTLE INDIANS",
    "LIT": "LITTLE BOILER WC",
    "LJW": "LAKE VIEW JR WILDCAT",
    "LLP": "LAKELAND PREDATORS",
    "LPC": "L-P CRUNCHING CAVS",
    "LRB": "LITTLE REDBIRD WC",
    "LSW": "LIL STORM YOUTH",
    "LVL": "LAKE VILLA LANCERS",
    "LYW": "LIMESTONE YOUTH ROCK",
    "MAN": "MANTENO JR PANTHERS",
    "MAR": "MARENGO WC",
    "MAT": "MATTOON YOUTH WC",
    "MCY": "MIDWEST CENTRAL YOUT",
    "ME": "MAINE EAGLES WC",
    "MEN": "MENDOTA MAT MASTERS",
    "MET": "METAMORA KIDS WC",
    "MFV": "MARTINEZ FOX VALLEY",
    "MKW": "MACOMB KIDS WRESTLIN",
    "MOR": "MORTON YOUTH WRESTLI",
    "MS": "METRO STALLIONS",
    "MTV": "MT VERNON LIONS",
    "MTZ": "MT ZION WC",
    "MUR": "MURPHYSBORO WRESTLIN",
    "NAP": "NAPERVILLE WC",
    "NE": "NAPERVILLE EAGLES",
    "NL": "NAPERVILLE LANCERS",
    "NW": "NAPERVILLE WARHAWKS",
    "OAK": "OAKWOOD WC",
    "OC": "OSWEGO COUGARS",
    "OPP": "ORLAND PARK PIONEERS",
    "OSP": "OSWEGO PANTHERS",
    "PCW": "PANTHER CUB WC",
    "PIN": "PINCKNEYVILLE JR",
    "PLH": "PLANIFIELD HUSKIES W",
    "PLT": "PLT PROPHETS WC",
    "PLW": "PLAINFIELD WOLVES WC",
    "POL": "POLO WC",
    "PON": "PONY EXPRESS WC",
    "PPW": "PONTIAC PYTHONS",
    "PWC": "PLAINFIELD WC",
    "RAM": "RAMS WC",
    "RFR": "ROCK FALLS RIPPIN",
    "RIV": "RIVERBEND WC",
    "RJH": "RIVERDALE JR HIGH",
    "RMD": "RICHMOND WC",
    "ROC": "ROCHELLE WC",
    "ROX": "ROXANA KIDS WC",
    "RWC": "ROCKFORD WC",
    "SAV": "SAVANNA REDHAWKS",
    "SC": "SPRINGFIELD CAPTIALS",
    "SHA": "SHARKS WC",
    "SHE": "SHERRAND JR WC",
    "SJW": "SHELBYVILLE JUNIOR R",
    "SN": "STERLING NEWMAN JR",
    "SSW": "SOUTHSIDE WC",
    "STB": "ST BEDE WC",
    "SVW": "STILLMAN VALLEY WC",
    "SW": "STATELINE WILDCATS",
    "SYW": "SAUKEE YOUTH WC",
    "TAY": "TAYLORVILLE WC",
    "TCB": "TRI-CITY BRAVES",
    "TPB": "TINLEY PARK BULLDOGS",
    "TTT": "TIGERTOWN TANGLERS",
    "TWC": "TIGER WC",
    "UNI": "UNITY WRESTLING CLUB",
    "VAN": "VANDALIA JR WRESTLIN",
    "VC": "VITTUM CATS",
    "VLC": "VILLA LOMBARD COUGAR",
    "VPY": "VILLA PARK YOUNG",
    "WAB": "WAUBONSIE BULLDOGS",
    "WAG": "WAUONSIE GRIZZLIES",
    "WAR": "WARRENSBURG WC",
    "WAU": "WAUBONSIE TRAILBLAZE",
    "WB": "WHEATON BULLDOGS",
    "WCI": "WEST CHICAGO PD",
    "WES": "WESTVILLE YOUTH WC",
    "WF": "WEST FRANKFORT JR WC",
    "WFL": "WRESTLING FACTORY",
    "WHC": "WHEATON WC",
    "WHE": "WHEATON BULLDOGS",
    "WHT": "WHEATON WC",
    "WJP": "WASHINGTON JR PANTHE",
    "WME": "WHEATON MONROE EAGLE",
    "WWC": "WOLFPAK WC",
    "YOU": "YOUNG CHAMPIONS",
    "YWC": "YORKVILLE WC",
    # NOTE: These are acronyms that show up in `team*.pdf` keys but do not
    #       have athletes in any brackets.
    #       * ADD: ADDISON ANIMALS (team name shows up twice in Senior Team Scores)
    #       * CW:  CROSSFACE WRESTLING
    #       * DW:  DUNDEE WESTFIELD
    #       * ERI: ERIE MIDDLE SCHOOL W (team name shows up twice in Senior Team Scores)
    #       * GAL: GALESBURG JR STREAKS
    #       * HER: HERRIN WC
    #       * LG:  LITTLE GIANTS
    #       * RIC: RICHMOND WC (team name shows up twice in Senior Team Scores)
}
# NOTE: Sometimes acronyms (or team names) differ between Novice and Senior
#       in the Team Scores.
NOVICE_TEAM_ACRONYM_MAPPING = {
    "CCK": "CHAMPAIGN CHARGER KD",  # Team Name Spelling Differs
    "CLW": "CRYSTAL LAKE WIRZARD",  # Team Name Spelling Differs
    "GDW": "GRAPPLIN'DEVILS WC",  # Team Name Spelling Differs
    "GEJ": "GLENBARD EST JR RAMS",  # Team Name Spelling Differs
    "HRD": "HINSDALE RED DEVIL W",  # Team Name Spelling Differs
    "OLW": "OAK LAWN PD WILDCATS",  # Team Name Spelling Differs
    "SIE": "SOUTHERN IL EAGLES",  # Team Name Spelling Differs
    "SJO": "SHO YOUTH WRESTLING",  # Team Name Spelling Differs
}
SENIOR_TEAM_ACRONYM_MAPPING = {
    "CCK": "CHAMPAIGN CHARGER KI",  # Team Name Spelling Differs
    "CLW": "CRYSTAL LAKE WIZARDS",  # Team Name Spelling Differs
    "GDW": "GRAPPLIN DEVILS WC",  # Team Name Spelling Differs
    "GEJ": "GLENBARD EAST JR RAM",  # Team Name Spelling Differs
    "HRD": "HINSDALE RED DEVILS",  # Team Name Spelling Differs
    "OLW": "OAK LAWN P.D. WILDCA",  # Team Name Spelling Differs
    "SIE": "SOUTHERN ILLINOIS EA",  # Team Name Spelling Differs
    "SJO": "SJO YOUTH WRESTLING",  # Team Name Spelling Differs
}
TEAM_NAME_MAPPING = {
    "A-O KIDS WC": 8,
    "ACES WRESTLING": 3,
    "ADDISON ANIMALS": 10147,
    "ALEDO BEAR COUNTRY W": 10002,
    "ARLINGTON CARDINALS": 9,
    "BADGER WC": 14,
    "BATAVIA PINNERS": 10005,
    "BELLEVILLE LITTLE DE": 23,
    "BELVIDERE BANDITS": 24,
    "BENTON JR. WC": 26,
    "BETHALTO JR HIGH": 10118,
    "BISMARK-HENNING WC": 28,
    "BOYS & GIRLS CLUB": 319,
    "BRAWLERS WC": 39,
    "BRONCO WRESTLING": 41,
    "CAMP POINT CENTRAL": 50,
    "CARBONDALE WC": 53,
    "CARLINVILLE KIDS WC": 54,
    "CARY JR TROJAN MATME": 59,
    "CENTRALIA WC": 64,
    "CHAMPAIGN CHARGER KD": 10124,
    "CHAMPAIGN CHARGER KI": 10124,
    "CHARLESTON WC": 69,
    "CHENOA MAT CATS": 10011,
    "CHILLICOTHE WC": 10014,
    "CRYSTAL LAKE WIRZARD": 89,
    "CRYSTAL LAKE WIZARDS": 89,
    "CUMBERLAND YOUTH WC": 90,
    "DAKOTA WC": 92,
    "DECATUR WC": 10137,
    "DIXON WC": 98,
    "DUNDEE CARPETERVILL": 10163,
    "DUNDEE HIGHLANDERS": 102,
    "DURAND-PECATONICA": 105,
    "EAST MOLINE PANTHER": 10121,
    "EDISON PANTHERS": 10131,
    "EDWARDSVILLE WC": 110,
    "ERIE MIDDLE SCHOOL W": 10025,
    "EUREKA KIDS WC": 117,
    "FALCON YOUTH WC": 123,
    "FISHER WC": 130,
    "FOX VALLEY CRONE WC": 10162,
    "FOX VALLEY WC": 134,
    "FRANKLIN PARK RAIDER": 10138,
    "GALESBURG JR STRK 2": 10030,
    "GENERALS": 10144,
    "GENESEO WC": 10033,
    "GLEN ELLYN DUNGEON W": 10039,
    "GLENBARD EAST JR RAM": 147,
    "GLENBARD EST JR RAMS": 147,
    "GRAPPLIN DEVILS WC": 153,
    "GRAPPLIN'DEVILS WC": 153,
    "HARLEM COUGARS": 10041,
    "HIGHLAND BULLDOG JR": 168,
    "HILLSBORO JR TOPPERS": 170,
    "HINSDALE RED DEVIL W": 171,
    "HINSDALE RED DEVILS": 171,
    "HONONEGAH KIDS WC": 173,
    "HOOPESTON AREA WC": 174,
    "HUSKIES WC": 10145,
    "ILLINI BLUFFS WC": 181,
    "JACKSONVILLE WC": 189,
    "JACOBS FALCONS": 10161,
    "JR GOLDEN EAGLES": 10050,
    "JR MAROON WC": 538,
    "JR ROCKET WRESTLING": 10052,
    "JR SENTINELS": 10054,
    "JUNIOR PIRATE WC": 201,
    "JUNIOR ROCKS WRESTLI": 10160,
    "L-P CRUNCHING CAVS": 241,
    "LAKE VIEW JR WILDCAT": 10159,
    "LAKE VILLA LANCERS": 10141,
    "LAKELAND PREDATORS": 10057,
    "LAWRENCE COUNTY WC": 217,
    "LEMONT BEARS WC": 219,
    "LIL STORM YOUTH": 10060,
    "LIMESTONE YOUTH ROCK": 10061,
    "LITTLE BOILER WC": 232,
    "LITTLE CELTIC WC": 233,
    "LITTLE INDIANS": 10063,
    "LITTLE REDBIRD WC": 10065,
    "MACOMB KIDS WRESTLIN": 243,
    "MAINE EAGLES WC": 245,
    "MANTENO JR PANTHERS": 247,
    "MARENGO WC": 248,
    "MARTINEZ FOX VALLEY": 250,
    "MATTOON YOUTH WC": 252,
    "MENDOTA MAT MASTERS": 10072,
    "METAMORA KIDS WC": 262,
    "METRO STALLIONS": 10142,
    "MIDWEST CENTRAL YOUT": 263,
    "MORTON YOUTH WRESTLI": 272,
    "MT VERNON LIONS": 275,
    "MT ZION WC": 276,
    "MURPHYSBORO WRESTLIN": 278,
    "NAPERVILLE EAGLES": 10133,
    "NAPERVILLE LANCERS": 10157,
    "NAPERVILLE WARHAWKS": 10158,
    "NAPERVILLE WC": 281,
    "OAK LAWN P.D. WILDCA": 10075,
    "OAK LAWN PD WILDCATS": 10075,
    "OAKWOOD WC": 299,
    "ORLAND PARK PIONEERS": 306,
    "OSWEGO COUGARS": 10136,
    "OSWEGO PANTHERS": 10076,
    "PANTHER CUB WC": 10079,
    "PINCKNEYVILLE JR": 10122,
    "PLAINFIELD WC": 326,
    "PLAINFIELD WOLVES WC": 10155,
    "PLANIFIELD HUSKIES W": 10156,
    "PLT PROPHETS WC": 10127,
    "POLO WC": 327,
    "PONTIAC PYTHONS": 10082,
    "PONY EXPRESS WC": 10154,
    "RAMS WC": 236,
    "RICHMOND WC": 350,
    "RIVERBEND WC": 354,
    "RIVERDALE JR HIGH": 10153,
    "ROCHELLE WC": 358,
    "ROCK FALLS RIPPIN": 10152,
    "ROCKFORD WC": 364,
    "ROXANA KIDS WC": 371,
    "SAUKEE YOUTH WC": 376,
    "SAVANNA REDHAWKS": 10089,
    "SHARKS WC": 381,
    "SHELBYVILLE JUNIOR R": 382,
    "SHERRAND JR WC": 383,
    "SHO YOUTH WRESTLING": 402,
    "SJO YOUTH WRESTLING": 402,
    "SOUTHERN IL EAGLES": 10092,
    "SOUTHERN ILLINOIS EA": 10092,
    "SOUTHSIDE WC": 10140,
    "SPRINGFIELD CAPTIALS": 397,
    "ST BEDE WC": 10095,
    "STATELINE WILDCATS": 10097,
    "STERLING NEWMAN JR": 10098,
    "STILLMAN VALLEY WC": 407,
    "TAYLORVILLE WC": 420,
    "TIGER WC": 10103,
    "TIGERTOWN TANGLERS": 441,
    "TINLEY PARK BULLDOGS": 443,
    "TRI-CITY BRAVES": 10104,
    "UNITY WRESTLING CLUB": 457,
    "VANDALIA JR WRESTLIN": 461,
    "VILLA LOMBARD COUGAR": 10109,
    "VILLA PARK YOUNG": 464,
    "VITTUM CATS": 466,
    "WARRENSBURG WC": 468,
    "WASHINGTON JR PANTHE": 10110,
    "WAUBONSIE BULLDOGS": 10149,
    "WAUBONSIE TRAILBLAZE": 10151,
    "WAUONSIE GRIZZLIES": 10150,
    "WEST CHICAGO PD": 10148,
    "WEST FRANKFORT JR WC": 478,
    "WESTVILLE YOUTH WC": 482,
    "WHEATON BULLDOGS": 10120,
    "WHEATON MONROE EAGLE": 10114,
    "WHEATON WC": 234,
    "WOLFPAK WC": 490,
    "WRESTLING FACTORY": 10115,
    "YORKVILLE WC": 497,
    "YOUNG CHAMPIONS": 10116,
}


def main():
    with open(HERE / "extracted.2001.json") as file_obj:
        extracted = bracket_utils.WeightClasses.model_validate_json(file_obj.read())

    weight_classes = extracted.root
    bracket_utils.print_division_team_scores(weight_classes, "novice")
    print("**************************************************")
    bracket_utils.print_division_team_scores(weight_classes, "senior")
    print("**************************************************")
    bracket_utils.validate_acronym_mappings(
        weight_classes,
        TEAM_ACRONYM_MAPPING,
        NOVICE_TEAM_ACRONYM_MAPPING,
        SENIOR_TEAM_ACRONYM_MAPPING,
        TEAM_NAME_MAPPING,
    )
    print("**************************************************")
    unclassified = sorted(
        name for name, team_id in TEAM_NAME_MAPPING.items() if team_id < 0
    )
    for i, name in enumerate(unclassified):
        print(f"{i + 1}: {name}")


if __name__ == "__main__":
    main()
