# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
TEAM_ACRONYM_MAPPING = {
    "AOK": "A-O KIDS WC",
    "BAD": "BADGER WC",
    "BAR": "TODO",
    "BAT": "BATAVIA PINNERS",
    "BB": "BELVIDERE BANDITS",
    "BBW": "bradley bourbonnais",  # TODO
    "BGP": "BOYS & GIRLS CLUB",  # ... of Pekin
    "BH": "BISMARCK-HENNING WC",
    "BJH": "BETHALTO JR HIGH",
    "BJW": "BENTON JR. WC",
    "BLD": "BELLEVILLE LITTLE DE",
    "BRO": "BRONCO WRESTLING",
    "CCK": "CHAMPAIGN CHARGER KI",
    "CDW": "Chillicothe?",  # TODO / CHILLI DAWGS WC
    "CEN": "CENTRALIA WC",
    "CHE": "CHENOA MAT CATS",
    "CJT": "CARY JR TROJAN MATME",
    "CLW": "CRYSTAL LAKE WIZARDS",
    "CW": "CROSSFACE WRESTLING",
    "CYW": "CUMBERLAND YOUTH WC",
    "DAK": "DAKOTA WC",
    "DEC": "DECATUR WC",
    "DGC": "TODO",
    "DH": "DUNDEE HIGHLANDERS",
    "DPC": "DURAND-PECATONICA",
    "EBK": "TODO",
    "EMP": "EAST MOLINE PANTHER",
    "EMS": "ERIE MIDDLE SCHOOL W",
    "EP": "EDISON PANTHERS",  # Wheaton / 10131
    "EWC": "EDWARDSVILLE WC",
    "FAW": "TODO",
    "FBG": "TODO",
    "FPR": "FRANKLIN PARK RAIDER",
    "FVW": "FOX VALLEY WC",
    "FWC": "FISHER WC",
    "FYW": "FALCON YOUTH WC",
    "GDW": "GRAPPLIN DEVILS WC",
    "GED": "GLEN ELLYN DUNGEON W",
    "GEJ": "GLENBARD EAST JR RAM",
    "GEN": "GENERALS",
    "GJS": "GALESBURG JR STREAKS",
    "GWC": "GENESEO WC",
    "HAW": "HOOPESTON AREA WC",
    "HBJ": "HIGHLAND BULLDOG JR",
    "HC": "HARLEM COUGARS",
    "HIL": "TODO",
    "HJT": "HILLSBORO JR TOPPERS",
    "HON": "HONONEGAH KIDS WC",
    "HPL": "TODO",
    "HRD": "HINSDALE RED DEVILS",
    "HUS": "HUSKIES WC",
    "IB": "ILLINI BLUFFS WC",
    "JAC": "JACKSONVILLE WC",
    "JGE": "JR GOLDEN EAGLES",
    "JRB": "TODO",
    "JRM": "JR MAROON WC",
    "JRW": "JR ROCKET WRESTLING",
    "JS2": "GALESBURG JR STREAKS 2",  # TODO: Verify
    "LB": "LEMONT BEARS WC",
    "LC": "LITTLE CELTIC WC",
    "LCW": "LAWRENCE COUNTY WC",
    "LKW": "TODO",
    "LLP": "LAKELAND PREDATORS",
    "LPC": "L-P CRUNCHING CAVS",
    "LRB": "LITTLE REDBIRD WC",
    "LSW": "LIL STORM YOUTH",
    "LVL": "LAKE VILLA LANCERS",
    "LYW": "LIMESTONE YOUTH ROCK",
    "MAR": "MARENGO WC",
    "MAT": "MATTOON YOUTH WC",
    "MCY": "MIDWEST CENTRAL YOUT",
    "ME": "MAINE EAGLES WC",
    "MET": "METAMORA KIDS WC",
    "MFV": "MARTINEZ FOX VALLEY",
    "MK": "TODO",
    "MKW": "MACOMB KIDS WRESTLIN",
    "MMM": "TODO",
    "MON": "TODO",
    "MOR": "MORTON YOUTH WRESTLI",
    "MS": "METRO STALLIONS",
    "MTV": "MT VERNON LIONS",
    "MTZ": "MT ZION WC",
    "MUR": "MURPHYSBORO WRESTLIN",
    "NAP": "NAPERVILLE WC",
    "NE": "NAPERVILLE EAGLES",
    "OAK": "OAKWOOD WC",
    "OC": "OSWEGO COUGARS",
    "OLW": "OAK LAWN PD WILDCATS",
    "OPP": "ORLAND PARK PIONEERS",
    "OSP": "OSWEGO PANTHERS",
    "PCW": "PANTHER CUB WC",
    "PIN": "PINCKNEYVILLE JR",
    "POL": "POLO WC",
    "PPW": "PONTIAC PYTHONS",
    "PR": "TODO",
    "PWC": "PLAINFIELD WC",
    "RAM": "RAMS WC",
    "RCK": "TODO",
    "RFW": "TODO",
    "RIV": "RIVERBEND WC",
    "RJH": "RIVERDALE JR HIGH",
    "ROC": "ROCHELLE WC",
    "ROX": "ROXANA KIDS WC",
    "RWC": "ROCKFORD WC",
    "SAN": "TODO",
    "SC": "SPRINGFIELD CAPITALS",
    "SHA": "SHARKS WC",
    "SHE": "SHERRARD JR WC",
    "SIE": "SOUTHERN IL EAGLES",
    "SII": "TODO",
    "SJO": "SJO YOUTH WRESTLING",
    "SJW": "SHELBYVILLE JR RAMS",
    "SN": "STERLING NEWMAN JR",
    "SSW": "SOUTHSIDE WC",
    "STB": "ST BEDE WC",
    "STC": "TODO",
    "SVW": "STILLMAN VALLEY WC",
    "SW": "STATELINE WILDCATS",
    "SYW": "SAUKEE YOUTH WC",
    "T1": "TODO",  # TEAM EL1TE WRESTLING ?? (Bloomingdale)
    "TAY": "TAYLORVILLE WC",
    "TAZ": "TODO",
    "TCB": "TRI-CITY BRAVES",
    "TPB": "TINLEY PARK BULLDOGS",
    "TRI": "TODO",
    "TTT": "TIGERTOWN TANGLERS",
    "TWC": "TIGER WC",
    "UNI": "UNITY WRESTLING CLUB",
    "VAN": "VANDALIA JR WRESTLIN",
    "VC": "VITTUM CATS",
    "VLC": "VILLA LOMBARD COUGAR",
    "VPY": "VILLA PARK YOUNG",
    "WB": "WHEATON BULLDOGS",
    "WES": "WESTVILLE YOUTH WC",
    "WF": "WEST FRANKFORT JR WC",
    "WFL": "WRESTLING FACTORY",
    "WJP": "WASHINGTON JR PANTHE",
    "WME": "WHEATON MONROE EAGLE",
    "WWC": "WOLFPAK WC",
    "YWC": "YORKVILLE WC",
}


def main():
    with open(HERE / "extracted.2000.json") as file_obj:
        extracted = json.load(file_obj)

    raise NotImplementedError(len(extracted))


if __name__ == "__main__":
    main()
