-- Copyright (c) 2025 - Present. IKWF History. All rights reserved.

PRAGMA foreign_keys = ON;
PRAGMA encoding = 'UTF-8';
PRAGMA integrity_check;

--------------------------------------------------------------------------------

-- NOTE: The following IDs are **mostly** from the IKWF website (2025-03-11).
--       Club information: https://www.ikwf.org/viewClubInfo.php?id=:id
--       There are clubs for IDs 1-686, except for 11 deleted IDs: 29, 159,
--       312, 432, 472, 476, 504, 505, 578, 599, 666. Among the 675 IDs that
--       are present, 340 are Active, 28 Inactive, and 307 are Old.
--
--       The https://www.ikwf.org/clubs/ page loads data via
--       https://www.ikwf.org/getClubs.php?q=:pageNumber, which is how the full
--       list of club IDs (maximum ID) was retrieved.
--
--       Any club with ID greater than 10000 is a historical club from the
--       `raw-data/` in years 2003, 2004, 2005, and 2006.
--
--       We made a few edits to the
--       * Club 283 renamed from `Next Level Wrestling` to `Next Level Wrestling (Norridge)`
--       * Club 558 (`None`) not included

INSERT INTO
  team (name, id)
VALUES
  ('239 Athletics, LLC',                               634),
  ('2nd Athlete Regiment, USAC',                       1),
  ('815 Stateline Wrestling Club',                     673),
  ('A & M Youth Wrestling',                            2),
  ('A-J Junior Wildcats',                              10001), -- Anna-Jonesboro
  ('ACE of Spades Wrestling',                          585),
  ('Aces Wrestling Club',                              3),
  ('Addison Street Wrestling Club',                    520),
  ('AJ Jr. Wildcats Wrestling Club',                   4),
  ('Alber Athletics Wrestling Club',                   569),
  ('Aledo Bear Country WC',                            10002),
  ('Alleman Junior Pioneer WC',                        10003),
  ('Alpha Troop Wrestling',                            540),
  ('Alpha Wrestling Academy',                          5),
  ('Alton Little Redbirds Wrestling Club',             6),
  ('Anchor Wrestling',                                 674),
  ('Animals WC',                                       10004),
  ('Animus Extreme Wrestling',                         7),
  ('Ano Kato FSGR Wrestling',                          529),
  ('Antioch Predators Wrestling Club',                 215),
  ('Apex Wrestling Club',                              523),
  ('Argenta-Oreana Kids Wrestling Club',               8),
  ('Arlington Cardinals Wrestling Club',               9),
  ('Arlington Heights Hersey War Dogs WC',             622),
  ('Assumption Elite WC',                              545),
  ('Astro Wrestling Club',                             10),
  ('Attrition Wrestling Club',                         11),
  ('ATTWarHawks Wrestling Club',                       12),
  ('Aurora Wrestling Club',                            586),
  ('Backyard Brawlers Midwest',                        626),
  ('Backyard Brawlers North Wrestling',                628),
  ('Backyard Brawlers West Wrestling',                 627),
  ('Bad Bass Wrestling',                               13),
  ('Badger Wrestling Club',                            14),
  ('Barrington Broncos Wrestling Club',                15),
  ('Bartlett Jr Hawks Wrestling Club',                 16),
  ('Batavia Pinners',                                  10005),
  ('Batavia Wrestling Club',                           17),
  ('Bearcat Wrestling Club',                           257),
  ('Beast Wrestling',                                  19),
  ('Beat the Streets Chicago-Avondale',                611),
  ('Beat the Streets Chicago-Bellwood',                612),
  ('Beat the Streets Chicago-Hyde Park',               613),
  ('Beat the Streets Chicago-Midway',                  20),
  ('Beat the Streets Chicago-Norwood Park',            614),
  ('Beat The Streets Chicago-NTA',                     650),
  ('Beat the Streets Chicago-Oak Park',                615),
  ('Beat the Streets Chicago-Roseland',                649),
  ('Beat the Streets Chicago-Tri Taylor',              629),
  ('Beebe Trained',                                    21),
  ('Bees Wrestling Club',                              668),
  ('Belleville Junior Hit Squad',                      22),
  ('Belleville Little Devils Wrestling Club',          23),
  ('Belvidere Bandits Wrestling Club',                 24),
  ('Belvidere Wrestling Club',                         526),
  ('Benefiel Wrestling',                               25),
  ('Benton Wrestling Club',                            26),
  ('Berta Wrestling Academy (BWA)',                    27),
  ('Bethalto Bulls WC',                                10006),
  ('Big Chief Wrestling Club',                         609),
  ('Bismarck-Henning Youth Wrestling Club',            28),
  ('Bison Wrestling Club',                             126),
  ('Black Kats WC',                                    10007),
  ('Black Ops WC',                                     624),
  ('Blackcat Wrestling',                               537),
  ('Blackhawk Wrestling Club',                         30),
  ('Blazer Kids',                                      10008),
  ('Bloomingdale Bears Wrestling Club',                669),
  ('Bloomington Combat Club',                          31),
  ('Bloomington Junior Eagle Wrestling Club',          510),
  ('Bloomington Raider Wrestling Club',                32),
  ('Blue Island Little Cardinals',                     33),
  ('Blue Line Training Academy',                       142),
  ('Bluejay Wrestling Club',                           34),
  ('Bolingbrook Junior Raiders Wrestling Club',        35),
  ('Boumans Academy of Wrestling',                     36),
  ('Bradley Bourbonnais Wrestling Club',               37),
  ('Braves Wrestling Club',                            38),
  ('Brawlers Wrestling Club',                          39),
  ('Bremen Wrestling Club',                            40),
  ('Bronco Wrestling Club',                            41),
  ('BTS Chicago-Screaming Eagles',                     42),
  ('BTS-Chicago St. Sabina',                           44),
  ('BTS-Pequenos Patriotas',                           45),
  ('Built By Brunson Wrestling',                       438),
  ('Bulldog Elite Wrestling Club',                     46),
  ('Bulldog Youth Sports Wrestling',                   47),
  ('Bulls Wrestling Club',                             48),
  ('C''Ville Raider Wrestling Club',                   338),
  ('Callan Wrestling Academy',                         550),
  ('Calumet Memorial PD Wolverines',                   49),
  ('Camp Point Central Youth Wrestling Club',          50),
  ('Camp Point Youth Wrestling',                       51),
  ('Caravan Kids Wrestling Club',                      52),
  ('Carbondale Junior Spirits',                        10009),
  ('Carbondale Wrestling Club',                        53),
  ('Cardinal WC',                                      556),
  ('Cardinals Wrestling Club',                         605),
  ('Carlinville Wrestling Club',                       54),
  ('Carlson Gracie Wrestling',                         55),
  ('Carlyle Wrestling Club',                           56),
  ('Carmi Junior Bulldogs',                            57),
  ('Carterville Wrestling Club',                       58),
  ('Carthage Wrestling Club',                          678),
  ('Cary-Grove Matmen',                                59),
  ('Catalyst Wrestling Club',                          566),
  ('Celtic Elite',                                     60),
  ('Celtic Wrestling Academy',                         671),
  ('Celtics Wrestling Club',                           502),
  ('Central Elite Rebels',                             61),
  ('Central Illinois Bulldogs Wrestling Club',         580),
  ('Central Illinois Regional Training Center',        62),
  ('Central Illinois Wrestling',                       70),
  ('Central Illinois Wrestling Academy',               63),
  ('Central Wrestling Club',                           10010),
  ('Centralia Wrestling Club',                         64),
  ('Champaign Wrestling Club',                         65),
  ('Champbuilders Wrestling',                          66),
  ('Champions 4 Life Wrestling Club',                  503),
  ('Champions Wrestling Club',                         67),
  ('Charger Wrestling Club',                           68),
  ('Charleston Wrestling Club',                        69),
  ('Chatham Wrestling Club',                           604),
  ('Chenoa Mat Cats',                                  10011),
  ('Chicago Bulldog WC',                               10012),
  ('Chicago Crusaders Wrestling Club',                 71),
  ('Chicago Knights',                                  10013),
  ('Chicago Park District',                            72),
  ('Chicago Skyline',                                  74),
  ('Chicago Trained',                                  522),
  ('Chicago Wolfpack Wrestling Club',                  179),
  ('Chicago Wolves Den',                               75),
  ('Chicago Wrestling Club',                           76),
  ('Chilli Dawgs WC',                                  10014),
  ('CICC',                                             77),
  ('Classic Wrestling School',                         78),
  ('Clinton Wrestling Club',                           79),
  ('Clipper Wrestling Club',                           80),
  ('CNH Heavy Hitters Wrestling',                      81),
  ('Coal City Diamonds Wrestling Club',                82),
  ('Coal City Kids WC',                                10015),
  ('Cogs Wrestling Club',                              665),
  ('Cohen Brothers Wrestling',                         645),
  ('Collinsville Raiders',                             10016),
  ('Collinsville Wrestling Club',                      197),
  ('Combative Sports Athletic Center Wrestling',       521),
  ('Contender Wrestling',                              83),
  ('Cortese Wrestling Club',                           607),
  ('Cory Clark Wrestling',                             625),
  ('Counter Wrestling Club',                           84),
  ('Cowboy WC',                                        85),
  ('Crawford County Wrestling Club',                   86),
  ('Crimson Heat WC',                                  10017),
  ('Crossface Wrestling',                              10018),
  ('Crosstown Crushers',                               10019),
  ('Crosstown Spartan Elite Wrestling Club',           87),
  ('Crusaders'' Elite',                                88),
  ('Crystal Lake Wizards Wrestling Club',              89),
  ('Cumberland Youth Wrestling Club',                  90),
  ('Cutlass Wrestling Club',                           635),
  ('Dakota Wrestling Club',                            92),
  ('Danville Chargers Wrestling Club',                 93),
  ('Dark Horse Wrestling Club',                        94),
  ('DAWC',                                             91),
  ('Dawgs Wrestling Club',                             95),
  ('DC Wrestling Club',                                548),
  ('Decatur Dawgs Wrestling Club',                     644),
  ('Decatur Lakers Wrestling Club',                    663),
  ('DeKalb Wrestling Club',                            96),
  ('Demolition Wrestling Club',                        577),
  ('Dinamo Wrestling',                                 97),
  ('Dixon Wrestling Club',                             98),
  ('Dolton Park District Falcons',                     99),
  ('Doom Wrestling',                                   546),
  ('Downers Grove Cougars WC',                         100),
  ('Downers Grove Wrestling Club',                     101),
  ('Dragons Lair Wrestling Club',                      651),
  ('Du-Pec Carnivores',                                10020),
  ('Du-Pec Wrestling Club',                            105),
  ('Dubtown Wrestling Club',                           416),
  ('Dundee Highlanders WC',                            102),
  ('Dungeon Wrestling Club',                           103),
  ('DuPage Wrestling Club',                            104),
  ('Dwight Wrestling Club',                            106),
  ('East Alton Wood River Jr. Oilers',                 107),
  ('East Peoria Crossface WC',                         108),
  ('East Peoria River Bandits Wrestling',              584),
  ('East St. Louis Wrestling Club',                    109),
  ('Edwardsville Wrestling Club',                      110),
  ('Effingham Junior WC',                              10021),
  ('Effingham Youth Wrestling Club',                   111),
  ('El Paso Gridley Youth Wrestling Club',             112),
  ('El Paso WC',                                       10022),
  ('Elevate Wrestling Academy',                        543),
  ('Elgin Mighty Maroons',                             10023),
  ('Elite Central Illinois WC',                        113),
  ('Elk Grove Junior Grens Wrestling Club',            114),
  ('Elmhurst Junior Dukes',                            10024),
  ('Elmhurst Titans Wrestling Academy',                570),
  ('Elmhurst Wrestling Club',                          115),
  ('Empire Academy',                                   653),
  ('Englewood Live Wire Wrestling Club',               300),
  ('Epic Wrestling',                                   116),
  ('Eremeiv Olympia Wrestling Academy',                652),
  ('Erie Middle School WC',                            10025),
  ('Ervin WC',                                         10026),
  ('Eureka Wrestling Club',                            117),
  ('Evanston School of Wrestling',                     118),
  ('Evergreen Park Stallions WC',                      119),
  ('Extreme Wrestling Levels',                         121),
  ('Fairfield Jr Mat Mules',                           122),
  ('Fairmont Rough Riders',                            10027),
  ('Falcon Youth Wrestling',                           123),
  ('Falcons Wrestling Club',                           124),
  ('Farmington Youth Wrestling',                       125),
  ('FCA Force Wrestling Club',                         539),
  ('Fenwick Falcons WC',                               10028),
  ('Fifth Freedom Wrestling Club',                     127),
  ('Fightin'' Titan WC RTC',                           682),
  ('Fighting Farmers Wrestling Club',                  579),
  ('Fighting Titans',                                  128),
  ('Fisher Wrestling Club',                            130),
  ('Fit & Fight Gym WC',                               630),
  ('Fitz Wrestling Academy',                           131),
  ('Force Elite Wrestling Club',                       132),
  ('Ford Heights Falcons',                             10029),
  ('Fox Lake Wrestling Club',                          133),
  ('Fox Valley Wrestling Club',                        134),
  ('Frankfort Gladiator Wrestling',                    506),
  ('Frankfort Wildcats Wrestling',                     135),
  ('Freeburg Blue Rage Wrestling Club',                136),
  ('Friar Wrestling Club',                             137),
  ('Fuel Wrestling Club',                              138),
  ('G2 WC',                                            140),
  ('Galena Grizzlies',                                 618),
  ('Galesburg Junior Streaks',                         10030),
  ('Gators Elite WC',                                  606),
  ('Gators Wrestling Club',                            141),
  ('GC Junior Warriors',                               10031),
  ('Geneseo Spider WC',                                10032),
  ('Geneseo WC',                                       10033),
  ('Geneva Junior Vikings',                            143),
  ('Geneva WC',                                        10034),
  ('Gentry Wrestling',                                 145),
  ('Georgetown Rude Dogs Youth WC',                    10035),
  ('Georgetown Youth WC',                              10036),
  ('Germantown WC',                                    10037),
  ('GK Wrestling Club',                                144),
  ('Gladiator Elite Wrestling Club',                   146),
  ('Gladiators',                                       10038),
  ('Glen Ellyn Dungeon WC',                            10039),
  ('Glenbard East Jr Rams Wrestling Club',             147),
  ('Glenbard South Junior Raiders',                    148),
  ('Golden Eagles Wrestling Club',                     149),
  ('Gomez Wrestling Academy',                          150),
  ('Gomez Wrestling RTC',                              647),
  ('Granby Style Wrestling',                           594),
  ('Grandpa''s Gang',                                  151),
  ('Granite City Junior Warriors',                     10040),
  ('Granite City Wrestling Association',               152),
  ('Grapplin'' Devils Wrestling Club',                 153),
  ('Grayslake Youth Wrestling Club',                   154),
  ('Greenfield Wrestling Academy',                     524),
  ('Greg Gomez Trained Wrestling',                     155),
  ('Guerrero''s Garage Wrestling',                     533),
  ('Hammer Wrestling School',                          156),
  ('Hampshire Wrestling Club',                         157),
  ('Harlem Cougars',                                   10041),
  ('Harlem Huskies WC',                                158),
  ('Harrisburg Junior Bulldogs',                       160),
  ('Harvard Wrestling Club',                           161),
  ('Harvey Twisters WC',                               162),
  ('Hawk Wrestling Club',                              163),
  ('Hawks Wrestling Club',                             620),
  ('Headlock Wrestling Academy',                       164),
  ('Hecox Team Benaiah',                               165),
  ('Herrin Junior WC',                                 10042),
  ('Herrin Tiger Wrestling',                           166),
  ('HF Elite WC',                                      508),
  ('HF Spartan Elite WC',                              167),
  ('Highland Bulldog Jr. Wrestling Club',              168),
  ('Highland Park Little Giants',                      10043),
  ('Hillsboro Jr Toppers Wrestling Club',              170),
  ('Hilltoppers WC',                                   10044),
  ('Hinsdale Red Devil WC',                            171),
  ('Hoffman Estates Wrestling Club',                   172),
  ('Homewood-Flossmoor RTC',                           638),
  ('Hononegah Wrestling Club',                         173),
  ('Hoopeston Area Youth Wrestling',                   174),
  ('Hoopeston Intermediate Wrestling',                 175),
  ('Howe Jets',                                        176),
  ('HP Little Giants Wrestling Club',                  169),
  ('HPL Wrestling',                                    567),
  ('Hurricanes',                                       10045),
  ('Husky Wrestling Club',                             177),
  ('Hybrid Wrestling Club',                            178),
  ('Iguana Wrestling Club',                            180),
  ('ILLest Wrestling Club',                            590),
  ('Illini Bluffs Kids Wrestling Club',                181),
  ('Illini Elite Wrestling Club',                      182),
  ('Illini Kids Wrestling - IKWC',                     183),
  ('Illinois American Gladiators Wrestling',           589),
  ('Illinois Regional Training Center/Illini WC',      184),
  ('Illinois Southern Elite Wrestling Club',           185),
  ('Illinois Valley Elite Wrestling',                  186),
  ('Illinois Valley Wrestling Club',                   541),
  ('Impact Wrestling',                                 654),
  ('Irish Wrestling Club',                             224),
  ('Iron Man',                                         10046),
  ('ISI School of Wrestling',                          187),
  ('ISI Wrestling Club',                               573),
  ('Izzy Style Wrestling',                             188),
  ('J.R. Warrior Wrestling Club',                      675),
  ('Jacksonville Area Wrestling',                      189),
  ('Jaguar Wrestling Club',                            190),
  ('Jasper County Youth Wrestling',                    509),
  ('Jersey Junior Panthers Wrestling',                 191),
  ('Joliet Area Wrestling Club',                       404),
  ('Joliet Boys Club Cobras',                          10047),
  ('Joliet Junior Steelmen',                           10048),
  ('Joliet WC',                                        192),
  ('Junior Blazers',                                   193),
  ('Junior Bronco Wrestling Club',                     571),
  ('Junior Bulldog Wrestling Club',                    194),
  ('Junior Comanche Wrestling Club',                   195),
  ('Junior Cougar Wrestling Club',                     196),
  ('Junior Cyclones Wrestling Club',                   398),
  ('Junior Gators WC',                                 10049),
  ('Junior Golden Eagles',                             10050),
  ('Junior Maroons WC',                                538),
  ('Junior Mustangs',                                  10051),
  ('Junior Panthers',                                  198),
  ('Junior Patriots Wrestling Club',                   199),
  ('Junior Pioneer Wrestling Club',                    200),
  ('Junior Pirates Wrestling Club',                    201),
  ('Junior Raiders West Wrestling Club',               582),
  ('Junior Rocket WC',                                 10052),
  ('Junior Saxons WC',                                 10053),
  ('Junior Sentinels WC',                              10054),
  ('Junior Titans Wrestling',                          203),
  ('Junior Vikings',                                   10055),
  ('Junior Warrior Wrestling Club',                    204),
  ('Junk Yard Dogs Wrestling Club',                    205),
  ('Just Wrestling',                                   535),
  ('Katana Wrestling',                                 677),
  ('Kennedy Knights',                                  207),
  ('King Cobras',                                      208),
  ('King Select Wrestling',                            209),
  ('Kishwaukee WC',                                    10056),
  ('Klub PowderKeg WC',                                210),
  ('Knights Wrestling Club',                           206),
  ('Knox County Krushers',                             211),
  ('Lake County Stallions Wrestling Academy',          643),
  ('Lake County Wrestling Club',                       212),
  ('Lake Forest Mat Club',                             213),
  ('Lake Zurich Cubs Wrestling Club',                  214),
  ('Lakeland Predators',                               10057),
  ('Lancer Wrestling Club',                            216),
  ('LaSalle Peru Crunching Cavs Youth WC',             241),
  ('Lawrence County Knights WC',                       217),
  ('Lee Kemp Academy of Wrestling',                    218),
  ('Legacy Wrestling Academy',                         593),
  ('Lemont Bears WC',                                  219),
  ('Leroy Wrestling Kids Club',                        10058),
  ('Lil'' Trojan Wrestling Club',                      220),
  ('Libertyville Wrestling Club',                      221),
  ('Lil'' Reaper Wrestling Club',                      223),
  ('Lil'' Coalers Wrestling Club',                     222),
  ('Lil'' Roughnecks',                                 10059),
  ('Lil'' Storm Youth WC',                             10060),
  ('Limestone Crusher Wrestling Club',                 225),
  ('Limestone Wrestling Club',                         632),
  ('Limestone Youth Rocket WC',                        10061),
  ('Lincoln RTC',                                      559),
  ('Lincoln Youth Wrestling Club',                     226),
  ('Lincoln-Way Wrestling Club',                       227),
  ('Lindblom Wrestling Club',                          43),
  ('Lion''s Den Wrestling Academy',                    547),
  ('Lionheart Intense Wrestling',                      228),
  ('Lions Wrestling Club',                             229),
  ('Lions Wrestling Elgin',                            230),
  ('Lisle Wrestling Club',                             681),
  ('Litchfield Wrestling Club',                        231),
  ('Little Boilers Wrestling Club',                    232),
  ('Little Celtic Wrestling Club',                     233),
  ('Little Falcons WC',                                10062),
  ('Little Giants WC',                                 641),
  ('Little Huskies Wrestling Club',                    235),
  ('Little Indians WC',                                10063),
  ('Little Panthers WC',                               10064),
  ('Little Rams Wrestling Club',                       340),
  ('Little Redbird WC',                                10065),
  ('Little Redskins WC',                               10066),
  ('Little Saints Wrestling Club',                     238),
  ('Little Tigers Wrestling Club',                     239),
  ('Little Vikings of H-F',                            10067),
  ('Lockport Gators WC',                               10068),
  ('Lockport Junior Porters WC',                       202),
  ('Longwood Wrestling Club',                          240),
  ('Los Guerreros WC',                                 631),
  ('Lynwood Pirates Wrestling Club',                   242),
  ('M-S Kids Club',                                    10069),
  ('Macomb Little Bombers Wrestling',                  243),
  ('MadDog Wrestling Academy',                         244),
  ('Maine Eagles WC',                                  245),
  ('Maine East Raptors WC',                            246),
  ('Manteno Jr Panthers Wrestling Club',               247),
  ('Marengo Youth Wrestling Club',                     248),
  ('Marion Mat Sharks WC',                             249),
  ('Marshall Red Rush Wrestling',                      683),
  ('Martinez Fox Valley Elite Wrestling Club',         250),
  ('Mascoutah Little Indians',                         534),
  ('Mat Rat Wrestling Club',                           465),
  ('Matburns Wrestling Club',                          555),
  ('Matt''s Militia',                                  251),
  ('Mattoon Youth Wrestling Club',                     252),
  ('Maywood Bandits',                                  253),
  ('Maywood Bucs',                                     254),
  ('Maywood Junior Pirates',                           255),
  ('MC Bulldog Wrestling Club',                        256),
  ('McHenry Wrestling Club',                           527),
  ('McKendree University Wrestling',                   258),
  ('McLean County WC',                                 10070),
  ('Mean Green Machine',                               259),
  ('Medalist WC',                                      10071),
  ('Mendota Mat Masters',                              10072),
  ('Mendota Wrestling Club',                           261),
  ('Mendota YMCA Mat Masters WC',                      260),
  ('Mercer County Wrestling Club',                     18),
  ('Meridian Hawks Youth Wrestling Club',              637),
  ('Metamora Kids Wrestling Club',                     262),
  ('Midway WC',                                        676),
  ('Midwest Central Youth WC',                         263),
  ('Midwest Titans Wrestling Club',                    264),
  ('Milo',                                             265),
  ('Minooka Indians Elite',                            266),
  ('MMA Stop H.E.A.T.',                                267),
  ('Moline Wrestling Club',                            268),
  ('Monticello Youth Wrestling Club',                  269),
  ('Morris Wrestling Club',                            237),
  ('Morrison Stallions Wrestling Club',                270),
  ('Morton Little Mustangs',                           271),
  ('Morton Youth Wrestling Club',                      272),
  ('MS Youth Wrestling Club',                          273),
  ('Mt. Olive Cats Kids Wrestling',                    274),
  ('Mt. Pulaski WC',                                   10073),
  ('Mt. Vernon Lions Wrestling',                       275),
  ('Mt. Zion Kids Wrestling Club',                     276),
  ('Mundelein Wrestling Club',                         277),
  ('Murdale Wrestling Club',                           588),
  ('Murphysboro Wrestling',                            278),
  ('Mustang Valley Wrestling Club',                    595),
  ('Mustang Wrestling Club',                           279),
  ('N.Y.A Jr. Rebels Wrestling Club',                  530),
  ('Naperville Hammer Huskies',                        280),
  ('Naperville North Wrestling Club',                  659),
  ('Naperville Wrestling Club',                        281),
  ('Natural Athlete Wrestling Club',                   561),
  ('New Berlin Wrestling Club',                        282),
  ('New Lenox Wrestling Club',                         542),
  ('New Wave Wrestling Club',                          685),
  ('Next Level Wrestling (Norridge)',                  283),
  ('Next Level Wrestling',                             553),
  ('Niles North Junior Vikings',                       284),
  ('No Mercy Wrestling Academy',                       285),
  ('Nomad Wrestling Academy',                          583),
  ('Nordic Greco Wrestling',                           655),
  ('Normal West FS/GR',                                658),
  ('North Boone Wrestling Club',                       286),
  ('North Chicago Redhawks',                           287),
  ('Northern Illinois Combat Club Elite',              289),
  ('Northern Illinois Girls Wrestling',                291),
  ('Northern Illinois RTC',                            290),
  ('Northern Lights Wrestling Club',                   292),
  ('Northshore Gators',                                10074),
  ('Northshore Girls Wrestling Club',                  293),
  ('Northwest Blue and White',                         294),
  ('Notre Dame Wrestling Club',                        295),
  ('nWo Wrestling Club',                               511),
  ('O''Fallon Little Panthers WC',                     296),
  ('Oak Forest Park District Warriors Wrestling',      297),
  ('Oak Lawn Acorns Wrestling Club',                   636),
  ('Oak Lawn Park District Wildcats',                  10075),
  ('Oak Lawn Spartan Youth WC NFP',                    298),
  ('Oakwood Youth Wrestling Club',                     299),
  ('Oilers Wrestling Club',                            301),
  ('Old King''s Orchard Community Center WC',          587),
  ('Old School Wrestling',                             302),
  ('OLD-TJ Trained-Springfield',                       447),
  ('OLD-Williamsville Wrestling Club',                 487),
  ('Olney Cubs Wrestling Club',                        303),
  ('Olympia Wrestling Club',                           304),
  ('Onslaught Wrestling',                              568),
  ('Orangeville Broncos Wrestling',                    305),
  ('Orland Park Pioneers Wrestling Club',              306),
  ('Oswego Panthers',                                  10076),
  ('Oswego Wrestling Club',                            431),
  ('Ottawa Crushers Kids Wrestling Club',              307),
  ('Ottawa Wolfpack Wrestling Club',                   602),
  ('Out of State',                                     557),
  ('Outlaw WC',                                        308),
  ('Outlaws Wrestling Club',                           512),
  ('Overtime School Of Wrestling',                     309),
  ('P3 Warrior Wrestling Academy',                     603),
  ('PAC Wrestling Club',                               310),
  ('Palatine Cobras Wrestling Club',                   311),
  ('Palatine Junior Pirates',                          10077),
  ('Palatine Panthers WC',                             10078),
  ('Panther Cub WC',                                   10079),
  ('Panther Paw Wrestling Club',                       633),
  ('Panther Powerhouse Wrestling',                     313),
  ('Panther Wrestling Club',                           346),
  ('Panther Youth WC',                                 315),
  ('Panther/Redhawk WC',                               10080),
  ('Patriot Grappling Systems',                        316),
  ('Patriot Wrestling Academy',                        657),
  ('Patton Trained WC',                                597),
  ('Paw Pack Wrestling',                               317),
  ('Paxton Youth Wrestling Club',                      318),
  ('Payson Wrestling Club',                            672),
  ('Pekin Boys & Girls Club',                          319),
  ('Peoria Heights Minutemen WC',                      320),
  ('Peoria Razorbacks Wrestling Club',                 321),
  ('Peoria Wizards Wrestling Club',                    513),
  ('Peotone Little Devils Wrestling Club',             322),
  ('Petersburg Wrestling Club',                        323),
  ('Pinnacle Performance',                             324),
  ('Pitbull Wrestling Alliance',                       325),
  ('Plainfield Tornadoes WC',                          10081),
  ('Plainfield Wrestling Club',                        326),
  ('Polo Wrestling Club',                              327),
  ('Pontiac Pythons',                                  10082),
  ('Pontiac Wrestling Club',                           328),
  ('Porta Wrestling Club',                             329),
  ('Power House Wrestling Club',                       330),
  ('Prairie Central Youth Wrestling',                  642),
  ('Prairie Central-Chenoa Hawks',                     10083),
  ('Prairie State Wrestling Club',                     332),
  ('Precision Wrestling Club',                         333),
  ('Proviso Power House Wrestling Club',               314),
  ('Proviso Township Gladiators WC',                   129),
  ('PSF Wrestling Academy',                            596),
  ('Push Wrestling',                                   334),
  ('Quincy Little Raiders Wrestling Club',             336),
  ('R.A.W. Dogs',                                      337),
  ('R13 Wrestling',                                    656),
  ('Radical Wrestling',                                660),
  ('Raider WC',                                        10084),
  ('Rambler Wrestling Club',                           339),
  ('Rams Academy of Wrestling (RAW)',                  686),
  ('Rams Wrestling Club',                              236),
  ('Rantoul Youth Wrestling',                          341),
  ('Rebels Wrestling Club',                            343),
  ('Red Raiders Wrestling Team',                       344),
  ('Redhawk Training Center',                          345),
  ('Reed Custer Jr. Panthers Wrestling Club',          342),
  ('Reed Custer Knights',                              10085),
  ('Relentless Pursuit',                               525),
  ('Relentless Training Center',                       565),
  ('Renegade Wrestling Club (NFP)',                    347),
  ('Renegades',                                        10086),
  ('Renegades Elite',                                  348),
  ('Respect Wrestling',                                514),
  ('Rich Rattlers Wrestling Club',                     349),
  ('Richmond Wrestling Club',                          350),
  ('Ridge Wrestling Club',                             351),
  ('Ridgeview Youth Wrestling',                        352),
  ('Riot Room Wrestling',                              592),
  ('Rippers Wrestling Club',                           353),
  ('River Bend Wrestling Club',                        354),
  ('Riverdale Elite',                                  355),
  ('Riverdale Wrestling Club',                         536),
  ('Road Warriors Wrestling Club',                     357),
  ('Robbins Jayhawks Wrestling Club',                  554),
  ('Rochelle Wrestling Club',                          358),
  ('Rochester WC',                                     10087),
  ('Rock Falls Junior Rocket Wrestling',               360),
  ('Rock Island Wrestling Club',                       361),
  ('Rocket Fuel Wrestling Club',                       362),
  ('Rockets Wrestling Club',                           363),
  ('Rockford Wrestling Club',                          364),
  ('Rockridge WC',                                     10088),
  ('Rocktown Raiders',                                 365),
  ('Rogue Wrestling',                                  366),
  ('Rolling Meadows Park District Mustangs Wrestling', 684),
  ('Romeoville Crusaders',                             367),
  ('Romeoville Wrestling Club',                        368),
  ('Roughnecks Wrestling Club',                        515),
  ('Round 1 Heat',                                     369),
  ('Round Lake Jr. Panthers Wrestling Club',           608),
  ('Round Lake Titans',                                370),
  ('Roxana Wrestling Club',                            371),
  ('RWC',                                              359),
  ('Saber Wrestling Club',                             372),
  ('Salem Wrestling Club',                             581),
  ('Sandwich Little Indians WC',                       373),
  ('Sandwich Wrestling Club',                          374),
  ('Sauk Valley Wrestling Club',                       375),
  ('Saukee Youth Wrestling Club',                      376),
  ('Savanna Redhawks',                                 10089),
  ('SCN Youth Wrestling Club',                         377),
  ('Scorpion Wrestling Club',                          378),
  ('Seneca Irish Cadets Wrestling Club',               379),
  ('Shadow Wolves Wrestling',                          617),
  ('Shamrock Wrestling Club',                          380),
  ('Sharks Wrestling Club',                            381),
  ('Shelbyville Jr. Wrestling Rams',                   382),
  ('Sherrard Jr. Tigers Wrestling Club',               383),
  ('Shooters Elite Wrestling Club',                    384),
  ('SI Golden Eagles',                                 549),
  ('Silver & Black Attack',                            10090),
  ('SIWA',                                             385),
  ('SIWC',                                             335),
  ('SJO Spartan YWC',                                  402),
  ('Sloth Strong Wrestling Club',                      662),
  ('Soldier Wrestling Allstar Training',               386),
  ('Somonauk Wrestlers Club',                          387),
  ('Sons of Thunder',                                  10091),
  ('SOT-C',                                            331),
  ('Southern Illinois Bulldogs WC',                    517),
  ('Southern Illinois Eagles',                         10092),
  ('Southern Illinois Girls WC',                       388),
  ('Southern Illinois Regional Training Center',       389),
  ('Southern Illinois United Thunder Cats',            10093),
  ('Southern Kings',                                   390),
  ('Southern Trained',                                 391),
  ('Southside Comets',                                 392),
  ('Southside Outlaws Wrestling Club',                 528),
  ('Southside Scramblers',                             393),
  ('Southside Stallions WC',                           394),
  ('SPAR Wrestling Academy',                           544),
  ('Sparta Junior Bulldogs Wrestling Club',            395),
  ('Spartan Wrestling Club',                           396),
  ('Spider WC',                                        10094),
  ('Springfield Capitals Kids WC',                     397),
  ('Springs Elite Wrestling Club',                     399),
  ('Squared Away Wrestling Club',                      616),
  ('St. Bede''s',                                      10095),
  ('St. Charles East WC',                              10096),
  ('St. Charles WC',                                   400),
  ('St. Cyprian Wrestling Club',                       401),
  ('St. Tarcissus Wrestling Club',                     403),
  ('Stampede Wrestling Club',                          572),
  ('Stateline Stingers Wrestling Club',                576),
  ('Stateline Wildcats',                               10097),
  ('Sterling Elite',                                   405),
  ('Sterling Matmen Wrestling',                        406),
  ('Sterling Newman Junior Comets',                    10098),
  ('Stillman Valley Wrestling Club',                   407),
  ('Stingers Wrestling Club',                          139),
  ('Stockton Renegades Wrestling Club',                408),
  ('Storm Wrestling Academy',                          409),
  ('Storm Youth Wrestling Club',                       410),
  ('Streator Bulldog Wrestling Club',                  411),
  ('Streator Wrestling Club',                          412),
  ('Strider WC',                                       413),
  ('Suburban Sprawl Wrestling Club',                   414),
  ('SUDA Spiders',                                     415),
  ('Sunshine Wrestling Academy',                       564),
  ('Suplex Wrestling Club',                            601),
  ('SWAT Wrestling Academy',                           417),
  ('Sycamore Wrestling Club',                          418),
  ('T-Bird Raider Wrestling',                          10099),
  ('T3 Sports Academy',                                551),
  ('Takedown Titan',                                   562),
  ('Takedown WC',                                      10100),
  ('Tanglewood',                                       419),
  ('Taylorville Wrestling Club',                       420),
  ('Team 1006 Wrestling',                              421),
  ('Team 312 Wrestling Club',                          422),
  ('Team 360 Gatorstyle Wrestling',                    423),
  ('Team Bring It',                                    424),
  ('Team C Squared',                                   425),
  ('Team DeVore',                                      427),
  ('Team El1te Wrestling',                             563),
  ('Team F.I.T.',                                      428),
  ('Team Mascoutah Wrestling Club',                    429),
  ('Team Natural',                                     430),
  ('Team Piasa Wrestling Club',                        648),
  ('Team Sehnert',                                     433),
  ('Team TopNotch Wrestling',                          434),
  ('Team Tortorice Wrestling',                         591),
  ('Team West Wolves',                                 10101),
  ('The Barracks Wrestling Club',                      575),
  ('The Island City Misfits Elite Wrestling',          664),
  ('The Law Wrestling Club',                           435),
  ('The School of Wrestling',                          436),
  ('The Ville WC',                                     679),
  ('The Wrestling Academy',                            437),
  ('The Zoo WC',                                       10102),
  ('Thunder Wrestling Club',                           507),
  ('Thunderbird Wrestling Club',                       439),
  ('Thundercats',                                      440),
  ('Tiger Elite Wrestling Inc.',                       426),
  ('Tiger Town Tanglers Wrestling Club',               441),
  ('Tiger WC',                                         10103),
  ('Tiger Wrestling Club - TPW4',                      661),
  ('Timber Wolves Wrestling Club',                     442),
  ('Tinley Park Bulldogs Wrestling Club',              443),
  ('Titan 2028 Wrestling Club',                        532),
  ('Titan Youth Wrestling',                            444),
  ('TJ Trained Wrestling',                             445),
  ('TJ Trained-Canton',                                446),
  ('TJ Trained-Clinton',                               680),
  ('TJ Trained-Springfield Wrestling',                 639),
  ('Tomcat Wrestling Club',                            448),
  ('Tony Capriola Sr. Wrestling Club',                 670),
  ('Top Dog Wrestling Club',                           640),
  ('Top Gun Wrestling Club',                           449),
  ('Top Pick Wrestling',                               450),
  ('Toss Em Up Wrestling Academy',                     474),
  ('Training To Win',                                  451),
  ('Trevian Wrestling Club',                           288),
  ('Tri-City Braves',                                  10104),
  ('Tri-Valley WC',                                    10105),
  ('Triad Knights Wrestling Club',                     452),
  ('Tribe Wrestling Club',                             120),
  ('Trico Wrestling Club',                             516),
  ('Triton Wrestling Club',                            453),
  ('Triumph ''The Art of Wrestling''',                 454),
  ('Twin City WC',                                     10106),
  ('Unattached',                                       455),
  ('Under Rated Wrestling Academy',                    623),
  ('United Southern Allstars',                         456),
  ('United Township WC',                               10107),
  ('Unity Youth Wrestling Club',                       457),
  ('Universal Stars Wrestling Club',                   458),
  ('UP Town Wrestling Club',                           459),
  ('Urbana Tigers Wrestling Club',                     460),
  ('Vandal Kings',                                     552),
  ('Vandalia Jr Wrestling Club',                       461),
  ('Vandalia Kings',                                   462),
  ('Vermilion Valley Elite',                           10108),
  ('Victory Elite Wrestling',                          598),
  ('Viking Wrestling Club',                            463),
  ('Villa Lombard Cougars',                            10109),
  ('Villa Park Young Warriors Wrestling Club',         464),
  ('Vitrychenko Academy',                              560),
  ('Vittum Cats Wrestling Club',                       466),
  ('Vortex Wrestling Club',                            531),
  ('War Dog Training Center',                          619),
  ('Warren County Wrestling Club',                     467),
  ('Warrensburg Wrestling Club',                       468),
  ('Warrensburg-Latham Jr. Cardinals Wrestling Club',  469),
  ('Warrior Monks',                                    470),
  ('Warrior Wrestling',                                471),
  ('Warriors Nation Wrestling',                        621),
  ('Warriors Wrestling Academy',                       610),
  ('Washington Junior Panthers',                       10110),
  ('Waubonsie Wrestling Club',                         473),
  ('Waukegan Youth WC',                                10111),
  ('West Carroll Wrestling Club',                      475),
  ('West Chicago Spider WC',                           10112),
  ('West Chicago Wrestling Club',                      477),
  ('West Frankfort Jr. Redbirds WC',                   478),
  ('West Hancock Wrestling Club',                      479),
  ('West Suburban Girls Wrestling Club',               574),
  ('Western Illinois All-Stars',                       480),
  ('Westmont Panther Wrestling',                       481),
  ('Westville Youth Wrestling',                        482),
  ('Wheaton Franklin WC',                              10113),
  ('Wheaton Monroe Eagles',                            10114),
  ('Wheaton Tigers Wrestling Club',                    483),
  ('Wheaton Wrestling Club',                           234),
  ('Wheeling Wildcat WC',                              518),
  ('Whips Wrestling Club',                             484),
  ('Wildcat Wrestling Club',                           73),
  ('Wildcat Wrestling Club (Naperville)',              485),
  ('Wildcats Wrestling Academy',                       600),
  ('Will County Warriors Wrestling Club',              486),
  ('Williamsville Wrestling Club',                     356),
  ('Wilmington Wrestling Club',                        488),
  ('Windy City Eagles',                                489),
  ('Wolfpak Wrestling Club',                           490),
  ('Wolverine Wrestling Club',                         491),
  ('Wolves Wrestling Club',                            492),
  ('Woodstock Cyclones WC',                            493),
  ('Woodstock Mathogs',                                494),
  ('Wrestling 365',                                    495),
  ('Wrestling Factory',                                10115),
  ('Wrestling Inc',                                    519),
  ('Xtreme Wrestling Club',                            496),
  ('Yorkville Wrestling Club',                         497),
  ('Young Bucks Wrestling of Illinois',                498),
  ('Young Champions',                                  10116),
  ('Young Guns Wrestling Club',                        499),
  ('Young Warrior Wrestling Academy',                  667),
  ('Z''s Team Pena',                                   500),
  ('Zee Bee Stingers',                                 501),
  ('Zero Fox Wrestling',                               646);
