# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils

_HERE = pathlib.Path(__file__).resolve().parent
_NOVICE_TEAM_REPLACE: dict[str, str] = {}
_NOVICE_COMPETITORS: dict[int, list[str | None]] = {
    62: [
        "GEORGE SIMS :: JOLIET :: 5",
        "MATT THOMPSON :: SJO KIDS",
        "STEVE OCKRIM :: HINSDALE",
        "SHAUN DANNENBRINK :: BETHALTO :: 4",
        "JOSH MOODY :: QUINCY",
        "BRET BAUMGARDNER :: TRAILBLAZER",
        "WILLIAM CARROLL :: MEAD",
        "KEVIN HASTINGS :: VITTUM CATS",
        "BRANDON WHARTON :: MT. ZION",
        "JUSTIN CLUBB :: HARLEM :: 2",
        "ROBERT ARKO :: VILLA-LOMBARD",
        "RAYMOND SCHNELL :: MOLINE TIGERS",
        "ISRAEL MARTINEZ :: TOMCATS :: 1",
        "DANNY MARTINEZ :: BELVIDERE",
        "EDDIE WOLF :: WARHAWKS",
        "JOHN SHARP :: PEKIN",
        "LEO NARENS :: BETHALTO",
        "RASHAAD BOYD :: JOLIET",
        "FRANK MCNAUGHTON :: OAK LAWN",
        "BRIAN GILLHAM :: ST. TARCISSUS",
        "CALEB FERRY :: HARLEM :: 3",
        "ROB KING :: UNITY YOUTH",
        "SIM BRANDAU :: LITTLE CELTIC :: 6",
        "ZACH ZEIGLER :: HERRIN",
    ],
    66: [
        "JARED MCCABE :: ROSEMONT",
        "JESS MCMECHAN :: CUMBERLAND",
        "JAMES KAMPER :: HICKORY HILLS",
        "RYAN HLINAK :: LAKE VILLA",
        "ADAM LAPE :: VANDALIA",
        "MARK WARREN :: LITTLE CELTIC :: 5",
        "NICK CIRRINCIONE :: VILLA-LOMBARD :: 1",
        "EDDIE ROMIC :: VITTUM CATS",
        "BRAD NORRIS :: REDBIRD",
        "JEREMY HAYES :: MORTON",
        "SEAN CHINSKI :: LITTLE CELTIC :: 3",
        "MATT HAMIL :: EDWARDSVILLE",
        "PAUL AUGLE :: TINLEY PARK :: 2",
        "KYLE WATERS :: PEKIN",
        "JED HOLDEMAN :: TRAILBLAZER",
        "SETH HENRY :: VANDALIA",
        "JUSTIN DARGAN :: CRYSTAL LAKE",
        "WILLIAM TROXEL :: WAUKEGAN",
        "RAY BLAKE :: MUSTANG",
        "BILL ZIGMAN :: INDIAN PRAIRIE",
        "BRANDON DECAP :: RIVERDALE",
        "MICHAEL STANLEY :: MATTOON :: 6",
        "BRIAN HAROFF :: ROSEMONT",
        "ANDREW PENNA :: CRYSTAL LAKE :: 4",
    ],
    70: [
        "PATRICK HAMILTON :: MORRISON :: 4",
        "TRAVIS STAEFFER :: MS. KID'S",
        "JOHN BENNER :: LITTLE GIANTS",
        "BLAKE DINTELMAN :: LITTLE DEVILS",
        "LONNIE CORBIN :: PANTHER BURBANK :: 5",
        "DANNY RICHARDSON :: BRADLEY-BOURBONNAIS",
        "NATHAN MARTINEZ :: TOMCATS :: 1",
        "TJ GRIDER :: ELMHURST",
        "PHILLIP REED :: DANVILLE",
        "TYLER KIMBERLIN :: DUNDEE",
        "ERIK HERNANDEZ :: JOLIET",
        "ALEX SHEAR :: MUSTANG",
        "ERIC NOVAK :: TINLEY PARK",
        "JERAD KARLEN :: ROUND LAKE",
        "RICH KUCZKOWSKI :: LEMONT",
        "JEFF JEZUIT :: PANTHER BURBANK :: 3",
        "GARY OXFORD :: GC COOLUDGE",
        "ANTHONY MULLINS :: METAMORA :: 6",
        "KEVIN HINKLE :: MEAD",
        "DOMINIC VALVANO :: TRAILBLAZER",
        "BILL SWAFFORD :: HARLEM",
        "BRIAN HAWXHURST :: MT. ZION",
        "JOSH PRICE :: RIVERDALE :: 2",
        "RYAN FEATHERSTUN :: MT. VERNON",
    ],
    74: [
        "KYLE ONEILL :: TINLEY PARK :: 1",
        "DAVID GNADEN :: DANVILLE",
        "KEVIN MCCANN :: ROSEMONT",
        "MARC PETERSON :: MUSTANG",
        "MARLAINA CLUBB :: HARLEM",
        "ADAM THORESEN :: LEMONT",
        "TONY RODGERS :: CROSSFACE",
        "ARAN ESPOSITO :: MEAD :: 6",
        "CHRIS TICKLE :: PONTIAC",
        "DUSTIN SCHLOEMANN :: LITTLE KNIGHTS :: 3",
        "CHRIS DZIEWIATKOWSKI :: TRAILBLAZER",
        "ROBERT CARDOSO :: LARKIN",
        "ANDY COYLE :: VILLA-LOMBARD",
        "ZACK MAY :: BETHALTO :: 4",
        "MATT MCKNIGHT :: ILLINOIS VALLEY",
        "BLAKE VERMILLION :: CRYSTAL LAKE",
        "STEVEN COZZIE :: ST. BARNABAS / CHRIST THE KING",
        "RYAN CUMBEE :: LITTLE CELTIC",
        "TONY GANAS :: ROSEMONT :: 2",
        "JESSE TRIBBETT :: MIDWEST CENTRAL",
        "JEREMY COX :: GC COOLIDGE",
        "SHANE MENDENHALL :: MT. ZION",
        "JOSEPH CLARK :: JOLIET :: 5",
        "BRIAN NELSON :: PANTHER BURBANK",
    ],
    79: [
        "PATRICK SPARKS :: TRIAD",
        "MATT WHITMER :: GIBSON CITY",
        "NICK FIORE :: OAK FOREST",
        "DAN NILES :: YORKVILLE :: 5",
        "CHRIS ILIOPOULOS :: ADDISON INDIAN TRAIL :: 4",
        "JAY MILLER :: TRAILBLAZER",
        "JAMIE HEY :: DIXON",
        "SEAN FAHEY :: LITTLE CELTIC",
        "MARSHALL JOYNER :: DANVILLE",
        "DAVID DREW :: MUSTANG :: 1",
        "DANNY ALCOCER JR :: TRAILBLAZER",
        "JASON CARTWRIGHT :: MEAD",
        "JOSEPH KRACHALA :: BATAVIA",
        "ALAN RODENBERG :: ST. BARNABAS / CHRIST THE KING :: 3",
        "BEN STOCKWELL :: RIVERDALE",
        "MIKE KOPECKY :: ROSEMONT",
        "NICK SCACCO :: RICHMOND",
        "DEREK STOLL :: LITTLE DEVILS",
        "RAYNELLE KIZZEE :: HARVEY :: 2",
        "JORDAN WEBSTER :: METAMORA :: 6",
        "ANDY FOSTER :: PANTHER BURBANK",
        "CASEY RODDIS :: MT. ZION",
        "DAVID KNIFFEN :: HERRIN",
        "RUSSELL VANDERHEYDEN :: HARLEM",
    ],
    84: [
        "JOSHUA SERRANO :: CHILLICOTHE",
        "CAL RYDER :: MATTOON :: 6",
        "EARNEST GREGORY :: JOLIET",
        "PATRICK ROSS :: MUSTANG :: 3",
        "BILL WALSH :: CRYSTAL LAKE",
        "RYAN PECK :: SPARTANS",
        "ANGELO GERVASIO :: LEMONT :: 2",
        "MIKE TROTTER :: OAK FOREST",
        "ADAM SEYMOUR :: HOOPESTON",
        "JUSTIN MCCABE :: ROSEMONT",
        "JIM AMSBURY :: EDWARDSVILLE",
        "GREGORY SCOTT :: ROUND LAKE",
        "NICK BINGHEIM :: BETHALTO :: 1",
        "MIKE CUNNINGHAM :: ST. TARCISSUS",
        "SEAN KRAMER :: ST. CHARLES",
        "KEVIN GRECE :: CRYSTAL LAKE",
        "JOE KING :: HICKORY HILLS",
        "RILEY SILES :: METAMORA",
        "RICKY OLSZTA :: LITTLE CELTIC :: 5",
        "DANNY BLAGAICH :: VILLA-LOMBARD",
        "CHRIS SCHUTT :: ROSEMONT",
        "MITCH UPTON :: MATTOON",
        "BOB WHITE :: MORRISON :: 4",
        "TONY SCHICKEL :: MUSTANG",
    ],
    89: [
        "BRAD SCHRADER :: HARLEM :: 3",
        "JEFFRRY SCHWARTZKOPF :: BISMARCK-HENNING",
        "DARREN ORCUTT :: VILLA-LOMBARD",
        "MATTHEW SANDBURG :: LIONS :: 2",
        "JIMMY KAPPAS :: LOCKPORT",
        "JEFFREY SCHMERBACH :: JR. ROCKET",
        "MATT EMERICK :: VANDALIA",
        "TERRY GARBIS :: TRAILBLAZER :: 6",
        "TYRONE BYRD :: DEWITT COUNTY",
        "TOMMY MIETUS :: ROSEMONT",
        "PAUL CLEARY :: EL PASO",
        "TERRANCE JOHNSON :: JOLIET",
        "BEN HOTT :: MOLINE TIGERS",
        "JARED WENDELL :: BISON",
        "KYLE BARBER :: SPARTANS",
        "JUSTIN CARR :: LITTLE CELTIC :: 5",
        "MICHAEL PASTERNAK :: DOLTON",
        "JESSE HALL :: LAKE VILLA",
        "JOHN VILLARREAL :: VILLA-LOMBARD :: 4",
        "BJ VAUGHN :: MURPHYSBORO",
        "CHAD JOHNSON :: MEAD",
        "BRIAN CRAVENS :: MT. ZION :: 1",
        "LYLE ERICKSON :: RICHMOND",
        "PHILLIP R. RUIZ :: ST. BARNABAS / CHRIST THE KING",
    ],
    95: [
        "DANNY QUARTZ :: LITTLE DEVILS :: 4",
        "MICHAEL POWELL :: FISHER :: 6",
        "ROBB GOTLUND :: LEMONT",
        "BRETT HARMAN :: ROSEMONT",
        "JASON MACEK :: PANTHER BURBANK",
        "DON SASO :: BELVIDERE",
        "STEVE AMY :: JR. ROCKET",
        "JOSH HORENI :: OSWEGO COUGARS",
        "CLAY FRENCH :: MATTOON",
        "JASON ERWINSKI :: TINLEY PARK :: 2",
        "MIKE BARDZINSKI :: LAKE VILLA",
        "CHRIS CANDELA :: ST. BARNABAS / CHRIST THE KING",
        "DUSTIN DILLOW :: ELGIN",
        "ROMAN NATOLI :: LOCKPORT :: 3",
        "MIKE RYAN :: JR. ROCKET",
        "WAYNE DEMONBREUN JR :: CRESTWOOD",
        "JASON SPONSEL :: PALATINE",
        "DUSTY GREEN :: RED HILLS",
        "DANA HOLLAND :: VILLA-LOMBARD :: 5",
        "CHRIS OSBORN :: MORRISON",
        "BRADLEY WEINHOLD :: PLAINFIELD INDIAN TRAIL",
        "BRAD OWENS :: MT. ZION :: 1",
        "MARC JUSTICE :: RAIDERS",
        "MATTHEW HOLMES :: WAUKEGAN",
    ],
    101: [
        "MATT LACKEY :: MOLINE TIGERS :: 1",
        "MICHAEL BROWN :: UNITY YOUTH",
        "JASON POTTER :: ST. CHARLES",
        "BRANDON DOLEZAL :: LOCKPORT :: 6",
        "DAVID HILLARD JR :: PIRATES",
        "GEORGE HUSKEY :: LITTLE KNIGHTS",
        "AARON POWERS :: ROCKFORD :: 4",
        "FRANK DE FILIPPIS :: VILLA-LOMBARD",
        "DREU LARSON :: MT. ZION",
        "RUSSELL LANGNER :: CRESTWOOD",
        "MORRIS OPPENHEIMER :: FAIRFIELD",
        "GRAHM GIOVAGNOLI :: ADDAMS",
        "JOSHUA DUKE :: W.F. THUNDERBIRD",
        "MATTHEW COLLINS :: PANTHER BURBANK",
        "JOSHUA RAYBORN :: DUNDEE",
        "DARLOS GOMEZ :: ADDISON INDIAN TRAIL :: 5",
        "ANTHONY MURPHY :: HOMEWOOD-FLOSSMOOR",
        "JEREMY MOORE :: RICHWOODS",
        "DENIS POOL :: GLENDALE :: 2",
        "ALEX MORENO :: CRYSTAL LAKE",
        "MARK EDER :: FALCON",
        "NICK UPTON :: MATTOON :: 3",
        "TIMOTHY PEREZ :: JORDAN-SETON",
        "JASON ROBINSON :: SENECA",
    ],
    108: [
        "SHAWN MCDONNELL :: CRYSTAL LAKE :: 5",
        "TOBY NEAL :: OAKWOOD",
        "MATT FARRARE :: STREATOR",
        "HORACE FLOURNOY :: TRI-CITY BRAVES :: 3",
        "JOHN ZINCHUK :: NOTRE DAME",
        "ANDREW CURRAN :: ST. BARNABAS / CHRIST THE KING",
        "KEVIN VENNE :: GC COOLIDGE",
        "JOSEPH BOYER :: MOLINE TIGERS",
        "JASON KESSLER :: MATTOON",
        "MARK MCCUTCHEON :: LEMONT :: 2",
        "BRENDAN CURRAN :: ST. BARNABAS / CHRIST THE KING",
        "JARED BURRESS :: MEAD",
        "DANIEL JORDAN :: DOLTON",
        "SEAN CONSIDINE :: VILLA-LOMBARD :: 1",
        "JEREMY BROOMBAUGH :: CARBONDALE",
        "MATTHEW ROSENGRANT :: NOTRE DAME",
        "BRIAN EBERSOLE :: BRADLEY-BOURBONNAIS",
        "BRIAN LEMMON :: HARVARD",
        "RUSSEL MCCALLISTER :: ERIE MS",
        "NICHOLAS SCHEIBEL :: HIGHLAND",
        "PATRICK ARVIN :: OSWEGO COUGARS :: 6",
        "SHAIN PRAHL :: MATTOON :: 4",
        "MATTHEW KAUPPINEN :: DAKOTA",
        "JUSTIN GOEBEL :: PLAINFIELD INDIAN TRAIL",
    ],
    115: [
        "GEORGE KIRGAN :: GC COOUDGE",
        "JOEY HOFFMAN :: URBANA",
        "ADAM FISHER :: CHILLICOTHE",
        "CHRIS KERSTEN :: VILLA-LOMBARD :: 5",
        "ROD GRIFFIN :: TRI-CITY BRAVES :: 3",
        "WESLEY ANDERSON :: ROUND LAKE",
        "MIKE SKRBINA :: DOLTON",
        "ROBB VERHURST :: PROPHETSTOWN-LYNDON",
        "BRIAN SMITH :: LANPHIER-SPRINGFIELD",
        "ANDREW HARRISON :: ADDISON INDIAN TRAIL :: 2",
        "SHAWN BABCOCK :: ROCKFORD",
        "RICHARD VORTES :: HARVEY",
        "DREW THOMAS :: ELGIN",
        "JAMES CARROLL :: MEAD",
        "CHAD FEIPEL :: MUSTANG",
        "CHAD KRNAC :: PLAINFIELD INDIAN TRAIL :: 1",
        "BRIAN SCHNURSTEIN :: VILLA-LOMBARD",
        "LUCAS DIESSELHORST :: LITCHFIELD",
        "TIM LEWIS :: RIVERDALE :: 4",
        "RAYMOND BOYD :: VITTUM CATS :: 6",
        "JOSEPH WEBER :: ROSEMONT",
        "BRAD LEFTWICH :: RANTOUL",
        "CHRIS MCCOY :: EDWARDSVILLE",
        "DONALD HOFF :: HUBBLE",
    ],
    122: [
        "MATTHEW PIOTROWICZ :: NOTRE DAME",
        "MATT FESES :: URBANA",
        "MICHEAL GREGORY :: MARION",
        "LEITH CROWTHER :: PLAINFIELD INDIAN TRAIL :: 3",
        "BRET EVINS :: JR. ROCKET :: 2",
        "JOHN WILKANS :: CRYSTAL LAKE",
        "BRENT KRUMPFES :: HINSDALE",
        "KENNETH LUTZ JR :: RAIDERS",
        "SAMUEL A WALTON :: TAYLORVILLE",
        "JOSH HJORTH :: VILLA-LOMBARD",
        "CHAD PEARSON :: SYCAMORE :: 5",
        "ANDY DYKEMA :: MORRISON",
        "JOE MCCARTHY :: HARVARD :: 1",
        "DUSTIN JENSEN :: ST. CHARLES",
        "AUKEY WILLIAMS :: CORKERY",
        "ADAM SERRANO :: CHILLICOTHE",
        "DONNY BALSAVICH :: ORLAND PARK",
        "ZACH MORRIS :: ROCKFORD",
        "ISAAC DIESSELHORST :: LITCHFIELD :: 4",
        "SETH HORVATH :: ST. BARNABAS / CHRIST THE KING",
        "JOSH JOHNSON :: TOMCATS",
        "RON TICKLE JR :: PONTIAC",
        "JAY PTAK :: ELMHURST",
        "MARTIN ELLIS :: JOLIET :: 6",
    ],
    130: [
        "JUSTIN SORNSIN :: ROCKFORD :: 4",
        "SCOTT RINKENBERGER :: GIBSON CITY",
        "NATHAN HILL :: LAWRENCEVILLE",
        "RAY LEONE :: BLUE CREW",
        "NICK KULBARTZ :: EAST MOLINE",
        "EDMON NEGRON :: CORKERY",
        "BILL KOPECKY :: ROSEMONT :: 1",
        "DEMARKO TAYLOR :: LITTLE KNIGHTS",
        "ANDREW MCMULLEN :: CHARGER KIDS",
        "JAMES YOUNG :: PEOTONE",
        "EDDIE NEGRON :: CORKERY",
        "BRYAN SCHULTZ :: EAGLE :: 5",
        "GARY SHERWOOD :: OAK LAWN :: 3",
        "DANIEL RICHARDS :: LOCKPORT",
        "DAVVD ODONNELL :: MEAD",
        "JESSE IZZO :: BRONCO :: 2",
        "JEREMY KOUNTZ :: EAST MOLINE",
        "DONNIE HALL :: ROCKFORD",
        "JUSTIN QUALLS :: CARBONDALE",
        "JAMES DORE :: NOTRE DAME",
        "SAMMY CONDE :: CALUMET CITY",
        "CHAD GRIGSBY :: CHARLESTON :: 6",
        "KRISTOFER SWANSON :: DUNDEE",
        "DANE SIMPSON :: EL PASO",
    ],
    138: [
        "SPENCER FETHERLING :: RICH",
        "CODY DAHL :: URBANA",
        "JUSTIN WATSON :: ROCKFORD",
        "MARK GENTHE :: VILLA-LOMBARD :: 1",
        "NICK PATRICK :: GC COOLIDGE",
        "TRAVIS WASHINGTON :: CORKERY",
        "BRYAN ROUSE :: MAINE TOWNSHIP EAGLES :: 3",
        "KYLE WISNIEWSKI :: ANTIOCH",
        "JOSH SPAIN :: MT. ZION",
        "JOHN DIETERLE :: QUINCY :: 6",
        "DAN PROROK :: OAK LAWN",
        "JERRY HEARN :: TRI-CITY TURTLES",
        "NICK CURBY :: LIONS :: 2",
        "SHANNON CHRISTIANSEN :: TIGERTOWN TANGLERS",
        "KYLE KING :: WAUKEGAN",
        "JOHNATHON CARPENTER :: LITTLE DEVILS",
        "ERIC SHARP :: OSWEGO COUGARS",
        "JOVAN GORRELL :: CHICAGO HTS",
        "RYAN LAIRD :: SYCAMORE",
        "PARKER PINNELL :: WAUKEGAN :: 4",
        "BRIAN MALOTT :: PEKIN",
        "ANDREW LINARES :: HOOPESTON :: 5",
        "NICK SHEPHERD :: BRADLEY-BOURBONNAIS",
        "MIKEY SALAH :: LEMONT",
    ],
    147: [
        "CHRISTOPH MARTINAT :: LAKE FOREST",
        "ARNOLD EVANS :: OAKWOOD",
        "GRANT GOLTZ :: GIBSON CITY",
        "NICK POEHLMAN :: MORTON :: 4",
        "NICHOLAS LATUS :: EAGLE :: 2",
        "WILL MCDERMOTT :: LITTLE CELTIC",
        "RAMONE BROWN :: ROBBINS",
        "DAN THORNTON :: PEORIA",
        "SEAN NEWBY :: MATTOON",
        "ALAN REYNOLDS :: FAIRFIELD",
        "RYAN HITE :: JOLIET",
        "NICK ESPOSITO :: VILLA-LOMBARD :: 5",
        "ADAM VENTSIAS :: PLAINFIELD INDIAN TRAIL :: 3",
        "BRYCE PARKS :: MARION",
        "GARY PARQUETTE :: HUBBLE",
        "JOE CHIRUMBOLO :: EAGLE :: 1",
        "RK LUNN :: TIGERTOWN TANGLERS",
        "SEAN GARAY :: RAMS",
        "KEVIN MCCORMICK :: ROCKFORD",
        "JON PAOLILLI :: HOMEWOOD-FLOSSMOOR",
        "NICK MYRES :: TRAID",
        "PHILIP HARBIN :: ARGENTA / OREANA",
        "JASON TEJERO :: ROSEMONT",
        "ADAM STIMPSON :: JORDAN-SETON :: 6",
    ],
    215: [
        "BRAD CRAIG :: ROBBINS :: 2",
        "GARRETT SEAMAN :: MATTOON",
        "JASON ROMANO :: CRYSTAL LAKE",
        "WILSON MOORE :: MURPHYSBORO :: 6",
        "DALE ANDERSON :: EL PASO",
        "STATHIE PANAYI :: PALATINE",
        "ERIC OLSON :: BRADLEY-BOURBONNAIS",
        "TRAVIS MARTINEZ :: LIL REAPER :: 3",
        "ADAM DETMERS :: MT. ZION",
        "PAT DALY :: VILLA PARK",
        "MATT MIKES :: PALATINE",
        "BRIAN STEELE :: MACOMB",
        "JASON MANGAWAN :: RAMS :: 5",
        "SALVADOR RAMIREZ :: TOMCATS",
        "DANNY CORDOVA :: LOCKPORT",
        "MATTHEW CARLSON :: GENESEO",
        "SETH WOMACK :: VANDALIA",
        "JEFFERY MISIOLEK :: ST. BARNABAS / CHRIST THE KING",
        "BRAD RUNKLE :: YORKVILLE :: 1",
        "MICHAEL MESSENGER :: PLAINFIELD INDIAN TRAIL",
        "MARK DICKER :: PALATINE",
        "JACOB ACORD :: WESTVILLE :: 4",
        "MICHAEL HARRIS :: ST. BARNABAS / CHRIST THE KING",
        "RANDY JOE WILKEY :: CENTRALIA",
    ],
}
_NOVICE_TEAM_SCORES: dict[str, float] = {
    "VILLA-LOMBARD": 179.0,
    "LITTLE CELTIC": 93.0,
    "PLAINFIELD INDIAN TRAIL": 87.0,
    "MATTOON": 82.5,
    "ROSEMONT": 78.0,
    "HARLEM COUGARS": 77.0,
    "TINLEY PARK": 74.0,
    "EAGLE": 70.5,
    "BETHALTO JR. HIGH": 61.0,
    "ADDISON INDIAN TRAIL": 58.0,
    "TOMCATS": 56.0,
    "MT. ZION": 55.0,
    "CRYSTAL LAKE": 53.5,
    "PANTHER BURBANK": 53.5,
    "MUSTANG WC": 53.0,
    "LEMONT": 52.0,
    "ROCKFORD": 49.5,
    "JOLIET": 49.0,
    "LIONS": 47.0,
    "YORKVILLE": 45.0,
    "LOCKPORT GRAPPLERS": 45.0,
    "TRI-CITY BRAVES": 42.5,
    "RIVERDALE": 42.0,
    "MORRISON": 42.0,
    "MOLINE TIGERS": 38.5,
    "ST. BARNABAS / CHRIST THE KING": 38.0,
    "HARVARD": 36.0,
    "JR. ROCKET": 34.5,
    "OAK LAWN": 34.0,
    "LITTLE DEVILS": 31.0,
    "DOLTON": 28.0,
    "MAINE TOWNSHIP EAGLES": 27.0,
    "LIL REAPER": 26.0,
    "MEAD JR. HIGH": 25.0,
    "WESTVILLE": 24.0,
    "GLENDALE": 24.0,
    "METAMORA": 24.0,
    "ROBBINS": 23.0,
    "LITTLE KNIGHTS": 23.0,
    "WAUKEGAN": 21.0,
    "OSWEGO COUGARS": 21.0,
    "TRAILBLAZER": 20.5,
    "BRONCO": 20.0,
    "HOOPESTON": 20.0,
    "HARVEY": 20.0,
    "LITCHFIELD": 19.0,
    "MURPHYSBORO": 19.0,
    "MORTON": 19.0,
    "VITTUM CATS": 18.0,
    "RAMS WC": 17.0,
}
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    70: [
        "DEREK DALY :: ADDISON INDIAN TRAIL",
        "ANDY KONC :: PLAINFIELD INDIAN TRAIL",
        "JAMES BEAUREGARD :: MUSTANG",
        "MATTHEW FRITZ :: HARLEM :: 2",
        "JERRY STECK :: BRONCO",
        "DONNY WALSH :: ORLAND PARK",
        "BRENT MALMSTROM :: OSWEGO PANTHERS",
        "MATTHEW EARNER :: ST. BARNABAS / CHRIST THE KING :: 4",
        "MIKE KENNEY :: JR. ROCKET",
        "JASON ATHERTON :: METAMORA :: 6",
        "SHAWN GOLDEN :: BRADLEY-BOURBONNAIS",
        None,
        "JEFF ANDERSON :: TINLEY PARK :: 3",
        "STEVE RODGERS :: CROSSFACE",
        "NICK POWELL :: EISENHOWER JH",
        "STEVEN BRYANT :: BETHALTO :: 1",
        "BRIAN CREIGHTON :: CRYSTAL LAKE",
        None,  # "DANNY ERICKSON :: EAST MOLINE",
        "DOMINIC CURATOLO :: DOLTON",
        "CHAD THRONDSON :: LEMONT",
        "ZACHARY ANDERSON :: TIGERTOWN TANGLERS :: 5",
        "NEIL REW :: SJO KIDS",
        None,  # "ADAM GUSTAFSON :: ROCK ISLAND RED",
        "ADAM FREESE :: LIL REAPER",
    ],
    74: [
        "ADAM WASON :: TIGERTOWN TANGLERS",
        "JARED SCHROEDER :: GIBSON CITY",
        "MICHAEL WETMORE :: WINSTON PARK",
        "CHUCK BURROWS :: BETHALTO :: 6",
        "JOHN STRAHLMAN :: MUSTANG",
        "LUIS CASTRO :: HARVEY",
        "ERIC WOLDIET :: VILLA-LOMBARD :: 2",
        "MARQUIS COLEMAN :: PIRATES",
        "CHRIS MURRAY :: FISHER",  # TYPO: Bracket says `DUSTIN COOK :: FISHER`
        "CHAD KARLEN :: ROUND LAKE :: 4",
        "CHRIS STUART :: OAK FOREST",
        "MICHAEL MOORE :: KNIGHTS",
        "DENNIS PLECKHAM :: RICH WRESTLING :: 3",
        "ROY GUSTAFSON :: KNIGHTS",
        "RICKIE YOUNG :: LEMONT",
        "KEVIN COZZIE :: ST. BARNABAS / CHRIST THE KING",
        "RICHARD WALLS :: RED HILLS",
        "MICHAEL DELOOSE :: MOLINE TIGERS",
        "TONY DOUGHTY :: FRANKLIN PARK :: 1",
        "KYLE BARZANO :: GLENDALE",
        "LUKE HALEY :: ANTIOCH",
        "RONNIE DALLUGE :: MT. ZION :: 5",
        "RICKY MCDONALD :: METAMORA",
        "RYAN RUMFELT :: EDWARDSVILLE",
    ],
    79: [
        "JOSHUA TURYNA :: ST. BARNABAS / CHRIST THE KING",
        "BRIAN EVERETT :: GIBSON CITY",
        "JOHN THORPE :: FROST",
        "AMADOR ESTRADA :: ROUND LAKE :: 2",
        "ETHAN CRANE :: GC COOLIDGE",
        "BRETT HOERR :: MORTON",
        "SCOTT KENNY :: ORLAND PARK :: 4",
        "ANTHONY BINION :: WARHAWKS",
        "TERENCE KENNEBREW :: PIRATES",
        "MARK MANKOWSKI :: HICKORY HILLS :: 5",
        "BRIAN CLODFELTER :: TIGERTOWN TANGLERS",
        "SAM MOHR :: PLAINFIELD INDIAN TRAIL",
        "SEAN PIPPIN :: GENESEO :: 6",
        "BRADY RUEL :: ST. BARNABAS / CHRIST THE KING",
        "DERRICK LOLLIS :: HARVEY",
        "ROY PIERCE :: SPARTANS",
        "BRAD VERMILLION :: CRYSTAL LAKE :: 3",
        "JASON ETZKORN :: LEMONT",
        "DAVID STOLTZ :: MEAD :: 1",
        "MIKE MURPHY :: LITTLE CELTIC",
        "TIM TYNSKI :: CRESTWOOD",
        "JAMIE FENDER :: FISHER",
        "BEN BRUNNER :: BLACKHAWK II",
        "RANDY ATERS :: LIL REAPER",
    ],
    84: [
        "ROAMELLE KIZZEE :: HARVEY :: 1",
        "MATT RUFF :: MATTOON",
        "STEVEN PALUMBO :: ST. TARCISSUS",
        "BEN BLACK :: HINSDALE",
        "BRIAN WILSON :: CRYSTAL LAKE :: 5",
        "BRENT PENTZIEN :: INDIAN PRAIRIE",
        "SOLOMON TAYLOR :: CHILLICOTHE",
        "COREY HEYDECKER :: ADAMS",
        "CHRIS GRIFFITH :: FISHER",
        "JC GAUNT :: MT. VERNON :: 3",
        "MIKE FORSYTH :: BRONCO",
        "METHANA LANGSY :: ROCKFORD",
        "JOE DI GIOIA :: VILLA-LOMBARD",
        "MIKE MABRY :: VANDALIA",
        "JARROD MERKELY :: TIGERTOWN TANGLERS",
        "STEVEN WERNSMAN :: YORKVILLE :: 6",
        "MICHAEL GASKIN :: ST. BARNABAS / CHRIST THE KING",
        "MATTHEW MORENO :: CHICAGO HEIGHTS",
        "TIMOTHY HAMILTON :: PIRATES",
        "MIKE NEELS :: MOLINE TIGERS",
        "JAKE SULLIVAN :: BETHALTO :: 4",
        "VINCE CHAMBLISS :: CATLIN",
        "JOE WZOREK :: ORLAND PARK :: 2",
        "LORENZO WILLIAMS :: CORKERY",
    ],
    89: [
        "MICHAEL SMITH :: BETHALTO",
        "JEFFREY EMMETT :: LANPHIER SPRINGFIELD",
        "DARNELL LOLLIS :: HARVEY :: 2",
        "JESSIE FLORES :: LIL REAPER",
        "DEREK DIXON :: LAKE FOREST",
        "JACOB THEISEN :: BLACKHAWK II",
        "NATHAN CROSS :: MOLINE TIGERS",
        "CRAIG COLLINS :: CALUMET CITY :: 6",
        "JEFFREY WILLIAMS :: LANPHIER SPRINGFIELD",
        "ANTHONY OPIOLA :: DOLTON :: 4",
        "BRIAN WEIMER :: TRAILBLAZER",
        "MATTHEW HENRY :: FRANKLIN PARK",
        "AARON GILSON :: ST. CHARLES :: 5",
        "MARTY FITZGIBBONS :: VITTUM CATS",
        "MATTHEW STEINKAMP :: QUINCY",
        "LUKE EWANIO :: ROSEMONT :: 3",
        "MARK NICOSON :: HARLEM",
        "TIN DONOHOO :: BETHALTO",
        "DAVID DOUGLAS :: HARVEY :: 1",
        "JOE FINDLEY :: RIVERDALE",
        "JIM NEEDHAM :: ST. BARNABAS / CHRIST THE KING",
        "BEN POTTER :: BISMARCK-HENNING",
        "DOC SANDERS :: EDWARDSVILLE",
        "BEN FAIVR :: DAKOTA",
    ],
    95: [
        "EDDIE VALDEZ :: WEST CHICAGO",
        "JOHN BELL :: HOOPESTON",
        "JEREMY PYLE :: RICH WRESTLING",
        "ARCHIE GRIFFIN :: PIRATES :: 2",
        "ANTONIO WILLIAMS :: CORKERY",
        "CRAIG SWANSON :: MOLINE LIONS",
        "IKE SULLIVAN :: BETHALTO :: 4",
        "KEVIN RANDOLPH :: OAK FOREST :: 5",
        "JASON MEDLIN :: RANTOUL",
        "KEVIN DOLDER :: YORKVILLE",
        "SHAWN DEWISPELAERE :: EL PASO",
        "TROY DONNAHUE :: PANTHER BURBANK",
        "GRANT HOERR :: MORTON :: 3",
        "JEFF BONNET :: PANTHER CUB",
        "TODD STICHT :: BETHALTO",
        "TODD COMBES :: DOLTON :: 1",
        "ERIC RAMIREZ :: ROSEMONT",
        "JONATHAN WALLACE :: BLACKHAWK",
        "ROBERT MURRAY :: ORLAND PARK :: 6",
        "TORY CUNNINGHAM :: MARION",
        "PETE RODRIGUEZ :: DUNDEE",
        "MOSES REED :: DANVILLE",
        "SOLVATOR RIGITANO :: VILLA-LOMBARD",
        "RICK HERZOG :: RAMS",
    ],
    101: [
        "ALAN WILSON :: CRYSTAL LAKE :: 1",
        "MICHAEL BORDERS :: HOOPESTON",
        "JACOB SMITH :: VILLA-LOMBARD :: 6",
        "JOHN LEHMAN :: VITTUM CATS",
        "MATTHEW WIGGINS :: HARVEY",
        "WESS GAFFEY :: MORRISON",
        "TRAVIS ZIMMERMAN :: BETHALTO :: 3",
        "BRYAN MURPHY :: VILLA PARK",
        "DAVID KESTER :: HOOPESTON",
        "LANCE WEBER :: ROSEMONT",
        "SCOTT MABUES :: RIVERDALE",
        "SCOTT HARRISON :: PLAINFIELD INDIAN TRAIL",
        "TIM ROLEY :: MORTON",
        "CRAIG LOREK :: FRANKLIN PARK",
        "NATHAN GRAUMENZ :: VANDALIA",
        "MICHAEL BRUNO :: PLAINFIELD INDIAN TRAIL :: 4",
        "STEVE NIELSEN :: HICKORY HILLS :: 5",
        "TOM CHISAMORE :: HARVARD",
        "CHRIS RODRIGUEZ :: TOMCATS :: 2",
        "NATHAN BADGETT :: BETHALTO",
        "DERRICO DANCRIDGE :: PIRATES",
        "OSCAR YOUNG :: HOOPESTON",
        "RYAN WEST :: KNIGHTS",
        "PATRICK FAHEY :: ST. BARNABAS / CHRIST THE KING",
        # ???? "LUCAS ALT :: HOOPESTON",
    ],
    108: [
        "BRAD BECKER :: BETHALTO",
        "BRIAN PALMORE :: PONTIAC",
        "RICH DIGIROLAMO :: TRAILBLAZER",
        "SCOTT JUTKINS :: LANCER",
        "SCOTT COWAN :: DOLTON",
        "SANDRO NUNEZ :: LIL REAPER :: 4",
        "DAVID CLEMENTZ :: GENESEO :: 6",
        "ERIC PEREZ :: TOMCATS",
        "JASON SEEFORTH :: MT. ZION",
        "ANDY VALCIK :: ORLAND PARK",
        "JOE JOHNSON :: KNIGHTS :: 2",
        "CHRIS OMARA :: MUSTANG",
        "RYAN MASON :: CRYSTAL LAKE :: 5",
        "DARREN SAATHOFF :: BRADLEY-BOURBONNAIS",
        "JOSH KANE :: MOLINE TIGERS",
        "NIKO FRENETTE :: DOLTON",
        "MATT SODERGREN :: ADAMS",
        "KEVIN MASON :: W.F. THUNDERBIRD",
        "BRIAN JOSEPH :: VILLA-LOMBARD :: 1",
        "MATT NELSON :: MORTON",
        "GARY GECAS :: OAK FOREST",
        "MICHAEL BRUCKER :: DANVILLE :: 3",
        "BILLY BRYANT :: BETHALTO",
        "MATTHEW IRVIN :: LITTLE GIANTS",
    ],
    115: [
        "MARK MCMENIMEN :: CROSSFACE",
        "JARED WEBER :: PONTIAC",
        "LEO DELATORRE :: VILLA-LOMBARD :: 5",
        "PATRICK MCENEANEY :: ORLAND PARK :: 4",
        "JIM BRODY :: ADDISON INDIAN TRAIL",
        "JACOB CULBERTSON :: VANDALIA",
        "TY POWERS :: ROCKFORD :: 1",
        "MICHAEL CUBASCHINI :: ST. CHARLES",
        "CHAD SCROGGINS :: MT. ZION",
        "JOE CHIAPPETTA :: FALCON",
        "JESSE CARAWAY :: MURPHYSBORO",
        "MICHAEL COSTELLO :: LAKE FOREST",
        "BRAD KERR :: BETHALTO :: 3",
        "DOUG CALLAHAN :: HINSDALE",
        "BENJAMIN SUTTMAN :: DAKOTA :: 6",
        "PAUL SPONSEL :: PALATINE",
        "BILLY IZZI :: OAK FOREST",
        "BLAKE GLEASON :: PEKIN",
        "BURTON HOLLOWAY :: VILLA-LOMBARD",
        "STEVEN SHADAB :: ELGIN",
        "SCOTT JACOBSON :: HINSDALE",
        "RYAN PETERSON :: MATTOON",
        "DAVID BURTON :: MORTON :: 2",
        "DONKOR PARKER :: HARVEY",
    ],
    122: [
        "ROBERTO RODRIGUEZ :: HARLEM :: 3",
        "JOE ROBERTS :: PONTIAC",
        "ERIC SMITH :: TIGERTOWN TANGLERS",
        "JAKE GRIFFIN :: OAK FOREST",
        "ADAM VASCONEZ :: MEAD",
        "BILLY BIGANE :: CRESTWOOD",
        "MIKE WEBER :: LITTLE DEVILS",
        "TIM GLOVER :: MORTON :: 1",
        "MATTHEW SMILEY :: HOOPESTON",
        "KEVIN MILLIGAN :: VILLA-LOMBARD :: 5",
        "ROCKY CAIFANO :: LIONS",
        "ANTHONY GENOVESI :: NOTRE DAME",
        "MITCHELL CHEST :: CORKERY",
        "JOSE ZEPEDA :: TOMCATS",
        "CLINT FREITAG :: EDWARDSVILLE",
        "CHRIS WINTER :: MAINE TOWNSHIP EAGLES",
        "SHAWN FORST :: TINLEY PARK :: 6",
        "SERGIO TINAJERO :: DUNDEE",
        "JOHN SCHULTZ :: GENESEO :: 2",
        "ANDY RAINS :: MARION :: 4",
        "TARL VON HATTEN :: ST. CHARLES",
        "ANDY MARTINEZ :: PONTIAC",
        "BRET DOUGHERTY :: HARVARD",
        "MATHEW GUILFOYLE :: PLAINFIELD INDIAN TRAIL",
    ],
    130: [
        "NICK STEELE :: GC COOLIDGE",
        "JOSHUA MILLER :: WESTVILLE",
        "BART REED :: GENESEO",
        "GREG SAKOWICZ :: TRAILBLAZER",
        "JASON GUISINGER :: TINLEY PARK :: 1",
        "TOBY THOMAS :: ELGIN",
        "MICHAEL BASILE :: DOLTON",
        "MIKE BERRY :: JORDAN-SETON :: 6",
        "TODD CANNON :: HOOPESTON",
        "BILL BIGGER :: WAUKEGAN :: 4",
        "SHANE SUSINA :: SYCAMORE",
        "MATTHEW UREMOVICH :: LITTLE CELTIC",
        "EMIL ODLING :: HARVARD :: 5",
        "BRIAN SHOBER :: WARHAWKS",
        "MARKELIAN WASHINGTON :: CORKERY",
        "LASHUN JACKSON :: HARVEY",
        "DAN DE BRUN :: VILLA-LOMBARD :: 3",
        "CHAD NEWBERRY :: MARION",
        "MIKE KANKE :: GENESEO :: 2",
        "JOHN SALVINO :: MUSTANG",
        "MICHAEL MARTINEZ :: WAUKEGAN",
        "DUSTIN COOK :: FISHER",
        "JAMES MCCULLOUGH :: LITTLE KNIGHTS",
        "RYAN TACK :: EISENHOWER JH",
        # ???? "KARL MALAGON :: WAUKEGAN",
    ],
    138: [
        "STANLEY EVANS JR :: PIRATES :: 4",
        "JOEY SWOPE :: UNITY YOUTH",
        "WILLIAM BELT :: LITTLE DEVILS",
        "TOMMY GROSSMAN :: TINLEY PARK :: 1",
        "BOBBY HUITT JR :: STREATOR",
        "JEFFREY SCACE :: DAKOTA",
        "DAMARIO PORTER :: CORKERY",
        "NATHAN SKELTON :: BETHALTO :: 6",
        "JEFFREY QUIMBY :: UNITY YOUTH",
        "TONY THEMAS :: TRAILBLAZER",
        "KENNY HENZE :: LIL REAPER",
        "MATT SEAMANS :: MOLINE TIGERS",
        "AARON SHADAB :: ELGIN :: 5",
        "DUSTAN YARMAN :: NAPERVILLE PATRIOTS",
        "SAUL MARQUEZ :: MUSTANG",
        "DEREK STACHURA :: MORTON :: 2",
        "SHAWN GALLAGHER :: PEOTONE",
        "EVAN HILL :: ST. TARCISSUS",
        "HANK STOUT :: VANDALIA :: 3",
        "JOHN JORDAN :: DOLTON",
        "MIKE TAYLOR :: LEMONT",
        "RICHARD OLSEN :: GIBSON CITY",
        "BRANDON YOUNG :: MEAD",
        "PETER DEMEIS :: LITTLE CELTIC",
    ],
    147: [
        "WILLIAM REIDY :: DOLTON :: 6",
        "PHIL TAYLOR JR :: MT. ZION",
        "JEREMIAH OWENS :: LITCHFIELD",
        "DAVID POTTER :: ST. CHARLES :: 2",
        "JUSTIN RUSSOW :: BRADLEY-BOURBONNAIS",
        "UNDRA BAILEY :: PIRATES",
        "MORIO SANCHEZ :: BELVIDERE :: 4",
        "ZACHARY BATHON :: GC COOLIDGE",
        "JOSHUA INGERSOLL :: CHARGER KIDS",
        "JEFF RIEGELEIN :: CROSSFACE",
        "JOSH BRUGH :: LITTLE GIANTS",
        "LUIS MAGANA :: PLAINFIELD INDIAN TRAIL",
        "BOB MEYER :: ADAMS",
        "MATT CORDES :: MOLINE TIGERS",  # MATT COMBES; TYPO?
        "BRIAN LYNDE :: HARLEM",
        "SCOTT EVANS :: LITTLE CELTIC",
        "CHARLES MCNEAL :: ST. CHARLES :: 3",
        "LEDESM ADRIAN :: CORKERY",
        "JASON CHRISTESON :: BETHALTO :: 1",
        "KENNY COOPER :: BELVIDERE",
        "AARON KUEBEL :: FULTON",
        "ADAM LYONS :: DANVILLE :: 5",
        "WILLIAM ANDREWS :: ROBBINS",
        "RYAN LANGILLE :: TRAILBLAZER",
    ],
    156: [
        "BEN MENA :: ROCKFORD :: 1",
        "DARWIN BROWN :: OAKWOOD",
        "RON WALTERS :: BETHALTO",
        "KEVIN BROWER :: JR. ROCKET :: 4",
        "MIKE MEDINA :: LEMONT",
        "JUAN PEREZ :: CORKERY",
        "ERIK CASTANEDA :: EISENHOWER JR HAWK :: 5",
        "CHRIS MILLER :: MARION",
        "GREGG GOSSETT :: HOOPESTON",
        "ARTHUR FALCON :: TRI-CITY BRAVES",
        "CHRIS LECOMPTE :: PANTHER BURBANK",
        "BRANDON MROZ :: GLENDALE",
        "JON LOVRICH :: HICKORY HILLS :: 2",
        "JOSHUA READING :: RICH WRESTLING",
        "JORGE ZAYAS :: WAUKEGAN",
        "JEFFREY BROUCEK :: LEMONT :: 6",
        "NATHAN SELL :: ILLINOIS VALLEY",
        "JEROMY MARTH :: DAKOTA",
        "DAVID PIERSON :: MURPHYSBORO",
        "PAUL BERGE :: FROST",
        "NAPOLEON HARRIS :: HARVEY",
        "ANDY MOORE :: ARGENTA / OREANA :: 3",
        "DEMAS MORENO :: CRYSTAL LAKE",
        "DANIEL STEVENS :: MORTON",
    ],
    166: [
        "MICHAEL BUCKNER :: HARVEY",
        "RYAN BURRIS :: EASTSIDE",
        "KEVIN EBERMAN :: ANTIOCH",
        "GENE BEARD :: VILLA-LOMBARD :: 2",
        "RICHARD ARRINGTON :: W.F. THUNDERBIRD",
        "THOMAS SCHICKEL :: PANTHER BURBANK",
        "D ANDRE DENTON :: PIRATES :: 5",
        "ERIC WENDLING :: HARVARD",
        "CLAY HOLYCROSS :: BISMARCK-HENNING",
        "STEVE HOAG :: JR. ROCKET",
        "ARMOND DAVIS :: CORKERY :: 4",
        "TOM MARSH :: GC COOLIDGE",
        "MICHEAL CUTLER :: DOLTON",
        "JOHN LAMB :: MOLINE TIGERS",
        None,
        "THOMAS RIGGINS :: BETHALTO :: 1",
        "BRIAN ANDERSON :: LEMONT",
        None,
        "RYAN LEMBERG :: YORKVILLE :: 3",
        "THADDEUS PATTERSON :: EISENHOWER JR HAWK",
        "CLYDE BASS :: TIGERTOWN TANGLERS",
        "JOHN LOCKHART :: HOOPESTON",
        "ERIC POWELL :: RICH WRESTLING :: 6",
        "MICHAEL MITTY :: INDIAN PRAIRIE",
        # "JEFFREY BROOKS :: NORTH CHICAGO",
        # "LONNIE HOLMAN :: HARVEY",
    ],
    177: [
        "MIKE GARCHIE :: ADAMS",
        "JOSHUA DRULLINGER :: BISMARCK-HENNING",
        "SCOTT DAVES :: PANTHER CUB :: 6",
        "TOBY ROLLYSON :: MIDWEST CENTRAL",
        "CHRIS PARCK :: NAPERVILLE WARRIORS :: 4",
        "CLARENCE CONNER :: CHICAGO HEIGHTS",
        "ALEX WEMMER :: ROCKFORD",
        "DANIEL LOPEZ :: RICHMOND",
        "KEVIN HUSTEDT :: GIBSON CITY",
        "TOBY ADAMS :: W.F. THUNDERBIRD :: 1",
        "AHMAUD CLARK :: HARVEY",
        "KELAN MOORE :: VILLA-LOMBARD",
        "JOHN LEE :: RICH WRESTLING",
        "BEN BERTELSMAN :: LITTLE DEVILS",
        "JASON MAYNARD :: LAN-OAK",
        "JOHN MAILLET :: DOWNERS GROVE :: 2",
        "TIM STARBUCK :: MACOMB",
        "SHANE SHAMOON :: ROSEMONT",
        "JASON BERG :: DAKOTA :: 3",
        "HAROLD LALUMONDIER :: GC COOLIDGE",
        "SHANE GRAUMENZ :: VANDALIA",
        "JACOB MANNING :: ARGENTA / OREANA",
        "DANNY LESTER :: RAMS",
        "MATTHEW KUEBEL :: FULTON :: 5",
    ],
    189: [
        "JASON NAPE :: CRESTWOOD :: 2",
        "KEVIN TYLER :: HOOPESTON",
        "NICK MANCUSO :: ROCKFORD",
        "JEREMY DURBIN :: VANDALIA :: 3",
        "RYAN WINSTEAD :: MORTON",
        "SPENCER KING :: PIRATES",
        "GREG PIPER :: OAK FOREST",
        "PAUL LOPEZ :: LARKIN",
        "JASON BOGAN :: ROSEMONT",
        "GEORGE GARCIA :: BLACKHAWK II :: 5",
        "JOE MARSICO :: WARHAWKS",
        "STEPHEN SPARROW :: MOLINE TIGERS",
        "ANTHONY ENGLESE :: MEAD :: 1",
        "DARRICK KARSJEN :: BATAVIA",
        "DAVE HICKS :: SENECA",
        "CASEY JONES :: EL PASO",
        "CHAD PIXLEY :: RED HILLS",
        "DAVID NOLAN :: MUSTANG",
        "MIKE DERRY :: HARLEM",
        "CHAD SHEPHERD :: BRADLEY-BOURBONNAIS :: 4",
        "JERRY KRAY :: LEMONT",
        "KOREY REID :: CHARGER KIDS :: 6",
        "TONY KUSTWAN :: DOLTON",
        "JOE WILSON :: LITTLE DEVILS",
    ],
    275: [
        "BALTAZAR NINO :: BATAVIA :: 6",
        "JASON CORKER :: GIBSON CITY",
        None,  # "WILLIARD WRIGHT :: CORKERY",
        "JEREMY WINSTEAD :: PEKIN",
        "LOUIS HILL :: ROCKFORD",
        "PHILIP HARPER :: PIRATES",
        "MARTIN GONZALEZ :: BRADLEY-BOURBONNAIS :: 4",
        "JOE GARRETT :: HOOPESTON",
        "MATTHEW ALFREDSON :: LIL REAPER",
        "NICK CAMPBELL :: GC COOLIDGE",
        "HUBERT THOMPSON :: WARHAWKS :: 1",
        "DANIEL ROGERS :: DAKOTA",
        "DAVID WITTENBORN :: EISENHOWER JR HAWK :: 5",
        "IAN MACCANN :: CARBONDALE",
        "TIM TEEHAN :: TINLEY PARK",
        "CHAD JENKINS :: DAKOTA :: 3",
        "ANDY STOCKMAN :: PEORIA",
        "ELI WALKER :: VILLA-LOMBARD",
        "JASON SURRATT :: OAK LAWN",
        "CHARLES KING :: HARVEY",
        "JOSEPH MCNELLY :: CENTRALIA",
        "ANDY MYERS :: PONTIAC :: 2",
        "MARTY BURTON :: ST. CHARLES",
        "BEN MCKAY :: MOLINE TIGERS",
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "BETHALTO JR. HIGH": 242.0,
    "VILLA-LOMBARD COUGARS": 158.5,
    "HARVEY": 103.5,
    "ST. CHARLES SAINTS": 102.0,
    "TINLEY PARK": 97.0,
    "MORTON": 90.5,
    "CRYSTAL LAKE": 87.0,
    "DOLTON": 87.0,
    "PIRATES": 81.0,
    "ORLAND PARK": 76.5,
    "GENESEO": 74.0,
    "ROCKFORD": 72.5,
    "HARLEM COUGARS": 69.0,
    "DAKOTA": 69.0,
    "MEAD JR. HIGH": 66.5,
    "VANDALIA": 64.5,
    "HICKORY HILLS": 58.0,
    "BRADLEY-BOURBONNAIS": 52.0,
    "DANVILE": 49.0,
    "OAK FOREST": 46.0,
    "ROUND LAKE SPARTANS": 46.0,
    "LIL REAPER": 45.0,
    "RICH WRESTLING": 43.0,
    "YORKVILLE": 40.0,
    "CORKERY": 39.0,
    "FRANKLIN PARK": 37.0,
    "W.F. THUNDERBIRD": 37.0,
    "WARHAWKS": 36.0,
    "PLAINFIELD INDIAN TRAIL": 36.0,
    "KNIGHTS": 34.0,
    "PONTIAC": 30.0,
    "JR. ROCKET": 29.0,
    "TIGERTOWN TANGLERS": 29.0,
    "TOMCATS": 28.0,
    "ROSEMONT": 27.0,
    "ST. BARNABAS / CHRIST THE KING": 26.0,
    "CRESTWOOD COLTS": 26.0,
    "ARGENTA / OREANA": 25.0,
    "DOWNERS GROVE": 24.0,
    "ELGIN": 24.0,
    "MT. VERNON": 23.0,
    "EISENHOWER JR HAWK": 23.0,
    "CHARGER KIDS": 22.0,
    "WAUKEGAN": 22.0,
    "NAPERVILLE WARRIORS": 21.0,
    "EISENHOWER JH": 21.0,
    "FULTON": 21.0,
    "BELVIDERE": 20.0,
    "MARION": 20.0,
    "HARVARD": 19.0,
}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    ("DANNY ALCOCER JR", "TRAILBLAZER"): bracket_utils.Competitor(
        full_name="DANNY ALCOCER JR",
        first_name="DANNY",
        last_name="ALCOCER",
        team_full="TRAILBLAZER",
        team_acronym=None,
    ),
    ("PHILLIP R. RUIZ", "ST. BARNABAS / CHRIST THE KING"): bracket_utils.Competitor(
        full_name="PHILLIP R. RUIZ",
        first_name="PHILLIP",
        last_name="RUIZ",
        team_full="ST. BARNABAS / CHRIST THE KING",
        team_acronym=None,
    ),
    ("WAYNE DEMONBREUN JR", "CRESTWOOD"): bracket_utils.Competitor(
        full_name="WAYNE DEMONBREUN JR",
        first_name="WAYNE",
        last_name="DEMONBREUN",
        team_full="CRESTWOOD",
        team_acronym=None,
    ),
    ("DAVID HILLARD JR", "PIRATES"): bracket_utils.Competitor(
        full_name="DAVID HILLARD JR",
        first_name="DAVID",
        last_name="HILLARD",
        team_full="PIRATES",
        team_acronym=None,
    ),
    ("FRANK DE FILIPPIS", "VILLA-LOMBARD"): bracket_utils.Competitor(
        full_name="FRANK DE FILIPPIS",
        first_name="FRANK",
        last_name="DE FILIPPIS",
        team_full="VILLA-LOMBARD",
        team_acronym=None,
    ),
    ("RON TICKLE JR", "PONTIAC"): bracket_utils.Competitor(
        full_name="RON TICKLE JR",
        first_name="RON",
        last_name="TICKLE",
        team_full="PONTIAC",
        team_acronym=None,
    ),
    ("KENNETH LUTZ JR", "RAIDERS"): bracket_utils.Competitor(
        full_name="KENNETH LUTZ JR",
        first_name="KENNETH",
        last_name="LUTZ",
        team_full="RAIDERS",
        team_acronym=None,
    ),
    ("SAMUEL A WALTON", "TAYLORVILLE"): bracket_utils.Competitor(
        full_name="SAMUEL A WALTON",
        first_name="SAMUEL",
        last_name="WALTON",
        team_full="TAYLORVILLE",
        team_acronym=None,
    ),
    ("RANDY JOE WILKEY", "CENTRALIA"): bracket_utils.Competitor(
        full_name="RANDY JOE WILKEY",
        first_name="RANDY JOE",
        last_name="WILKEY",
        team_full="CENTRALIA",
        team_acronym=None,
    ),
    ("JOE DI GIOIA", "VILLA-LOMBARD"): bracket_utils.Competitor(
        full_name="JOE DI GIOIA",
        first_name="JOE",
        last_name="DI GIOIA",
        team_full="VILLA-LOMBARD",
        team_acronym=None,
    ),
    ("TARL VON HATTEN", "ST. CHARLES"): bracket_utils.Competitor(
        full_name="TARL VON HATTEN",
        first_name="TARL",
        last_name="VON HATTEN",
        team_full="ST. CHARLES",
        team_acronym=None,
    ),
    ("DAN DE BRUN", "VILLA-LOMBARD"): bracket_utils.Competitor(
        full_name="DAN DE BRUN",
        first_name="DAN",
        last_name="DE BRUN",
        team_full="VILLA-LOMBARD",
        team_acronym=None,
    ),
    ("STANLEY EVANS JR", "PIRATES"): bracket_utils.Competitor(
        full_name="STANLEY EVANS JR",
        first_name="STANLEY",
        last_name="EVANS",
        team_full="PIRATES",
        team_acronym=None,
    ),
    ("BOBBY HUITT JR", "STREATOR"): bracket_utils.Competitor(
        full_name="BOBBY HUITT JR",
        first_name="BOBBY",
        last_name="HUITT",
        team_full="STREATOR",
        team_acronym=None,
    ),
    ("PHIL TAYLOR JR", "MT. ZION"): bracket_utils.Competitor(
        full_name="PHIL TAYLOR JR",
        first_name="PHIL",
        last_name="TAYLOR",
        team_full="MT. ZION",
        team_acronym=None,
    ),
    ("D ANDRE DENTON", "PIRATES"): bracket_utils.Competitor(
        full_name="D ANDRE DENTON",
        first_name="D ANDRE",
        last_name="DENTON",
        team_full="PIRATES",
        team_acronym=None,
    ),
}
_BOUT_NUMBER_INPUTS: dict[tuple[bracket_utils.Division, int], tuple[int, int]] = {
    ("novice", 62): (2, 705),
    ("novice", 66): (18, 706),
    ("novice", 70): (34, 707),
    ("novice", 74): (50, 708),
    ("novice", 79): (66, 709),
    ("novice", 84): (82, 710),
    ("novice", 89): (98, 711),
    ("novice", 95): (114, 712),
    ("novice", 101): (130, 713),
    ("novice", 108): (146, 714),
    ("novice", 115): (162, 715),
    ("novice", 122): (178, 716),
    ("novice", 130): (194, 717),
    ("novice", 138): (210, 718),
    ("novice", 147): (226, 719),
    ("novice", 215): (242, 720),
    ("senior", 70): (2, 793),
    ("senior", 74): (18, 794),
    ("senior", 79): (34, 795),
    ("senior", 84): (50, 796),
    ("senior", 89): (66, 797),
    ("senior", 95): (82, 798),
    ("senior", 101): (98, 799),
    ("senior", 108): (114, 800),
    ("senior", 115): (130, 801),
    ("senior", 122): (146, 802),
    ("senior", 130): (162, 803),
    ("senior", 138): (178, 804),
    ("senior", 147): (194, 805),
    ("senior", 156): (210, 806),
    ("senior", 166): (226, 807),
    ("senior", 177): (242, 808),
    ("senior", 189): (258, 809),
    ("senior", 275): (274, 810),
}


def _get_bout_numbers(
    division: bracket_utils.Division, weight: int
) -> dict[bracket_utils.MatchSlot, int]:
    key = (division, weight)
    entry = _BOUT_NUMBER_INPUTS.get(key)
    if entry is None:
        return {}

    first_pigtail, first_place = entry
    if division == "novice":
        weight_count = 16
    elif division == "senior":
        weight_count = 18
    else:
        raise NotImplementedError(division)

    return {
        "championship_r32_02": first_pigtail,
        "championship_r32_04": first_pigtail + 2,
        "championship_r32_06": first_pigtail + 4,
        "championship_r32_08": first_pigtail + 6,
        "championship_r32_10": first_pigtail + 8,
        "championship_r32_12": first_pigtail + 10,
        "championship_r32_14": first_pigtail + 12,
        "championship_r32_16": first_pigtail + 14,
        "consolation_fifth_place": first_place - 2 * weight_count,
        "consolation_third_place": first_place - weight_count,
        "championship_first_place": first_place,
    }


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["novice"] = []
    for team_name, score in _NOVICE_TEAM_SCORES.items():
        team_scores["novice"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    weight_classes: list[bracket_utils.WeightClass] = []

    for weight, competitors in _NOVICE_COMPETITORS.items():
        bout_numbers = _get_bout_numbers("novice", weight)
        weight_class = bracket_utils.weight_class_from_competitors(
            "novice",
            weight,
            competitors,
            _NOVICE_TEAM_REPLACE,
            _NAME_EXCEPTIONS,
            bout_numbers,
        )
        weight_classes.append(weight_class)

    for weight, competitors in _SENIOR_COMPETITORS.items():
        bout_numbers = _get_bout_numbers("senior", weight)
        weight_class = bracket_utils.weight_class_from_competitors(
            "senior",
            weight,
            competitors,
            _SENIOR_TEAM_REPLACE,
            _NAME_EXCEPTIONS,
            bout_numbers,
        )
        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1993.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
