# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils
import manual_entry

_HERE = pathlib.Path(__file__).resolve().parent
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    # 60: "Peter Ruffino :: FALCONS MAYWOOD" # ???
    # 64: "Tim Nelson :: BARRINGTON" # ???
    72: [
        "Grant Hoerr :: MORTON YOUTH :: 2",
        "Cal Ryder :: MATTOON",
        "Matthew Henry :: FRANKLIN PARK RAIDERS",
        "Jake Sullivan :: BETHALTO JR. HIGH SCHOOL",
        "Pat Wrona :: DOLTON PARK FALCONS",
        "Calvin Glasby :: HARVEY PD TWISTERS",
        "Joel Howard :: NAPERVILLE PATRIOTS :: 4",
        "Mike Harrison :: ADDISON / INDIAN TRAIL ANIMALS",
        "Chris Thompson :: CUMBERLAND COUNTY",
        "Jessie Flores :: LIL REAPER",
        "Roamelle Kizzee :: HARVEY PD TWISTERS :: 6",
        "Patrick Fahey :: ST. BARNABAS / CHRIST THE KING",
        "David Douglas :: HARVEY PD TWISTERS :: 5",
        "Michael Bondi :: DUNDEE HIGHLANDERS",
        "Brian Comstock :: GENEVA PD",
        "Tony Gill :: DOLTON PARK FALCONS :: 3",
        "JC Gaunt :: GOLDEN EAGLES LTD",
        "Brian Prunty :: MACOMB YMCA KIDS W.C.",
        "Lawan Gray :: WARHAWKS :: 1",
        "Jeremy Larsen :: OSWEGO COUGARS",
        "Lucas Dyer :: ANTIOCH UPPER GRADE",
        "Lucas Aht :: HOOPESTON-EAST LYNN JR.",
        "Shawn Dewispelaere :: EL PASO",
        "Doc Sanders :: EDWARDSVILLE",
    ],
    77: [
        "Aaron Gilson :: ST. CHARLES",
        "Brian Ebersole :: BRADLEY - BOURBONNAIS",
        "Mike Komo :: MAINE TWP. EAGLES",
        "James Aberle :: ROUND LAKE SPARTAN :: 4",
        "Nick Burrows :: LITTLE DEVILS BELLEVILLE",
        "Matthew Lackey :: MOLINE TIGERS",
        "Milton Blakely :: HARVEY PD TWISTERS :: 1",
        "Craig Lorek :: FRANKLIN PARK RAIDERS",
        "Shane Cox :: WESTVILLE JR. HIGH",
        "Ryan Delira :: DOLTON PARK FALCONS :: 5",
        "Matt Nelson :: CHILLICOTHE",
        "Brad Becker :: BETHALTO JR. HIGH SCHOOL",
        "Daniel Borland :: BLUE CREW :: 2",
        "Steven Nielsen :: HICKORY HILLS PD",
        "Gregory Cora :: OAK FOREST WARRIORS",
        "Chris Hogan :: GRANITE CITY GRISBY",
        "Ryan Mason :: CRYSTAL LAKE WIZARDS",
        "Wesley Young :: AURORA J HAWKS",
        "Alan Cartwright :: WARHAWKS :: 3",
        "Kevin Randolph :: OAK FOREST WARRIORS",
        "Matthew Fahey :: ST. BARNABAS / CHRIST THE KING",
        "Ryan Owens :: MT. ZION",
        "Ian Penzato :: VILLA LOMBARD COUGARS :: 6",
        "Berry Chapman :: ROUND LAKE SPARTAN",
    ],
    82: [
        "Tony Davis :: HARVEY PD TWISTERS :: 1",
        "Tony Niebur :: REDBIRDS",
        "Luke Ewanio :: ROSEMONT COBRAS",
        "Fran Blake :: MUSTANGS :: 6",
        "Robert Pyfer :: HARLEM SCHOOL DIST. 122",
        "Dale Simpson :: WHEATON WARRENVILLE",
        "Tim Glover :: MORTON YOUTH :: 4",
        "Timothy Kazmierczak :: FRANKLIN PARK RAIDERS",
        "Chad Moore :: WESTVILLE JR. HIGH",
        "Travis Zimmerman :: BETHALTO JR. HIGH SCHOOL",
        "Michael Husslein :: VILLA LOMBARD COUGARS",
        "Josh Moore :: KNIGHT",
        "Brian Joseph :: VILLA LOMBARD COUGARS",
        "Billy Bryant :: BETHALTO JR. HIGH SCHOOL",
        "James Ealy :: ROCKRIDGE JR. HIGH",
        "Alan Wilson :: CRYSTAL LAKE WIZARDS",
        "Billy Kucinski :: VITTUM CATS",
        "Francisco Bermudez :: LOCKPORT GRAPPLERS :: 2",
        "Griff Powell :: ARLINGTON CARDINALS :: 5",
        "Cody Vanklaveren :: MOLINE TIGERS",
        "Jason Hayden :: ROXANA VIKINGS",
        "Drew Blickensderfer :: MT. ZION",
        "Tommy Lee :: OAK FOREST WARRIORS :: 3",
        "Conor Ruel :: ST. BARNABAS / CHRIST THE KING",
    ],
    87: [
        "Micheal Delisle :: RAIDERS :: 5",
        "Richard Root :: CHATHAM",
        "John Evans :: OAK FOREST WARRIORS",
        "Shaun Bouback :: BELVIDERE YMCA BANDITS :: 4",
        "Justin Henry :: WARHAWKS",
        "Keith Gall :: VILLA LOMBARD COUGARS",
        "Elijah Roberts :: ROCK ISLAND",
        "Jake Griffin :: OAK FOREST WARRIORS",
        "Nick Upton :: MATTOON",
        "Jim Brasher :: VITTUM CATS :: 2",
        "Leo Delatorre :: VILLA LOMBARD COUGARS",
        "Poncho Villarreal :: ARLINGTON CARDINALS",
        "Jason Rahn :: AURORA J HAWKS",
        "Josue Villasenor :: DOLTON PARK FALCONS",
        "Mike Hasty :: MORTON YOUTH",
        "Reginald Wright :: WARHAWKS :: 1",
        "Ty Powers :: HARLEM SCHOOL DIST. 122",
        "John Heathcott :: EDWARDSVILLE",
        "Mike O'Neill :: TINLEY PARK BULLDOGS :: 3",
        "Josh Inch :: GENESEO",
        "Derek Starr :: HINSDALE RED DEVILS :: 6",
        "Jeff Wilson :: MT. ZION",
        "Matt Tomanovich :: WEST FRANKFORT THUNDERBIRDS",
        "Matt Bagley :: LIL REAPER",
    ],
    93: [
        "Blake Hoerr :: MORTON YOUTH :: 2",
        "Brian Nettleton :: GIBSON CITY YOUTH",
        "Philp Thorne :: OAK FOREST WARRIORS :: 3",
        "Patrick Sheahan :: ST. BARNABAS / CHRIST THE KING",
        "Matthew McDonnell :: CRYSTAL LAKE WIZARDS",
        "Ronnie Hansen :: EDWARDSVILLE",
        "Javier Parras :: TOMCATS :: 6",
        "Robert Dela Fuente :: LOCKPORT GRAPPLERS",
        "Michael Brucker :: GEORGETOWN",
        "Sean Klatt :: ARLINGTON CARDINALS",
        "Luke Rives :: BETHALTO JR. HIGH SCHOOL",
        "Roberto Rodriguez :: HARLEM SCHOOL DIST. 122",
        "Jason Christeson :: BETHALTO JR. HIGH SCHOOL",
        "Ryan Duggan :: ST. TARCISSUS RAIDERS",
        "Kevin Milligan :: VILLA LOMBARD COUGARS",
        "Rob Anderson :: BELVIDERE YMCA BANDITS :: 1",
        "Patrick O'Connor :: ST. BARNABAS / CHRIST THE KING",
        "C.J. Jacks :: MOLINE TIGERS",
        "Terrance Snapp :: JOLIET BOYS CLUB COBRAS :: 4",
        "Henry Len Franklin :: BLACKHAWK :: 5",
        "Marcus Wegner :: NOTRE DAME",
        "Jon Swanson :: MT. ZION",
        "Zac Charlton :: FORMAN",
        "Ron Winchel :: MUSTANGS",
    ],
    105: [
        "Marcus Smith :: ELGIN GRAPPLERS",
        "Jimmy Talbert :: OAKWOOD",
        "Clint Hornbuckle :: YORKVILLE",
        "Dan McNulty :: ST. BARNABAS / CHRIST THE KING :: 6",
        "Adam Wattles :: OAK FOREST WARRIORS",
        "Matt Webster :: METAMORA KIDS :: 2",
        "Mike Greenfield :: LITTLE DEVILS BELLEVILLE",
        "Peter Currie :: VILLA LOMBARD COUGARS",
        "Cory Schroeder :: GIBSON CITY YOUTH",
        "Joseph Geraci :: ARLINGTON CARDINALS",
        "Aaron Christiansen :: TIGERTOWN TANGLERS :: 4",
        "Ricky Perez :: CALUMET MEMORIAL PD",
        "Tyler Hurry :: RIVERDALE JR. HIGH :: 1",
        "Trent Vensas :: ROSEMONT COBRAS",
        "Andy Rains :: MARION :: 5",
        "Michael Grencik :: TINLEY PARK BULLDOGS",
        "Matt Dorgan :: MUSTANGS",
        "Philip McCormick :: SYCAMORE COMMUNITY SCHOOL",
        "Richard Berendson :: WEST CHICAGO PD",
        "TJ Slay :: GRANITE CITY GRISBY :: 3",
        "Daniel McDonough :: MEAD JR. HIGH SCHOOL",
        "Luke Tuggle :: WESTVILLE JR. HIGH",
        "Ben Mena :: HARLEM SCHOOL DIST. 122",
        "Antwaun Scott :: MASON SCHOOL PLAYGROUND",
    ],
    112: [
        "Matt Ferguson :: LITTLE DEVILS BELLEVILLE :: 6",
        "Matt Terrell :: BISMARK - HENNING",
        "Gildardo Lopez :: TOMCATS",
        "Ryan Lee :: ROSEMONT COBRAS",
        "Timothy Donnahue :: PANTHERS :: 3",
        "David Creighton :: CRYSTAL LAKE WIZARDS",
        "Chad Orr :: RIVERDALE JR. HIGH",
        "Billy Hughes :: BLACKHAWK",
        "Adam Lyons :: OAKWOOD",
        "Timothy Williams :: HARVEY PD TWISTERS :: 1",
        "Isaac Hood :: NORTH CHICAGO MIDGET WARHAWKS",
        "Tom Ciezki :: MUSTANGS",
        "Stephen Zalapi :: ANTIOCH UPPER GRADE",
        "Ed Howlett :: TINLEY PARK BULLDOGS",
        "Rusty Smith :: METAMORA KIDS",
        "Steven Torres :: VITTUM CATS :: 4",
        "Sean Lovelace :: ARLINGTON CARDINALS",
        "Alex Smiley :: BETHALTO JR. HIGH SCHOOL",
        "Randy Divelbiss :: WHEATON WARRENVILLE",
        "Matt Wilson :: GENESEO",
        "Michael Lucido :: CALUMET MEMORIAL PD",
        "Cody Abbott :: URBANA KIDS :: 2",
        "Ronnie Gill :: MURPHY JR. HIGH",
        "Kevin O'Niell :: ADDAMS JR. HIGH SCHOOL W.C. :: 5",
        # "Nick Schumacher :: ADDISON / INDIAN TRAIL ANIMALS" # ???
    ],
    119: [
        "Sam Crowder :: JORDON",
        "Clay Roan :: CUMBERLAND COUNTY",
        "Germaine Lishman :: BLACKHAWK :: 3",
        "Robert Jenkins :: OAK FOREST WARRIORS",
        "Jarvis Wardlow :: WARHAWKS",
        "Richard Ripley :: MURPHY JR. HIGH",
        "James Patterson :: LAKE VILLA LANCERS",
        "Carlo Valentino :: BATAVIA",
        "Chris Hall :: URBANA KIDS",
        "Joseph Brauer :: PANTHERS :: 2",
        "Thomas Riggins :: ROXANA VIKINGS",
        "Larry Zoldowski :: ST. TARCISSUS RAIDERS :: 6",
        "Jeremy Christeson :: BETHALTO JR. HIGH SCHOOL",
        "Steven Carroll :: DOLTON PARK FALCONS :: 5",
        "Johnny Crenshaw :: HARLEM SCHOOL DIST. 122",
        "Daniel Weber :: ADDAMS JR. HIGH SCHOOL W.C. :: 1",
        "Charles Crescenzo :: LITTLE CELTICS",
        "Peter Cleary :: EL PASO",
        "Corey Schoo :: VILLA LOMBARD COUGARS",
        "Timothy Gehant :: BELVIDERE YMCA BANDITS",
        "Dylan Shaughnessy :: CRESTWOOD COLTS",
        "Timothy Forgey :: DECATUR :: 4",
        "Randy Richardson :: METAMORA KIDS",
        "Issac Hampton :: CALUMET MEMORIAL PD",
    ],
    127: [
        "Ken Mills :: DOLTON PARK FALCONS :: 2",
        "Ben Sollars :: HOOPESTON-EAST LYNN JR.",
        "Jon Ketelsen :: RIVERDALE JR. HIGH",
        "Ramon Navarro :: GORDON TECH RAMS",
        "Matt Andriano :: TRAILBLAZERS",
        "Jamie Kirby :: GRANITE CITY COOLIDGE",
        "Aaron Latino :: BELVIDERE YMCA BANDITS",
        "Billy Missel :: STREATOR BULLDOGS",
        "Kevin Temples :: BISMARK - HENNING",
        "Josh Pearson :: TRI-CITY BRAVES :: 3",
        "John Hope :: MURPHY JR. HIGH",
        "Brett Runkle :: YORKVILLE :: 5",
        "Preston Deason :: WEST FRANKFORT THUNDERBIRDS",
        "Chad Albold :: PLAINFIELD INDIAN TRAIL",
        "Chris Segatto :: SYCAMORE COMMUNITY SCHOOL",
        "Ruben Saldana :: TOMCATS :: 1",
        "Tim Duggan :: ST. TARCISSUS RAIDERS :: 4",
        "Ryan Sheahan :: ST. BARNABAS / CHRIST THE KING",
        "Rick Babb :: CHILLICOTHE",
        "Jason Breen :: ANTIOCH UPPER GRADE",
        "Ray Gunier :: LOCKPORT GRAPPLERS",
        "Cecil Severado :: GEORGETOWN :: 6",
        "Ryan Stonitsch :: CRESTWOOD COLTS",
        "David Diaz :: FROST / BAD BOYZ",
    ],
    135: [
        "Ray Hopkins :: SYCAMORE COMMUNITY SCHOOL",
        "Timothy Brant :: BISMARK - HENNING",
        "Chad Snook :: GENESEO",
        "Pat Otto :: ORLAND PARK PIONEERS :: 4",
        "Mike Lopez :: FROST / BAD BOYZ",
        "Randy Anderson :: CRESTWOOD COLTS",
        "Adam Witsken :: BETHALTO JR. HIGH SCHOOL",
        "Deric Schradeya :: JORDON :: 5",
        "Ryan Reinhart :: UNITY YOUTH",
        "Chris Kucharski :: INDIAN PRAIRIE PIONEERS :: 2",
        "Bill Zeman :: LIONS",
        "Jake Bricker :: DUKES WRESTLING YORKS",
        "Mike Bertoni :: VITTUM CATS :: 1",
        "Daniel Beatty :: TRAILBLAZERS",
        "Brian Decker :: MURPHY JR. HIGH",
        "Brandon Presern :: FRANKLIN PARK RAIDERS :: 3",
        "Daman Montello :: PLAINFIELD INDIAN TRAIL",
        "Robert Ertmer :: PANTHER CUBS",
        "Leeantwon Jones :: ROCK ISLAND :: 6",
        "Russell Wininger :: WEST FRANKFORT THUNDERBIRDS",
        "Brian Runkle :: YORKVILLE",
        "Korry Zike :: CUMBERLAND COUNTY",
        "Josh Johnston :: ANTIOCH UPPER GRADE",
        "Dave Marevka :: PEOTONE PD",
    ],
    144: [
        "Les Whittaker :: LITTLE DEVILS BELLEVILLE :: 3",
        "Jerome Holt :: DECATUR",
        "Andy Ball :: MACOMB YMCA KIDS W.C.",
        "Steven Alf :: ST. CHARLES :: 5",
        "Dan Roth :: ORLAND PARK PIONEERS",
        "Peter Hackman :: HARLEM SCHOOL DIST. 122",
        "Ray Todd Guzak :: CRESTWOOD COLTS :: 2",
        "Matt Peterson :: CHILLICOTHE",
        "David Delmonico :: DEWITT COUNTY",
        "John Ochana :: FROST / BAD BOYZ",
        "Ryan Seloover :: ELGIN MATT RATS",
        "Roy Bardwell :: TRI-CITY BRAVES",
        "Angel Morales :: WAUKEGAN PD HAWKEYE :: 6",
        "Louis Sponsel :: PALATINE CHARGERS",
        "Terry McCabe :: MUSTANGS",
        "James Hlavin :: PLAINFIELD INDIAN TRAIL",
        "Scott Slaughter :: OSWEGO PANTHERS",
        "Brett Mason :: WEST FRANKFORT THUNDERBIRDS",
        "Shane Hudnall :: GENESEO :: 1",
        "Kevin Omara :: MUSTANGS",
        "Terry Pierce :: NOTRE DAME",
        "Shane White :: DEWITT COUNTY",
        "Tony Buchek :: GRANITE CITY COOLIDGE :: 4",
        "Willie Trezvant :: BLACKHAWK",
    ],
    153: [
        "Jason Salley :: EISENHOWER JR. HIGH :: 3",
        "Ben Pyle :: HOOPESTON-EAST LYNN JR.",
        "Matt Dawson :: WEST FRANKFORT THUNDERBIRDS",
        "Tim Angsten :: TINLEY PARK BULLDOGS :: 2",
        "David Freeman :: ROCKRIDGE JR. HIGH",
        "Brad Cobb :: SYCAMORE COMMUNITY SCHOOL",
        "William Arthur :: VITTUM CATS :: 5",
        "Justin Bilderback :: MURPHY JR. HIGH",
        "Ryan Harter :: BISMARK - HENNING",
        "Gregory Radish :: BATAVIA",
        "Jason Sauber :: KNIGHT",
        "Donald Hock :: GENESEO",
        "Chuck Blazer :: HARVARD :: 6",
        "Jared McDonough :: NAPERVILLE WARRIORS",
        "Joe Barrins :: MUSTANGS",
        "Adam Mool :: EL PASO :: 1",
        "Eddie Adam :: PLAINFIELD INDIAN TRAIL",
        "Jason Nicolosi :: WARHAWKS",
        "Brent Rogers :: EDWARDSVILLE :: 4",
        "Pat Mai :: DOLTON PARK FALCONS",
        "Chet Stroschine :: NAPERVILLE WARRIORS",
        "Bill Baird :: BISMARK - HENNING",
        "Nate Vaughn :: MEAD JR. HIGH SCHOOL",
        "Quincy Porter :: TRI-CITY BRAVES",
        # "John Deligiannis :: HICKORY HILLS PD" # ???
    ],
    163: [
        "Anthony Munizzi :: MUSTANGS",
        "Jamie Castle :: UNITY YOUTH",
        "Ryan Collins :: BETHALTO JR. HIGH SCHOOL",
        "Al Olieh :: TRAILBLAZERS :: 6",
        "Omari McClellan :: HARVEY PD TWISTERS",
        "Damion Flowers :: WARHAWKS",
        "Matt Heiser :: ELGIN MATT RATS :: 4",
        "Tony Leopold :: EDWARDSVILLE",
        "Rob Neal :: GIBSON CITY YOUTH",
        "John Rupprecht :: GENESEO :: 1",
        "John Kern :: MEAD JR. HIGH SCHOOL",
        "Sam Pavesich :: PEOTONE PD",
        "Daryl Phillips :: FRANKLIN PARK CHIEFS",
        "Nick Knapp :: PEORIA RAZORBACKS YOUTH :: 2",
        "Dan Newcomb :: ANTIOCH UPPER GRADE",
        "Nicholas Piper :: OAK FOREST WARRIORS",
        "Nathanial Fookes :: BATAVIA",
        "Jason Nowicki :: CRESTWOOD COLTS",
        "Matt Major :: MURPHY JR. HIGH :: 5",
        "Ches Dougherty :: HARVARD",
        "Brian Benson :: ILLINI BLUFFS",
        "Greg Baird :: BISMARK - HENNING :: 3",
        "Tony Zitzka :: HICKORY HILLS PD",
        "Dan Rudny :: NAPERVILLE WARHAWKS",
    ],
    173: [
        "Jason Harper :: NORTH CHICAGO MIDGET WARHAWKS",
        "Greg Homrighous :: MT. ZION",
        "Craig Eddinger :: LITTLE DEVILS BELLEVILLE",
        "Chris Kearney :: EL PASO",
        "Kris Hermansen :: LEMONT :: 1",
        "Jack Patti :: DUKES WRESTLING YORKS",
        "Peter Mikhail :: GORDON TECH RAMS :: 5",
        "Ryan Callajs :: MURPHY JR. HIGH",
        "Clinton Smith :: ARGENTA - OREANA W.C.",
        "Kevin Corrigan :: IRISH CADETS",
        "Bob Rowell :: VITTUM CATS",
        "Steven Harvard :: EDISON MIDDLE :: 3",
        "Brian Billett :: HICKORY HILLS PD :: 4",
        "Ricky Hudson :: HARVEY PD TWISTERS",
        "Ben Kieckhefer :: WARHAWKS",
        "Jerry Planek :: WEST CHICAGO PD :: 2",
        "Johnny Knight :: MACOMB YMCA KIDS W.C.",
        "Tim Brown :: HARVARD",
        "Mark King :: MURPHY JR. HIGH :: 6",
        "Ken Galton :: ADDISON / INDIAN TRAIL ANIMALS",
        "Ryan Peterson :: BETHALTO JR. HIGH SCHOOL",
        "Jason Crippin :: BISMARK - HENNING",
        "Stanley Hayes :: WAUKEGAN PD HAWKEYE",
        "Tony Wright :: TIGERTOWN TANGLERS",
        # "Matthew Jacobs :: MURPHY JR. HIGH" # ???
    ],
    185: [
        "Lewis Lang :: RICH WRESTLING",
        "Chris McCay :: HOOPESTON-EAST LYNN JR.",
        "Jeffrey Alheit :: CRYSTAL LAKE WIZARDS",
        "Craig Turner :: TRAILBLAZERS :: 5",
        "Josh Mileur :: MURPHY JR. HIGH",
        "Marc Speziale :: GORDON TECH RAMS",
        "Dan Volipendentest :: LITTLE GIANTS :: 2",
        "Jacob Nathan :: LAKE VILLA LANCERS",
        "David Yokley :: UNITY YOUTH :: 4",
        "Brian Smith :: TIGERTOWN TANGLERS",
        "Andrew Dall :: LIONS",
        "Eric Balch :: MURPHY JR. HIGH",
        "Chris Rowell :: VITTUM CATS",
        "Matt Hoffmiller :: NEWMAN BLUE DEVILS",
        "Bryan Epting :: WARHAWKS :: 6",
        "Josh Champlin :: EDWARDSVILLE",
        "Mike Flaar :: OSWEGO PANTHERS",
        "Bobby Zink :: IRISH CADETS",
        "Jose Saucedo :: HARVARD :: 3",
        "Mark Comny :: PALATINE CHARGERS",
        "Ken Keltner :: BLUE CREW",
        "Mark Harvey :: MT. ZION :: 1",
        "Ronald Becker :: PLAINFIELD INDIAN TRAIL",
        "Marco Ordaz :: AURORA J HAWKS",
    ],
    275: [
        "Luis Aguirre :: FROST / BAD BOYZ :: 3",
        "Matthew Freeman :: MT. ZION",
        "Bill Ries :: LAKE VILLA LANCERS",
        "Bill Parrish :: EL PASO",
        "Albert Licka :: VILLA LOMBARD COUGARS :: 2",
        "Dave Rodriques :: DUKES WRESTLING YORKS",
        "Paul Naumowicz :: PANTHERS",
        "Gregorio Bonilla :: NORTH CHICAGO MIDGET WARHAWKS",
        "Randy Matas :: ARGENTA - OREANA W.C.",
        "Jeff Sticht :: BETHALTO JR. HIGH SCHOOL :: 6",
        "Eddy Solis :: IRISH CADETS",
        "Robert Kronn :: NAPERVILLE PATRIOTS",
        "Ricky Biggs :: HARVEY PD TWISTERS :: 5",
        "Terry Thornton :: BETHALTO JR. HIGH SCHOOL",
        "Jason Nape :: CRESTWOOD COLTS",
        "Richard Reynolds :: AURORA J HAWKS :: 1",
        "Ricardo Rodriguez :: CHILLICOTHE",
        "Eric Dongus :: GORDON TECH RAMS",
        "Mike Carreno :: LIL REAPER",
        "Timothy Edwards :: DOLTON PARK FALCONS",
        "Brad Evans :: EDWARDSVILLE",
        "Michael Rossow :: BRADLEY - BOURBONNAIS :: 4",
        "John Rutledge :: FRANKLIN PARK CHIEFS",
        "Jake Johnston :: METAMORA KIDS",
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "HARVEY PD TWISTERS": 169.0,
    "DOLTON PARK FALCONS": 146.5,
    "WARHAWKS": 109.0,
    "VITTUM CATS": 93.0,
    "BETHALTO JR. HIGH SCHOOL": 92.5,
    "TOMCATS": 89.5,
    "FRANKLIN PARK RAIDERS": 70.0,
    "PANTHERS": 68.0,
    "GENESEO": 66.0,
    "VILLA LOMBARD COUGARS": 65.5,
    "BELVIDERE YMCA BANDITS": 65.0,
    "LITTLE DEVILS BELLEVILLE": 63.5,
    "MORTON YOUTH": 60.0,
    "ARLINGTON CARDINALS": 58.0,
    "OAK FOREST WARRIORS": 55.0,
    "LOCKPORT GRAPPLERS": 54.0,
    "TINLEY PARK BULLDOGS": 53.0,
    "LITTLE GIANTS": 52.0,
    "HARVARD": 50.0,
    "AURORA J HAWKS": 46.0,
    "NAPERVILLE PATRIOTS": 46.0,
    "MT. ZION": 43.5,
    "TRAILBLAZERS": 43.5,
    "ADDAMS JR. HIGH SCHOOL W.C.": 42.0,
    "PLAINFIELD INDIAN TRAIL": 42.0,
    "BLACKHAWK": 41.0,
    "TIGERTOWN TANGLERS": 41.0,
}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    ("Darnell D Lollis", "HARVEY PD TWISTERS"): bracket_utils.Competitor(
        full_name="Darnell D Lollis",
        first_name="Darnell",
        last_name="Lollis",
        team_full="HARVEY PD TWISTERS",
    ),
    ("Robert Dela Fuente", "LOCKPORT GRAPPLERS"): bracket_utils.Competitor(
        full_name="Robert Dela Fuente",
        first_name="Robert",
        last_name="Dela Fuente",
        team_full="LOCKPORT GRAPPLERS",
    ),
    ("Henry Len Franklin", "BLACKHAWK"): bracket_utils.Competitor(
        full_name="Henry Len Franklin",
        first_name="Henry",
        last_name="Len Franklin",
        team_full="BLACKHAWK",
    ),
    ("Ray Todd Guzak", "CRESTWOOD COLTS"): bracket_utils.Competitor(
        full_name="Ray Todd Guzak",
        first_name="Ray Todd",
        last_name="Guzak",
        team_full="CRESTWOOD COLTS",
    ),
}


def _get_bout_numbers() -> dict[bracket_utils.MatchSlot, int]:
    return {
        "championship_r32_02": 1,
        "championship_r32_04": 2,
        "championship_r32_06": 3,
        "championship_r32_08": 4,
        "championship_r32_10": 5,
        "championship_r32_12": 6,
        "championship_r32_14": 7,
        "championship_r32_16": 8,
        "consolation_fifth_place": 35,
        "consolation_third_place": 36,
        "championship_first_place": 37,
    }


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, score=score)
        )

    weight_classes = manual_entry.load_manual_entries(
        _HERE.parent, 1991, _NAME_EXCEPTIONS
    )
    for weight, competitors in _SENIOR_COMPETITORS.items():
        bout_numbers = _get_bout_numbers()
        weight_class = bracket_utils.weight_class_from_competitors(
            "senior",
            weight,
            competitors,
            _SENIOR_TEAM_REPLACE,
            _NAME_EXCEPTIONS,
            bout_numbers,
        )
        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1991.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
