# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils
import manual_entry

_HERE = pathlib.Path(__file__).resolve().parent
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    # 60: "Grant Hoerr :: CHILLICOTHE WC" # ???
    64: [
        "Mike Smith :: BETHALTO BOYS CLUB BULLS",
        "Juan Salgado :: JR. BISON WC",
        "Paul Garbis :: INDIAN PRAIRIE TRAILBLAZERS",
        "Eric Henry :: REDBIRD WC",
        "Daniel Forystek :: THORNWOOD KIDS WC",
        "Ryan De Lira :: DOLTON PARK FALCONS :: 6",
        "Jerry Clementz :: GENESEO WC",
        "Brian Comstock :: ST. CHARLES WC",
        "Archie Griffin :: OAK PARK RIVER FOREST WARHAWKS",
        "Chris Bonati :: DUNDEE HIGHLANDERS :: 4",
        "Patrick Wrona :: DOLTON PARK FALCONS",
        "David Douglas :: HARVEY PARK DISTRICT TWISTERS :: 2",
        "Matt Goldstein :: LITTLE GIANTS WC :: 1",
        "Nicholas Delisle :: RAIDER WC",
        "Brad Prunty :: MACOMB YMCA KIDS WRESTLING",
        "Gerry Hilton :: THORNWOOD KIDS WC :: 5",
        "Moses Reed :: DANVILLE WC",
        "Brian Wilson :: DUNDEE HIGHLANDERS",
        "Jason Malmstrom :: OSWEGO PANTHERS",
        "Adam Jones :: PEORIA RAZORBACKS YOUTH WC",
        "Pat Gaskin :: ST. BARNABAS / CHRIST THE KING",
        "Sean Hastings :: VITTUM CATS :: 3",
        "Brad Vermillion :: DUNDEE HIGHLANDERS",
        "Ronnie Dalluge :: MT. ZION WC",
    ],
    68: [
        "Tim Donohoo :: BETHALTO BOYS CLUB BULLS",
        "Chris Thompson :: CUMBERLAND COUNTY WC",
        "Lawan Gray :: OAK PARK RIVER FOREST WARHAWKS",
        "Francisco Bermudez :: LOCKPORT GRAPPLERS WC :: 2",
        "Jason Lau :: VITTUM CATS",
        "Ryan Mason :: SYCAMORE WC",
        "Joel Howard :: NAPERVILLE PATRIOTS WRESTLING :: 6",
        "Craig Lorek :: JR. BISON WC",
        "Mike Nelson :: REDBIRD WC",
        "Danny Borland :: BLUE CREW WRESTLING CLUB :: 3",
        "Michael Bondi :: DUNDEE HIGHLANDERS",
        "Ben Black :: HINSDALE RED DEVIL WC",
        "Lucas Alt :: HOOPESTON-EAST LYNN JR. HIGH",
        "J.C. Gaunt :: GOLDEN EAGLES",
        "Adam Dyche :: AURORA J-HAWKS",
        "Brian Hastings :: VITTUM CATS",
        "Milton Blakely :: HARVEY PARK DISTRICT TWISTERS :: 5",
        "Matt Nelson :: CHILLICOTHE WC",
        "Marc Zehr :: ARLINGTON CARDINALS WC :: 1",
        "Aaron Gilson :: ST. CHARLES WC",
        "Ike Sullivan :: BETHALTO BOYS CLUB BULLS",
        "Jim Aberle :: ROUND LAKE SPARTANS :: 4",
        "Phillip J. Foster :: NEWMAN BLUE DEVILS",
        "Chris Traversa :: PLAINFIELD INDIAN TRAIL WILDCATS",
    ],
    72: [
        "Brad Becker :: BETHALTO BOYS CLUB BULLS",
        "Chris Yourgalite :: HOOPESTON-EAST LYNN JR. HIGH",
        "Luke Ewanio :: ROSEMONT COBRAS WRESTLING",
        "Bill Kucinski :: VITTUM CATS",
        "Tim Glover :: MORTON YOUTH WRESTLING :: 6",
        "Scooter Gregory :: OSWEGO COUGARS",
        "Tony Davis :: HARVEY PARK DISTRICT TWISTERS :: 1",
        "Alan Cartwright :: OAK PARK RIVER FOREST WARHAWKS :: 4",
        "Kevin Wilson :: MATTOON WC",
        "Justin Dyer :: ANTIOCH UPPER GRADE",
        "Brian Joseph :: GENEVA PARK DISTRICT",
        "Craig Gillum :: METAMORA KIDS WC",
        "Scott Ginger :: REDBIRD WC",
        "John Heathcott :: EDWARDSVILLE",
        "Nick Hoehn :: TINLEY PARK BULLDOGS",
        "Michael Galvin :: FORMAN WC",
        "Jim Gahagan :: VITTUM CATS :: 2",
        "Jim Jones :: ROUND LAKE SPARTANS",
        "Matthew Wegner :: WARRIOR WC (NILES) :: 3",
        "Tommy Lee :: OAK FOREST WARRIORS :: 5",
        "Billy Bryant :: BETHALTO BOYS CLUB BULLS",
        "Ian Penzato :: VILLA-LOMBARD COUGARS",
        "Berry Chapman :: ROUND LAKE SPARTANS",
        "Jacob Doody :: ST. BARNABAS / CHRIST THE KING",
    ],
    77: [
        "Jason Christeson :: BETHALTO BOYS CLUB BULLS",
        "Don Bermudez :: LOCKPORT GRAPPLERS WC :: 1",
        "Tony Niebur :: REDBIRD WC",
        "Mike Harrington :: ROUND LAKE SPARTANS",
        "Justin Henry :: WEST CHICAGO WILDCATS P.D.",
        "William Tyler :: OAK PARK RIVER FOREST WARHAWKS",
        "Jim Brasher :: VITTUM CATS :: 5",
        "Jeff Wilson :: MT. ZION WC",
        "Philip Thorne :: OAK FOREST WARRIORS",
        "Blake Hoerr :: CHILLICOTHE WC :: 3",
        "John Kopecky :: ROSEMONT COBRAS WRESTLING",
        "Kevin Milligan :: VILLA-LOMBARD COUGARS",
        "Durand Womack :: HARVEY PARK DISTRICT TWISTERS :: 4",
        "Travis Zimmerman :: BETHALTO BOYS CLUB BULLS",
        "Andrew O'Malley :: ST. BARNABAS / CHRIST THE KING :: 6",
        "David Kabbe :: NAPERVILLE WARRIORS",
        "Alan Wilson :: DUNDEE HIGHLANDERS",
        "Mike Hasty :: MORTON YOUTH WRESTLING",
        "Andrew Blickensderfer :: MT. ZION WC",
        "Jared Camer :: MUSTANG WC",
        "Tim Vediz :: EDWARDSVILLE",
        "Marc Wegner :: WARRIOR WC (NILES)",
        "Thomas Grennan :: NEWMAN BLUE DEVILS :: 2",
        "Robby Pyfer :: HARLEM-PARK BOYS CLUB",
    ],
    82: [
        "Michael Shields :: BELLEVILLE LITTLE DEVILS",
        "Derek Starr :: HINSDALE RED DEVIL WC",
        "Mike O'Neil :: TINLEY PARK BULLDOGS",
        "Bradley Schnowske :: GENESEO WC :: 3",
        "Griff Powell :: ARLINGTON CARDINALS WC",
        "Jason Heefner :: REDBIRD WC",
        "Rafael Avila :: BELVIDERE YMCA BANDITS :: 5",
        "Jake Griffin :: OAK FOREST WARRIORS",
        "Tim Ottolson :: PANTHER WC",
        "Javier Quintanilla :: TOMCAT WC :: 2",
        "Richard Root :: LANPHIER-SPRINGFIELD WRESTLING",
        "Ryan Duggan :: ST. TARCISSUS RAIDERS",
        "Patrick Sheahan :: ST. BARNABAS / CHRIST THE KING :: 4",
        "Chris Donohoo :: ROXANA VIKINGS",
        "Ty Powers :: HARLEM-PARK BOYS CLUB",
        "Reginald Wright :: OAK PARK RIVER FOREST WARHAWKS :: 6",
        "Jon Bergen :: CHILLICOTHE WC",
        "Mark Schaefer :: WHEATON-WARRENVILLE WC",
        "Jason Pero :: HARVEY PARK DISTRICT TWISTERS :: 1",
        "Roberto Rodriguez :: HARLEM-PARK BOYS CLUB",
        "Luke Ries :: BETHALTO BOYS CLUB BULLS",
        "Jon Swanson :: MT. ZION WC",
        "Robert Meek :: LEMONT WC",
        "Josh Inch :: GENESEO WC",
    ],
    87: [
        "Mike Pryor :: BETHALTO BOYS CLUB BULLS",
        "Aaron Ehle :: HARLEM-PARK BOYS CLUB",
        "Terry O'Brien :: PANTHER WC :: 3",
        "Steve Wallace :: BLACKHAWK WC",
        "Michael Brucker :: GEORGETOWN WC",
        "Karl Hofbauer :: OAK FOREST WARRIORS",
        "Tyler Hurry :: RIVERDALE JR. HIGH WC :: 1",
        "Tim Gaskin :: ST. BARNABAS / CHRIST THE KING",
        "Shaun Bouback :: BELVIDERE YMCA BANDITS",
        "Mark Pishotta :: ROSEMONT COBRAS WRESTLING :: 5",
        "Josh Griffin :: OAK FOREST WARRIORS",
        "Steve Marvin :: DANVILLE WC",
        "Robbie Cox :: BELVIDERE YMCA BANDITS :: 6",
        "Ronnie Hansen :: EDWARDSVILLE :: 4",
        "Jeff Swanson :: MORTON YOUTH WRESTLING",
        "Andrew Shandor :: REDBIRD WC",
        "Rich Berendson :: WEST CHICAGO WILDCATS P.D.",
        "Anuj Maniar :: MEADE JR. WC",
        "Mark Bybee :: VITTUM CATS :: 2",
        "Mark McMenimen :: CROSSFACE WC",
        "Gregory Voegtle :: BELLEVILLE LITTLE DEVILS",
        "John Rogers :: TRI-CITY BRAVES",
        "Steven Craig :: FRANKLIN PARK RAIDERS",
        "Steven Molinari :: VILLA-LOMBARD COUGARS",
    ],
    93: [
        "Bryon Krummelbein :: BETHALTO BOYS CLUB BULLS",
        "TJ Watts :: FORMAN WC",
        "Bob Johnson :: WARHAWK WC",
        "Dan Collins :: ARLINGTON CARDINALS WC :: 1",
        "Timothy Miller :: PLAINFIELD INDIAN TRAIL WILDCATS :: 6",
        "Timothy Donnahue :: PANTHER WC",
        "Eric Scroggins :: AURORA J-HAWKS",
        "Mark Jones :: HARVARD WC",
        "Brian Davis :: NEWMAN BLUE DEVILS",
        "Stephen Stanley :: MATTOON WC :: 4",
        "Jason Eierman :: MUSTANG WC",
        "Karman Bradshaw :: HARVEY PARK DISTRICT TWISTERS",
        "Matthew Webster :: PEORIA RAZORBACKS YOUTH WC",
        "Kyle Bollinger :: TRIMPE JUNIOR HIGH",
        "Ken Biala :: VILLA-LOMBARD COUGARS :: 5",
        "James Crnich :: OAK FOREST WARRIORS :: 2",
        "Ryan Lee :: ROSEMONT COBRAS WRESTLING",
        "Eric Tempel :: UNITY YOUTH",
        "Andrew Heilemeier :: DAKOTA MATT RATS",
        "Leon Ramsey :: AURORA J-HAWKS",
        "Michael Banfield :: TRIMPE JUNIOR HIGH",
        "Joseph Opiola :: DOLTON PARK FALCONS :: 3",
        "Chad Hawkins :: BISMARCK-HENNING WRESTLING",
        "Danny Otero :: GORDON TECH RAMS WC CHICAGO",
    ],
    99: [
        "Mike Greenfield :: BELLEVILLE LITTLE DEVILS",
        "Robert Serio :: CAROL STREAM P.D. PANTHERS",
        "Randall Richardson :: METAMORA KIDS WC",
        "Scott Benjamin :: CATLIN YOUTH WC :: 3",
        "Steve Torres :: VITTUM CATS",
        "Matt Longton :: ELGIN GRAPPLERS",
        "Jermaine White :: OAK PARK RIVER FOREST WARHAWKS :: 5",
        "Tony Didonato :: PEKIN BOY'S CLUB",
        "Ben Niles :: YORKVILLE WC",
        "Ben Gerdes :: ORLAND PARK PIONEERS :: 2",
        "Jose Villarreal :: LIL' REAPER",
        "David Hoenig :: HICKORY HILLS PARK DISTRICT",
        "Richie Marmolejo :: WEST CHICAGO WILDCATS P.D.",
        "Shane Zorbrist :: GRANITE CITY WC COOLIDGE",
        "Jarvis Wardlow :: OAK PARK RIVER FOREST WARHAWKS",
        "Danny Jovanovic :: DOLTON PARK FALCONS :: 4",
        "Ben Sollars :: HOOPESTON-EAST LYNN JR. HIGH",
        "Jerry Swift :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Brody Rude :: NEWMAN BLUE DEVILS :: 6",
        "Dino Kokkines :: PALATINE P.D. SUNDLING",
        "Michael Overby :: WEST FRANKFORT WRESTLING",
        "Jose Barrera :: BELVIDERE YMCA BANDITS",
        "Timothy Williams :: HARVEY PARK DISTRICT TWISTERS :: 1",
        "Jason Osterhoff :: ARGENTA-OREANA WC",
    ],
    105: [
        "Matt Ferguson :: BELLEVILLE LITTLE DEVILS",
        "Ryan Ewanio :: ROSEMONT COBRAS WRESTLING :: 4",
        "Derek Santiago :: AURORA J-HAWKS",
        "Aren Arechiga :: THORNWOOD KIDS WC :: 6",
        "Ricky Avila :: BELVIDERE YMCA BANDITS",
        "Eric Griffin :: RIVERDALE JR. HIGH WC",
        "Chuck Powell :: HOOPESTON-EAST LYNN JR. HIGH",
        "Jason Coleman :: ST. CHARLES WC",
        "Michael Rosengrant :: WARRIOR WC (NILES)",
        "Thomas Combes :: DOLTON PARK FALCONS :: 1",
        "Jon Clauson :: ILLINI BLUFFS WC",
        "Matt Becker :: ELGIN GRAPPLERS",
        "Curtis Owen :: FRANKLIN PARK RAIDERS :: 3",
        "Jeremy Christeson :: BETHALTO BOYS CLUB BULLS",
        "Troy Brigham :: GEORGETOWN WC",
        "Bob Remily :: HARLEM-PARK BOYS CLUB :: 5",
        "Charles Crescenzo :: LINCOLN WAY AREA WRESTLING",
        "Joseph Brauer :: PANTHER WC",
        "Matt Goncher :: BLACKHAWK WC",
        "Frank Lamie :: BRADLEY BOURBONNAIS WC",
        "Chris Carlisle :: TRIMPE JUNIOR HIGH",
        "Sam Watts :: FORMAN WC :: 2",
        "Cyril Strezo :: DOLTON PARK FALCONS",
        "Joe Kalous :: PLAINFIELD INDIAN TRAIL WILDCATS",
    ],
    112: [
        "Jesse Carmack :: BELLEVILLE LITTLE DEVILS",
        "Joe Pierce :: ADDAMS JR. HIGH SCHOOL W.C.",
        "Jeremy Neufeld :: OAK FOREST WARRIORS :: 3",
        "Steve Carroll :: DOLTON PARK FALCONS",
        "Charles Damptz :: JEFFERSON WOLVERINES",
        "Richard Weber :: ANTIOCH UPPER GRADE",
        "Clayton Reed :: UNITY YOUTH",
        "Joe Minott :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Chris Papanek :: MEADE JR. WC :: 6",
        "Kristian Wahlgren :: TIGERTOWN TANGLERS :: 2",
        "Brock Baer :: ELGIN GRAPPLERS",
        "Tom Hisey :: WEST CHICAGO WILDCATS P.D.",
        "Manuel Villarreal :: ARLINGTON CARDINALS WC :: 1",
        "Aaron Jacobs :: MURPHYSBORO JR. HIGH",
        "Tim Forgey :: DECATUR WC",
        "Edward Rivera :: AURORA J-HAWKS",
        "David Rivera :: DOLTON PARK FALCONS",
        "Rick Babb :: CHILLICOTHE WC",
        "Aaron Mihaljevich :: CALUMET MEMORIAL PARK DISTRICT :: 5",
        "Jason Miller :: HOOPESTON-EAST LYNN JR. HIGH",
        "Ben Ancona :: GOLDEN EAGLES",
        "Ryan Seloover :: DUNDEE HIGHLANDERS",
        "Dan Schmidt :: MOLINE TIGERS :: 4",
        "Mike Bertoni :: VITTUM CATS",
    ],
    119: [
        "Brian Martin :: EDWARDSVILLE :: 6",
        "Matt Berg :: ARGENTA-OREANA WC",
        "Kenneth Mills :: DOLTON PARK FALCONS",
        "Marc Hornsby :: ELGIN MATT RATS",
        "Ramon Navarro :: GORDON TECH RAMS WC CHICAGO",  # Marcos Navarro?
        "Jon Bussert :: RIVERDALE JR. HIGH WC",
        "Issac Hampton :: CALUMET MEMORIAL PARK DISTRICT",
        "Ron Stonitsch :: CRESTWOOD COLTS WC :: 1",
        "Clint Clevenger :: BRADLEY BOURBONNAIS WC",
        "Ruben Saldana :: TOMCAT WC :: 3",
        "Joshua Clark :: CHILLICOTHE WC",
        "David Gierke :: FRANKLIN PARK RAIDERS",
        "Ryan Reinhart :: UNITY YOUTH :: 4",
        "Adam Witsken :: BETHALTO BOYS CLUB BULLS",
        "Daman Montello :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Jim Dieringer :: ARLINGTON CARDINALS WC",
        "Ben Palmer :: HARVARD WC",
        "Jim Leduc :: INDIAN PRAIRIE TRAILBLAZERS :: 5",
        "Ryan Casey :: ST. BARNABAS / CHRIST THE KING :: 2",
        "Josh Pearson :: TRI-CITY BRAVES",
        "Travis Kassing :: BELLEVILLE LITTLE DEVILS",
        "Andy Royce :: MOLINE TIGERS",
        "Michael Murdough :: ST. CHARLES WC",
        "Brett Gautcher :: SYCAMORE WC",
    ],
    127: [
        "Brett Mason :: WEST FRANKFORT WRESTLING",
        "Colin Thompson :: PLAINFIELD INDIAN TRAIL WILDCATS :: 5",
        "Todd Madden :: SYCAMORE WC",
        "Matt McDonnell :: NEWMAN BLUE DEVILS :: 2",
        "Shane York :: HOOPESTON-EAST LYNN JR. HIGH",
        "Lance Douglas :: MARQUART MIDDLE JR. HIGH",
        "Craig Padgett :: CRESTWOOD COLTS WC",
        "Ernie Slavik :: ANTIOCH UPPER GRADE",
        "Tim Angsten :: TINLEY PARK BULLDOGS",
        "Mike Powell :: OAK PARK RIVER FOREST WARHAWKS :: 3",
        "Matt Frego :: NAPERVILLE LANCERS",
        "Tim Davis :: ARGENTA-OREANA WC",
        "Shay Hawkins :: RICH WRESTLING LTD.",
        "Leslie Whittake :: BELLEVILLE LITTLE DEVILS",
        "Ryan Daprile :: LIONS WC",
        "Willie Morris :: DANVILLE WC :: 4",
        "Jeff Defauw :: GENESEO WC :: 6",
        "Brandon Presern :: FRANKLIN PARK RAIDERS",
        "Brian McCollum :: HARLEM-PARK BOYS CLUB",
        "Shawn Stafford :: HICKORY HILLS PARK DISTRICT",
        "Robert Porter :: GRANITE CITY WC COOLIDGE",
        "Gerardo Quintanilla :: TOMCAT WC :: 1",
        "Daniel Moynihan :: ARLINGTON CARDINALS WC",
        "Bryan Medlin :: MORTON YOUTH WRESTLING",
    ],
    135: [
        "Brent Rogers :: EDWARDSVILLE",
        "Bill Schaack :: CRESTWOOD COLTS WC",
        "Jeffrey Garretson :: STREATOR JUNIOR BULLDOGS",
        "Khamla Sounthala :: MARQUART MIDDLE JR. HIGH",
        "Kevin Singletary :: ORLAND PARK PIONEERS :: 2",
        "Steven Froelich :: MEADE JR. WC",
        "Matt Hayes :: ELGIN MATT RATS",
        "C.J. Protsman :: MACOMB YMCA KIDS WRESTLING :: 4",
        "David Migut :: HICKORY HILLS PARK DISTRICT",
        "Cody Lewis :: CUMBERLAND COUNTY WC",
        "Dean Bielawa :: ARLINGTON CARDINALS WC",
        "Steve Bailey :: PLAINFIELD INDIAN TRAIL WILDCATS :: 5",
        "Kirk Gill :: DOLTON PARK FALCONS",
        "Jason Yarber :: GRANITE CITY WC COOLIDGE",
        "Joshua Thalman :: KNIGHTS WC",
        "Denny Hartwig :: OAK FOREST WARRIORS :: 1",
        "Mike Etzkorn :: LEMONT WC :: 6",
        "Shane Richards :: OAKWOOD WC",
        "Shane Hudnall :: GENESEO WC",
        "Scott Borota :: HARLEM-PARK BOYS CLUB",
        "Brian Proffitt :: EDWARDSVILLE",
        "Austin Collins :: FRANKLIN PARK RAIDERS :: 3",
        "William York :: GEORGETOWN WC",
        "Steve Pawlak :: VILLA-LOMBARD COUGARS",
    ],
    144: [
        "Ryan Beivenue :: TRIMPE JUNIOR HIGH :: 3",
        "Sean Pruden :: WOODSTOCK CARDINAL WRESTLING",
        "Michael Burlack :: CAROL STREAM P.D. PANTHERS",
        "Ryan Pape :: FRANKLIN PARK RAIDERS :: 1",
        "Tony Volini :: HINSDALE RED DEVIL WC",
        "Derek Meadows :: TAYLORVILLE WC",
        "Dave Cardin :: METAMORA KIDS WC :: 5",
        "Lenny Walker :: LEMONT WC",
        "Jacob Csiszer :: LIL' REAPER",
        "Robert Carlson :: ORLAND PARK PIONEERS",
        "Robert Wright :: WESTVILLE JR. HIGH",
        "Dino Cece :: HINSDALE RED DEVIL WC",
        "Jeremy Judd :: LIL' REAPER :: 4",
        "Eric Chappell :: CARBONDALE WC",
        "Mike Chance :: PEORIA RAZORBACKS YOUTH WC",
        "Matt Carlson :: NAPERVILLE PATRIOTS WRESTLING",
        "Jason Salley :: EISENHOWER JR. HIGH WC",
        "Brandon O'Daniel :: ORLAND PARK PIONEERS",
        "Ray Todd Guzak :: CRESTWOOD COLTS WC :: 6",
        "Matt Burdette :: PEKIN BOY'S CLUB",
        "Jeff Witter :: GRANITE CITY WC GRIGSBY",
        "Chris Timmons :: HOOPESTON-EAST LYNN JR. HIGH :: 2",
        "Kori Hooe :: JOLIET BOYS CLUB COBRAS",
        "Mike Clark :: PALATINE P.D. CHARGERS",
    ],
    153: [
        "Ryan Ahring :: EDWARDSVILLE",
        "Scott Reed :: TIGERTOWN TANGLERS",
        "David Hanchrr :: WARRIOR WC (NILES)",
        "Matthew Beeler :: MATTOON WC :: 2",
        "Jason Finks :: KNIGHTS WC",
        "Bob Nelson :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Brandon Dahlke :: AURORA J-HAWKS :: 4",
        "Dean Phillips :: JR. BISON WC :: 5",
        "Jessie Whitton Jr. :: EL PASO WRESTLING",
        "Kevin Powers :: DOLTON PARK FALCONS",
        "Clifton Oliviel :: TRI-CITY BRAVES",
        "Joshua Slaten :: WOODSTOCK CARDINAL WRESTLING",
        "John Rupprecht :: GENESEO WC :: 3",
        "Brian Dill :: CENTRALIA WC :: 6",
        "Jason Slavicek :: LEMONT WC",
        "Dan Green :: DAKOTA MATT RATS",
        "Tommy McHarry :: UNITY YOUTH",
        "Brian Billett :: HICKORY HILLS PARK DISTRICT",
        "Jose Medina :: GORDON TECH RAMS WC CHICAGO :: 1",
        "Jeff Harrington :: INDIAN PRAIRIE TRAILBLAZERS",
        "Aaron Wright :: TRIAD WC",
        "Curtis Berry :: TRI-CITY BRAVES",
        "William Arthur :: VITTUM CATS",
        "Jason Dillingham :: UNITY YOUTH",
    ],
    163: [
        "Nathan Kincade :: TRIMPE JUNIOR HIGH",
        "PJ McEnroe :: BLACKHAWK WC",
        "Sean Denton :: BRADLEY BOURBONNAIS WC",
        "Ray Jebsen :: TINLEY PARK BULLDOGS :: 4",
        "Brian Smith :: TIGERTOWN TANGLERS",
        "Ilija Dragisic :: JR. FALCON WRESTLING",
        "Andy Donaldson :: MEADE JR. WC :: 1",
        "Jeff Chandler :: HOOPESTON-EAST LYNN JR. HIGH",
        "Chris Williams :: INDIAN PRAIRIE PIONEERS :: 5",
        "Michael Smith :: DAKOTA MATT RATS",
        "Paul Naumowicz :: PANTHER WC",
        "D.J. Brigham :: TIGERTOWN TANGLERS",
        "Scott Wulff :: OSWEGO PANTHERS :: 3",
        "Jason Tebbe :: HIGHLAND JUNIOR BULLDOGS",
        "Jeff Heavrin :: OAK PARK RIVER FOREST WARHAWKS",
        "Philip Buck :: CROSSFACE WC",
        "Floyd Smith :: RICH WRESTLING LTD.",
        "John Koitz :: HARVARD WC",
        "Michael Acord :: WESTVILLE JR. HIGH :: 2",
        "Dan Volpentesta :: LITTLE GIANTS WC",
        "John Sherrill :: MURPHYSBORO JR. HIGH :: 6",
        "Richard Hunt :: DOLTON PARK FALCONS",
        "Brian Woodley :: DAKOTA MATT RATS",
        "Lewis Lang :: RICH WRESTLING LTD.",
    ],
    173: [
        "Jason Middleton :: GRANITE CITY WC GRIGSBY",
        "Pip Gray :: TRI-CITY BRAVES",
        "Chris McCay :: HOOPESTON-EAST LYNN JR. HIGH :: 4",
        "Chuck Morin :: INDIAN PRAIRIE TRAILBLAZERS :: 5",
        "Jose Saucedo :: HARVARD WC",
        "Roy Vix :: CAROL STREAM P.D. PANTHERS",
        "Sheamus Fergus :: MATBURNS WC",
        "Douglas Roderick :: BISMARCK-HENNING WRESTLING",
        None,
        "Glen Humphrey :: AURORA J-HAWKS :: 2",
        "Jon Danao :: MARQUART MIDDLE JR. HIGH",
        None,
        "Keith Heiy :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Kelly Feltes :: TRIMPE JUNIOR HIGH",
        "Larry Fong :: MEADE JR. WC :: 3",
        "Mike Shea :: ANTIOCH UPPER GRADE",
        "Phillip Grandfield :: MT. ZION WC",
        "Kris Hermansen :: LEMONT WC",
        "Matthew Weidner :: GIBSON CITY YOUTH WRESTLING :: 6",
        "Scott Owen :: FRANKLIN PARK RAIDERS",
        None,
        "Ken Keltnee :: BLUE CREW WRESTLING CLUB",
        "Ken Robinson :: ST. CHARLES WC :: 1",
        None,
        # "Mark Conmy :: PALATINE P.D. CHARGERS", # SCRATCH
    ],
    185: [
        "Andy Sutt :: GOLDEN EAGLES",
        "John Haar :: BELLEVILLE LITTLE DEVILS",
        "Charlie Ellis :: CALUMET MEMORIAL PARK DISTRICT",
        "Don Madenis :: HARVARD WC :: 3",
        "Peter Wildermuth :: RIVERDALE JR. HIGH WC",
        "Jeffrey Rohde :: YORKVILLE WC :: 6",
        "Mark Harvey :: MT. ZION WC :: 1",
        "Neil Dickann :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "David Miller :: AURORA J-HAWKS",
        "Jim Witte :: ADDAMS JR. HIGH SCHOOL W.C.",
        "David Meroni :: NAPERVILLE PATRIOTS WRESTLING",
        "David Yokley :: UNITY YOUTH",
        "Brian Washington :: DOLTON PARK FALCONS :: 5",
        "Kyle Feltes :: TRIMPE JUNIOR HIGH",
        "L.T. Garrett :: HOOPESTON-EAST LYNN JR. HIGH :: 4",
        "Matt Riney :: RIVERDALE JR. HIGH WC",
        "Chris Hagg :: ANTIOCH UPPER GRADE",
        "Nicholas Fulara :: ST. TARCISSUS RAIDERS",
        "Johnny Jaworski :: OAK FOREST WARRIORS",
        "Jeremy Harter :: BISMARCK-HENNING WRESTLING",
        "Steve Ritter :: RAIDER WC",
        "Nathan Shelton :: AURORA J-HAWKS :: 2",
        "Johnathan Rutledge :: JR. BISON WC",
        "James Choate :: LIL' REAPER",
    ],
    275: [
        "Jeff Sticht :: BETHALTO BOYS CLUB BULLS",
        "Miguel Carreno :: LIL' REAPER",
        "Brett George :: FRANKLIN PARK RAIDERS",
        "Fred Larson :: MOLINE TIGERS",
        "Tommy Rush :: AURORA J-HAWKS",
        "Spyros Fetsis :: MATBURNS WC",
        "Cameron Randolph :: HARVEY PARK DISTRICT TWISTERS :: 4",
        "Ted Stec :: LIONS WC",
        "Patrick Parham :: TRI-CITY BRAVES :: 6",
        "Jerry Jontry :: ARGENTA-OREANA WC :: 2",
        "Mark Prehar :: LITTLE GIANTS WC",
        "Albert Licka :: CAROL STREAM P.D. PANTHERS",
        "John Bettasso :: ANTIOCH UPPER GRADE",
        "Matt Bolandis :: GRANITE CITY WC COOLIDGE",
        "Raymond Holden :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Richard Reynolds :: AURORA J-HAWKS :: 5",
        "Joe De Voss Jr. :: RIVERDALE JR. HIGH WC",
        "Armenoius Griham :: URBANA KIDS WC",
        "Seneca Carey :: DOLTON PARK FALCONS",
        "Mike Johnson :: TRI-CITY BRAVES :: 3",
        "Rick Starr :: CENTRALIA WC",
        "Peter Marx :: EISENHOWER JR. HIGH WC :: 1",
        "Jon Jordan :: MT. ZION WC",
        "Cory Martin :: DELAVAN MAT WRATS",
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "HARVEY PARK DISTRICT TWISTERS": 195.0,
    "DOLTON PARK FALCONS": 143.5,
    "VITTUM CATS": 103.5,
    "AURORA J-HAWKS": 102.0,
    "OAK FOREST WARRIORS": 101.5,
    "ARLINGTON CARDINALS WC": 93.0,
    "FRANKLIN PARK RAIDERS": 83.5,
    "OAK PARK RIVER FOREST WARHAWKS": 82.5,
    "TOMCAT WC": 80.5,
    "LOCKPORT GRAPPLERS WC": 80.0,
    "GENESEO WC": 68.0,
    "NEWMAN BLUE DEVILS": 66.5,
    "MEADE JR. WC": 66.0,
    "PLAINFIELD INDIAN TRAIL WILDCATS": 64.0,
    "ST. BARNABAS / CHRIST THE KING": 59.0,
    "TRI-CITY BRAVES": 57.5,
    "HOOPESTON-EAST LYNN JR. HIGH": 56.0,
    "ORLAND PARK PIONEERS": 54.5,
    "ARGENTA-OREANA WC": 42.0,
    "ROSEMONT COBRAS WRESTLING": 41.0,
    "CRESTWOOD COLTS WC": 40.5,
    "MATTOON WC": 40.5,
    "EDWARDSVILLE": 39.0,
    "INDIAN PRAIRIE TRAILBLAZERS": 39.0,
    "ROUND LAKE SPARTANS": 39.0,
    "THORNWOOD KIDS WC": 36.5,
    "CATLIN YOUTH WC": 36.0,
    "LEMONT WC": 36.0,
    "MT. ZION WC": 36.0,
    "FORMAN WC": 34.0,
    "ST. CHARLES WC": 33.0,
    "GORDON TECH RAMS WC CHICAGO": 33.0,
    "NAPERVILLE PATRIOTS WRESTLING": 32.0,
    "WESTVILLE JR. HIGH": 31.0,
    "BELLEVILLE LITTLE DEVILS": 31.0,
    "RIVERDALE JR. HIGH WC": 31.0,
    "WARRIOR WC (NILES)": 31.0,
    "EISENHOWER JR. HIGH WC": 30.0,
    "UNITY YOUTH": 29.0,
    "TINLEY PARK BULLDOGS": 28.5,
    "BELVIDERE YMCA BANDITS": 28.0,
    "LITTLE GIANTS WC": 28.0,
    "OSWEGO PANTHERS": 28.0,
    "JR. BISON WC": 27.0,
    "PANTHER WC": 26.0,
    "ANTIOCH UPPER GRADE": 24.0,
    "TIGERTOWN TANGLERS": 24.0,
    "BISMARCK-HENNING WRESTLING": 23.5,
    "TRIMPE JUNIOR HIGH": 23.0,
    "DUNDEE HIGHLANDERS": 22.0,
    "HARLEM-PARK BOYS CLUB": 21.0,
    "MOLINE TIGERS": 21.0,
    "HARVARD WC": 20.0,
    "VILLA-LOMBARD COUGARS": 20.0,
    "YORKVILLE WC": 20.0,
    "CAROL STREAM P.D. PANTHERS": 17.5,
    "BLUE CREW WRESTLING CLUB": 17.0,
    "CALUMET MEMORIAL PARK DISTRICT": 17.0,
    "CHILLICOTHE WC": 17.0,
    "GIBSON CITY YOUTH WRESTLING": 17.0,
    "LIL' REAPER": 17.0,
    "BLACKHAWK WC": 16.0,
    "MARQUART MIDDLE JR. HIGH": 16.0,
    "MURPHYSBORO JR. HIGH": 16.0,
    "CENTRALIA WC": 15.0,
    "INDIAN PRAIRIE PIONEERS": 15.0,
    "BETHALTO BOYS CLUB BULLS": 14.0,
    "GRANITE CITY WC COOLIDGE": 14.0,
    "MACOMB YMCA KIDS WRESTLING": 14.0,
    "MORTON YOUTH WRESTLING": 14.0,
    "CARBONDALE WC": 12.0,
    "DANVILLE WC": 12.0,
    "RICH WRESTLING LTD.": 12.0,
    "METAMORA KIDS WC": 11.0,
    "WEST CHICAGO WILDCATS P.D.": 11.0,
    "DAKOTA MATT RATS": 10.0,
    "REDBIRD WC": 10.0,
    "STREATOR JUNIOR BULLDOGS": 10.0,
    "BRADLEY BOURBONNAIS WC": 9.0,
    "ADDAMS JR. HIGH SCHOOL W.C.": 7.0,
    "HINSDALE RED DEVIL WC": 7.0,
    "MUSTANG WC": 7.0,
    "ELGIN MATT RATS": 6.0,
    "HICKORY HILLS PARK DISTRICT": 6.0,
    "KNIGHTS WC": 6.0,
    "WOODSTOCK CARDINAL WRESTLING": 6.0,
    "GENEVA PARK DISTRICT": 5.0,
    "DECATUR WC": 4.0,
    "JR. FALCON WRESTLING": 4.0,
    "NAPERVILLE WARRIORS": 4.0,
    "SPARTANS WC": 4.0,
    "ST. TARCISSUS RAIDERS": 4.0,
    "SYCAMORE WC": 4.0,
    "TAYLORVILLE WC": 4.0,
    "URBANA KIDS WC": 4.0,
    "GRANITE CITY WC GRIGSBY": 3.5,
    "JR. BISON WC (2)": 3.0,
    "PALATINE P.D. SUNDLING": 3.0,
    "PEKIN BOY'S CLUB": 3.0,
    "ELGIN GRAPPLERS": 2.0,
    "HIGHLAND JUNIOR BULLDOGS": 2.0,
    "ILLINI BLUFFS WC": 2.0,
    "JOLIET BOYS CLUB COBRAS": 2.0,
    "LIONS WC": 2.0,
}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    ("Michael Murphy, Jr", "LOCKPORT GRAPPLERS WC"): bracket_utils.Competitor(
        full_name="Michael Murphy, Jr",
        first_name="Michael",
        last_name="Murphy",
        team_full="LOCKPORT GRAPPLERS WC",
    ),
    ("Ryan De Lira", "DOLTON PARK FALCONS"): bracket_utils.Competitor(
        full_name="Ryan De Lira",
        first_name="Ryan",
        last_name="De Lira",
        team_full="DOLTON PARK FALCONS",
    ),
    ("Phillip J. Foster", "NEWMAN BLUE DEVILS"): bracket_utils.Competitor(
        full_name="Phillip J. Foster",
        first_name="Phillip",
        last_name="Foster",
        team_full="NEWMAN BLUE DEVILS",
    ),
    ("Ray Todd Guzak", "CRESTWOOD COLTS WC"): bracket_utils.Competitor(
        full_name="Ray Todd Guzak",
        first_name="Ray Todd",
        last_name="Guzak",
        team_full="CRESTWOOD COLTS WC",
    ),
    ("Jessie Whitton Jr.", "EL PASO WRESTLING"): bracket_utils.Competitor(
        full_name="Jessie Whitton Jr.",
        first_name="Jessie",
        last_name="Whitton",
        team_full="EL PASO WRESTLING",
    ),
    ("Joe De Voss Jr.", "RIVERDALE JR. HIGH WC"): bracket_utils.Competitor(
        full_name="Joe De Voss Jr.",
        first_name="Joe",
        last_name="De Voss",
        team_full="RIVERDALE JR. HIGH WC",
    ),
}


def _get_bout_numbers() -> dict[bracket_utils.MatchSlot, int]:
    return {
        "championship_r32_02": 1,
        "championship_r32_04": 2,
        "championship_r32_06": 3,
        "championship_r32_08": 4,
        "championship_r32_10": 5,
        "championship_r32_12": 6,
        "championship_r32_14": 7,
        "championship_r32_16": 8,
        "consolation_fifth_place": 35,
        "consolation_third_place": 36,
        "championship_first_place": 37,
    }


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, score=score)
        )

    weight_classes = manual_entry.load_manual_entries(
        _HERE.parent, 1990, _NAME_EXCEPTIONS
    )
    for weight, competitors in _SENIOR_COMPETITORS.items():
        bout_numbers = _get_bout_numbers()
        weight_class = bracket_utils.weight_class_from_competitors(
            "senior",
            weight,
            competitors,
            _SENIOR_TEAM_REPLACE,
            _NAME_EXCEPTIONS,
            bout_numbers,
        )
        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1990.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
