# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils

HERE = pathlib.Path(__file__).resolve().parent
_NOVICE_TEAM_REPLACE: dict[str, str] = {}
_NOVICE_COMPETITORS: dict[int, list[str | None]] = {
    62: [
        "ISRAEL MARTINEZ :: TOMCAT WC :: 1",
        "JUSTIN CLUBB :: HARLEM SCHOOL DIST. 122 :: 2",
        "CALEB FERRY :: HARLEM SCHOOL DIST. 122 :: 3",
        "SHAUN DANNENBRINK :: BETHALTO :: 4",
        "GEORGE SIMS :: JOLIET BOYS CLUB COBRAS :: 5",
        "SIM BRANDAU :: LITTLE CELTICS :: 6",
    ],
    66: [
        "NICK CIRRINCIONE :: VILLA LOMBARD COUGARS :: 1",
        "PAUL AUGLE :: TINLEY PARK BULLDOGS :: 2",
        "SEAN CHINSKI :: LITTLE CELTICS :: 3",
        "ANDDREW PENA :: CRYSTAL LAKE WIZARDS :: 4",
        "MARK WARREN :: LITTLE CELTICS :: 5",
        "MICHAEL STANLEY :: MATTOON :: 6",
    ],
    70: [
        "NATHAN MARTINEZ :: TOMCATS :: 1",
        "JOSH PRICE :: RIVERDALE JR. HIGH :: 2",
        "JEFF JEZUIT :: BURBANK PANTHERS :: 3",
        "PATRICK HAMILTON :: MORRISON :: 4",
        "LONNIE CORBIN :: BURBANK PANTERS :: 5",
        "ANTHONY MULLINS :: METAMORA :: 6",
    ],
    74: [
        "KYLE ONEILL :: TINLEY PARK BULLDOGS :: 1",
        "TONY GANAS :: ROSEMONT COBRAS :: 2",
        "DUSTIN CHLOEMAN :: LITTLE KNIGHTS :: 3",
        "ZACK MAY :: BETHALTO :: 4",
        "JOSEPH CLARK :: JOLIET COBRAS :: 5",
        "ARAN ESPOSITO :: MEAD :: 6",
    ],
    79: [
        "DAVID DREW :: MUSTANGS :: 1",
        "RAYNELLE KIZZEE :: HARVEY TWISTERS :: 2",
        "ALLEN RODENBRG :: ST. BARNABAS/CHRIST THE KING :: 3",
        "CHRIS ILIOPOULOS :: ADDISON INDIAN TRAIL :: 4",
        "DAN NILES :: YORKVILLE :: 5",
        "JORDAN WEBSTER :: METAMORA :: 6",
    ],
    84: [
        "NICK BINGHEIM :: BETHALTO :: 1",
        "ANGELO GERVASIO :: LEMONT BEARS :: 2",
        "PATRICK ROSS :: MUSTANGS :: 3",
        "BOB WHITE :: MORRISON :: 4",
        "RICKY OLSZTA :: LITTLE CELTICS :: 5",
        "CAL RYDER :: MATTOON :: 6",
    ],
    89: [
        "BRIAN CRAVENS :: MT. ZION :: 1",
        "MATTHEW SANDBURG :: LIONS WC :: 2",
        "BRAD SCHRADER :: HARLEM SCHOOL DIST. 122 :: 3",
        "JOHN VILLARREAL :: VILLA LOMBARD COUGARS :: 4",
        "JUSTIN CARR :: LITTLE CELTICS :: 5",
        "TERRY GARBS :: TRAILBLAZERS :: 6",
    ],
    95: [
        "BRAD OWENS :: MT. ZION :: 1",
        "JASON ERWINSKI :: TINLEY PARK BULLDOGS :: 2",
        "ROMAN NATOLI :: LOCKPORT :: 3",
        "DANNY QUARTZ :: LITTLE DEVILS :: 4",
        "DANA HOLLAND :: VILLA LOMBARD COUGARS :: 5",
        "MICHAEL POWELL :: FISHER :: 6",
    ],
    101: [
        "MATT LACKEY :: MOLINE TIGERS :: 1",
        "DENIS POOL :: GLENDALE GRAPPLERS :: 2",
        "NICK UPTON :: MATTOON :: 3",
        "AARON POWERS :: ROCKFORD :: 4",
        "DARLOS GOMEZ :: ADDISON INDIAN TRAIL :: 5",
        "BRANDON DOLEZAL :: LOCKPORT :: 6",
    ],
    108: [
        "SEAN CONSIDINE :: VILLA LOMBARD COUGARS :: 1",
        "MARK MCCUTCHEON :: LOCKPORT :: 2",
        "HORACE FLOURNOY :: TRICITY BRAVES :: 3",
        "SHAIN PRAHL :: OSWEGO COUGARS :: 4",
        "SHAWN MCDONNELL :: CRYSTAL LAKE WIZARDS :: 5",
        "PATRICK ARVIN :: OSWEGO COUGARS :: 6",
    ],
    115: [
        "CHAD KRNAC :: PLAINFIELD IT :: 1",
        "ANDREW HARRISON :: ADDISON INDIAN TRAIL :: 2",
        "ROD GRIFFIN :: TRI-CITY BRAVES :: 3",
        "TIM LEWIS :: RIVERDALE JR. HIGH :: 4",
        "CHRIS KERSTEN :: VILLA LOMBARD COUGARS :: 5",
        "RAYMOND BOYD :: VITTUM CATS :: 6",
    ],
    122: [
        "JOE MCCARTHY :: HARVARD :: 1",
        "BRET EVINS :: JR. ROCKETS :: 2",
        "LEITH CROWTHER :: PLAINFIELD :: 3",
        "ISAAC DIESSELHORST :: UTCHFIELD :: 4",
        "CHAD PEARSON :: SYCAMORE :: 5",
        "MARTIN ELLIS :: JOLET :: 6",
    ],
    130: [
        "BILL KOPECKY :: ROSEMONT COBRAS :: 1",
        "JESSE IZZO :: BRONCO :: 2",
        "GARY SHERWOOD :: OAK LAWN :: 3",
        "JUNSIN SORNSIN :: ROCKFORD :: 4",
        "BRYAN SCHULTZ :: EAGLE WC :: 5",
        "CHAD GRIGSBY :: CHARLESTON :: 6",
    ],
    138: [
        "MARCK GENTHE :: VILLA LOMBARD COUGARS :: 1",
        "NICK CURBY :: LIONS WC :: 2",
        "BRYAN ROUSE :: MAIN TWP EAGLES :: 3",
        "PARKER PINNELL :: WAUKEGAN :: 4",
        "ANDREW LINARES :: HOOPESTON :: 5",
        "JOHN DIETERLE :: QUINCY :: 6",
    ],
    147: [
        "JOE CHIRUMBOLO :: EAGLE WC :: 1",
        "NICHOLAS LATUS :: EAGLE WC :: 2",
        "ADAM VENTSIAS :: PLAINFIELD IT :: 3",
        "NICK POEHLMAN :: MORTON :: 4",
        "CK ESPOSITO :: VILLA LOMBARD COUGARS :: 5",
        "ADAM STIMPSON :: JORDAN SETON :: 6",
    ],
    215: [
        "BRAD RUNKLE :: YORKVILLE :: 1",
        "BRAD CRAIG :: ROBBINS :: 2",
        "TRAVIS MARTINEZ :: LIL REAPER :: 3",
        "JACOB ACORD :: WESTVILLE :: 4",
        "JASON MANGAWAN :: RAMS :: 5",
        "WILSON MOORE :: MURPHYSBORO :: 6",
    ],
}
_NOVICE_PLACERS: dict[int, list[bracket_utils.Placer]] = {
    62: [
        bracket_utils.Placer(name="ISRAEL MARTINEZ", team="TOMCAT WC"),
        bracket_utils.Placer(name="JUSTIN CLUBB", team="HARLEM SCHOOL DIST. 122"),
        bracket_utils.Placer(name="CALEB FERRY", team="HARLEM SCHOOL DIST. 122"),
        bracket_utils.Placer(name="SHAUN DANNENBRINK", team="BETHALTO"),
        bracket_utils.Placer(name="GEORGE SIMS", team="JOLIET BOYS CLUB COBRAS"),
        bracket_utils.Placer(name="SIM BRANDAU", team="LITTLE CELTICS"),
    ],
    66: [
        bracket_utils.Placer(name="NICK CIRRINCIONE", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="PAUL AUGLE", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="SEAN CHINSKI", team="LITTLE CELTICS"),
        bracket_utils.Placer(name="ANDDREW PENA", team="CRYSTAL LAKE WIZARDS"),
        bracket_utils.Placer(name="MARK WARREN", team="LITTLE CELTICS"),
        bracket_utils.Placer(name="MICHAEL STANLEY", team="MATTOON"),
    ],
    70: [
        bracket_utils.Placer(name="NATHAN MARTINEZ", team="TOMCATS"),
        bracket_utils.Placer(name="JOSH PRICE", team="RIVERDALE JR. HIGH"),
        bracket_utils.Placer(name="JEFF JEZUIT", team="BURBANK PANTHERS"),
        bracket_utils.Placer(name="PATRICK HAMILTON", team="MORRISON"),
        bracket_utils.Placer(name="LONNIE CORBIN", team="BURBANK PANTERS"),
        bracket_utils.Placer(name="ANTHONY MULLINS", team="METAMORA"),
    ],
    74: [
        bracket_utils.Placer(name="KYLE ONEILL", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="TONY GANAS", team="ROSEMONT COBRAS"),
        bracket_utils.Placer(name="DUSTIN CHLOEMAN", team="LITTLE KNIGHTS"),
        bracket_utils.Placer(name="ZACK MAY", team="BETHALTO"),
        bracket_utils.Placer(name="JOSEPH CLARK", team="JOLIET COBRAS"),
        bracket_utils.Placer(name="ARAN ESPOSITO", team="MEAD"),
    ],
    79: [
        bracket_utils.Placer(name="DAVID DREW", team="MUSTANGS"),
        bracket_utils.Placer(name="RAYNELLE KIZZEE", team="HARVEY TWISTERS"),
        bracket_utils.Placer(
            name="ALLEN RODENBRG", team="ST. BARNABAS/CHRIST THE KING"
        ),
        bracket_utils.Placer(name="CHRIS ILIOPOULOS", team="ADDISON INDIAN TRAIL"),
        bracket_utils.Placer(name="DAN NILES", team="YORKVILLE"),
        bracket_utils.Placer(name="JORDAN WEBSTER", team="METAMORA"),
    ],
    84: [
        bracket_utils.Placer(name="NICK BINGHEIM", team="BETHALTO"),
        bracket_utils.Placer(name="ANGELO GERVASIO", team="LEMONT BEARS"),
        bracket_utils.Placer(name="PATRICK ROSS", team="MUSTANGS"),
        bracket_utils.Placer(name="BOB WHITE", team="MORRISON"),
        bracket_utils.Placer(name="RICKY OLSZTA", team="LITTLE CELTICS"),
        bracket_utils.Placer(name="CAL RYDER", team="MATTOON"),
    ],
    89: [
        bracket_utils.Placer(name="BRIAN CRAVENS", team="MT. ZION"),
        bracket_utils.Placer(name="MATTHEW SANDBURG", team="LIONS WC"),
        bracket_utils.Placer(name="BRAD SCHRADER", team="HARLEM SCHOOL DIST. 122"),
        bracket_utils.Placer(name="JOHN VILLARREAL", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="JUSTIN CARR", team="LITTLE CELTICS"),
        bracket_utils.Placer(name="TERRY GARBS", team="TRAILBLAZERS"),
    ],
    95: [
        bracket_utils.Placer(name="BRAD OWENS", team="MT. ZION"),
        bracket_utils.Placer(name="JASON ERWINSKI", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="MICHAEL POWELL", team="FISHER"),
        bracket_utils.Placer(name="DANNY QUARTZ", team="LITTLE DEVILS"),
        bracket_utils.Placer(name="DANA HOLLAND", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="MICHAEL POWELL(2)", team="FISHER"),  # BIG TYPO
    ],
    101: [
        bracket_utils.Placer(name="MATT LACKEY", team="MOLINE TIGERS"),
        bracket_utils.Placer(name="DENIS POOL", team="GLENDALE GRAPPLERS"),
        bracket_utils.Placer(name="NICK UPTON", team="MATTOON"),
        bracket_utils.Placer(name="AARON POWERS", team="ROCKFORD"),
        bracket_utils.Placer(name="DARLOS GOMEZ", team="ADDISON INDIAN TRAIL"),
        bracket_utils.Placer(name="BRANDON DOLEZAL", team="LOCKPORT"),
    ],
    108: [
        bracket_utils.Placer(name="SEAN CONSIDINE", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="MARK MCCUTCHEON", team="LOCKPORT"),
        bracket_utils.Placer(name="HORACE FLOURNOY", team="TRICITY BRAVES"),
        bracket_utils.Placer(name="SHAIN PRAHL", team="OSWEGO COUGARS"),
        bracket_utils.Placer(name="SHAWN MCDONNELL", team="CRYSTAL LAKE WIZARDS"),
        bracket_utils.Placer(name="PATRICK ARVIN", team="OSWEGO COUGARS"),
    ],
    115: [
        bracket_utils.Placer(name="CHAD KRNAC", team="PLAINFIELD IT"),
        bracket_utils.Placer(name="ANDREW HARRISON", team="ADDISON INDIAN TRAIL"),
        bracket_utils.Placer(name="ROD GRIFFIN", team="TRI-CITY BRAVES"),
        bracket_utils.Placer(name="TIM LEWIS", team="RIVERDALE JR. HIGH"),
        bracket_utils.Placer(name="CHRIS KERSTEN", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="RAYMOND BOYD", team="VITTUM CATS"),
    ],
    122: [
        bracket_utils.Placer(name="JOE MCCARTHY", team="HARVARD"),
        bracket_utils.Placer(name="BRET EVINS", team="JR. ROCKETS"),
        bracket_utils.Placer(name="LEITH CROWTHER", team="PLAINFIELD"),
        bracket_utils.Placer(name="ISAAC DIESSELHORST", team="UTCHFIELD"),
        bracket_utils.Placer(name="CHAD PEARSON", team="SYCAMORE"),
        bracket_utils.Placer(name="MARTIN ELLIS", team="JOLET"),
    ],
    130: [
        bracket_utils.Placer(name="BILL KOPECKY", team="ROSEMONT COBRAS"),
        bracket_utils.Placer(name="JESSE IZZO", team="BRONCO"),
        bracket_utils.Placer(name="GARY SHERWOOD", team="OAK LAWN"),
        bracket_utils.Placer(name="JUNSIN SORNSIN", team="ROCKFORD"),
        bracket_utils.Placer(name="BRYAN SCHULTZ", team="EAGLE WC"),
        bracket_utils.Placer(name="CHAD GRIGSBY", team="CHARLESTON"),
    ],
    138: [
        bracket_utils.Placer(name="MARCK GENTHE", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="NICK CURBY", team="LIONS WC"),
        bracket_utils.Placer(name="BRYAN ROUSE", team="MAIN TWP EAGLES"),
        bracket_utils.Placer(name="PARKER PINNELL", team="WAUKEGAN"),
        bracket_utils.Placer(name="ANDREW LINARES", team="HOOPESTON"),
        bracket_utils.Placer(name="JOHN DIETERLE", team="QUINCY"),
    ],
    147: [
        bracket_utils.Placer(name="JOE CHIRUMBOLO", team="EAGLE WC"),
        bracket_utils.Placer(name="NICHOLAS LATUS", team="EAGLE WC"),
        bracket_utils.Placer(name="ADAM VENTSIAS", team="PLAINFIELD IT"),
        bracket_utils.Placer(name="NICK POEHLMAN", team="MORTON"),
        bracket_utils.Placer(name="CK ESPOSITO", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="ADAM STIMPSON", team="JORDAN SETON"),
    ],
    215: [
        bracket_utils.Placer(name="BRAD RUNKLE", team="YORKVILLE"),
        bracket_utils.Placer(name="BRAD CRAIG", team="ROBBINS"),
        bracket_utils.Placer(name="TRAVIS MARTINEZ", team="LIL REAPER"),
        bracket_utils.Placer(name="JACOB ACORD", team="WESTVILLE"),
        bracket_utils.Placer(name="JASON MANGAWAN", team="RAMS"),
        bracket_utils.Placer(name="WILSON MOORE", team="MURPHYSBORO"),
    ],
}
_NOVICE_TEAM_SCORES: dict[str, float] = {
    "VILLA LOMBARD COUGARS": 179.0,
    "LITTLE CELTICS": 93.0,
    "PLAINFIELD INDIAN TRAIL": 87.0,
    "MATTOON": 82.5,
    "ROSEMONT COBRAS": 78.0,
    "HARLEM COUGARS": 77.0,
    "TINLEY PARK BULLDOGS": 74.0,
    "EAGLE": 70.5,
    "BETHALTO JR. HIGH": 61.0,
    "ADDISON/INDIAN TRAIL": 58.0,
    "TOMCATS": 56.0,
    "MT. ZION": 55.0,
    "CRYSTAL LAKE": 53.5,
    "PANTHER WC": 53.5,
    "MUSTANG WC": 53.0,
    "LEMONT BEARS": 52.0,
    "ROCKFORD": 49.5,
    "JOLIET COBRAS": 49.0,
    "LIONS": 47.0,
    "YORKVILLE": 45.0,
    "LOCKPORT GRAPPLERS": 45.0,
    "TRI-CITY BRAVES": 42.5,
    "RIVERDALE RAMS": 42.0,
    "MORRISON": 42.0,
    "MOLINE TIGERS": 38.5,
    "ST. BARNABAS/CHRIST THE KING": 38.0,
    "HARVARD": 36.0,
    "JR. ROCKET": 34.5,
    "OAK LAWN": 34.0,
    "LITTLE DEVILS": 31.0,
    "DOLTON FALCONS": 28.0,
    "MAINE TOWNSHIP EAGLES": 27.0,
    "LIL REAPER": 26.0,
    "MEAD JR. HIGH": 25.0,
    "WESTVILLE": 24.0,
    "GLENDALE": 24.0,
    "METAMORA": 24.0,
    "ROBBINS": 23.0,
    "LITTLE KNIGHTS": 23.0,
    "WAUKEGAN": 21.0,
    "OSWEGO COUGARS": 21.0,
    "TRAILBLAZERS": 20.5,
    "BRONCO": 20.0,
    "HOOPESTON": 20.0,
    "HARVEY PD TWISTERS": 20.0,
    "LITCHFIELD": 19.0,
    "MURPHYSBORO": 19.0,
    "MORTON": 19.0,
    "VITTUM CATS": 18.0,
    "RAMS WC": 17.0,
}
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    70: [
        "ADAM FREESE :: LIL REAPER",
        "ADAM GUSTAFSON :: ROCK ISLAND RED",
        "ANDY KONC :: PLAINFIELD",
        "BRENT MALMSTROM :: OSWEGO PANTHERS",
        "BRIAN CREIGHTON :: CRYSTAL LAKE",
        "CHAD THRONDSON :: LEMONT",
        "DANNY ERICKSON :: EAST MOLINE",
        "DEREK DALY :: ADDISON INDIAN TRAIL",
        "DOMINIC CURATOLO :: DOLTON",
        "DONNY WALSH :: ORLAND PARK",
        "JAMES BEAUREGARD :: MUSTANG",
        "JASON ATHERTON :: METAMORA :: 6",
        "JEFF ANDERSON :: TINLEY PARK :: 3",
        "JERRY STECK :: BRONCO",
        "MATTHEW EARNER :: ST. BARNABAS / CHRIST THE KING :: 4",
        "MATTHEW FRITZ :: HARLEM :: 2",
        "MIKE KENNEY :: JR. ROCKET",
        "NEIL REW :: SJO KIDS",
        "NICK POWELL :: EISENHOWER JH",
        "SHAWN GOLDEN :: BRADLEY-BOURBONNAIS",
        "STEVE RODGERS :: CROSSFACE",
        "STEVEN BRYANT :: BETHALTO :: 1",
        "ZACHARY ANDERSON :: TIGERTOWN :: 5",
    ],
    74: [
        "ADAM WASON :: TIGERTOWN",
        "CHAD KARLEN :: ROUND LAKE :: 4",
        "CHRIS MURRAY :: FISHER",
        "CHRIS STUART :: OAK FOREST",
        "CHUCK BURROWS :: BETHALTO :: 6",
        "DENNIS PLECKHAM :: RICH WRESTLING :: 3",
        "ERIC WOLDIET :: VILLA-LOMBARD :: 2",
        "JARED SCHROEDER :: GIBSON CITY",
        "JOHN STRAHLMAN :: MUSTANG",
        "KEVIN COZZIE :: ST. BARNABAS / CHRIST THE KING",
        "KYLE BARZANO :: GLENDALE",
        "LUIS CASTRO :: HARVEY",
        "LUKE HALEY :: ANTIOCH",
        "MARQUIS COLEMAN :: PIRATES",
        "MICHAEL DELOOSE :: MOLINE TIGERS",
        "MICHAEL MOORE :: KNIGHTS",
        "MICHAEL WETMORE :: WINSTON PARK",
        "RICHARD WALLS :: RED HILLS",
        "RICKIE YOUNG :: LEMONT",
        "RICKY MCDONALD :: METAMORA",
        "RONNIE DALLUGE :: MT. ZION :: 5",
        "ROY GUSTAFSON :: KNIGHTS",
        "RYAN RUMFELT :: EDWARDSVILLE",
        "TONY DOUGHTY :: FRANKLIN PARK :: 1",
    ],
    79: [
        "JOSHUA TURYNA :: ST. BARNABAS / CHRIST THE KING",
        "BRIAN EVERETT :: GIBSON CITY",
        "JOHN THORPE :: FROST",
        "AMADOR ESTRADA :: ROUND LAKE :: 2",
        "ETHAN CRANE :: GC COOLIDGE",
        "BRETT HOERR :: MORTON",
        "SCOTT KENNY :: ORLAND PARK :: 4",
        "ANTHONY BINION :: WARHAWKS",
        "TERENCE KENNEBREW :: PIRATES",
        "MARK MANKOWSKI :: HICKORY HILLS :: 5",
        "BRIAN CLODFELTER :: TIGERTOWN",
        "SAM MOHR :: PLAINFIELD",
        "SEAN PIPPIN :: GENESEO :: 6",
        "BRADY RUEL :: ST. BARNABAS / CHRIST THE KING",
        "DERRICK LOLLIS :: HARVEY",
        "ROY PIERCE :: SPARTANS",
        "BRAD VERMILLION :: CRYSTAL LAKE :: 3",
        "JASON ETZKORN :: LEMONT",
        "DAVID STOLTZ :: MEAD :: 1",
        "MIKE MURPHY :: LITTLE CELTIC",
        "TIM TYNSKI :: CRESTWOOD",
        "JAMIE FENDER :: FISHER",
        "BEN BRUNNER :: BLACKHAWK II",
        "RANDY ATERS :: LIL REAPER",
        # ???? "MICHAEL MARTINEZ :: WAUKEGAN",
    ],
    84: [
        "BEN BLACK :: HINSDALE",
        "BRENT PENTZIEN :: INDIAN PRAIRIE",
        "BRIAN WILSON :: CRYSTAL LAKE :: 5",
        "CHRIS GRIFFITH :: FISHER",
        "COREY HEYDECKER :: ADAMS",
        "JAKE SULLIVAN :: BETHALTO :: 4",
        "JARROD MERKELY :: TIGERTOWN",
        "JC GAUNT :: MT. VERNON :: 3",
        "JOE DI GIOLA :: VILLA-LOMBARD",
        "JOE WZOREK :: ORLAND PARK :: 2",
        "LORENZO WILLIAMS :: CORKERY",
        "MATT RUFF :: MATTOON",
        "MATTHEW MORENO :: CHICAGO HEIGHTS",
        "METHANA LANGSY :: ROCKFORD",
        "MICHAEL GASKIN :: ST. BARNABAS / CHRIST THE KING",
        "MIKE FORSYTH :: BRONCO",
        "MIKE MABRY :: VANDALIA",
        "MIKE NEELS :: MOLINE TIGERS",
        "ROAMELLE KIZZEE :: HARVEY :: 1",
        "SOLOMON TAYLOR :: CHILLICOTHE",
        "STEVEN PALUMBO :: ST. TARCISSUS",
        "STEVEN WERNSMAN :: YORKVILLE :: 6",
        "TIMOTHY HAMILTON :: PIRATES",
        "VINCE CHAMBLISS :: CATLIN",
    ],
    89: [
        "AARON GILSON :: ST. CHARLES :: 5",
        "ANTHONY OPIOLA :: DOLTON :: 4",
        "BEN FAIVR :: DAKOTA",
        "BEN POTTER :: BISMARCK-HENNING",
        "BRIAN WEIMER :: TRAILBLAZER",
        "CRAIG COLLINS :: CALUMET CITY :: 6",
        "DARNELL LOLLIS :: HARVEY :: 2",
        "DAVID DOUGLAS :: HARVEY :: 1",
        "DEREK DIXON :: LAKE FOREST",
        "DOC SANDERS :: EDWARDSVILLE",
        "JACOB THEISEN :: BLACKHAWK II",
        "JEFFREY EMMETT :: LANPHIER SPRINGFIELD",
        "JEFFREY WILLIAMS :: LANPHIER SPRINGFIELD",
        "JESSIE FLORES :: LIL REAPER",
        "JIM NEEDHAM :: ST. BARNABAS / CHRIST THE KING",
        "JOE FINDLEY :: RIVERDALE",
        "LUKE EWANIO :: ROSEMONT :: 3",
        "MARK NICOSON :: HARLEM",
        "MARTY FITZGIBBONS :: VITTUM CATS",
        "MATTHEW HENRY :: FRANKLIN PARK",
        "MATTHEW STEINKAMP :: QUINCY",
        "MICHAEL SMITH :: BETHALTO",
        "NATHAN CROSS :: MOLINE TIGERS",
        "TIN DONOHOO :: BETHALTO",
    ],
    95: [
        "ANTONIO WILLIAMS :: CORKERY",
        "ARCHIE GRIFFIN :: PIRATES :: 2",
        "CRAIG SWANSON :: MOLINE LIONS",
        "EDDIE VALDEZ :: WEST CHICAGO",
        "ERIC RAMIREZ :: ROSEMONT",
        "GRANT HOERR :: MORTON :: 3",
        "JAKE SULLIVAN :: BETHALTO :: 4",
        "JASON MEDLIN :: RANTOUL",
        "JEFF BONNET :: PANTHER CUB",
        "JEREMY PYLE :: RICH WRESTLING",
        "JOHN BELL :: HOOPESTON",
        "JONATHAN WALLACE :: BLACKHAWK",
        "KEVIN DOLDER :: YORKVILLE",
        "KEVIN RANDOLPH :: OAK FOREST :: 5",
        "MOSES REED :: DANVILLE",
        "PETE RODRIGUEZ :: DUNDEE",
        "RICK HERZOG :: RAMS",
        "ROBERT MURRAY :: ORLAND PARK :: 6",
        "SHAWN DEWISPELAERE :: EL PASO",
        "SOLVATOR RIGITANO :: VILLA-LOMBARD",
        "TODD COMBES :: DOLTON :: 1",
        "TODD STICHT :: BETHALTO",
        "TORY CUNNINGHAM :: MARION",
        "TROY DONNAHUE :: PANTHER BURBANK",
    ],
    101: [
        "ALAN WILSON :: CRYSTAL LAKE :: 1",
        "BRYAN MURPHY :: VILLA PARK",
        "CHRIS RODRIGUEZ :: TOMCATS :: 2",
        "CRAIG LOREK :: FRANKLIN PARK",
        "DERRICO DANCRIDGE :: PIRATES",
        "JACOB SMITH :: VILLA-LOMBARD :: 6",
        "JOHN LEHMAN :: VITTUM CATS",
        "LANCE WEBER :: ROSEMONT",
        "LUCAS ALT :: HOOPESTON",
        "MATTHEW WIGGINS :: HARVEY",
        "MICHAEL BORDERS :: HOOPESTON",
        "MICHAEL BRUNO :: PLAINFIELD :: 4",
        "NATHAN BADGETT :: BETHALTO",
        "NATHAN GRAUMENZ :: VANDALIA",
        "OSCAR YOUNG :: HOOPESTON",
        "PATRICK FAHEY :: ST. BARNABAS / CHRIST THE KING",
        "RYAN WEST :: KNIGHTS",
        "SCOTT HARRISON :: PLAINFIELD",
        "SCOTT MABUES :: RIVERDALE",
        "STEVE NIELSEN :: HICKORY HILLS :: 5",
        "TIM ROLEY :: MORTON",
        "TOM CHISAMORE :: HARVARD",
        "TRAVIS ZIMMERMAN :: BETHALTO :: 3",
        "WESS GAFFEY :: MORRISON",
    ],
    108: [
        "ANDY VALCIK :: ORLAND PARK",
        "BILLY BRYANT :: BETHALTO",
        "BRAD BECKER :: BETHALTO",
        "BRIAN JOSEPH :: VILLA-LOMBARD :: 1",
        "BRIAN PALMORE :: PONTIAC",
        "CHRIS OMARA :: MUSTANG",
        "DARREN SAATHOFF :: BRADLEY-BOURBONNAIS",
        "DAVID CLEMENTZ :: GENESEO :: 6",
        "ERIC PEREZ :: TOMCATS",
        "GARY GECAS :: OAK FOREST",
        "JASON SEEFORTH :: MT. ZION",
        "JOE JOHNSON :: KNIGHTS :: 2",
        "JOSH KANE :: MOLINE TIGERS",
        "KEVIN MASON :: W.F. T'BIRD",
        "MATT NELSON :: MORTON",
        "MATT SODERGREN :: ADAMS",
        "MATTHEW IRVIN :: LITTLE GIANTS",
        "MICHAEL BRUCKER :: DANVILLE :: 3",
        "NIKO FRENETTE :: DOLTON",
        "RICH DIGIROLAMO :: TRAILBLAZER",
        "RYAN MASON :: CRYSTAL LAKE :: 5",
        "SANDRO NUNEZ :: LIL REAPER :: 4",
        "SCOTT COWAN :: DOLTON",
        "SCOTT JUTKINS :: LANCER",
    ],
    115: [
        "MARK MCMENIMEN :: CROSSFACE",
        "JARED WEBER :: PONTIAC",
        "LEO DELATORRE :: VILLA-LOMBARD :: 5",
        "PATRICK MCENEANEY :: ORLAND PARK :: 4",
        "JIM BRODY :: ADDISON INDIAN TRAIL",
        "JACOB CULBERTSON :: VANDALIA",
        "TY POWERS :: ROCKFORD :: 1",
        "MICHAEL CUBASCHINI :: ST. CHARLES",
        "CHAD SCROGGINS :: MT. ZION",
        "JOE CHIAPPETTA :: FALCON",
        "JESSE CARAWAY :: MURPHYSBORO",
        "MICHAEL COSTELLO :: LAKE FOREST",
        "BRAD KERR :: BETHALTO :: 3",
        "DOUG CALLAHAN :: HINSDALE",
        "BENJAMIN SUTTMAN :: DAKOTA :: 6",
        "PAUL SPONSEL :: PALATINE",
        "BILLY IZZI :: OAK FOREST",
        "BLAKE GLEASON :: PEKIN",
        "BURTON HOLLOWAY :: VILLA-LOMBARD",
        "STEVEN SHADAB :: ELGIN",
        "SCOTT JACOBSON :: HINSDALE",
        "RYAN PETERSON :: MATTOON",
        "DAVID BURTON :: MORTON :: 2",
        "DONKOR PARKER :: HARVEY",
    ],
    122: [
        "ADAM VASCONEZ :: MEAD",
        "ANDY MARTINEZ :: PONTIAC",
        "ANDY RAINS :: MARION :: 4",
        "ANTHONY GENOVESI :: NOTRE DAME",
        "BILLY BIGANE :: CRESTWOOD",
        "BRET DOUGHERTY :: HARVARD",
        "CHRIS WINTER :: MAIN TWP",
        "CLINT FREITAG :: EDWARDSVILLE",
        "ERIC SMITH :: TIGERTOWN",
        "JAKE GRIFFIN :: OAK FOREST",
        "JOE ROBERTS :: PONTIAC",
        "JOHN SCHULTZ :: GENESEO :: 2",
        "JOSE ZEPEDA :: TOMCATS",
        "KEVIN MILLIGAN :: VILLA-LOMBARD :: 5",
        "MATHEW GUILFOYLE :: PLAINFIELD",
        "MATTHEW SMILEY :: HOOPESTON",
        "MIKE WEBER :: LITTLE DEVILS",
        "MITCHELL CHEST :: CORKERY",
        "ROBERTO RODRIGUEZ :: HARLEM :: 3",
        "ROCKY CAIFANO :: LIONS",
        "SERGIO TINAJERO :: DUNDEE",
        "SHAWN FORST :: TINLEY PARK :: 6",
        "TARL VON HATTEN :: ST. CHARLES",
        "TIM GLOVER :: MORTON :: 1",
    ],
    130: [
        "BART REED :: GENESEO",
        "BILL BIGGER :: WAUKEGAN :: 4",
        "BRIAN SHOBER :: WARHAWKS",
        "CHAD NEWBERRY :: MARION",
        "DAN DE BRUN :: VILLA-LOMBARD :: 3",
        "DUSTIN COOK :: FISHER",
        "EMIL ODLING :: HARVARD :: 5",
        "GREG SAKOWICZ :: TRAILBLAZER",
        "JAMES MCCULLOUGH :: LITTLE KNIGHTS",
        "JASON GUISINGER :: TINLEY PARK :: 1",
        "JOHN SALVINO :: MUSTANG",
        "JOSHUA MILLER :: WESTVILLE",
        "KARL MALAGON :: WAUKEGAN",
        "LASHUN JACKSON :: HARVEY",
        "MARKELIAN WASHINGTON :: CORKERY",
        "MATTHEW UREMOVICH :: LITTLE CELTIC",
        "MICHAEL BASILE :: DOLTON",
        "MIKE BERRY :: JORDAN-SETON :: 6",
        "MIKE KANKE :: GENESEO :: 2",
        "NICK STEELE :: GC COOLIDGE",
        "RYAN TACK :: EISENHOWER JH",
        "SHANE SUSINA :: SYCAMORE",
        "TOBY THOMAS :: ELGIN",
        "TODD CANNON :: HOOPESTON",
    ],
    138: [
        "AARON SHADAB :: ELGIN :: 5",
        "BOBBY HUITT JR :: STREATOR",
        "BRANDON YOUNG :: MEAD",
        "DAMARIO PORTER :: CORKERY",
        "DEREK STACHURA :: MORTON :: 2",
        "DUSTAN YARMAN :: NAPERVILLE PATRIOTS",
        "EVAN HILL :: ST. TARCISSUS",
        "HANK STOUT :: VANDALIA :: 3",
        "JEFFREY QUIMBY :: UNITY YOUTH",
        "JEFFREY SCACE :: DAKOTA",
        "JOEY SWOPE :: UNITY YOUTH",
        "JOHN JORDAN :: DOLTON",
        "KENNY HENZE :: LIL REAPER",
        "MATT SEAMANS :: MOLINE TIGERS",
        "MIKE TAYLOR :: LEMONT",
        "NATHAN SKELTON :: BETHALTO :: 6",
        "PETER DEMEIS :: LITTLE CELTIC",
        "RICHARD OLSEN :: GIBSON CITY",
        "SAUL MARQUEZ :: MUSTANG",
        "SHAWN GALLAGHER :: PEOTONE",
        "STANLEY EVANS JR :: PIRATES :: 4",
        "TOMMY GROSSMAN :: TINLEY PARK :: 1",
        "TONY THEMAS :: TRAILBLAZER",
        "WILLIAM BELT :: LITTLE DEVILS",
    ],
    147: [
        "AARON KUEBEL :: FULTON",
        "ADAM LYONS :: DANVILLE :: 5",
        "BOB MEYER :: ADAMS",
        "BRIAN LYNDE :: HARLEM",
        "CHARLES MCNEAL :: ST. CHARLES :: 3",
        "DAVID POTTER :: ST. CHARLES :: 2",
        "JASON CHRISTESON :: BETHALTO :: 1",
        "JEFF RIEGELEIN :: CROSSFACE",
        "JEREMIAH OWENS :: LITCHFIELD",
        "JOSH BRUGH :: LITTLE GIANTS",
        "JOSHUA INGERSOLL :: CHARGER KIDS",
        "JUSTIN RUSSOW :: BRADLEY-BOURBONNAIS",
        "KENNY COOPER :: BELVIDERE",
        "LEDESM ADRIAN :: CORKERY",
        "LUIS MAGANA :: PLAINFIELD",
        "MATT CORDES :: MOLINE TIGERS",
        "MORIO SANCHEZ :: BELVIDERE :: 4",
        "PHIL TAYLOR JR :: MT. ZION",
        "RYAN LANGILLE :: TRAILBLAZER",
        "SCOTT EVANS :: LITTLE CELTIC",
        "UNDRA BAILEY :: PIRATES",
        "WILLIAM ANDREWS :: ROBBINS",
        "WILLIAM REIDY :: DOLTON :: 6",
        "ZACHARY BATHON :: GC COOLIDGE",
    ],
    156: [
        "ANDY MOORE :: ARGENTA / OREANA :: 3",
        "ARTHUR FALCON :: TRI-CITY BRAVES",
        "BEN MENA :: ROCKFORD :: 1",
        "BRANDON MROZ :: GLENDALE",
        "CHRIS LECOMPTE :: PANTHER BURBANK",
        "CHRIS MILLER :: MARION",
        "DANIEL STEVENS :: MORTON",
        "DARWIN BROWN :: OAKWOOD",
        "DAVID PIERSON :: MURPHYSBORO",
        "DEMAS MORENO :: CRYSTAL LAKE",
        "ERIK CASTANEDA :: EISENHOWER JR HAWK :: 5",
        "GREGG GOSSETT :: HOOPESTON",
        "JEFFREY BROUCEK :: LEMONT :: 6",
        "JEROMY MARTH :: DAKOTA",
        "JON LOVRICH :: HICKORY HILLS :: 2",
        "JORGE ZAYAS :: WAUKEGAN",
        "JOSHUA READING :: RICH WRESTLING",
        "JUAN PEREZ :: CORKERY",
        "KEVIN BROWER :: JR. ROCKET :: 4",
        "MIKE MEDINA :: LEMONT",
        "NAPOLEON HARRIS :: HARVEY",
        "NATHAN SELL :: ILLINOIS VALLEY",
        "PAUL BERGE :: FROST",
        "RON WALTERS :: BETHALTO",
    ],
    166: [
        "ARMOND DAVIS :: CORKERY :: 4",
        "BRIAN ANDERSON :: LEMONT",
        "CLAY HOLYCROSS :: BISMARCK-HENNING",
        "CLYDE BASS :: TIGERTOWN",
        "D ANDRE DENTON :: PIRATES :: 5",
        "ERIC POWELL :: RICH WRESTLING :: 6",
        "ERIC WENDLING :: HARVARD",
        "GENE BEARD :: VILLA-LOMBARD :: 2",
        "JEFFREY BROOKS :: NORTH CHICAGO",
        "JOHN LAMB :: MOLINE TIGERS",
        "JOHN LOCKHART :: HOOPESTON",
        "KEVIN EBERMAN :: ANTIOCH",
        "LONNIE HOLMAN :: HARVEY",
        "MICHAEL BUCKNER :: HARVEY",
        "MICHAEL MITTY :: INDIAN PRAIRIE",
        "MICHEAL CUTLER :: DOLTON",
        "RICHARD ARRINGTON :: W.F. T'BIRD",
        "RYAN BURRIS :: EASTSIDE",
        "RYAN LEMBERG :: YORKVILLE :: 3",
        "STEVE HOAG :: JR. ROCKET",
        "THADDEUS PATTERSON :: EISENHOWER JR HAWK (2)",
        "THOMAS RIGGINS :: BETHALTO :: 1",
        "THOMAS SCHICKEL :: PANTHER BURBANK",
        "TOM MARSH :: GC COOLIDGE",
    ],
    177: [
        "MIKE GARCHIE :: ADAMS",
        "JOSHUA DRULLINGER :: BISMARCK-HENNING",
        "SCOTT DAVES :: PANTHER CUB :: 6",
        "TOBY ROLLYSON :: MIDWEST CENTRAL",
        "CHRIS PARCK :: NAPERVILLE WARRIORS :: 4",
        "CLARENCE CONNER :: CHICAGO HEIGHTS",
        "ALEX WEMMER :: ROCKFORD",
        "DANIEL LOPEZ :: RICHMOND",
        "KEVIN HUSTEDT :: GIBSON CITY",
        "TOBY ADAMS :: W.F. T'BIRD :: 1",
        "AHMAUD CLARK :: HARVEY",
        "KELAN MOORE :: VILLA-LOMBARD",
        "JOHN LEE :: RICH WRESTLING",
        "BEN BERTELSMAN :: LITTLE DEVILS",
        "JASON MAYNARD :: LAN-OAK",
        "JAHON MAILLET :: DOWNERS GROVE :: 2",
        "TIM STARBUCK :: MACOMB",
        "SHANE SHAMOON :: ROSEMONT",
        "JASON BERG :: DAKOTA :: 3",
        "HAROLD LALUMONDIER :: GC COOLIDGE",
        "SHANE GRAUMENZ :: VANDALIA",
        "JACOB MANNING :: ARGENTA / OREANA",
        "DANNY LESTER :: RAMS",
        "MATTHEW KUEBEL :: FULTON :: 5",
    ],
    189: [
        "ANTHONY ENGLESE :: MEAD :: 1",
        "CASEY JONES :: EL PASO",
        "CHAD PIXLEY :: RED HILLS",
        "CHAD SHEPHERD :: BRADLEY-BOURBONNAIS :: 4",
        "DARRICK KARSJEN :: BATAVIA",
        "DAVE HICKS :: SENECA",
        "DAVID NOLAN :: MUSTANG",
        "GEORGE GARCIA :: BLACKHAWK II :: 5",
        "GREG PIPER :: OAK FOREST",
        "JASON BOGAN :: ROSEMONT",
        "JASON NAPE :: CRESTWOOD :: 2",
        "JEREMY DURBIN :: VANDALIA :: 3",
        "JERRY KRAY :: LEMONT",
        "JOE MARSICO :: WARHAWKS",
        "JOE WILSON :: LITTLE DEVILS",
        "KEVIN TYLER :: HOOPESTON",
        "KOREY REID :: CHARGER KIDS :: 6",
        "MIKE DERRY :: HARLEM",
        "NICK MANCUSO :: ROCKFORD",
        "PAUL LOPEZ :: LARKIN",
        "RYAN WINSTEAD :: MORTON",
        "SPENCER KING :: PIRATES",
        "STEPHEN SPARROW :: MOLINE TIGERS",
        "TONY KUSTWAN :: DOLTON",
    ],
    275: [
        "ANDY MYERS :: PONTIAC :: 2",
        "ANDY STOCKMAN :: PEORIA",
        "BALTAZAR NINO :: BATAVIA :: 6",
        "BEN MCKAY :: MOLINE TIGERS",
        "CHAD JENKINS :: DAKOTA :: 3",
        "CHARLES KING :: HARVEY",
        "DANIEL ROGERS :: DAKOTA",
        "DAVID WITTENBORN :: EISENHOWER JR HAWK (2) :: 5",
        "ELI WALKER :: VILLA-LOMBARD",
        "HUBERT THOMPSON :: WARHAWKS :: 1",
        "JASON COKER :: GIBSON CITY",
        "JASON SURRATT :: OAK LAWN",
        "JEREMY WINSTEAD :: PEKIN",
        "JOE GARRETT :: HOOPESTON",
        "JOSEPH MCNELLY :: CENTRALIA",
        "LAN MCCANN :: CARBONDALE",
        "LOUIS HILL :: ROCKFORD",
        "MARTIN GONZALEZ :: BRADLEY-BOURBONNAIS :: 4",
        "MARTY BURTON :: ST. CHARLES",
        "MATTHEW ALFREDSON :: LIL REAPER",
        "NICK CAMPBELL :: GC COOLIDGE",
        "PHILIP HARPER :: PIRATES",
        "TIM TEEHAN :: TINLEY PARK",
        "WILLIARD WRIGHT :: CORKERY",
    ],
}
_SENIOR_PLACERS: dict[int, list[bracket_utils.Placer]] = {
    70: [
        bracket_utils.Placer(name="STEVEN BRYANT", team="BETHALTO"),
        bracket_utils.Placer(name="MATTHEW FRITZ", team="HARLEM SCHOOL DIST. 122"),
        bracket_utils.Placer(name="JEFF ANDERSON", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(
            name="MATTHEW EARNER", team="ST. BARNABAS CHRIST THE KING"
        ),
        bracket_utils.Placer(name="ZACHARY ANDERSON", team="TIGERTOWN TANGLERS"),
        bracket_utils.Placer(name="JASON ATHERTON", team="METAMORA"),
    ],
    74: [
        bracket_utils.Placer(name="TONY DOUGHTY", team="FRANKLIN PARK RAIDERS"),
        bracket_utils.Placer(name="ERIC WOLDIET", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="DENNIS PLECKHAM", team="RICH WRESTLING"),
        bracket_utils.Placer(name="CHAD KARLEN", team="ROUND LAKE SPARTANS"),
        bracket_utils.Placer(name="RONNIE DALLGE", team="MT. ZION"),
        bracket_utils.Placer(name="CHUCK BURROWS", team="BETHALTO"),
    ],
    79: [
        bracket_utils.Placer(name="DAVID STOLTZ", team="MEAD"),
        bracket_utils.Placer(name="AMADOR ESTRADA", team="ROUND LAKE SPARTANS"),
        bracket_utils.Placer(name="BRAD VERMILLION", team="CRYSTAL LAKE"),
        bracket_utils.Placer(name="SCOTT KENNY", team="ORLAND PARK PIONEERS"),
        bracket_utils.Placer(name="MARK MANKOWSKI", team="HICKORY HILLS"),
        bracket_utils.Placer(name="SEAN PIPPIN", team="GENESEO"),
    ],
    84: [
        bracket_utils.Placer(name="ROAMELLE KIZZEE", team="HARVEY TWISTERS"),
        bracket_utils.Placer(name="JOE WZOREK", team="ORLAND PARK PIONEERS"),
        bracket_utils.Placer(name="JC GAUNT", team="MT. VERNON"),
        bracket_utils.Placer(name="JAKE SULLIVAN", team="BETHALTO"),
        bracket_utils.Placer(name="BRIAN WILSON", team="CRYSTAL LAKE"),
        bracket_utils.Placer(name="STEVEN WERNSMAN", team="YORKVILLE"),
    ],
    89: [
        bracket_utils.Placer(name="DAVID DOUGLAS", team="HARVEY TWISTERS"),
        bracket_utils.Placer(name="DARNELL LOLLIS", team="HARVEY TWISTERS"),
        bracket_utils.Placer(name="LUKE EWANIO", team="ROSEMONT COBRAS"),
        bracket_utils.Placer(name="ANTHONY OPIOLA", team="DOLTON FALCONS"),
        bracket_utils.Placer(name="AARON GILSON", team="ST. CHARLES"),
        bracket_utils.Placer(name="CRAIG COLLINS", team="CALUMET CITY"),
    ],
    95: [
        bracket_utils.Placer(name="TODD COMBES", team="DOLTON FALCONS"),
        bracket_utils.Placer(name="ARCHIE GRIFFIN", team="PIRATES"),
        bracket_utils.Placer(name="GRANT HOERR", team="MORTON YOUTH"),
        bracket_utils.Placer(name="IKE SULLIVAN", team="BETHALTO"),
        bracket_utils.Placer(name="KEVIN RANDOLPH", team="OAK FOREST WARRIORS"),
        bracket_utils.Placer(name="ROBERT MURRAY", team="ORLAND PARK PIONEERS"),
    ],
    101: [
        bracket_utils.Placer(name="ALAN WILSON", team="CRYSTAL LAKE WIZARDS"),
        bracket_utils.Placer(name="CHRIS RODRIGUEZ", team="TOMCAT WC"),
        bracket_utils.Placer(name="TRAVIS ZIMMERMAN", team="BETHALTO"),
        bracket_utils.Placer(name="MICHAEL BRUNO", team="PLAINFIELD IT"),
        bracket_utils.Placer(name="STEVE NIELSEN", team="HICKORY HILLS"),
        bracket_utils.Placer(name="JACOB SMITH", team="VILLA LOMBARD COUGARS"),
    ],
    108: [
        bracket_utils.Placer(name="BRIAN JOSEPH", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="JOE JOHNSON", team="KNIGHTS"),
        bracket_utils.Placer(name="MICHAEL BRUCKER", team="DANVILLE"),
        bracket_utils.Placer(name="SANDRO NUNEZ", team="LIL REAPER"),
        bracket_utils.Placer(name="RYAN MASON", team="CRYSTAL LAKE WIZARDS"),
        bracket_utils.Placer(name="DAVID CLEMENTZ", team="GENESEO"),
    ],
    115: [
        bracket_utils.Placer(name="TY POWERS", team="ROCKFORD WC"),
        bracket_utils.Placer(name="DAVID BURTON", team="MORTON"),
        bracket_utils.Placer(name="BRAD KERR", team="BETHALTO"),
        bracket_utils.Placer(name="PATRICK MCENEANEY", team="ORLAND PARK PIONEERS"),
        bracket_utils.Placer(name="LEO DELATORRE", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="BENJAMIN SUTMAN", team="DAKOTA"),
    ],
    122: [
        bracket_utils.Placer(name="TIM GLOVER", team="MORTON YOUTH"),
        bracket_utils.Placer(name="JOHN SCHULTZ", team="GENESEO"),
        bracket_utils.Placer(name="ROBERTO RODRIGUEZ", team="HARLEM SCHOOL DIST. 122"),
        bracket_utils.Placer(name="ANDY RAINS", team="MARION"),
        bracket_utils.Placer(name="DEVIN MILLIGAN", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="SHAWN FORST", team="TINLEY PARK BULLDOGS"),
    ],
    130: [
        bracket_utils.Placer(name="JASON GUISINGER", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="MIKE KANKE", team="GENESEO"),
        bracket_utils.Placer(name="DAN DEBRUN", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="BILL BIGGER", team="WAUKEGAN"),
        bracket_utils.Placer(name="EMIL ODLING", team="HARVARD"),
        bracket_utils.Placer(name="MIKE BERRY", team="JORDAN SEATON"),
    ],
    138: [
        bracket_utils.Placer(name="TOMMY GROSSMAN", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="DEREK STACHURA", team="MORTON YOUTH"),
        bracket_utils.Placer(name="HANK STOUT", team="VANDALIA"),
        bracket_utils.Placer(name="STANLEY EVANS", team="PIRATES"),
        bracket_utils.Placer(name="AARON SHADAB", team="ELGIN"),
        bracket_utils.Placer(name="MAATHAN SKELTON", team="BETHALTO"),
    ],
    147: [
        bracket_utils.Placer(name="JASON CHRISTESON", team="BETHALTO"),
        bracket_utils.Placer(name="DAVID POTTER", team="ST. CHARLES"),
        bracket_utils.Placer(name="CHARLES MCNEAL", team="ST. CHARLES"),
        bracket_utils.Placer(name="MORIO SANCHEZ", team="BELVIDERE"),
        bracket_utils.Placer(name="ADAM LYONS", team="DANVILLE"),
        bracket_utils.Placer(name="WILLIAM REIDY", team="DOLTON FALCONS"),
    ],
    156: [
        bracket_utils.Placer(name="BEN MENA", team="ROCKFORD WC"),
        bracket_utils.Placer(name="JON LOVRICH", team="HICKORY HILLS"),
        bracket_utils.Placer(name="ANDY MOORE", team="ARGENTA OREANA"),
        bracket_utils.Placer(name="KEVIN BROWER", team="JR. ROCKET"),
        bracket_utils.Placer(name="ERIC CASTANEDA", team="EISENHOWER JR. HAWK"),
        bracket_utils.Placer(name="JEFFREY BROUCEK", team="LEMONT"),
    ],
    166: [
        bracket_utils.Placer(name="THOMAS RIGGINS", team="BETHALTO"),
        bracket_utils.Placer(name="GENE BEARD", team="VILLA LOMBARD COUGARS"),
        bracket_utils.Placer(name="RYAN LEMBERG", team="YORKVILLE"),
        bracket_utils.Placer(name="ARMOND DAVIS", team="CORKERY COUGARS"),
        bracket_utils.Placer(name="ANDRE DENTON", team="PIRATES"),
        bracket_utils.Placer(name="ERIC POWELL", team="RICH WRESTLING"),
    ],
    177: [
        bracket_utils.Placer(name="TOBY ADAMS", team="W.F. THUNDERBIRD"),
        bracket_utils.Placer(name="JOHN MAILLET", team="DOWNERS GROVE"),
        bracket_utils.Placer(name="JASON BERG", team="DAKOTA"),
        bracket_utils.Placer(name="CHRIS PARCK", team="NAPERVILLE WARRIORS"),
        bracket_utils.Placer(name="MATTHEW KUEBEL", team="FULTON"),
        bracket_utils.Placer(name="SCOTT DAVES", team="PANTHER CUB"),
    ],
    189: [
        bracket_utils.Placer(name="ANTHONY ENGLESE", team="MEAD"),
        bracket_utils.Placer(name="JASON NAPE", team="CRESTWOOD"),
        bracket_utils.Placer(name="JEREMY DURBIN", team="VANDALIA"),
        bracket_utils.Placer(name="CHAD SHEPHERD", team="BRADLEY BOURBONAIS"),
        bracket_utils.Placer(name="GEORGE GARCIA", team="BLACKHAWK II"),
        bracket_utils.Placer(name="KOREY REID", team="CHARGER KIDS"),
    ],
    275: [
        bracket_utils.Placer(name="HUBERT THOMPSON", team="WARHAWK WC"),
        bracket_utils.Placer(name="ANDY MYERS", team="OAK LAWN"),
        bracket_utils.Placer(name="CHAD JENKINS", team="DAKOTA"),
        bracket_utils.Placer(name="MARTIN GONZALEZ", team="BRADLEY BOURBONAIS"),
        bracket_utils.Placer(name="DAVID WITTENBORN", team="EISENHOWER JR. HAWK"),
        bracket_utils.Placer(name="BALTAZAR NINO", team="BATAVIA"),
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "BETHALTO JR. HIGH": 242.0,
    "VILLA-LOMBARD COUGARS": 158.5,
    "HARVEY TWISTERS": 103.5,
    "ST. CHARLES SAINTS": 102.0,
    "TINLEY PARK BULLDOGS": 97.0,
    "MORTON YOUTH": 90.5,
    "CRYSTAL LAKE WIZARDS": 87.0,
    "DOLTON FALCONS": 87.0,
    "PIRATES": 81.0,
    "ORLAND PARK PIONEERS": 76.5,
    "GENESEO": 74.0,
    "ROCKFORD": 72.5,
    "HARLEM COUGARS": 69.0,
    "DAKOTA": 69.0,
    "MEAD JR. HIGH": 66.5,
    "VANDALIA": 64.5,
    "HICKORY HILLS": 58.0,
    "BRADLEY BOURBONNAIS": 52.0,
    "DANVILE": 49.0,
    "OAK FOREST WARRIORS": 46.0,
    "ROUND LAKE SPARTANS": 46.0,
    "LIL REAPER": 45.0,
    "RICH WRESTLING": 43.0,
    "YORKVILLE": 40.0,
    "CORKERY COUGARS": 39.0,
    "FRANKLIN PARK RAIDERS": 37.0,
    "W.F. THUNDERBIRDS": 37.0,
    "WARHAWKS": 36.0,
    "PLAINFIELD INDIAN TRAIL": 36.0,
    "KNIGHTS": 34.0,
    "PONTIAC": 30.0,
    "JR. ROCKET": 29.0,
    "TIGERTOWN TANGLERS": 29.0,
    "TOMCAT": 28.0,
    "ROSEMONT COBRAS": 27.0,
    "ST. BARNABAS/CHRIST THE KING": 26.0,
    "CRESTWOOD COLTS": 26.0,
    "ARGENTA ORENA": 25.0,
    "DOWNERS GROVE": 24.0,
    "ELGIN": 24.0,
    "MT. VERNON": 23.0,
    "EISENHOWER JR. HAWK": 23.0,
    "CHARGER KIDS": 22.0,
    "WAUKEGAN": 22.0,
    "NAPERVILLE WARRIORS": 21.0,
    "EISENHOWER JR. HIGH": 21.0,
    "FULTON": 21.0,
    "BELVIDERE": 20.0,
    "MARION": 20.0,
    "HARVARD": 19.0,
}


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["novice"] = []
    for team_name, score in _NOVICE_TEAM_SCORES.items():
        team_scores["novice"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    weight_classes: list[bracket_utils.WeightClass] = []
    for weight, placers in _NOVICE_PLACERS.items():
        weight_class = bracket_utils.create_weight_class_from_placers(
            "novice", weight, placers, _NOVICE_TEAM_REPLACE
        )
        weight_classes.append(weight_class)

    for weight, placers in _SENIOR_PLACERS.items():
        weight_class = bracket_utils.create_weight_class_from_placers(
            "senior", weight, placers, _SENIOR_TEAM_REPLACE
        )
        if weight == 130:
            _, match_3rd, _ = weight_class.matches
            match_3rd.top_competitor.full_name = "DAN DE BRUN"
            match_3rd.top_competitor.last_name = "DE BRUN"
        if weight == 138:
            _, match_3rd, _ = weight_class.matches
            match_3rd.bottom_competitor.full_name = "STANLEY EVANS JR."

        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(HERE / "extracted.1993.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
