# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils
import manual_entry

_HERE = pathlib.Path(__file__).resolve().parent
_NOVICE_TEAM_SCORES: dict[str, float] = {
    "LITTLE CELTIC WRESTLING": 181,
    "FOX VALLEY WRESTLING CLUB": 169.5,
    "VILLA LOMBARD COUGARS": 150,
    "TINLEY PARK BULLDOGS": 138.5,
    "LEMONT BEARS WRESTLING": 106,
    "STERLING NEWMAN JR.": 102,
    "VITTUM CATS": 96,
    "ORLAND PARK PIONEERS": 95,
    "BETHALTO / JR. HIGH": 84,
    "HARLEM COUGARS": 73,
    "WOLFPAK WRESTLING CLUB": 67,
    "A-O KIDS WRESTLING": 59,
    "BELLEVILLE LITTLE DEVILS": 56,
    "ROXANA KIDS WRESTLING CLUB": 52.5,
    "LASALLE PERU CRUNCHING CAVS": 50,
    "MURPHYSBORO MIDDLE": 45,
    "MATTOON YOUTH WRESTLING": 44,
    "CROSSFACE WRESTLING": 43.5,
    "CRYSTAL LAKE WIZARDS": 41,
    "MIDWEST CENTRAL YOUTH": 40,
    "HIGHLAND PARK LITTLE GIANTS": 37,
    "WHEATON BULLDOGS": 37,
    "BELVIDERE BANDITS": 35,
    "EAST MOLINE WRESTLING CLUB": 34,
    "VANDALIA JR WRESTLING": 33,
    "DUNDEE HIGHLANDERS": 31,
    "JR. GOLDEN EAGLES": 30,
    "HIGHLAND BULLDOG JR": 28,
    "DAKOTA WRESTLING CLUB": 27,
    "HARVARD WC": 27,
    "PINCKNEYVILLE JR. PANTHERS": 27,
    "A-J JR. WILDCATS": 26,
    "BRADLEY-BOURBONNAIS": 26,
    "PONTIAC PYTHONS": 26,
    "URBANA KIDS CLUB": 26,
    "MT. ZION WRESTLING CLUB": 25,
    "HONONEGAH KIDS WRESTLING": 21,
    "YORKVILLE WRESTLING CLUB": 21,
    "WESTVILLE YOUTH WRESTLING": 19.5,
    "BATAVIA PINNERS": 19,
    "LITTLE REDBIRD WRESTLING": 19,
    "ST. BARNABAS / CHRIST THE KING": 19,
    "PLAINFIELD WRESTLING CLUB": 18.5,
    "NAPERVILLE WRESTLING CLUB": 17,
    "MORTON YOUTH WRESTLING": 16,
    "CUMBERLAND WRESTLING": 15,
    "UNITY WRESTLING CLUB": 14,
    "LITCHFIELD KIDS WRESTLING": 13,
    "HUSKIES WRESTLING CLUB": 12,
    "PLAINFIELD WOLVES WC": 12,
    "WHEATON MONROE EAGLES": 12,
    "GALESBURG JUNIOR STREAKS": 11,
    "BEAR COUNTRY WRESTLING": 10,
    "EDWARDSVILLE WRESTLING": 10,
    "METAMORA KIDS WRESTLING": 10,
    "RIVERDALE JR. HIGH WC": 10,
    "VILLA PARK YOUNG WARRIORS": 9.5,
    "MONTEGO MATMEN": 9,
    "SAVANNA REDHAWKS": 9,
    "EL PASO WRESTLING CLUB": 8,
    "LAKE VIEW JR. WILDCATS": 8,
    "OAK LAWN P.D. WILDCATS": 8,
    "POLO WRESTLING CLUB": 8,
    "WASHINGTON JR. PANTHERS": 8,
    "DEWITT COUNTY WRESTLING": 7,
    "EDISON PANTHERS": 7,
    "THE JACKSONVILLE WC": 7,
    "BISMARCK-HENNING": 6,
    "GLENBARD EAST JR. RAMS": 6,
    "METRO STALLIONS": 6,
    "SAUKEE YOUTH WRESTLING": 6,
    "SJO YOUTH WRESTLING": 5,
    "BENTON JR. WRESTLING CLUB": 4,
    "BRONCO WRESTLING CLUB": 4,
    "GENESEO WC": 4,
    "HINSDALE RED DEVIL WC": 4,
    "MARION WRESTLING": 4,
    "ORION KNIGHTS": 4,
    "OSWEGO PANTHERS WC": 4,
    "WARRENSBURG WRESTLING": 4,
    "NAPERVILLE EAGLES": 3.5,
    "FISHER WRESTLING CLUB": 3,
    "OAKWOOD WRESTLING CLUB": 3,
    "ST. BEDE'S": 3,
    "BADGER WRESTLING CLUB": 2,
    "DECATUR WRESTLING CLUB": 2,
    "LIMESTONE YOUTH ROCKET": 2,
    "MUSTANG WC": 2,
    "PANTHER CUB WRESTLING": 2,
    "SHARKS WRESTLING CLUB": 2,
    "WEST FRANKFORT REDBIRDS": 2,
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "FOX VALLEY WRESTLING CLUB": 352.5,
    "LITTLE CELTIC WRESTLING": 181,
    "VITTUM CATS": 172.5,
    "TINLEY PARK BULLDOGS": 153,
    "VILLA LOMBARD COUGARS": 120,
    "HARLEM COUGARS": 88,
    "LEMONT BEARS WRESTLING": 80,
    "BRADLEY-BOURBONNAIS": 68,
    "ORLAND PARK PIONEERS": 63,
    "SPRINGFIELD CAPITALS": 63,
    "STERLING NEWMAN JR.": 56,
    "YORKVILLE WRESTLING CLUB": 53,
    "CRYSTAL LAKE WIZARDS": 51,
    "ROCK ISLAND WRESTLING CLUB EDISON": 45,
    "TIGERTOWN TANGLERS": 45,
    "SHERRARD JR. WRESTLING": 44,
    "MORTON YOUTH WRESTLING": 42,
    "MURPHYSBORO MIDDLE": 41,
    "EAST MOLINE WRESTLING CLUB": 40,
    "URBANA KIDS CLUB": 39.5,
    "ROCKFORD WRESTLING CLUB": 38.5,
    "METRO STALLIONS": 37.5,
    "CHAMPAIGN CHARGER KIDS": 36,
    "WHEATON MONROE EAGLES": 35.5,
    "BATAVIA PINNERS": 33,
    "MT. ZION WRESTLING CLUB": 33,
    "CENTRALIA WRESTLING CLUB": 32,
    "ROXANA KIDS WRESTLING CLUB": 30.5,
    "EDWARDSVILLE WRESTLING": 30,
    "CHILLI DAWGS WRESTLING": 29.5,
    "MARION WRESTLING": 29,
    "VANDALIA JR WRESTLING": 29,
    "BELLEVILLE LITTLE DEVILS": 28,
    "BISMARCK-HENNING": 28,
    "BROWNSON WC": 28,
    "EL PASO WRESTLING CLUB": 28,
    "LITTLE REDBIRD WRESTLING": 27,
    "BELVIDERE BANDITS": 26.5,
    "RIVERBEND / FULTON WC": 26,
    "GENESEO WC": 25,
    "PLT PROPHETS WC": 25,
    "JR. ROCKET WRESTLING CLUB": 23,
    "LASALLE PERU CRUNCHING CAVS": 23,
    "OAK LAWN P.D. WILDCATS": 22,
    "BETHALTO / JR. HIGH": 21,
    "MATTOON YOUTH WRESTLING": 21,
    "WOLFPAK WRESTLING CLUB": 20,
    "UNITY WRESTLING CLUB": 19,
    "ACES WRESTLING": 18,
    "EDISON PANTHERS": 17,
    "MUSTANG WC": 16,
    "WEST FRANKFORT REDBIRDS": 16,
    "CHENOA WRESTLING CLUB": 14,
    "JR. GOLDEN EAGLES": 13,
    "METAMORA KIDS WRESTLING": 13,
    "OAKWOOD WRESTLING CLUB": 11,
    "JR. MAROON'S WRESTLING": 10,
    "JR. PANTHERS WRESTLING": 10,
    "OSWEGO PANTHERS WC": 10,
    "ST. BARNABAS / CHRIST THE KING": 9.5,
    "BEAR COUNTRY WRESTLING": 9,
    "SOUTHERN ILLINOIS EAGLES": 8.5,
    "BADGER WRESTLING CLUB": 8,
    "NAPERVILLE EAGLES": 8,
    "PONTIAC PYTHONS": 8,
    "MT. VERNON LIONS WRESTLING": 7,
    "DAKOTA WRESTLING CLUB": 6,
    "HINSDALE RED DEVIL WC": 6,
    "LIL' STORM YOUTH WRESTLING": 6,
    "OSWEGO COUGARS": 6,
    "DECATUR WRESTLING CLUB": 4,
    "FISHER WRESTLING CLUB": 4,
    "FOX VALLEY WRESTLING-GRANGER": 4,
    "HERRIN WRESTLING CLUB": 4,
    "SAUKEE YOUTH WRESTLING": 4,
    "WARRENSBURG WRESTLING": 4,
    "WHEATON BULLDOGS": 4,
    "BENTON JR. WRESTLING CLUB": 3.5,
    "DURAND-PECATONICA": 3,
    "LAKELAND PREDATORS": 3,
    "CUMBERLAND WRESTLING": 2,
    "GALESBURG JUNIOR STREAKS": 2,
    "HARVARD WC": 2,
    "HUSKIES WRESTLING CLUB": 2,
    "NAPERVILLE WRESTLING CLUB": 2,
    "ROCK ISLAND WC-WASHINGTON": 2,
    "SJO YOUTH WRESTLING": 2,
    "TAYLORVILLE WC": 2,
}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    (
        "ANTHONY (A.J.) CICCARELLI",
        "ROXANA KIDS WRESTLING CLUB",
    ): bracket_utils.Competitor(
        full_name="ANTHONY (A.J.) CICCARELLI",
        first_name="AJ",
        last_name="CICCARELLI",
        team_full="ROXANA KIDS WRESTLING CLUB",
    ),
    (
        "PATRICK GADIENT YOUNG",
        "ERIE MIDDLE SCHOOL WRESTLING CLUB",
    ): bracket_utils.Competitor(
        full_name="PATRICK GADIENT YOUNG",
        first_name="PATRICK",
        last_name="YOUNG",
        team_full="ERIE MIDDLE SCHOOL WRESTLING CLUB",
    ),
    ("RYAN JAMES GLENN", "ELGIN LARKIN JR. ROYALS"): bracket_utils.Competitor(
        full_name="RYAN JAMES GLENN",
        first_name="RYAN",
        last_name="GLENN",
        team_full="ELGIN LARKIN JR. ROYALS",
    ),
    ("RYAN ST. JOSEPH", "CRYSTAL LAKE WIZARDS"): bracket_utils.Competitor(
        full_name="RYAN ST. JOSEPH",
        first_name="RYAN",
        last_name="ST. JOSEPH",
        team_full="CRYSTAL LAKE WIZARDS",
    ),
}


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["novice"] = []
    for team_name, score in _NOVICE_TEAM_SCORES.items():
        team_scores["novice"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    weight_classes = manual_entry.load_manual_entries(
        _HERE.parent, 1999, _NAME_EXCEPTIONS
    )

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1999.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
