# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils

HERE = pathlib.Path(__file__).resolve().parent
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    60: [
        "ANDREW OCONNOR :: ORLAND PARK PIONEERS",
        "ANDREW PENNA :: CRYSTAL LAKE WIZARDS :: 6",
        "BRAD BRONDSEMA :: MAINE TOWNSHIP EAGLES",
        "BRIAN GILLHAM :: ST. TARCISSUS RAIDERS",
        "BRIAN HARAF :: ROSEMONT COBRAS",
        "DANNY MARTINEZ :: BELVIDERE YMCA BANDITS :: 5",
        "EDDIE ROMIC :: VITTUM CATS",
        "FRANK MCNAUGHTON :: OAK LAWN PD WILDCATS",
        "JEREMY HAYES :: MORTON YOUTH WC :: 1",
        "JON DEAL :: PONTIAC WC",
        "JUSTIN CLUBB :: HARLEM SCHOOL DISTRICT 122 WC",
        "JUSTIN KAMPER :: HICKORY HILLS PD",
        "MARK WARREN :: LITTLE CELTIC WC",
        "MICHAEL STANLEY :: MATTOON WC",
        "NICHOLAS CIRRINCIONE :: VILLA-LOMBARD COUGARS :: 4",
        "PATRICK HAMILTON :: MORRISON JR. HIGH WC",
        "PAUL AUGLE :: TINLEY PARK BULLDOGS :: 3",
        "RICHARD CARNEY :: GRANITE CITY WC COOLIDGE",
        "ROB KING :: UNITY YOUTH WC",
        "ROBERT ARKO :: VILLA-LOMBARD COUGARS",
        "RYAN FEATHERSTUN :: MT. VERNON LIONS WC",
        "SAM LAUX :: BETHALTO / JR. HIGH",
        "STEVE RODGERS :: CROSSFACE WC :: 2",
        "WILLIAM ZIGMAN :: TRAILBLAZER WC",
    ],
    64: [
        "ADAM JOHNSON :: ILLINI BLUFFS WC",
        "AMADOR ESTRADA :: ROUND LAKE SPARTAN WC :: 1",
        "BLAKE DINTELMAN :: BELLEVILLE LITTLE DEVILS",
        "BLAKE VERMILLION :: CRYSTAL LAKE WIZARDS :: 2",
        "BRAD NORRIS :: REDBIRD WC",
        "GEORGE ODELL :: QUINCY / JR. HIGH WC",
        "JADEN EDWARDS :: CHARGER KIDS WC",
        "JARED SCHROEDER :: GIBSON CITY YOUTH",
        "JEFF ANDERSON :: TINLEY PARK BULLDOGS :: 3",
        "JERAD KARLEN :: ROUND LAKE SPARTAN WC",
        "JEREMIAH MCMECHAN :: CUMBERLAND COUNTY WC",
        "JUAN ORTIZ :: TOMCAT WC",
        "LONNIE CORBIN :: PANTHER WRESTLING :: 4",
        "MARC PETERSON :: MUSTANG WC",
        "MATTHEW EARNER :: ST. BARNABAS / CHRIST THE KING",
        "RICHARD KUCZKOWSKI :: LEMONT WC",
        "SCOTT PARSONS :: WEST CHICAGO PD",
        "SEAN CHINSKI :: LITTLE CELTIC WC :: 6",
        "SHAWN GOLDEN :: BRADLEY-BOURBONAIS YOUTH",
        "STEVEN BRYANT :: BETHALTO / JR. HIGH :: 5",
        "TERENCE KENNEBREW :: PIRATES",
        "TJ GRIDER :: ELMHURST JR. DUKES",
        "TONY GANAS :: ROSEMONT COBRAS",
        "ZACH ANDERSON :: TIGERTOWN TANGLERS",
    ],
    68: [
        "ADAM WASON :: TIGERTOWN TANGLERS :: 4",
        "ANDY COYLE :: VILLA-LOMBARD COUGARS",
        "ANTHONY OPIOLA :: DOLTON PARK FALCONS :: 2",
        "CHAD KARLEN :: ROUND LAKE SPARTAN WC",
        "CHRIS STUART :: OAK FOREST WARRIORS",
        "CHUCK BURROWS :: BELLEVILLE LITTLE DEVILS",
        "DAN NILES :: YORKVILLE WC",
        "DAVID GNADEN :: DANVILLE YOUTH WC",
        "ERIC WOLDEIT :: VILLA-LOMBARD COUGARS",
        "JEFF JEZUIT :: PANTHER WRESTLING",
        "KYLE ONEILL :: TINLEY PARK BULLDOGS :: 1",
        "MARK MANKOWSKI :: HICKORY HILLS PD :: 5",
        "MARQUIS COLEMAN :: PIRATES",
        "MATT WHITMER :: GIBSON CITY YOUTH",
        "MIKE KOPECKY :: ROSEMONT COBRAS",
        "NATHANIEL MARTINEZ :: TOMCAT WC",
        "RICKY MCDONALD :: METAMORA KIDS WC",
        "ROY PIERCE :: SPARTANS",
        "RYAN RUMFELT :: BETHALTO / JR. HIGH",
        "SCOTT KENNY :: ORLAND PARK PIONEERS :: 3",
        "SEAN PIPPIN :: GENESEO WC",
        "SHANE MENDENHALL :: MT. ZION WC",
        "TONY DOUGHTY :: FRANKLIN PARK RAIDERS :: 6",
        "TYLER KIMBERLIN :: DUNDEE HIGHLANDERS WC",
    ],
    72: [
        "ALAN RODENBERG :: ST. BARNABAS / CHRIST THE KING",
        "BRAD SCHRADER :: HARLEM SCHOOL DISTRICT 122 WC",
        "BRADLEE VERMILLION :: CRYSTAL LAKE WIZARDS :: 5",
        "CHRIS GRIFFITH :: FISHER WC",
        "DAVID DREW :: MUSTANG WC",
        "DAVID STOLTZ :: ARLINGTON CARDINALS WC :: 3",
        "ETHAN CRANE :: GRANITE CITY WC COOLIDGE",
        "JASON RYMUT :: ORLAND PARK PIONEERS",
        "JOE DIGOIA :: VILLA-LOMBARD COUGARS",
        "JOEL CATOUR :: MOLINE TIGERS",
        "JORDAN WEBSTER :: METAMORA KIDS WC",
        "JUSTIN MCCABE :: ROSEMONT COBRAS",
        "LEONARD BOWENS :: HARVEY PARK TWISTERS :: 1",
        "LYLE PLOTT :: UNION COUNTY WC",
        "MATT JOHNSON :: ILLINI BLUFFS WC",
        "MICHAEL MURPHY :: LOCKPORT GRAPPLERS WC",
        "NICHOLAS BINGHEIM :: BETHALTO / JR. HIGH :: 2",
        "PAT ROSS :: MUSTANG WC",
        "PAUL GARBIS :: TRAILBLAZER WC :: 4",
        "RONNIE DALLUGE :: MT. ZION WC",
        "SAM SCHAEFER :: WHEATON-WARRENVILLE :: 6",
        "STEVE WERNSMAN :: YORKVILLE WC",
        "TOMMY MIETUS :: ROSEMONT COBRAS",
        "VINCE CHAMBLISS :: CATLIN WC",
    ],
    77: [
        "AARON GILSON :: ST. CHARLES WC DISTRICT 303",
        "ARCHIE GRIFFIN :: PIRATES",
        "BEN BLACK :: HINSDALE RED DEVIL WC :: 4",
        "BOB WHITE :: MORRISON JR. HIGH WC",
        "BOBBY CHAULSETL :: GRANITE CITY WC GRISBY",
        "BRAD OWENS :: MT. ZION WC",
        "BRAD PRUNTY :: MACOMB KIDS",
        "BRIAN WILSON :: CRYSTAL LAKE WIZARDS",
        "CAL RYDER :: MATTOON WC",
        "CRAIG COLLINS :: CALUMET MEMORIAL PD :: 6",
        "DAVID DOUGLAS :: HARVEY PARK TWISTERS :: 3",
        "DERRICK DAWSON :: CORKERY COUGARS",
        "JC GAUNT :: MT. VERNON LIONS WC",
        "JESSIE FLORES :: LIL REAPER WRESTLING",
        "JOEL HOWARD :: NAPERVILLE PATRIOTS :: 5",
        "MATTHEW GOLDSTEIN :: HIGHLAND PARK LITTLE GIANTS :: 1",
        "MIKE MATHEWS :: INDIAN PRAIRIE PIONEERS",
        "MIKE NEELS :: MOLINE TIGERS",
        "MIKE SMITH :: BETHALTO / JR. HIGH",
        "ROAMELLE KIZZEE :: HARVEY PARK TWISTERS",
        "RUDX PANKRATZ :: KNIGHT WC",
        "TODD COMBES :: DOLTON PARK FALCONS :: 2",
        "TOM RYAN :: ROSEMONT COBRAS",
        "TONY SKINNER :: WESTVILLE JR. HIGH",
    ],
    82: [
        "ANTHONIO WILLIAMS :: MASON SCHOOL PLAYGROUND",
        "BRIAN COMSTOCK :: ST. CHARLES WC DISTRICT 303 :: 6",
        "BRIAN PRUNTY :: MACOMB KIDS",
        "CHRIS RODRIGUEZ :: TOMCAT WC",
        "CLAY FRENCH :: MATTOON WC",
        "GRANT HOERR :: MORTON YOUTH WC",
        "IKE SULLIVAN :: BETHALTO / JR. HIGH",
        "JAKE SULLIVAN :: BETHALTO / JR. HIGH",
        "JASON ERWINSKI :: TINLEY PARK BULLDOGS",
        "JEREMY LARSEN :: OSWEGO COUGARS :: 4",
        "JIM ABERLE :: ROUND LAKE SPARTAN WC :: 1",
        "KEVIN RANDOLPH :: OAK FOREST WARRIORS :: 5",
        "LAWAN GRAY :: PIRATES :: 3",
        "LUCAS DYER :: ANTIOCH UPPER GRADE",
        "MATTHEW HENRY :: FRANKLIN PARK RAIDERS",
        "MATTHEW LONG :: YORKVILLE WC",
        "MICHAEL HARRISON :: ADDISON / INDIAN TRAIL ANIMALS",
        "MILTON BLAKELY :: HARVEY PARK TWISTERS :: 2",
        "MITCH UPTON :: MATTOON WC",
        "MOSES REED :: DANVILLE YOUTH WC",
        "NATE BADGETT :: BETHALTO / JR. HIGH",
        "SOLOMON TAYLOR :: CHILLICOTHE WRESTLING",
        "STEVEN NIELSEN :: HICKORY HILLS PD",
        "TONY GILL :: DOLTON PARK FALCONS",
    ],
    87: [
        "ALAN WILSON :: CRYSTAL LAKE WIZARDS :: 5",
        "ANDY DOUGLAS :: ADDAMS JH WC :: 1",
        "ANDY VALCIK :: ORLAND PARK PIONEERS",
        "BILL BRYANT :: BETHALTO / JR. HIGH",
        "BRANDON TURNER :: DUNDEE HIGHLANDERS WC",
        "BRYAN MURPHY :: VILLA PARK YOUNG WARRIORS",
        "CRAIG LOREK :: FRANKLIN PARK RAIDERS",
        "DOMINIC CICCONE :: TINLEY PARK BULLDOGS :: 6",
        "IAN PENZATO :: VILLA-LOMBARD COUGARS :: 4",
        "JOHN BELL :: HOOPESTON-EAST LYNN JH",
        "LUKE EWANIO :: ROSEMONT COBRAS :: 3",
        "MATT BOECK :: EDWARDSVILLE",
        "MATT LACKEY :: MOLINE TIGERS",
        "MICHAEL BONDI :: DUNDEE HIGHLANDERS WC :: 2",
        "MICHAEL KELLEY :: CROSSFACE WC",
        "MICHAEL POWELL :: FISHER WC",
        "MIKE BONOVICH :: OAK LAWN PD WILDCATS",
        "OSCAR YOUNG :: HOOPESTON-EAST LYNN JH",
        "PATRICK WRONA :: DOLTON PARK FALCONS",
        "PHILLIP FOSTES :: NEWMAN BLUE DEVILS",
        "ROBERT MURRAY :: ORLAND PARK PIONEERS",
        "RYAN WEST :: ST. CHARLES WC DISTRICT 303",
        "TIM DONOHOO :: BETHALTO / JR. HIGH",
        "TIMOTHY DREW :: MUSTANG WC",
    ],
    93: [
        "ALAN CARTWRIGHT :: WARHAWK WC :: 1",
        "BRAD BECKER :: BETHALTO / JR. HIGH",
        "BRIAN JOSEPH :: VILLA-LOMBARD COUGARS",
        "BRYAN GIBBONS :: KNIGHT WC :: 4",
        "CHRIS TRAVERSA :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "DALE SIMPSON JR :: WHEATON-WARRENVILLE",
        "DAN DOYLE :: DOLTON PARK FALCONS :: 6",
        "DAVID CLEMENTZ :: GENESEO WC",
        "ERIC GIBSON :: EDWARDSVILLE",
        "FRANCISCO BERMUDEZ :: LOCKPORT GRAPPLERS WC :: 3",
        "GRIFF POWELL :: ARLINGTON CARDINALS WC :: 2",
        "JAMES EALY :: ROCKET WC",
        "KIETH PETRO :: LITTLE CELTIC WC",
        "LANCE WEBER :: ROSEMONT COBRAS",
        "MATT NELSON :: MORTON YOUTH WC",
        "MATTHEW FAHEY :: ST. BARNABAS / CHRIST THE KING",
        "MICHAEL BRUCKER :: DANVILLE YOUTH WC",
        "MICHAEL CASTILLO :: LIONS WC",
        "NICK UPTON :: MATTOON WC",
        "RON TICKLE :: PONTIAC WC",
        "SHAUN RICHMOND :: WHEATON-WARRENVILLE",
        "TAD HARPER :: ANTIOCH UPPER GRADE",
        "TRAVIS ZIMMERMAN :: BETHALTO / JR. HIGH :: 5",
        "TY POWERS :: ROCKFORD WC",
    ],
    99: [
        "BART BROSNAN :: ST. BARNABAS / CHRIST THE KING :: 6",
        "BEN KING :: LIONS WC :: 5",
        "BILL KOPECKY :: ROSEMONT COBRAS",
        "BRANDON PIERSON :: BLUE CREW ROCKETS",
        "BRIAN SITZE :: ALTON-ROXANA WC",
        "DAVID BURTON :: MORTON YOUTH WC",
        "DAVID VANCURA :: MEAD JH WC",
        "ERIC CAMPBELL :: LAKE VILLA LANCERS",
        "JAMAE PHILLIPS :: WEST CHICAGO PD",
        "JOE CASH :: W.F. THUNDERBIRD",
        "JOE JOHNSON :: TINLEY PARK BULLDOGS",
        "JOSH MOORE :: KNIGHT WC",
        "KEVIN FEIGEHBUTZ :: GRANITE CITY WC GRISBY",
        "KEVIN SIPP :: ADDAMS JH WC :: 2",
        "LEO DELATORRE :: VILLA-LOMBARD COUGARS :: 3",
        "MATHEW GUILFOYLE :: PLAINFIELD INDIAN TRAIL WRESTLING :: 4",
        "MATT SMITH :: HARLEM SCHOOL DISTRICT 122 WC",
        "RYAN OWENS :: MT. ZION WC",
        "RYAN PETERSON :: MATTOON WC",
        "SCOTT ALBRITTON :: CROSSFACE WC",
        "SCOTT SCHROEDER :: DOWNERS GROVE COUGARS",
        "TONY BORREGO :: PONTIAC WC",
        "TONY DAVIS :: HARVEY PARK TWISTERS :: 1",
        "WILLIAM ALBRECHT :: VITTUM CATS",
    ],
    105: [
        "AARON ROACH :: EDWARDSVILLE",
        "AMOS MITCHELL :: HARVEY PARK TWISTERS",
        "BRET DOUGHERTY :: HARVARD WC",
        "BRIAN NETTLETON :: GIBSON CITY YOUTH",
        "ELI LAWHORN :: MACOMB KIDS",
        "FRANSISCO VILLARREAL :: VILLA-LOMBARD COUGARS :: 6",
        "JASON SEEFORTH :: MT. ZION WC",
        "JASON WILSON :: GRANITE CITY WC COOLIDGE",
        "JOHN BUCKLEY :: MUSTANG WC",
        "JOHN GARCIA :: ADDISON / INDIAN TRAIL ANIMALS",
        "JOHN SCHULTZ :: GENESEO WC",
        "KENT DASHEL :: CRESTWOOD COLTS",
        "KEVIN MILLIGAN :: VILLA-LOMBARD COUGARS :: 2",
        "MATTHEW BYBEE :: PONTIAC WC",
        "MATTHEW TOMANOVICH :: W.F. THUNDERBIRD",
        "NICHOLAS NIELSEN :: ST. BARNABAS / CHRIST THE KING",
        "REGINALD WRIGHT :: PIRATES :: 1",
        "ROBERT DELA FUENTE :: LOCKPORT GRAPPLERS WC",
        "RONALD FARINA :: RICH WRESTLING",
        "RYAN DUGGAN :: ST. TARCISSUS RAIDERS :: 3",
        "RYAN POZEN :: KNIGHT WC :: 5",
        "RYAN SWEENEY :: BLACKHAWK WC",
        "SHANE SUSINA :: CRYSTAL LAKE WIZARDS",
        "TIM GLOVER :: MORTON YOUTH WC :: 4",
    ],
    112: [
        "AARON EHLE :: HARLEM SCHOOL DISTRICT 122 WC :: 2",
        "ANDY KUKLA :: ROUND LAKE SPARTAN WC",
        "ANDY MARTINEZ :: PONTIAC WC",
        "BRIAN SHOBER :: WARHAWK WC",
        "BRIAN WEEKS :: LAKE VILLA LANCERS",
        "CAM STOCK :: HINSDALE RED DEVIL WC",
        "DAVE KELVER :: NAPERVILLE LANCERS",
        "JAMES MCCULLOUGH :: BELLEVILLE LITTLE DEVILS",
        "JASON CHRISTESON :: BETHALTO / JR. HIGH :: 1",
        "JEREMIAH BURKHART :: IRISH CADET WC",
        "JEREMIAH SPRAGUE :: OAKWOOD WC",
        "JOHN KOPECKY :: ROSEMONT COBRAS",
        "JOHN PHILLIPS :: ROCKET WC",
        "JON SWANSON :: MT. ZION WC",
        "KEVIN NEVILLS :: ADDAMS JH WC :: 4",
        "MARK MCMENIMEN :: CROSSFACE WC",
        "MARK MICHELINI :: BLACKHAWK WC",
        "MIKE KANKE :: GENESEO WC :: 6",
        "NICK HOWLETT :: TINLEY PARK BULLDOGS",
        "PAT QUIRK :: HINSDALE RED DEVIL WC",
        "ROY KING :: JOLIET BOYS CLUB COBRAS :: 5",
        "STEVE LEVEREN :: MUSTANG WC :: 3",
        "STEVE WEBER :: VILLA-LOMBARD COUGARS",
        "TODD HALE :: VANDALIA JR. WC",
    ],
    119: [
        "ANDY RAINS :: MARION WC",
        "ANTHONY CROCENZI :: FRANKLIN PARK RAIDERS",
        "CHRIS COSIMO :: FALCON WC",
        "CHRIS WHISENANT :: OSWEGO COUGARS",
        "CLINT KERSCHIETER :: RIVERDALE JH WC",
        "CODY ABBOTT :: URBANA KIDS WC :: 3",
        "DAN MCNULTY :: ST. BARNABAS / CHRIST THE KING",
        "EDWIN PEREZ :: WAUKEGAN PD HAWKEYE WC",
        "GREG VOEGTLE :: BELLEVILLE LITTLE DEVILS :: 1",
        "GREGORY STUBBE :: DAKOTA WC",
        "JOHN HAMADA :: MEAD JH WC",
        "JOSEPH GERACI :: VILLA-LOMBARD COUGARS",
        "JUSTIN BEAN :: GRANITE CITY WC COOLIDGE",
        "KURT KIETZMAN :: GIBSON CITY YOUTH",
        "LASHAUN JACKSON :: HARVEY PARK TWISTERS :: 2",
        "MARK BLACKMORE :: JOLIET BOYS CLUB COBRAS",
        "MATT DEGROOT :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "PETE CURRIE :: VILLA-LOMBARD COUGARS :: 5",
        "ROBERTO RODRIGUEZ :: HARLEM SCHOOL DISTRICT 122 WC :: 4",
        "SHAWN PRICE :: RIVERDALE JH WC",
        "STANLEY CLEMENTZ :: GENESEO WC",
        "TIM GRAY :: PONTIAC WC :: 6",
        "TOBY THOMAS :: ELGIN GRAPPLERS",
        "TONY COLLINS :: PANTHER WRESTLING",
    ],
    127: [
        "ANTHONY EVANS :: GRANITE CITY WC COOLIDGE :: 4",
        "ANTWAUN SCOTT :: MASON SCHOOL PLAYGROUND",
        "BRADLEY ROSS :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "CHAD ORR :: RIVERDALE JH WC :: 3",
        "CHRIS CATALANO :: VILLA-LOMBARD COUGARS",
        "CORD SCHROEDER :: GIBSON CITY YOUTH",
        "DAN MATTER :: OLSON JR. HIGH",
        "DEREK STACHURA :: MORTON YOUTH WC :: 2",
        "ERIC SCHOO :: VILLA-LOMBARD COUGARS",
        "JAMES PATTERSON :: LAKE VILLA LANCERS",
        "JASON PEREZ :: TOMCAT WC",
        "JEFF ESTRADA :: GRANITE CITY WC GRISBY :: 5",
        "JOHN VENNE :: GRANITE CITY WC COOLIDGE :: 6",
        "JON LOVRICH :: HICKORY HILLS PD",
        "JOSHUA LINDSEY :: GIBSON CITY YOUTH",
        "MIKE NEVEL :: BUFFALO GROVE WC",
        "PETE REYNA :: CORKERY COUGARS",
        "ROBERT GAINES :: PONTIAC WC",
        "RON WERCHEK :: ANTIOCH UPPER GRADE",
        "RYAN MCGOVERN :: ROSEMONT COBRAS",
        "STANLEY EVANS JR :: PIRATES",
        "TIM GIBSON :: RICHWOODS SQUIRES",
        "TIMOTHY HARTWIG :: OAK FOREST WARRIORS",
        "TIMOTHY WILLIAMS :: HARVEY PARK TWISTERS :: 1",
    ],
    135: [
        "AARON SHADAB :: ELGIN GRAPPLERS",
        "BEN MENA :: HARLEM SCHOOL DISTRICT 122 WC",
        "BOB HORN :: ROCKET WC",
        "BRIAN KOZAK :: HINSDALE RED DEVIL WC",
        "DAN WEBER :: ADDAMS JH WC :: 1",
        "DAVID POTTER :: ST. CHARLES WC DISTRICT 303 :: 5",
        "JASON SOSNOWSKI :: ADDISON / INDIAN TRAIL ANIMALS",
        "JEFF RIEGELEIN :: CROSSFACE WC",
        "JOE SCOTT :: GRANITE CITY WC COOLIDGE :: 4",
        "JUSTIN FRIS :: LITTLE CELTIC WC",
        "KENNY HENZE :: LIL REAPER WRESTLING",
        "KEVIN SUCHOCKI :: VITTUM CATS",
        "KYLE GREENSTEIN :: MEAD JH WC",
        "MATT ANDERSON :: EDWARDSVILLE",
        "MATTHEW TERRELL :: BISMARK-HENNING WC",
        "NATHAN SKELTON :: BETHALTO / JR. HIGH",
        "NICK WHITMER :: GIBSON CITY YOUTH",
        "ROBERT MELGOZA :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "SETH SOUZA :: INDIAN PRAIRIE PIONEERS",
        "STEVEN OLIVIERO :: GIBSON CITY YOUTH",
        "STEWART BURCHFIELD :: EAGLE WC :: 2",
        "THOMAS DIIULIO :: JORDAN WRESTLING :: 6",
        "TOM CIEZKI :: MUSTANG WC :: 3",
        "TOM GROSSMAN :: TINLEY PARK BULLDOGS",
    ],
    144: [
        "ANDY BALL :: MACOMB KIDS",
        "ANTHONY SHEWMAKER :: INDIAN PRAIRIE PIONEERS",
        "ANTHONY VASCONEZ :: MEAD JH WC",
        "ARMANDO CAZARES :: OLSON JR. HIGH",
        "BRIAN KEANE :: VITTUM CATS",
        "CORY CREGERR :: JORDAN WRESTLING :: 3",
        "DEREK BURCHAM :: DECATUR WC",
        "HANK STOUT :: VANDALIA JR. WC",
        "JASON BONILLA :: ADDAMS JH WC",
        "JASON BREEN :: ANTIOCH UPPER GRADE :: 1",
        "JASON ORLOS :: RICH WRESTLING",
        "JEREMY SEURING :: PANTHER CUB WC",
        "JOEL MUNRO :: EDWARDSVILLE",
        "JOHN PARISE :: LITTLE CELTIC WC",
        "KEN SPRAGUE :: URBANA KIDS WC",
        "MATT ANDRIANO :: TRAILBLAZER WC :: 2",
        "ROBERT GOLDEN :: BISMARK-HENNING WC",
        "RUSSELL ALLEN :: FALCON WC",
        "RYAN HITE :: JOLIET BOYS CLUB COBRAS",
        "SCOTT BERGE :: NEWMAN BLUE DEVILS :: 6",
        "THOMAS RIGGINS :: ALTON-ROXANA WC",
        "TONY TARANTO :: HICKORY HILLS PD :: 4",
        "TRAVIS KASKI :: WAUKEGAN PD HAWKEYE WC :: 5",
        "WILLIE LESURE :: AURORA J-HAWKS",
    ],
    153: [
        "ANDY MOORE :: ARGENTA-OREANA :: 4",
        "BOB BARTH :: TINLEY PARK BULLDOGS",
        "BOWEN HOPPER :: HARLEM SCHOOL DISTRICT 122 WC",
        "BRAD JACOBSON :: HINSDALE RED DEVIL WC",
        "CHAD MILLER :: WHEATON-WARRENVILLE",
        "CHARLES DYXIN :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "CHRIS HENSON :: PONTIAC WC",
        "ERIC RIGGI :: OAK FOREST WARRIORS",
        "GEO BROWN :: ELMHURST JR. DUKES :: 5",
        "JEREMY MARTIN :: TRAILBLAZER WC",
        "JIM WATKINS :: GRANITE CITY WC GRISBY",
        "JOHN LOCKHART :: HOOPESTON-EAST LYNN JH",
        "JOSE DELTORO :: CROSSFACE WC",
        "KEVIN BRIDGES :: EDWARDSVILLE",
        "KEVIN KEMPHER :: GENESEO WC",
        "MATT MOYNIHAN :: ARLINGTON CARDINALS WC :: 2",
        "MATTHEW STACH :: MEAD JH WC",
        "PHILP POWELL :: EISENHOWER JH :: 6",
        "RANDY ANDERSON :: CRESTWOOD COLTS :: 1",
        "RODNEY JOHNSON :: KNIGHT WC",
        "RON NOWAK :: BRIDGEVIEW PD",
        "SCOTT CLINE :: METAMORA KIDS WC",
        "SCOTT HAMPTON :: YORKVILLE WC :: 3",
        "TOBY ADAMS :: W.F. THUNDERBIRD",
    ],
    163: [
        "AARON VALLEY :: ST. CHARLES WC DISTRICT 303 :: 1",
        "ADAM ROSILLO :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "ARMOND DAVIS :: MASON SCHOOL PLAYGROUND :: 3",
        "BRANDON COLE :: BELVIDERE YMCA BANDITS",
        "BRIAN MOORE :: DAKOTA WC",
        "CHAD ADAMS :: BISMARK-HENNING WC",
        "CHAD MARTIN :: HARLEM SCHOOL DISTRICT 122 WC",
        "CHRIS THACKER :: BELLEVILLE LITTLE DEVILS",
        "DAN KIM :: MEAD JH WC",
        "ERIC CLARY :: TIGERTOWN TANGLERS",
        "JAMES CURRY :: UNITY YOUTH WC",
        "JESSE BEESON :: DECATUR WC",
        "JOE GRIPPO :: ST. TARCISSUS RAIDERS :: 6",
        "JOHN HEATER :: EDWARDSVILLE",
        "JOHN RUIZ :: ST. BARNABAS / CHRIST THE KING :: 4",
        "JOHN TAYLOR :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "JOSEPH TERRY :: PANTHER WC",
        "LEWIS SCOTT :: NEIGHBORHOODD HOUSE RAZORBACKS",
        "LOUIE SPONSEL :: PALATINE CHARGERS :: 5",
        "MICHAEL O GRADNEY :: LOCKPORT GRAPPLERS WC",
        "RICHARD ARRINGTON :: W.F. THUNDERBIRD",
        "TOBY ROMLYSON :: MIDWEST CENTRAL WC",
        "WARD CAMER :: MUSTANG WC",
        "WES INMAN :: TRAILBLAZER WC :: 2",
    ],
    173: [
        "ANDY BRISCQE :: DECATUR WC",
        "DANIEL CAREY :: DOLTON PARK FALCONS",
        "DAVID DRAKE :: BLUE CREW ROCKETS",
        "GARRET ANDERSON :: MURPHYSBORO JH",
        "JACOB MANNING :: ARGENTA-OREANA",
        "JASON HOLLENDONER :: TINLEY PARK BULLDOGS :: 4",
        "JASON MAYNARD :: LAN-OAK PD LITTLE REBELS",
        "JASON NAPE :: CRESTWOOD COLTS",
        "JASON ROSILLO :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "JOHN JANEK :: GRANITE CITY WC COOLIDGE :: 3",
        "JOHN MAILLET :: DOWNERS GROVE COUGARS",
        "JOHNNY KNIGHT :: MACOMB KIDS :: 6",
        "JOSH CRIPPIN :: BISMARK-HENNING WC",
        "KURT PARKER :: ADDAMS JH WC",
        "LUIS ARREDONDO :: BLACKHAWK WC :: 2",
        "MARK RATLIFF :: EDWARDSVILLE",
        "MATT CASELLA :: LIONS WC :: 5",
        "MICHAEL CELEKETIC :: ROCHELLE AREA WC",
        "MICHAEL JOHANSEN :: HARVARD WC",
        "MIKE MORRISON :: TRAILBLAZER WC",
        "RYAN POTTRATZ :: DAKOTA WC",
        "STEVE LONES :: MT. ZION WC",
        "TERRY GRIFFIS :: ROCKFORD WC :: 1",
        "TIM STARBUCK :: MACOMB KIDS",
    ],
    185: [
        "ADAM DETMERS :: MT. ZION WC",
        "BOB REESE :: ROCKFORD WC",
        "BOB ZINK :: IRISH CADET WC :: 6",
        "BRANDON KEEP :: DAKOTA WC :: 2",
        "CASEY JONES :: EL PASO WC",
        "CHRIS ROWELL :: VITTUM CATS :: 1",
        "DAVID CRUZ :: AURORA J-HAWKS",
        "HERIBERTO FLORES :: CORKERY COUGARS",
        "JERRY KRAY :: LEMONT WC",
        "JESSE PIERCE :: ADDISON / INDIAN TRAIL ANIMALS",
        "JIM FERGUSON :: MORTON YOUTH WC",
        "JOSHUA CARTER :: WARHAWK WC",
        "KOREY REID :: CHARGER KIDS WC",
        "LONNIE NUNLEY :: NEIGHBORHOODD HOUSE RAZORBACKS",
        "MATT MCNICHOLAS :: BRONCO WC",
        "MICHAEL HARRIS :: ST. BARNABAS / CHRIST THE KING",
        "NATHAN LABELLE :: OLSON JR. HIGH :: 5",
        "PETER DIGANGI :: BRIDGEVIEW PD",
        "ROBBIE BURGENER :: GRANITE CITY WC COOLIDGE :: 4",
        "ROSS WILLIAMS :: VILLA-LOMBARD COUGARS :: 3",
        "SHANE HUBBARD :: WESTVILLE JR. HIGH",
        "STEVE MEYERS :: ANTIOCH UPPER GRADE",
        "TONY ENGLESE :: MEAD JH WC",
        "TROY MARKLEY :: SPARTANS",
    ],
    275: [
        "ANDRE CALDWELL :: WARHAWK WC",
        "COREY LOGEMANN :: PANTHER CUB WC",
        "DAN KORSO :: MUSTANG WC",
        "DANIEL STIEFEL :: YORKVILLE WC",
        "GABE BARKER :: HAVANA WC",
        "GEORGE TOVAR :: CORKERY COUGARS",
        "JAMES HAGLEY :: BISMARK-HENNING WC",
        "JASON RAYMER :: BETHALTO / JR. HIGH",
        "JEFF WINIARSKI :: TRAILBLAZER WC :: 6",
        "JEREMY WINSTEAD :: BOYS & GIRLS CLUB PEKIN",
        "JOHN SMITH :: PLAINFIELD INDIAN TRAIL WRESTLING",
        "LEWIS LANG :: RICH WRESTLING :: 4",
        "LOUIS HILL :: ROCKFORD WC",
        "MARCO ORDAZ :: AURORA J-HAWKS :: 5",
        "MARTIN GONZALEZ :: BRADLEY-BOURBONAIS YOUTH",
        "MATT HENKEL :: ANTIOCH UPPER GRADE",
        "MOSES KNAPP :: DECATUR WC :: 1",
        "RICARDO RODRIGUEZ :: CHILLICOTHE WRESTLING",
        "ROBERT WALKER :: GORDON TECH RAMS WC",
        "RYAN BELL :: WARHAWK WC",
        "RYAN STOLCIS :: EDWARDSVILLE",
        "RYANY EDWARDS :: MURPHYSBORO JH",
        "STEVE OLIEH :: TRAILBLAZER WC :: 3",
        "TROY KIER :: MT. ZION WC :: 2",
    ],
}
_SENIOR_PLACERS: dict[int, list[bracket_utils.Placer]] = {
    60: [
        bracket_utils.Placer(name="JEREMY HAYES", team="MORTON YOUTH WC"),
        bracket_utils.Placer(name="STEVE RODGERS", team="CROSSFACE WC"),
        bracket_utils.Placer(name="PAUL AUGLE", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="NICHOLAS CIRRINCIONE", team="VILLA-LOMBARD COUGARS"),
        bracket_utils.Placer(name="DANNY MARTINEZ", team="BELVIDERE YMCA BANDITS"),
        bracket_utils.Placer(name="ANDREW PENNA", team="CRYSTAL LAKE WIZARDS"),
    ],
    64: [
        bracket_utils.Placer(name="AMADOR ESTRADA", team="ROUND LAKE SPARTAN WC"),
        bracket_utils.Placer(name="BLAKE VERMILLION", team="CRYSTAL LAKE WIZARDS"),
        bracket_utils.Placer(name="JEFF ANDERSON", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="LONNIE CORBIN", team="PANTHER WRESTLING"),
        bracket_utils.Placer(name="STEVEN BRYANT", team="BETHALTO JR. HIGH"),
        bracket_utils.Placer(name="SEAN CHINSKI", team="LITTLE CELTIC WC"),
    ],
    68: [
        bracket_utils.Placer(name="KYLE ONEILL", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="ANTHONY OPIOLA", team="DOLTON PARK FALCONS"),
        bracket_utils.Placer(name="SCOTT KENNY", team="ORLAND PARK PIONEERS"),
        bracket_utils.Placer(name="ADAM WASON", team="TIGERTOWN TANGLERS"),
        bracket_utils.Placer(name="MARK MANKOWSKI", team="HICKORY HILLS PD"),
        bracket_utils.Placer(name="TONY DOUGHTY", team="FRANKLIN PARK RAIDERS"),
    ],
    72: [
        bracket_utils.Placer(name="LEONARD BOWENS", team="HARVEY PARK TWISTERS"),
        bracket_utils.Placer(name="NICHOLAS BINGHEIM", team="BETHALTO JR. HIGH"),
        bracket_utils.Placer(name="DAVID STOLTZ", team="ARLINGTON CARDINALS WC"),
        bracket_utils.Placer(name="PAUL GARBIS", team="TRAILBLAZER WC"),
        bracket_utils.Placer(name="BRADLEE VERMILLION", team="CRYSTAL LAKE WIZARDS"),
        bracket_utils.Placer(name="SAM SCHAEFER", team="WHEATON WARRENVILLE"),
    ],
    77: [
        bracket_utils.Placer(
            name="MATTHEW GOLDSTEIN", team="HIGHLAND PK LITTLE GIANTS"
        ),
        bracket_utils.Placer(name="TODD COMBES", team="DOLTON PARK FALCONS"),
        bracket_utils.Placer(name="DAVID DOUGLAS", team="HARVEY PARK TWISTERS"),
        bracket_utils.Placer(name="BEN BLACK", team="HINSDALE RED DEVIL WC"),
        bracket_utils.Placer(name="JOEL HOWARD", team="NAPERVILE PATRIOTS"),
        bracket_utils.Placer(name="CRAIG COLLINS", team="CALUMET MEMORIAL PD"),
    ],
    82: [
        bracket_utils.Placer(name="JIM ABERLE", team="ROUND LAKE SPARTAN WC"),
        bracket_utils.Placer(name="MILTON BLAKELY", team="HARVEY PARK TWISTERS"),
        bracket_utils.Placer(name="LAWAN GRAY", team="PIRATES"),
        bracket_utils.Placer(name="JEREMY LARSEN", team="OSWEGO COUGARS"),
        bracket_utils.Placer(name="KEVIN RANDOLPH", team="OAK FOREST WARBIORS"),
        bracket_utils.Placer(name="BRIAN COMSTOCK", team="ST. CHARLES WC"),
    ],
    87: [
        bracket_utils.Placer(name="ANDY DOUGLAS", team="ADDAMS JH WC"),
        bracket_utils.Placer(name="MICHAEL BONDI", team="DUNDEE HIGHLANDERS WC"),
        bracket_utils.Placer(name="LUKE EWANIO", team="ROSEMONT COBRAS"),
        bracket_utils.Placer(name="IAN PENZATO", team="VILLA-LOMBARD"),
        bracket_utils.Placer(name="ALAN WILSON", team="CRYSTAL LAKE WIZARDS"),
        bracket_utils.Placer(name="DOMINIC CICCONE", team="TINLEY PARK BULLDOGS"),
    ],
    93: [
        bracket_utils.Placer(name="ALAN CARTWRIGHT", team="WARHAWK WC"),
        bracket_utils.Placer(name="GRIFF POWELL", team="ARLINGTON CARDINALS WC"),
        bracket_utils.Placer(name="FRANCISCO BERMUDEZ", team="LOCKPORT GRAPPLERS"),
        bracket_utils.Placer(name="BRYAN GIBBONS", team="KNIGHT WC"),
        bracket_utils.Placer(name="TRAVIS ZIMMERMAN", team="BETHALTO JR. HIGH"),
        bracket_utils.Placer(name="DAN DOYLE", team="DOLTON PARK FALCONS"),
    ],
    99: [
        bracket_utils.Placer(name="TONY DAVIS", team="HARVEY PARK TWISTERS"),
        bracket_utils.Placer(name="KEVIN SIPP", team="ADDAMS JH WC"),
        bracket_utils.Placer(name="LEO DELATORRE", team="VILLA-LOMBARD COUGARS"),
        bracket_utils.Placer(name="MATHEW GUILFOYLE", team="PLAINFIELD I.T."),
        bracket_utils.Placer(name="BEN KING", team="LIONS WC"),
        bracket_utils.Placer(name="BART BROSNAN", team="ST. BARNABAS/CHRIST THE KING"),
    ],
    105: [
        bracket_utils.Placer(name="REGINALD WRIGHT", team="PIRATES"),
        bracket_utils.Placer(name="KEVIN MILLIGAN", team="VILLA-LOMBARD COUGARS"),
        bracket_utils.Placer(name="RYAN DUGGAN", team="ST. TAR'S RAIDERS"),
        bracket_utils.Placer(name="TIM GLOVER", team="MORTON YOUTH WC"),
        bracket_utils.Placer(name="RYAN POZEN", team="KNIGHT WC"),
        bracket_utils.Placer(name="FRANSISCO VILLARREAL", team="VILLA-LOMBARD COUGARS"),
    ],
    112: [
        bracket_utils.Placer(name="JASON CHRISTESON", team="BETHALTO JR. HIGH"),
        bracket_utils.Placer(name="AARON EHLE", team="HARLEM SD. 122"),
        bracket_utils.Placer(name="STEVE LEVEREZ", team="MUSTANG WC"),
        bracket_utils.Placer(name="KEVIN NEVILLS", team="ADDAMS JH WC"),
        bracket_utils.Placer(name="ROY KING", team="JOLIET BOYS CLUB COBRAS"),
        bracket_utils.Placer(name="MIKE KANKE", team="GENESEO WC"),
    ],
    119: [
        bracket_utils.Placer(name="GREG VOEGTLE", team="BELLEVILLE LITTLE DEVILS"),
        bracket_utils.Placer(name="LASHAUN JACKSON", team="HARVEY PARK TWISTERS"),
        bracket_utils.Placer(name="CODY ABBOTT", team="URBANA KIDS WC"),
        bracket_utils.Placer(name="ROBERTO RODRIQUEZ", team="HARLEM SD. 122"),
        bracket_utils.Placer(name="PETE CURRIE", team="VILLA-LOMBARD COUGARS"),
        bracket_utils.Placer(name="TIM GRAY", team="PONTIAC WC"),
    ],
    127: [
        bracket_utils.Placer(name="TIMOTHY WILLIAMS", team="HARVEY PARK TWISTERS"),
        bracket_utils.Placer(name="DEREK STACHURA", team="MORTON YOUTH"),
        bracket_utils.Placer(name="CHAD ORR", team="RIVERDALE JH WC"),
        bracket_utils.Placer(name="JEFF EVANS", team="BETHALTO JR. HIGH"),
        bracket_utils.Placer(name="JEFF ESTRADA", team="GCWC GRIGSBY"),
        bracket_utils.Placer(name="JOHN VENNE", team="GCWC COOLIDGE"),
    ],
    135: [
        bracket_utils.Placer(name="DAN WEBER", team="ADDAMS JH WC"),
        bracket_utils.Placer(name="STEWART BURCHFIELD", team="EAGLE WC"),
        bracket_utils.Placer(name="TOM CIEZKI", team="MUSTANG WC"),
        bracket_utils.Placer(name="JOE SCOTT", team="GCWC COOLIDGE"),
        bracket_utils.Placer(name="DAVID POTTER", team="ST. CHARLES WC DIST 303"),
        bracket_utils.Placer(name="THOMAS DIIULIO", team="JORDAN WRESTLING"),
    ],
    144: [
        bracket_utils.Placer(name="JASON BREEN", team="ANTIOCH UPPER GRADE"),
        bracket_utils.Placer(name="MATT ANDRIANO", team="TRAILBLAZER WC"),
        bracket_utils.Placer(name="CORY CREGER", team="JORDAN WRESTLING"),
        bracket_utils.Placer(name="TONY TARANTO", team="HICKORY HILLS PD"),
        bracket_utils.Placer(name="TRAVIS KASKI", team="WAUKEGAN PD HAWKEYE WC"),
        bracket_utils.Placer(name="SCOTT BERGE", team="NEWMAN BLUE DEVILS"),
    ],
    153: [
        bracket_utils.Placer(name="RANDY ANDERSON", team="CRESTWOOD COLTS"),
        bracket_utils.Placer(name="MATT MOYNIHAN", team="ARLINGTON CARDINALS WC"),
        bracket_utils.Placer(name="SCOTT HAMPTON", team="YORKVILLE WC"),
        bracket_utils.Placer(name="ANDY MOORE", team="ARGENTA OREANA"),
        bracket_utils.Placer(name="GEO BROWN", team="ELMHURST JR. DUKES"),
        bracket_utils.Placer(name="PHILIP POWELL", team="EISENHOWER JH"),
    ],
    163: [
        bracket_utils.Placer(name="AARON VALLEY", team="ST. CHARLES WC DIST 303"),
        bracket_utils.Placer(name="WES INMAN", team="TRAILBLAZERS WC"),
        bracket_utils.Placer(name="ARMOND DAVIS", team="MASON SCHOOL PLAYGROUND"),
        bracket_utils.Placer(name="JOHN RUIZ", team="ST. BARNABAS/CHRIST THE KING"),
        bracket_utils.Placer(name="LOUIE SPONSEL", team="PALATINE CHARGERS"),
        bracket_utils.Placer(name="JOE GRIPPO", team="ST. TAR'S RAIDERS"),
    ],
    173: [
        bracket_utils.Placer(name="TERRY GRIFFIS", team="ROCKFORD WC"),
        bracket_utils.Placer(name="LUIS ARREDONDO", team="BLACKHAWK WC"),
        bracket_utils.Placer(name="JOHN JANEK", team="GCWC COOLIDGE"),
        bracket_utils.Placer(name="JASON HOLLENDONER", team="TINLEY PARK BULLDOGS"),
        bracket_utils.Placer(name="MATT CASELLA", team="LIONS WC"),
        bracket_utils.Placer(name="JOHNNY KNIGHT", team="MACOMB KIDS"),
    ],
    185: [
        bracket_utils.Placer(name="CHRIS ROWELL", team="VITTUM CATS"),
        bracket_utils.Placer(name="BRANDON KEEP", team="DAKOTA WC"),
        bracket_utils.Placer(name="ROSS WILLIAMS", team="VILLA-LOMBARD COUGARS"),
        bracket_utils.Placer(name="ROBBIE BURGENER", team="GCWC COOLIDGE"),
        bracket_utils.Placer(name="NATHAN LABELLE", team="OLSON JR. HIGH"),
        bracket_utils.Placer(name="BOB ZINK", team="IRISH CADET WC"),
    ],
    275: [
        bracket_utils.Placer(name="MOSES KNAPP", team="DECATUR WC"),
        bracket_utils.Placer(name="TROY KIER", team="MT. ZION WC"),
        bracket_utils.Placer(name="STEVE OLEH", team="TRAILBLAZER WC"),
        bracket_utils.Placer(name="LEWIS LANG", team="RICH WRESTLING"),
        bracket_utils.Placer(name="MARCO ORDAZ", team="AURORA J-HAWKS"),
        bracket_utils.Placer(name="JEFF WINIARSKI", team="TRAILBLAZER WC"),
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "HARVEY TWISTERS": 184.0,
    "VILLA-LOMBARD COUGARS": 137.0,
    "BETHALTO JR. HIGH": 125.0,
    "TRAILBLAZER WC": 124.0,
    "TINLEY PARK BULLDOGS": 112.0,
    "ADDAMS JR. HIGH": 103.5,
    "MUSTANG WC": 71.0,
    "MORTON YOUTH WC": 67.5,
    "ST. CHARLES WC": 67.0,
    "ROUND LAKE SPARTAN WC": 66.5,
    "ROSEMONT COBRAS": 65.0,
    "ARLINGTON CARDINALS": 64.5,
    "DOLTON PARK FALCONS": 64.5,
    "GRANITE CITY COOLIDGE": 64.0,
    "HARLEM SCHOOL DIST 122": 61.0,
    "CRYSTAL LAKE WIZARDS": 59.0,
    "PIRATES": 49.0,
    "MEAD JR HIGH WC": 47.5,
    "VITTUM CATS": 47.5,
    "ORLAND PARK PIONEERS": 44.5,
    "WARHAWK WC": 43.5,
    "ANTIOCH UPPER GRADE": 42.0,
    "HICKORY HILLS PK. DIST": 42.0,
    "ST. BARNABAS/CHRIST THE KING": 40.0,
    "ROCKFORD WC": 39.0,
}


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    weight_classes: list[bracket_utils.WeightClass] = []
    for weight, placers in _SENIOR_PLACERS.items():
        weight_class = bracket_utils.create_weight_class_from_placers(
            "senior", weight, placers, _SENIOR_TEAM_REPLACE
        )
        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(HERE / "extracted.1992.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
