# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

"""
The competitor list (from scans from Terry Weber) is contained below.

Note in 1979 there were not 24 qualifiers. Instead it was an "extended" 16 man
bracket. 14 normal spots and then 2 pigtails in random places for a total of
18 wrestlers per bracket.
"""

import pathlib

import bracket_utils

_HERE = pathlib.Path(__file__).resolve().parent
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    60: [
        "Bam Bam Pustelnik :: East Moline",
        "Mike Urwin :: Orland Park",
        None,
        "Phil Gray :: Naperville :: 1",
        "Jeff Scott :: Decatur",
        None,
        "Ed Cantrell :: Belleville",
        "Jeff Brannan :: Jack London",
        None,
        "Mark Becker :: Panther W.C.",
        "Jim Throw :: Dolton",
        "Mike Chihoski :: Rosemont Cobras",
        "Mike LaMonica :: Orland Park",
        "Darren Brown :: Rock Falls",
        "Nino Chiapetta :: Bobcats",
        "Chuck Reed :: Pekin B.C.",
        "John Walter :: Indian Trail / Plainfield",
        None,
        "Scott Sutton :: Shady Lane W.C.",
        "John Churchill :: Belleville",
        None,
        "Dan Evensen :: Chicago Ridge",
        "Bill Lamanna :: Park Ridge",
        None,
    ],
    65: [
        "Welsh :: Coolidge",
        "Mike Witkowski :: Indian Trail / Plainfield",
        None,
        "Lance Pero :: Glenwood",
        "Walter Scott :: Decatur",
        "Mike Pfingston :: Tinley Park",
        "Tim Allgire :: Belleville",
        "Johnson :: Eisenhower",
        None,
        "Dan Muehl :: Harvard W.C.",
        "Troy Protsman :: McDonough County YMCA",
        None,
        "Ed Moholick :: Indian Trail / Plainfield",
        "Kirk Jurinek :: Rosemont Cobras",
        None,
        "Robbie Porter :: Mahomet Seymour",
        "Mike O'Brien :: Chicago Ridge :: 1",
        None,
        "Spacone :: Lincoln Cicero",
        "Eric Walker :: Carbondale",
        "Dean Souder :: Rich Township",
        "John Loos :: Park Ridge",
        "Kollin Stagnito :: Lake Zurich W.C.",
        None,
    ],
    70: [
        "Chris Tiemeier :: East Moline",
        "Brad Johnson :: Bloomington Jr. High",
        None,
        "Tim Meagher :: Joliet YMCA :: 1",
        "Bob Calhoun :: Belleville",
        None,
        "Joe Lind :: Pontiac",
        "Joe Bochenski :: Panther W.C.",
        None,
        "Craig DeBevec :: Oak Forest",
        "Jeff Jensen :: Shady Lane W.C.",
        "Phillip Chihoski :: Rosemont Cobras",
        "Mike Hoover :: Bismarck",
        "Joe Williams :: Dixon W.C.",
        None,
        "Collin Davis :: Prather",
        "Dwane Maue :: Mokena",
        None,
        "Jeff Pahlos :: Lake Zurich W.C.",
        "Dorich :: Lincoln Cicero",
        "Craig Sterr :: Hufford",
        "Kevin Powers :: Franklin Pk Raiders",
        "Tom Carroll :: St. Barnabas",
        None,
    ],
    75: [
        "Steve Glawe :: Sycamore",
        "Dave Berg :: Lake Zurich W.C.",
        "Kip Kristoff :: Alton W.C.",
        "Fredrick Ferguson :: Peter Claver",
        "Jon Popp :: Panther W.C.",
        None,
        "Chuck McCann :: Indian Trail / Plainfield",
        "Laparker Everett :: St. Phillips",
        None,
        "Eric Mueller :: Champaign W.C.",
        "Rich Ryser :: Oak Park",
        None,
        "Rob Millazzo :: Roxana Jr. High :: 1",
        "Roger Shelton :: Dundee Highlanders",
        None,
        "Joe Chiapetta :: Bobcats",
        "Navel Woods :: Washington Jr. High",
        None,
        "Joe White :: Palos South",
        "Dave Dupree :: Indian Trail / Plainfield",
        None,
        "Marvin Robackowski :: Rosemont Cobras",
        "Greg Durst :: Mahomet Seymour",
        "Dave Doulghenbauch :: Belvidere",
    ],
    80: [
        "Scott Sisler :: Rosette Middle School",
        "Peter Tarzygnat :: Franklin Pk Raiders",
        "Reid Diehl :: Naperville",
        "Chris Scott :: Joliet YMCA :: 1",
        "Jeff Nieze :: Antioch Upper Grade",
        None,
        "Mike Neiner :: Belleville",
        "Denning :: Eisenhower",
        None,
        "John Suter :: Springfield W.C.",
        "Dave Elkin :: Palos South",
        None,
        "Terry Higgins :: Mat Burns",
        "Brad Larson :: Huntley Middle School",
        None,
        "Todd Stanton :: Deerpath",
        "Chris Paynic :: Roxana Jr. High",
        "Scott Zayner :: Rich Township",
        "Phil Daniels :: Troy",
        "Flanagan :: Lincoln Cicero",
        None,
        "Mike Muilli :: Oak Forest",
        "Gary Campbell :: Mahomet Seymour",
        None,
    ],
    85: [
        "Tim Weeks :: Rosette Middle School",
        "Steve Zehr :: Mahomet Seymour",
        None,
        "Joe Zaccone :: Hickory Hills",
        "Ralf Diehl :: Naperville",
        None,
        "Mike Hruska :: West Leyden",
        "Randy Womack :: Quincy",
        None,
        "Carl Hildinger :: Lake Villa",
        "Ken Sroka :: Panther W.C.",
        "Hal Olofsson :: St. Barnabas",
        "Pierre :: Wheaton Pk Dist.",
        "Jeff Meier :: Huntley Middle School",
        "Scoh Mitchell :: Decatur",
        "Nick Quas :: Indian Trail / Plainfield :: 1",
        "Mike Terrell :: Rich Township",
        None,
        "Mike Bellipanni :: Grigsby",
        "Ralph Milito :: Park Ridge",
        None,
        "Ted Howlett :: Tinley Park",
        "Steve Petersen :: Jack London",
        None,
    ],
    90: [
        "Bill Herrmann :: Huntley Middle School",
        "Dave Arndt :: Tinley Park",
        None,
        "Vincent Criscione :: Joliet YMCA",
        "Jamie Litchfield :: Troy",
        None,
        "Mike Arnold :: Urbana",
        "Steve Schmidt :: Edwardsville",
        None,
        "Jim Schultz :: Panther W.C.",
        "Dave Sherman :: Apollo Jr. High",
        "Todd Jenkins :: Lake Villa",
        "Greg Flores :: Chicago Ridge",
        "Kerry Flynn :: Belvidere",
        None,
        "Bob Gonnella :: West Leyden",
        "Pat Kohl :: Gower",
        "Mark Olsen :: Orland Park",
        "Scott Grammer :: Carbondale",
        "Joe Landis :: Lincoln Jr. High",
        None,
        "Tad DeRousse :: Antioch Upper Grade",
        "Keith Healy :: Panther W.C. :: 1",
        None,
    ],
    95: [
        "Jody Flynn :: Belvidere",
        "Todd Kunz :: Rich Township",
        "Steve Case :: Antioch Upper Grade",
        "Dan Residori :: Coal City",
        "Danny Marcinac :: West Leyden",
        None,
        "Doug Dennison :: Hoopeston E. Lynn",
        "Carlson :: West Chicago",
        None,
        "Bruce Widel :: Prather",
        "Pat Nolan :: Chicago Ridge",
        None,
        "Korry Stagnito :: Lake Zurich W.C.",
        "Sean Mann :: Joliet YMCA",
        None,
        "Scott Fitzgibbons :: Franklin Pk Raiders",
        "John Rajich :: Indian Trail / Plainfield",
        None,
        "Jerry Blaney :: Panther W.C. :: 1",
        "Mike Patting :: Jordon Jr. High",
        "Mark Mannen :: Urbana",
        "John Bulf :: Dolton",
        "Rob Mauser :: Roxana Jr. High",
        None,
    ],
    100: [
        "Todd Conroy :: Joliet YMCA",
        "Don Butler :: Rosette Middle School",
        None,
        "Jim Henderson :: Hufford",
        "Charlie Sherertz :: Alton W.C.",
        "Mah Fassan :: St. Barnabas",
        "Dan Smalley :: Bismarck",
        "Tim Curtis :: Antioch Upper Grade",
        None,
        "Knez :: Eisenhower",
        "Tom Klescyk :: Rosemont Cobras",
        None,
        "Fitzgerald :: Oak Lawn",
        "Bryant Capodice :: Mokena :: 1",
        None,
        "Matt Lemming :: Carbondale",
        "Schilling :: Vittum Vikings",
        "Kevin Craggs :: Gower",
        "Tony Rivoppo :: Cooper",
        "Darrin Pierce :: Hoopeston E. Lynn",
        None,
        "Robert Watters :: River Trails",
        "Bill Schepler :: Sycamore",
        None,
    ],
    105: [
        "Welch :: Coolidge",
        "Bill Collins :: Hickory Hills",
        None,
        "Mike Friddle :: Coal City",
        "Todd Spraggs :: Pekin B.C.",
        None,
        "Mark Gowdy :: Prather",
        "John Corrigan :: Shady Lane W.C.",
        None,
        "Jacobs :: Lincoln Cicero",
        "Brian Porter :: Oak Forest",
        "Dave Paske :: West Leyden",
        "Tom Hoch :: Orland Park",
        "Paul Hammett :: Huntley Middle School",
        "Cothron :: West Chicago",
        "Terry Thomason :: Mattoon W.C.",
        "Rene Robles :: Troy",
        None,
        "John Oelkers :: Antioch Upper Grade",
        "Kent Patterson :: Grigsby",
        None,
        "Tony Evensen :: Chicago Ridge :: 1",
        "Wayne Bohenek :: West Leyden",
        None,
    ],
    111: [
        "John Doak :: Jordon Jr. High",
        "Mike Oshiro :: Jane Adams",
        None,
        "Rick Pedigo :: Mokena",
        "Greg Winchester :: Mattoon W.C.",
        "Scott Barczi :: Palos South",
        "Bob Unger :: Grigsby",
        "Rodriguez :: Indian Trail / Addison",
        None,
        "Steve Schrey :: Lundahl Jr. High",
        "Fernado Malabehar :: Mat Burns",
        None,
        "Darren Herbst :: Indian Trail / Plainfield",
        "Jerry Dobson :: Sycamore",
        None,
        "Carlos Ortiz :: Bloomington Jr. High",
        "Denton :: Hazel Crest",
        None,
        "Jim Popp :: Panther W.C.",
        "Tim Brown :: Carbondale",
        "Steve Myers :: Hickory Hills",
        "Bob Guerrieri :: West Leyden :: 1",
        "Mark Nowak :: Jack London",
        None,
    ],
    118: [
        "Ric Petruchius :: Sycamore",
        "Tom Vielek :: Decatur",
        None,
        "Dean Rodgers :: Huth Jr. High",
        "John Frangovils :: Prather",
        None,
        "Rich Henderson :: Indian Trail / Plainfield :: 1",
        "Taylor :: West Chicago",
        None,
        "Kevin Jarchow :: Oak Forest",
        "Jim Rosman :: Palatine P.D.",
        "Mike Burke :: Mat Burns",
        "Randy Evans :: Bloomington Jr. High",
        "John Wetherell :: Jordon Jr. High",
        None,
        "Adam Phavorachit :: Carbondale",
        "Keith Rumchuck :: Joliet YMCA",
        None,
        "Bob Ratajczyk :: Lake Villa",
        "Lullo :: Indian Trail / Addison",
        "Bob Atkinson :: Troy",
        "Tony Cortese :: Mat Burns",
        "Rodger Mayer :: King Upper Grade",
        None,
    ],
    125: [
        "Dave Loos :: Belvidere",
        "Andy Lehn :: Antioch Upper Grade",
        "Greg Mihalich :: Edwardsville",
        "John Terrell :: Rich Township",
        "Lavenske :: Lincoln Cicero",
        None,
        "Chris Gresham :: Stephens Middle School",
        "Dion Stewart :: Tinley Park",
        None,
        "Charles Robb :: Bloomington Jr. High",
        "John Egan :: St. Tarcissus",
        None,
        "Jeff Nichols :: Alton W.C.",
        "Mike Rowden :: Shady Lane W.C.",
        None,
        "Hernandez :: West Chicago",
        "Mike Flannery :: Hickory Hills",
        None,
        "Tim Cocco :: Chicago Ridge :: 1",
        "Bob Davies :: Naperville",
        None,
        "Angelo Campanella :: Apollo Jr. High",
        "Joe Hoiness :: Rosette Middle School",
        "Kane Robertson :: Springfield S.E.",
    ],
    135: [
        "Williams :: Coolidge",
        "Dana Anastasia :: Champaign W.C.",
        "Frank Ostir :: Troy",
        "Reed :: Gompers Jr. High",
        "Dave Alborn :: Dundee Highlanders",
        None,
        "Gary Enquita :: Panther W.C.",
        "Eric Brown :: Edwardsville",
        None,
        "Dick McCormick :: Springfield W.C.",
        "John Connel :: Palos South",
        None,
        "Mike Redden :: Glenview",
        "Shawn Harris :: East Moline",
        None,
        "George Bessette :: Antioch Upper Grade :: 1",
        "Mike Kessler :: Grigsby",
        "James Cotton :: Rich Township",
        "Jeff Goodwin :: Jane Adams",
        "Kallas :: Eisenhower",
        None,
        "Mucenski :: Calumet City",
        "Alegoz Satlimis :: Holmes Jr. High",
        None,
    ],
    145: [
        "Scott Herbert :: Rosette Middle School",
        "John Rodlands :: Springfield W.C.",
        None,
        "Tim Johnson :: Hickory Hills",
        "Connor McCarthy :: Naperville",
        None,
        "Asquini :: Glenview",
        "Frank Edwards :: Grigsby",
        None,
        "Tim Linhart :: Harvard W.C.",
        "Martin :: Westview Hills",
        "Ed Cineda :: St. Barnabas",
        "Little :: Eisenhower",
        "Shawn Wildermuth :: Riverdale",
        "Daron Smith :: Lincoln Jr. High",
        "Ken Johnson :: Ward Middle School",
        "Charles VanGamert :: Rich Township",
        None,
        "Chett McAdams :: Murphysboro",
        "Derek Grandt :: Holmes Jr. High",
        None,
        "Dale Schmidt :: Oak Forest :: 1",
        "Pibor Jung :: Antioch Upper Grade",
        None,
    ],
    155: [
        "Danny Bushaw :: Rock Falls",
        "Bob Clancy :: Mount Greenwood",
        None,
        "Houston :: Washington Jr. High",
        "Larry Parece :: Naperville",
        None,
        "Geese :: Mahomet Seymour",
        "Dave Miller :: Trimpe",
        None,
        "Miller :: Eisenhower",
        "Jeff Sorensen :: Oak Park",
        "Chuck Sherman :: Lundahl Jr. High",
        "Bill Anderson :: Dolton",
        "Gilbert Almanza :: Rock Falls",
        None,
        "Dave Vohaska :: Franklin Pk Raiders :: 1",
        "Guy Pennington :: Indian Trail / Plainfield",
        "Don Miller :: Summit Hill",
        "Bill Zimmer :: Prather",
        "Kip Flairty :: Pekin B.C.",
        None,
        "Bill Carney :: Antioch Upper Grade",
        "Jaskowke :: West Chicago",
        None,
    ],
    170: [
        "Dan Goldsmith :: Lil Reaper W.C.",
        "Scott Scelfo :: Hickory Hills",
        "Joe Fortin :: Lundahl Jr. High",
        "Jim Taylor :: Troy",
        "James Holman :: Oak Park",
        None,
        "Jammie Abbott :: Normal",
        "Gennevali :: Bobcats",
        None,
        "Tracy Bradford :: Edwardsville",
        "Mark Antonietti :: Calumet Pk. Dist.",
        None,
        "Rich Ilmberger :: Big Hollow W.C.",
        "Eric Koeller :: Mat Burns",
        None,
        "Jeff Adams :: Glenwood",
        "Randy Crow :: Bower",
        None,
        "Shemshedini :: West Chicago",
        "Paul Klink :: Sycamore",
        "Jerry Ware :: Springfield S.E.",
        "Rod Martin :: St. Phillips :: 1",
        "John Morris :: Grigsby",
        None,
    ],
    185: [
        "Sefcik :: Gompers Jr. High",
        "Dale Johnson :: East Moline",
        None,
        "Eric Greenup :: Indian Trail / Plainfield",
        "Eric Gunderson :: Prather",
        None,
        "Dennis Stabl :: Champaign W.C. :: 1",
        "Mike Wilson :: Jack London",
        None,
        "King :: West Chicago",
        "Craig Drummond :: Oak Park",
        None,
        None,
        "Mitchell :: Lockport Wrestlers",
        None,
        "Eric Wildgrube :: Edwardsville",
        "Zezulak :: Lombard Jr. Rams",
        "Lou Rinaldi :: Jane Adams",
        "Bob Bruno :: Cooper",
        "Jim Scherbering :: Rantoul",
        None,
        "Ronald Renaud :: River Trails",
        "Rich Spears :: Lil Reaper W.C.",
        None,
    ],
    275: [
        "Ken Taylor :: Huntley Middle School",
        "Ed Lusting :: Rich Township",
        None,
        "Ray Tyree :: Ward Middle School :: 1",  # Bolingbrook
        None,
        None,
        "Davis :: Trimpe",
        "Mike Meinhart :: Lake Zurich W.C.",
        None,
        "Winze :: Lisle",
        "Kevin Goudeau :: Blue Island W.C.",
        "John Phelan :: Oak Park",
        "Mike Webster :: Huth Jr. High",
        "Dave Browning :: Lil Reaper W.C.",
        "Schrock :: Westview Hills",
        "Gill Crutcher :: Bloomington Jr. High",
        "Richard Weaver :: Pontiac",
        None,
        "Marcelino Garcia :: Jack London",
        "Bob Allen :: Prather",
        None,
        "Mike Eperjesi :: Mount Greenwood",
        "Lou Rodriguez :: Mat Burns",
        None,
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "Indian Trail / Plainfield": 146.0,  # PLAINFIELD
    "Joliet YMCA": 119.0,
}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    ("Bam Bam Pustelnik", "East Moline"): bracket_utils.Competitor(
        full_name="Bam Bam Pustelnik",
        first_name="Bam Bam",
        last_name="Pustelnik",
        team_full="East Moline",
    ),
    ("Welsh", "Coolidge"): bracket_utils.Competitor(
        full_name="Welsh",
        first_name="",
        last_name="Welsh",
        team_full="Coolidge",
    ),
    ("Spacone", "Lincoln Cicero"): bracket_utils.Competitor(
        full_name="Spacone",
        first_name="",
        last_name="Spacone",
        team_full="Lincoln Cicero",
    ),
    ("Johnson", "Eisenhower"): bracket_utils.Competitor(
        full_name="Johnson",
        first_name="",
        last_name="Johnson",
        team_full="Eisenhower",
    ),
    ("Dorich", "Lincoln Cicero"): bracket_utils.Competitor(
        full_name="Dorich",
        first_name="",
        last_name="Dorich",
        team_full="Lincoln Cicero",
    ),
    ("Denning", "Eisenhower"): bracket_utils.Competitor(
        full_name="Denning",
        first_name="",
        last_name="Denning",
        team_full="Eisenhower",
    ),
    ("Flanagan", "Lincoln Cicero"): bracket_utils.Competitor(
        full_name="Flanagan",
        first_name="",
        last_name="Flanagan",
        team_full="Lincoln Cicero",
    ),
    ("Pierre", "Wheaton Pk Dist."): bracket_utils.Competitor(
        full_name="Pierre",
        first_name="",
        last_name="Pierre",
        team_full="Wheaton Pk Dist.",
    ),
    ("Carlson", "West Chicago"): bracket_utils.Competitor(
        full_name="Carlson",
        first_name="",
        last_name="Carlson",
        team_full="West Chicago",
    ),
    ("Knez", "Eisenhower"): bracket_utils.Competitor(
        full_name="Knez",
        first_name="",
        last_name="Knez",
        team_full="Eisenhower",
    ),
    ("Fitzgerald", "Oak Lawn"): bracket_utils.Competitor(
        full_name="Fitzgerald",
        first_name="",
        last_name="Fitzgerald",
        team_full="Oak Lawn",
    ),
    ("Schilling", "Vittum Vikings"): bracket_utils.Competitor(
        full_name="Schilling",
        first_name="",
        last_name="Schilling",
        team_full="Vittum Vikings",
    ),
    ("Welch", "Coolidge"): bracket_utils.Competitor(
        full_name="Welch",
        first_name="",
        last_name="Welch",
        team_full="Coolidge",
    ),
    ("Jacobs", "Lincoln Cicero"): bracket_utils.Competitor(
        full_name="Jacobs",
        first_name="",
        last_name="Jacobs",
        team_full="Lincoln Cicero",
    ),
    ("Cothron", "West Chicago"): bracket_utils.Competitor(
        full_name="Cothron",
        first_name="",
        last_name="Cothron",
        team_full="West Chicago",
    ),
    ("Rodriguez", "Indian Trail / Addison"): bracket_utils.Competitor(
        full_name="Rodriguez",
        first_name="",
        last_name="Rodriguez",
        team_full="Indian Trail / Addison",
    ),
    ("Denton", "Hazel Crest"): bracket_utils.Competitor(
        full_name="Denton",
        first_name="",
        last_name="Denton",
        team_full="Hazel Crest",
    ),
    ("Taylor", "West Chicago"): bracket_utils.Competitor(
        full_name="Taylor",
        first_name="",
        last_name="Taylor",
        team_full="West Chicago",
    ),
    ("Lullo", "Indian Trail / Addison"): bracket_utils.Competitor(
        full_name="Lullo",
        first_name="",
        last_name="Lullo",
        team_full="Indian Trail / Addison",
    ),
    ("Hernandez", "West Chicago"): bracket_utils.Competitor(
        full_name="Hernandez",
        first_name="",
        last_name="Hernandez",
        team_full="West Chicago",
    ),
    ("Lavenske", "Lincoln Cicero"): bracket_utils.Competitor(
        full_name="Lavenske",
        first_name="",
        last_name="Lavenske",
        team_full="Lincoln Cicero",
    ),
    ("Williams", "Coolidge"): bracket_utils.Competitor(
        full_name="Williams",
        first_name="",
        last_name="Williams",
        team_full="Coolidge",
    ),
    ("Reed", "Gompers Jr. High"): bracket_utils.Competitor(
        full_name="Reed",
        first_name="",
        last_name="Reed",
        team_full="Gompers Jr. High",
    ),
    ("Mucenski", "Calumet City"): bracket_utils.Competitor(
        full_name="Mucenski",
        first_name="",
        last_name="Mucenski",
        team_full="Calumet City",
    ),
    ("Kallas", "Eisenhower"): bracket_utils.Competitor(
        full_name="Kallas",
        first_name="",
        last_name="Kallas",
        team_full="Eisenhower",
    ),
    ("Asquini", "Glenview"): bracket_utils.Competitor(
        full_name="Asquini",
        first_name="",
        last_name="Asquini",
        team_full="Glenview",
    ),
    ("Little", "Eisenhower"): bracket_utils.Competitor(
        full_name="Little",
        first_name="",
        last_name="Little",
        team_full="Eisenhower",
    ),
    ("Martin", "Westview Hills"): bracket_utils.Competitor(
        full_name="Martin",
        first_name="",
        last_name="Martin",
        team_full="Westview Hills",
    ),
    ("Houston", "Washington Jr. High"): bracket_utils.Competitor(
        full_name="Houston",
        first_name="",
        last_name="Houston",
        team_full="Washington Jr. High",
    ),
    ("Geese", "Mahomet Seymour"): bracket_utils.Competitor(
        full_name="Geese",
        first_name="",
        last_name="Geese",
        team_full="Mahomet Seymour",
    ),
    ("Miller", "Eisenhower"): bracket_utils.Competitor(
        full_name="Miller",
        first_name="",
        last_name="Miller",
        team_full="Eisenhower",
    ),
    ("Jaskowke", "West Chicago"): bracket_utils.Competitor(
        full_name="Jaskowke",
        first_name="",
        last_name="Jaskowke",
        team_full="West Chicago",
    ),
    ("Shemshedini", "West Chicago"): bracket_utils.Competitor(
        full_name="Shemshedini",
        first_name="",
        last_name="Shemshedini",
        team_full="West Chicago",
    ),
    ("Gennevali", "Bobcats"): bracket_utils.Competitor(
        full_name="Gennevali",
        first_name="",
        last_name="Gennevali",
        team_full="Bobcats",
    ),
    ("Sefcik", "Gompers Jr. High"): bracket_utils.Competitor(
        full_name="Sefcik",
        first_name="",
        last_name="Sefcik",
        team_full="Gompers Jr. High",
    ),
    ("King", "West Chicago"): bracket_utils.Competitor(
        full_name="King",
        first_name="",
        last_name="King",
        team_full="West Chicago",
    ),
    ("Mitchell", "Lockport Wrestlers"): bracket_utils.Competitor(
        full_name="Mitchell",
        first_name="",
        last_name="Mitchell",
        team_full="Lockport Wrestlers",
    ),
    ("Zezulak", "Lombard Jr. Rams"): bracket_utils.Competitor(
        full_name="Zezulak",
        first_name="",
        last_name="Zezulak",
        team_full="Lombard Jr. Rams",
    ),
    ("Davis", "Trimpe"): bracket_utils.Competitor(
        full_name="Davis",
        first_name="",
        last_name="Davis",
        team_full="Trimpe",
    ),
    ("Winze", "Lisle"): bracket_utils.Competitor(
        full_name="Winze",
        first_name="",
        last_name="Winze",
        team_full="Lisle",
    ),
    ("Schrock", "Westview Hills"): bracket_utils.Competitor(
        full_name="Schrock",
        first_name="",
        last_name="Schrock",
        team_full="Westview Hills",
    ),
}


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, score=score)
        )

    weight_classes: list[bracket_utils.WeightClass] = []
    for weight, competitors in _SENIOR_COMPETITORS.items():
        bout_numbers = {}  # No bout numbers at all in 1979
        weight_class = bracket_utils.weight_class_from_competitors(
            "senior",
            weight,
            competitors,
            _SENIOR_TEAM_REPLACE,
            _NAME_EXCEPTIONS,
            bout_numbers,
            placers_type="champ",
        )
        bracket_utils.promote_first_round(weight_class)
        bracket_utils.clear_bout_numbers(weight_class)
        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1979.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
