# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils
import manual_entry

_HERE = pathlib.Path(__file__).resolve().parent
_NOVICE_TEAM_REPLACE: dict[str, str] = {}
_NOVICE_COMPETITORS: dict[int, list[str | None]] = {
    62: [
        "GEORGE SIMS :: JOLIET :: 5",
        "MATT THOMPSON :: SJO KIDS",
        "STEVE OCKRIM :: HINSDALE",
        "SHAUN DANNENBRINK :: BETHALTO :: 4",
        "JOSH MOODY :: QUINCY",
        "BRET BAUMGARDNER :: TRAILBLAZER",
        "WILLIAM CARROLL :: MEAD",
        "KEVIN HASTINGS :: VITTUM CATS",
        "BRANDON WHARTON :: MT. ZION",
        "JUSTIN CLUBB :: HARLEM :: 2",
        "ROBERT ARKO :: VILLA-LOMBARD",
        "RAYMOND SCHNELL :: MOLINE TIGERS",
        "ISRAEL MARTINEZ :: TOMCATS :: 1",
        "DANNY MARTINEZ :: BELVIDERE",
        "EDDIE WOLF :: WARHAWKS",
        "JOHN SHARP :: PEKIN",
        "LEO NARENS :: BETHALTO",
        "RASHAAD BOYD :: JOLIET",
        "FRANK MCNAUGHTON :: OAK LAWN",
        "BRIAN GILLHAM :: ST. TARCISSUS",
        "CALEB FERRY :: HARLEM :: 3",
        "ROB KING :: UNITY YOUTH",
        "SIM BRANDAU :: LITTLE CELTIC :: 6",
        "ZACH ZEIGLER :: HERRIN",
    ],
    66: [
        "JARED MCCABE :: ROSEMONT",
        "JESS MCMECHAN :: CUMBERLAND",
        "JAMES KAMPER :: HICKORY HILLS",
        "RYAN HLINAK :: LAKE VILLA",
        "ADAM LAPE :: VANDALIA",
        "MARK WARREN :: LITTLE CELTIC :: 5",
        "NICK CIRRINCIONE :: VILLA-LOMBARD :: 1",
        "EDDIE ROMIC :: VITTUM CATS",
        "BRAD NORRIS :: REDBIRD",
        "JEREMY HAYES :: MORTON",
        "SEAN CHINSKI :: LITTLE CELTIC :: 3",
        "MATT HAMIL :: EDWARDSVILLE",
        "PAUL AUGLE :: TINLEY PARK :: 2",
        "KYLE WATERS :: PEKIN",
        "JED HOLDEMAN :: TRAILBLAZER",
        "SETH HENRY :: VANDALIA",
        "JUSTIN DARGAN :: CRYSTAL LAKE",
        "WILLIAM TROXEL :: WAUKEGAN",
        "RAY BLAKE :: MUSTANG",
        "BILL ZIGMAN :: INDIAN PRAIRIE",
        "BRANDON DECAP :: RIVERDALE",
        "MICHAEL STANLEY :: MATTOON :: 6",
        "BRIAN HAROFF :: ROSEMONT",
        "ANDREW PENNA :: CRYSTAL LAKE :: 4",
    ],
    70: [
        "PATRICK HAMILTON :: MORRISON :: 4",
        "TRAVIS STAEFFER :: MS. KID'S",
        "JOHN BENNER :: LITTLE GIANTS",
        "BLAKE DINTELMAN :: LITTLE DEVILS",
        "LONNIE CORBIN :: PANTHER BURBANK :: 5",
        "DANNY RICHARDSON :: BRADLEY-BOURBONNAIS",
        "NATHAN MARTINEZ :: TOMCATS :: 1",
        "TJ GRIDER :: ELMHURST",
        "PHILLIP REED :: DANVILLE",
        "TYLER KIMBERLIN :: DUNDEE",
        "ERIK HERNANDEZ :: JOLIET",
        "ALEX SHEAR :: MUSTANG",
        "ERIC NOVAK :: TINLEY PARK",
        "JERAD KARLEN :: ROUND LAKE",
        "RICH KUCZKOWSKI :: LEMONT",
        "JEFF JEZUIT :: PANTHER BURBANK :: 3",
        "GARY OXFORD :: GC COOLIDGE",
        "ANTHONY MULLINS :: METAMORA :: 6",
        "KEVIN HINKLE :: MEAD",
        "DOMINIC VALVANO :: TRAILBLAZER",
        "BILL SWAFFORD :: HARLEM",
        "BRIAN HAWXHURST :: MT. ZION",
        "JOSH PRICE :: RIVERDALE :: 2",
        "RYAN FEATHERSTUN :: MT. VERNON",
    ],
    74: [
        "KYLE ONEILL :: TINLEY PARK :: 1",
        "DAVID GNADEN :: DANVILLE",
        "KEVIN MCCANN :: ROSEMONT",
        "MARC PETERSON :: MUSTANG",
        "MARLAINA CLUBB :: HARLEM",
        "ADAM THORESEN :: LEMONT",
        "TONY RODGERS :: CROSSFACE",
        "ARAN ESPOSITO :: MEAD :: 6",
        "CHRIS TICKLE :: PONTIAC",
        "DUSTIN SCHLOEMANN :: LITTLE KNIGHTS :: 3",
        "CHRIS DZIEWIATKOWSKI :: TRAILBLAZER",
        "ROBERT CARDOSO :: LARKIN",
        "ANDY COYLE :: VILLA-LOMBARD",
        "ZACK MAY :: BETHALTO :: 4",
        "MATT MCKNIGHT :: ILLINOIS VALLEY",
        "BLAKE VERMILLION :: CRYSTAL LAKE",
        "STEVEN COZZIE :: ST. BARNABAS / CHRIST THE KING",
        "RYAN CUMBEE :: LITTLE CELTIC",
        "TONY GANAS :: ROSEMONT :: 2",
        "JESSE TRIBBETT :: MIDWEST CENTRAL",
        "JEREMY COX :: GC COOLIDGE",
        "SHANE MENDENHALL :: MT. ZION",
        "JOSEPH CLARK :: JOLIET :: 5",
        "BRIAN NELSON :: PANTHER BURBANK",
    ],
    79: [
        "PATRICK SPARKS :: TRIAD",
        "MATT WHITMER :: GIBSON CITY",
        "NICK FIORE :: OAK FOREST",
        "DAN NILES :: YORKVILLE :: 5",
        "CHRIS ILIOPOULOS :: ADDISON INDIAN TRAIL :: 4",
        "JAY MILLER :: TRAILBLAZER",
        "JAMIE HEY :: DIXON",
        "SEAN FAHEY :: LITTLE CELTIC",
        "MARSHALL JOYNER :: DANVILLE",
        "DAVID DREW :: MUSTANG :: 1",
        "DANNY ALCOCER JR :: TRAILBLAZER",
        "JASON CARTWRIGHT :: MEAD",
        "JOSEPH KRACHALA :: BATAVIA",
        "ALAN RODENBERG :: ST. BARNABAS / CHRIST THE KING :: 3",
        "BEN STOCKWELL :: RIVERDALE",
        "MIKE KOPECKY :: ROSEMONT",
        "NICK SCACCO :: RICHMOND",
        "DEREK STOLL :: LITTLE DEVILS",
        "RAYNELLE KIZZEE :: HARVEY :: 2",
        "JORDAN WEBSTER :: METAMORA :: 6",
        "ANDY FOSTER :: PANTHER BURBANK",
        "CASEY RODDIS :: MT. ZION",
        "DAVID KNIFFEN :: HERRIN",
        "RUSSELL VANDERHEYDEN :: HARLEM",
    ],
    84: [
        "JOSHUA SERRANO :: CHILLICOTHE",
        "CAL RYDER :: MATTOON :: 6",
        "EARNEST GREGORY :: JOLIET",
        "PATRICK ROSS :: MUSTANG :: 3",
        "BILL WALSH :: CRYSTAL LAKE",
        "RYAN PECK :: SPARTANS",
        "ANGELO GERVASIO :: LEMONT :: 2",
        "MIKE TROTTER :: OAK FOREST",
        "ADAM SEYMOUR :: HOOPESTON",
        "JUSTIN MCCABE :: ROSEMONT",
        "JIM AMSBURY :: EDWARDSVILLE",
        "GREGORY SCOTT :: ROUND LAKE",
        "NICK BINGHEIM :: BETHALTO :: 1",
        "MIKE CUNNINGHAM :: ST. TARCISSUS",
        "SEAN KRAMER :: ST. CHARLES",
        "KEVIN GRECE :: CRYSTAL LAKE",
        "JOE KING :: HICKORY HILLS",
        "RILEY SILES :: METAMORA",
        "RICKY OLSZTA :: LITTLE CELTIC :: 5",
        "DANNY BLAGAICH :: VILLA-LOMBARD",
        "CHRIS SCHUTT :: ROSEMONT",
        "MITCH UPTON :: MATTOON",
        "BOB WHITE :: MORRISON :: 4",
        "TONY SCHICKEL :: MUSTANG",
    ],
    89: [
        "BRAD SCHRADER :: HARLEM :: 3",
        "JEFFRRY SCHWARTZKOPF :: BISMARCK-HENNING",
        "DARREN ORCUTT :: VILLA-LOMBARD",
        "MATTHEW SANDBURG :: LIONS :: 2",
        "JIMMY KAPPAS :: LOCKPORT",
        "JEFFREY SCHMERBACH :: JR. ROCKET",
        "MATT EMERICK :: VANDALIA",
        "TERRY GARBIS :: TRAILBLAZER :: 6",
        "TYRONE BYRD :: DEWITT COUNTY",
        "TOMMY MIETUS :: ROSEMONT",
        "PAUL CLEARY :: EL PASO",
        "TERRANCE JOHNSON :: JOLIET",
        "BEN HOTT :: MOLINE TIGERS",
        "JARED WENDELL :: BISON",
        "KYLE BARBER :: SPARTANS",
        "JUSTIN CARR :: LITTLE CELTIC :: 5",
        "MICHAEL PASTERNAK :: DOLTON",
        "JESSE HALL :: LAKE VILLA",
        "JOHN VILLARREAL :: VILLA-LOMBARD :: 4",
        "BJ VAUGHN :: MURPHYSBORO",
        "CHAD JOHNSON :: MEAD",
        "BRIAN CRAVENS :: MT. ZION :: 1",
        "LYLE ERICKSON :: RICHMOND",
        "PHILLIP R. RUIZ :: ST. BARNABAS / CHRIST THE KING",
    ],
    95: [
        "DANNY QUARTZ :: LITTLE DEVILS :: 4",
        "MICHAEL POWELL :: FISHER :: 6",
        "ROBB GOTLUND :: LEMONT",
        "BRETT HARMAN :: ROSEMONT",
        "JASON MACEK :: PANTHER BURBANK",
        "DON SASO :: BELVIDERE",
        "STEVE AMY :: JR. ROCKET",
        "JOSH HORENI :: OSWEGO COUGARS",
        "CLAY FRENCH :: MATTOON",
        "JASON ERWINSKI :: TINLEY PARK :: 2",
        "MIKE BARDZINSKI :: LAKE VILLA",
        "CHRIS CANDELA :: ST. BARNABAS / CHRIST THE KING",
        "DUSTIN DILLOW :: ELGIN",
        "ROMAN NATOLI :: LOCKPORT :: 3",
        "MIKE RYAN :: JR. ROCKET",
        "WAYNE DEMONBREUN JR :: CRESTWOOD",
        "JASON SPONSEL :: PALATINE",
        "DUSTY GREEN :: RED HILLS",
        "DANA HOLLAND :: VILLA-LOMBARD :: 5",
        "CHRIS OSBORN :: MORRISON",
        "BRADLEY WEINHOLD :: PLAINFIELD INDIAN TRAIL",
        "BRAD OWENS :: MT. ZION :: 1",
        "MARC JUSTICE :: RAIDERS",
        "MATTHEW HOLMES :: WAUKEGAN",
    ],
    101: [
        "MATT LACKEY :: MOLINE TIGERS :: 1",
        "MICHAEL BROWN :: UNITY YOUTH",
        "JASON POTTER :: ST. CHARLES",
        "BRANDON DOLEZAL :: LOCKPORT :: 6",
        "DAVID HILLARD JR :: PIRATES",
        "GEORGE HUSKEY :: LITTLE KNIGHTS",
        "AARON POWERS :: ROCKFORD :: 4",
        "FRANK DE FILIPPIS :: VILLA-LOMBARD",
        "DREU LARSON :: MT. ZION",
        "RUSSELL LANGNER :: CRESTWOOD",
        "MORRIS OPPENHEIMER :: FAIRFIELD",
        "GRAHM GIOVAGNOLI :: ADDAMS",
        "JOSHUA DUKE :: W.F. THUNDERBIRD",
        "MATTHEW COLLINS :: PANTHER BURBANK",
        "JOSHUA RAYBORN :: DUNDEE",
        "DARLOS GOMEZ :: ADDISON INDIAN TRAIL :: 5",
        "ANTHONY MURPHY :: HOMEWOOD-FLOSSMOOR",
        "JEREMY MOORE :: RICHWOODS",
        "DENIS POOL :: GLENDALE :: 2",
        "ALEX MORENO :: CRYSTAL LAKE",
        "MARK EDER :: FALCON",
        "NICK UPTON :: MATTOON :: 3",
        "TIMOTHY PEREZ :: JORDAN-SETON",
        "JASON ROBINSON :: SENECA",
    ],
    108: [
        "SHAWN MCDONNELL :: CRYSTAL LAKE :: 5",
        "TOBY NEAL :: OAKWOOD",
        "MATT FARRARE :: STREATOR",
        "HORACE FLOURNOY :: TRI-CITY BRAVES :: 3",
        "JOHN ZINCHUK :: NOTRE DAME",
        "ANDREW CURRAN :: ST. BARNABAS / CHRIST THE KING",
        "KEVIN VENNE :: GC COOLIDGE",
        "JOSEPH BOYER :: MOLINE TIGERS",
        "JASON KESSLER :: MATTOON",
        "MARK MCCUTCHEON :: LEMONT :: 2",
        "BRENDAN CURRAN :: ST. BARNABAS / CHRIST THE KING",
        "JARED BURRESS :: MEAD",
        "DANIEL JORDAN :: DOLTON",
        "SEAN CONSIDINE :: VILLA-LOMBARD :: 1",
        "JEREMY BROOMBAUGH :: CARBONDALE",
        "MATTHEW ROSENGRANT :: NOTRE DAME",
        "BRIAN EBERSOLE :: BRADLEY-BOURBONNAIS",
        "BRIAN LEMMON :: HARVARD",
        "RUSSEL MCCALLISTER :: ERIE MS",
        "NICHOLAS SCHEIBEL :: HIGHLAND",
        "PATRICK ARVIN :: OSWEGO COUGARS :: 6",
        "SHAIN PRAHL :: MATTOON :: 4",
        "MATTHEW KAUPPINEN :: DAKOTA",
        "JUSTIN GOEBEL :: PLAINFIELD INDIAN TRAIL",
    ],
    115: [
        "GEORGE KIRGAN :: GC COOLIDGE",
        "JOEY HOFFMAN :: URBANA",
        "ADAM FISHER :: CHILLICOTHE",
        "CHRIS KERSTEN :: VILLA-LOMBARD :: 5",
        "ROD GRIFFIN :: TRI-CITY BRAVES :: 3",
        "WESLEY ANDERSON :: ROUND LAKE",
        "MIKE SKRBINA :: DOLTON",
        "ROBB VERHURST :: PROPHETSTOWN-LYNDON",
        "BRIAN SMITH :: LANPHIER-SPRINGFIELD",
        "ANDREW HARRISON :: ADDISON INDIAN TRAIL :: 2",
        "SHAWN BABCOCK :: ROCKFORD",
        "RICHARD VORTES :: HARVEY",
        "DREW THOMAS :: ELGIN",
        "JAMES CARROLL :: MEAD",
        "CHAD FEIPEL :: MUSTANG",
        "CHAD KRNAC :: PLAINFIELD INDIAN TRAIL :: 1",
        "BRIAN SCHNURSTEIN :: VILLA-LOMBARD",
        "LUCAS DIESSELHORST :: LITCHFIELD",
        "TIM LEWIS :: RIVERDALE :: 4",
        "RAYMOND BOYD :: VITTUM CATS :: 6",
        "JOSEPH WEBER :: ROSEMONT",
        "BRAD LEFTWICH :: RANTOUL",
        "CHRIS MCCOY :: EDWARDSVILLE",
        "DONALD HOFF :: HUBBLE",
    ],
    122: [
        "MATTHEW PIOTROWICZ :: NOTRE DAME",
        "MATT FESES :: URBANA",
        "MICHEAL GREGORY :: MARION",
        "LEITH CROWTHER :: PLAINFIELD INDIAN TRAIL :: 3",
        "BRET EVINS :: JR. ROCKET :: 2",
        "JOHN WILKANS :: CRYSTAL LAKE",
        "BRENT KRUMPFES :: HINSDALE",
        "KENNETH LUTZ JR :: RAIDERS",
        "SAMUEL A WALTON :: TAYLORVILLE",
        "JOSH HJORTH :: VILLA-LOMBARD",
        "CHAD PEARSON :: SYCAMORE :: 5",
        "ANDY DYKEMA :: MORRISON",
        "JOE MCCARTHY :: HARVARD :: 1",
        "DUSTIN JENSEN :: ST. CHARLES",
        "AUKEY WILLIAMS :: CORKERY",
        "ADAM SERRANO :: CHILLICOTHE",
        "DONNY BALSAVICH :: ORLAND PARK",
        "ZACH MORRIS :: ROCKFORD",
        "ISAAC DIESSELHORST :: LITCHFIELD :: 4",
        "SETH HORVATH :: ST. BARNABAS / CHRIST THE KING",
        "JOSH JOHNSON :: TOMCATS",
        "RON TICKLE JR :: PONTIAC",
        "JAY PTAK :: ELMHURST",
        "MARTIN ELLIS :: JOLIET :: 6",
    ],
    130: [
        "JUSTIN SORNSIN :: ROCKFORD :: 4",
        "SCOTT RINKENBERGER :: GIBSON CITY",
        "NATHAN HILL :: LAWRENCEVILLE",
        "RAY LEONE :: BLUE CREW",
        "NICK KULBARTZ :: EAST MOLINE",
        "EDMON NEGRON :: CORKERY",
        "BILL KOPECKY :: ROSEMONT :: 1",
        "DEMARKO TAYLOR :: LITTLE KNIGHTS",
        "ANDREW MCMULLEN :: CHARGER KIDS",
        "JAMES YOUNG :: PEOTONE",
        "EDDIE NEGRON :: CORKERY",
        "BRYAN SCHULTZ :: EAGLE :: 5",
        "GARY SHERWOOD :: OAK LAWN :: 3",
        "DANIEL RICHARDS :: LOCKPORT",
        "DAVVD ODONNELL :: MEAD",
        "JESSE IZZO :: BRONCO :: 2",
        "JEREMY KOUNTZ :: EAST MOLINE",
        "DONNIE HALL :: ROCKFORD",
        "JUSTIN QUALLS :: CARBONDALE",
        "JAMES DORE :: NOTRE DAME",
        "SAMMY CONDE :: CALUMET CITY",
        "CHAD GRIGSBY :: CHARLESTON :: 6",
        "KRISTOFER SWANSON :: DUNDEE",
        "DANE SIMPSON :: EL PASO",
    ],
    138: [
        "SPENCER FETHERLING :: RICH WRESTLING",
        "CODY DAHL :: URBANA",
        "JUSTIN WATSON :: ROCKFORD",
        "MARK GENTHE :: VILLA-LOMBARD :: 1",
        "NICK PATRICK :: GC COOLIDGE",
        "TRAVIS WASHINGTON :: CORKERY",
        "BRYAN ROUSE :: MAINE TOWNSHIP EAGLES :: 3",
        "KYLE WISNIEWSKI :: ANTIOCH",
        "JOSH SPAIN :: MT. ZION",
        "JOHN DIETERLE :: QUINCY :: 6",
        "DAN PROROK :: OAK LAWN",
        "JERRY HEARN :: TRI-CITY TURTLES",
        "NICK CURBY :: LIONS :: 2",
        "SHANNON CHRISTIANSEN :: TIGERTOWN TANGLERS",
        "KYLE KING :: WAUKEGAN",
        "JOHNATHON CARPENTER :: LITTLE DEVILS",
        "ERIC SHARP :: OSWEGO COUGARS",
        "JOVAN GORRELL :: CHICAGO HEIGHTS",
        "RYAN LAIRD :: SYCAMORE",
        "PARKER PINNELL :: WAUKEGAN :: 4",
        "BRIAN MALOTT :: PEKIN",
        "ANDREW LINARES :: HOOPESTON :: 5",
        "NICK SHEPHERD :: BRADLEY-BOURBONNAIS",
        "MIKEY SALAH :: LEMONT",
    ],
    147: [
        "CHRISTOPH MARTINAT :: LAKE FOREST",
        "ARNOLD EVANS :: OAKWOOD",
        "GRANT GOLTZ :: GIBSON CITY",
        "NICK POEHLMAN :: MORTON :: 4",
        "NICHOLAS LATUS :: EAGLE :: 2",
        "WILL MCDERMOTT :: LITTLE CELTIC",
        "RAMONE BROWN :: ROBBINS",
        "DAN THORNTON :: PEORIA",
        "SEAN NEWBY :: MATTOON",
        "ALAN REYNOLDS :: FAIRFIELD",
        "RYAN HITE :: JOLIET",
        "NICK ESPOSITO :: VILLA-LOMBARD :: 5",
        "ADAM VENTSIAS :: PLAINFIELD INDIAN TRAIL :: 3",
        "BRYCE PARKS :: MARION",
        "GARY PARQUETTE :: HUBBLE",
        "JOE CHIRUMBOLO :: EAGLE :: 1",
        "RK LUNN :: TIGERTOWN TANGLERS",
        "SEAN GARAY :: RAMS",
        "KEVIN MCCORMICK :: ROCKFORD",
        "JON PAOLILLI :: HOMEWOOD-FLOSSMOOR",
        "NICK MYRES :: TRIAD",
        "PHILIP HARBIN :: ARGENTA / OREANA",
        "JASON TEJERO :: ROSEMONT",
        "ADAM STIMPSON :: JORDAN-SETON :: 6",
    ],
    215: [
        "BRAD CRAIG :: ROBBINS :: 2",
        "GARRETT SEAMAN :: MATTOON",
        "JASON ROMANO :: CRYSTAL LAKE",
        "WILSON MOORE :: MURPHYSBORO :: 6",
        "DALE ANDERSON :: EL PASO",
        "STATHIE PANAYI :: PALATINE",
        "ERIC OLSON :: BRADLEY-BOURBONNAIS",
        "TRAVIS MARTINEZ :: LIL REAPER :: 3",
        "ADAM DETMERS :: MT. ZION",
        "PAT DALY :: VILLA PARK",
        "MATT MIKES :: PALATINE",
        "BRIAN STEELE :: MACOMB",
        "JASON MANGAWAN :: RAMS :: 5",
        "SALVADOR RAMIREZ :: TOMCATS",
        "DANNY CORDOVA :: LOCKPORT",
        "MATTHEW CARLSON :: GENESEO",
        "SETH WOMACK :: VANDALIA",
        "JEFFERY MISIOLEK :: ST. BARNABAS / CHRIST THE KING",
        "BRAD RUNKLE :: YORKVILLE :: 1",
        "MICHAEL MESSENGER :: PLAINFIELD INDIAN TRAIL",
        "MARK DICKER :: PALATINE",
        "JACOB ACORD :: WESTVILLE :: 4",
        "MICHAEL HARRIS :: ST. BARNABAS / CHRIST THE KING",
        "RANDY JOE WILKEY :: CENTRALIA",
    ],
}
_NOVICE_TEAM_SCORES: dict[str, float] = {
    "VILLA-LOMBARD": 179.0,
    "LITTLE CELTIC": 93.0,
    "PLAINFIELD INDIAN TRAIL": 87.0,
    "MATTOON": 82.5,
    "ROSEMONT": 78.0,
    "HARLEM": 77.0,
    "TINLEY PARK": 74.0,
    "EAGLE": 70.5,
    "BETHALTO": 61.0,
    "ADDISON INDIAN TRAIL": 58.0,
    "TOMCATS": 56.0,
    "MT. ZION": 55.0,
    "CRYSTAL LAKE": 53.5,
    "PANTHER BURBANK": 53.5,
    "MUSTANG": 53.0,
    "LEMONT": 52.0,
    "ROCKFORD": 49.5,
    "JOLIET": 49.0,
    "LIONS": 47.0,
    "YORKVILLE": 45.0,
    "LOCKPORT": 45.0,
    "TRI-CITY BRAVES": 42.5,
    "RIVERDALE": 42.0,
    "MORRISON": 42.0,
    "MOLINE TIGERS": 38.5,
    "ST. BARNABAS / CHRIST THE KING": 38.0,
    "HARVARD": 36.0,
    "JR. ROCKET": 34.5,
    "OAK LAWN": 34.0,
    "LITTLE DEVILS": 31.0,
    "DOLTON": 28.0,
    "MAINE TOWNSHIP EAGLES": 27.0,
    "LIL REAPER": 26.0,
    "MEAD": 25.0,
    "WESTVILLE": 24.0,
    "GLENDALE": 24.0,
    "METAMORA": 24.0,
    "ROBBINS": 23.0,
    "LITTLE KNIGHTS": 23.0,
    "WAUKEGAN": 21.0,
    "OSWEGO COUGARS": 21.0,
    "TRAILBLAZER": 20.5,
    "BRONCO": 20.0,
    "HOOPESTON": 20.0,
    "HARVEY": 20.0,
    "LITCHFIELD": 19.0,
    "MURPHYSBORO": 19.0,
    "MORTON": 19.0,
    "VITTUM CATS": 18.0,
    "RAMS": 17.0,
}
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "BETHALTO": 242.0,
    "VILLA-LOMBARD": 158.5,
    "HARVEY": 103.5,
    "ST. CHARLES": 102.0,
    "TINLEY PARK": 97.0,
    "MORTON": 90.5,
    "CRYSTAL LAKE": 87.0,
    "DOLTON": 87.0,
    "PIRATES": 81.0,
    "ORLAND PARK": 76.5,
    "GENESEO": 74.0,
    "ROCKFORD": 72.5,
    "HARLEM": 69.0,
    "DAKOTA": 69.0,
    "MEAD": 66.5,
    "VANDALIA": 64.5,
    "HICKORY HILLS": 58.0,
    "BRADLEY-BOURBONNAIS": 52.0,
    "DANVILLE": 49.0,
    "OAK FOREST": 46.0,
    "ROUND LAKE": 46.0,
    "LIL REAPER": 45.0,
    "RICH WRESTLING": 43.0,
    "YORKVILLE": 40.0,
    "CORKERY": 39.0,
    "FRANKLIN PARK": 37.0,
    "W.F. THUNDERBIRD": 37.0,
    "WARHAWKS": 36.0,
    "PLAINFIELD INDIAN TRAIL": 36.0,
    "KNIGHTS": 34.0,
    "PONTIAC": 30.0,
    "JR. ROCKET": 29.0,
    "TIGERTOWN TANGLERS": 29.0,
    "TOMCATS": 28.0,
    "ROSEMONT": 27.0,
    "ST. BARNABAS / CHRIST THE KING": 26.0,
    "CRESTWOOD": 26.0,
    "ARGENTA / OREANA": 25.0,
    "DOWNERS GROVE": 24.0,
    "ELGIN": 24.0,
    "MT. VERNON": 23.0,
    "EISENHOWER JR HAWK": 23.0,
    "CHARGER KIDS": 22.0,
    "WAUKEGAN": 22.0,
    "NAPERVILLE WARRIORS": 21.0,
    "EISENHOWER JH": 21.0,  # Yes, this is different than `EISENHOWER JR HAWK`
    "FULTON": 21.0,
    "BELVIDERE": 20.0,
    "MARION": 20.0,
    "HARVARD": 19.0,
}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    ("DANNY ALCOCER JR", "TRAILBLAZER"): bracket_utils.Competitor(
        full_name="DANNY ALCOCER JR",
        first_name="DANNY",
        last_name="ALCOCER",
        team_full="TRAILBLAZER",
    ),
    ("PHILLIP R. RUIZ", "ST. BARNABAS / CHRIST THE KING"): bracket_utils.Competitor(
        full_name="PHILLIP R. RUIZ",
        first_name="PHILLIP",
        last_name="RUIZ",
        team_full="ST. BARNABAS / CHRIST THE KING",
    ),
    ("WAYNE DEMONBREUN JR", "CRESTWOOD"): bracket_utils.Competitor(
        full_name="WAYNE DEMONBREUN JR",
        first_name="WAYNE",
        last_name="DEMONBREUN",
        team_full="CRESTWOOD",
    ),
    ("DAVID HILLARD JR", "PIRATES"): bracket_utils.Competitor(
        full_name="DAVID HILLARD JR",
        first_name="DAVID",
        last_name="HILLARD",
        team_full="PIRATES",
    ),
    ("FRANK DE FILIPPIS", "VILLA-LOMBARD"): bracket_utils.Competitor(
        full_name="FRANK DE FILIPPIS",
        first_name="FRANK",
        last_name="DE FILIPPIS",
        team_full="VILLA-LOMBARD",
    ),
    ("RON TICKLE JR", "PONTIAC"): bracket_utils.Competitor(
        full_name="RON TICKLE JR",
        first_name="RON",
        last_name="TICKLE",
        team_full="PONTIAC",
    ),
    ("KENNETH LUTZ JR", "RAIDERS"): bracket_utils.Competitor(
        full_name="KENNETH LUTZ JR",
        first_name="KENNETH",
        last_name="LUTZ",
        team_full="RAIDERS",
    ),
    ("SAMUEL A WALTON", "TAYLORVILLE"): bracket_utils.Competitor(
        full_name="SAMUEL A WALTON",
        first_name="SAMUEL",
        last_name="WALTON",
        team_full="TAYLORVILLE",
    ),
    ("RANDY JOE WILKEY", "CENTRALIA"): bracket_utils.Competitor(
        full_name="RANDY JOE WILKEY",
        first_name="RANDY JOE",
        last_name="WILKEY",
        team_full="CENTRALIA",
    ),
    ("JOE DI GIOIA", "VILLA-LOMBARD"): bracket_utils.Competitor(
        full_name="JOE DI GIOIA",
        first_name="JOE",
        last_name="DI GIOIA",
        team_full="VILLA-LOMBARD",
    ),
    ("TARL VON HATTEN", "ST. CHARLES"): bracket_utils.Competitor(
        full_name="TARL VON HATTEN",
        first_name="TARL",
        last_name="VON HATTEN",
        team_full="ST. CHARLES",
    ),
    ("DAN DE BRUN", "VILLA-LOMBARD"): bracket_utils.Competitor(
        full_name="DAN DE BRUN",
        first_name="DAN",
        last_name="DE BRUN",
        team_full="VILLA-LOMBARD",
    ),
    ("STANLEY EVANS JR", "PIRATES"): bracket_utils.Competitor(
        full_name="STANLEY EVANS JR",
        first_name="STANLEY",
        last_name="EVANS",
        team_full="PIRATES",
    ),
    ("BOBBY HUITT JR", "STREATOR"): bracket_utils.Competitor(
        full_name="BOBBY HUITT JR",
        first_name="BOBBY",
        last_name="HUITT",
        team_full="STREATOR",
    ),
    ("PHIL TAYLOR JR", "MT. ZION"): bracket_utils.Competitor(
        full_name="PHIL TAYLOR JR",
        first_name="PHIL",
        last_name="TAYLOR",
        team_full="MT. ZION",
    ),
    ("D ANDRE DENTON", "PIRATES"): bracket_utils.Competitor(
        full_name="D ANDRE DENTON",
        first_name="D ANDRE",
        last_name="DENTON",
        team_full="PIRATES",
    ),
}
_BOUT_NUMBER_INPUTS: dict[tuple[bracket_utils.Division, int], tuple[int, int]] = {
    ("novice", 62): (2, 705),
    ("novice", 66): (18, 706),
    ("novice", 70): (34, 707),
    ("novice", 74): (50, 708),
    ("novice", 79): (66, 709),
    ("novice", 84): (82, 710),
    ("novice", 89): (98, 711),
    ("novice", 95): (114, 712),
    ("novice", 101): (130, 713),
    ("novice", 108): (146, 714),
    ("novice", 115): (162, 715),
    ("novice", 122): (178, 716),
    ("novice", 130): (194, 717),
    ("novice", 138): (210, 718),
    ("novice", 147): (226, 719),
    ("novice", 215): (242, 720),
    ("senior", 70): (2, 793),
    ("senior", 74): (18, 794),
    ("senior", 79): (34, 795),
    ("senior", 84): (50, 796),
    ("senior", 89): (66, 797),
    ("senior", 95): (82, 798),
    ("senior", 101): (98, 799),
    ("senior", 108): (114, 800),
    ("senior", 115): (130, 801),
    ("senior", 122): (146, 802),
    ("senior", 130): (162, 803),
    ("senior", 138): (178, 804),
    ("senior", 147): (194, 805),
    ("senior", 156): (210, 806),
    ("senior", 166): (226, 807),
    ("senior", 177): (242, 808),
    ("senior", 189): (258, 809),
    ("senior", 275): (274, 810),
}


def _get_bout_numbers(
    division: bracket_utils.Division, weight: int
) -> dict[bracket_utils.MatchSlot, int]:
    key = (division, weight)
    entry = _BOUT_NUMBER_INPUTS.get(key)
    if entry is None:
        return {}

    first_pigtail, first_place = entry
    if division == "novice":
        weight_count = 16
    elif division == "senior":
        weight_count = 18
    else:
        raise NotImplementedError(division)

    return {
        "championship_r32_02": first_pigtail,
        "championship_r32_04": first_pigtail + 2,
        "championship_r32_06": first_pigtail + 4,
        "championship_r32_08": first_pigtail + 6,
        "championship_r32_10": first_pigtail + 8,
        "championship_r32_12": first_pigtail + 10,
        "championship_r32_14": first_pigtail + 12,
        "championship_r32_16": first_pigtail + 14,
        "consolation_fifth_place": first_place - 2 * weight_count,
        "consolation_third_place": first_place - weight_count,
        "championship_first_place": first_place,
    }


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["novice"] = []
    for team_name, score in _NOVICE_TEAM_SCORES.items():
        team_scores["novice"].append(
            bracket_utils.TeamScore(team=team_name, score=score)
        )

    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, score=score)
        )

    weight_classes = manual_entry.load_manual_entries(
        _HERE.parent, 1993, _NAME_EXCEPTIONS
    )

    for weight, competitors in _NOVICE_COMPETITORS.items():
        bout_numbers = _get_bout_numbers("novice", weight)
        weight_class = bracket_utils.weight_class_from_competitors(
            "novice",
            weight,
            competitors,
            _NOVICE_TEAM_REPLACE,
            _NAME_EXCEPTIONS,
            bout_numbers,
        )
        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1993.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
