# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

"""
The competitor list (from scans from Corey Atwell) is contained below.
"""

import pathlib

import bracket_utils

_HERE = pathlib.Path(__file__).resolve().parent
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    60: [
        "Michael Shields :: Belleville Little Devils",
        "Marshall Watson :: Redbird WC",
        "Wesley Nicholas :: Oak Park River Forest WC",
        "Tony Davis :: Harvey Twisters :: 3",
        "Mike Hasty :: Morton Youth WC",
        "Paul Ostapczuk :: St. Charles J.H. WC",
        "Ben Gerdes :: Orland Park Pioneers :: 1",
        "Jim Brasher :: Vittum Cats :: 6",
        "Stephen Stanley :: Mattoon WC",
        "Tom Grennan :: Newman Middle School",
        "Tony Ranieri :: Villa Lombard WC",
        "Micheal Galvin :: Forman WC",
        "Chad Red :: Danville YMCA WC :: 5",
        "Michael Pryor :: Roxana Roughnecks",
        "Bobby Meek :: Lemont Bears WC",
        "Blake Hoerr :: Chillicothe WC",
        "Jerry Delira :: Lan-Oak Park District :: 4",
        "Bobby Remily :: Harlem-Franklin Boys Club",
        "Jason Kolecke :: Vittum Cats",
        "Jason Finley :: Orland Park Pioneers",
        "Bryon Krummelbein :: Bethalto Boys Club",
        "Justin Weber :: Villa Lombard WC :: 2",
        "Peter Kukla :: Round Lake P.D. Spartans",
        "Tom Combes :: Dolton Park Jr. Falcons",
    ],
    65: [
        "Jason Slade :: Cahokia WC South",
        "Leo Otto :: Orland Park Pioneers",
        "Brent Henschel :: Mt. Zion WC",
        "Brent Pinkston :: Newman Middle School",
        "Dan Monchunsk :: Medinah Lancers WC",
        "Mark Bybee :: Vittum Cats :: 5",
        "Nathan Camer :: Colts WC :: 4",
        "Scott Benjamin :: Catlin WC",
        "Don Bermudez :: Lockport Grapplers WC",
        "Cory Daker :: Forman WC :: 1",
        "Matt Hayes :: Arlington Cardinals WC",
        "Mike Renella :: Naperville Patriots",
        "Joseph Flemings :: Rich Wrestling LTD",
        "Ron Hansen :: Bethalto Boys Club",
        "Jason Pero :: Lan-Oak Park District :: 6",
        "Jason Chappell :: Villa Lombard WC",
        "Micah Hey :: Dixon WC",
        "Brad Schnowske :: Geneseo WC",
        "Frank Lamie :: Bradley Bourbonnais WC",
        "Jason Eierman :: Colts WC :: 2",
        "Steve Dickinson :: Roxana Roughnecks",
        "Derrick Noble :: Arlington Cardinals WC :: 3",
        "Sammy Watts :: Forman WC",
        "Rick Cliffe :: DeKalb WC",
    ],
    70: [
        "Jason Johnson :: Roxana Jr. High Vikings",
        "Tim Stringer :: Dolton Park Jr. Falcons :: 4",
        "Mike Triolo :: Tinley Park Bulldogs",
        "Bryant Crawford :: Geneseo WC :: 6",
        "Jesse Kennedy :: Rosemont Cobras",
        "Brad Hathaway :: Westville Jr. High",
        "Jacob Hey :: Dixon WC",
        "James Crnich :: Oak Forest Warriors",
        "Joey O'Sullivan :: Colts WC",
        "Ryan Ferguson :: Medinah Lancers WC :: 2",
        "Natris Morris :: Danville YMCA WC",
        "Damon Federighi :: Vittum Cats",
        "Daniel Schickel :: Colts WC :: 5",
        "Mike Dickinson :: Roxana Jr. High Vikings",
        "Steve Willard :: Harlem-Franklin Boys Club",
        "Dan Collins :: Arlington Cardinals WC",
        "Bill Loftus :: Geneseo WC",
        "John Cervenka :: Naperville Patriots",
        "Jason Ford :: Rich Wrestling LTD :: 1",
        "Matt Bouback :: Belvidere Bandits YMCA WC :: 3",
        "Clay Cochran :: Murphysboro Jr. High",
        "Mike French :: Mattoon WC",
        "Jim Virnich :: St. Charles J.H. WC",
        "Chris Cape :: Bartonville Blue Crew",
    ],
    75: [
        "Peter Smith :: Carbondale WC",
        "Rusty Nofsinger :: Round Lake P.D. Spartans",
        "Kenneth Kowalski :: Lan-Oak Park District",
        "Chuy Villareal :: Medinah Lancers WC :: 6",
        "Joe Steiner :: Bloomington Jr. High",
        "Michael Griffin :: Rich Wrestling LTD :: 3",
        "Van Whitcanack :: Moline Wildcats",
        "Nick Parisi :: Hickory Hills Park District",
        "Jack Vu :: Newman Middle School",
        "Jamit Swift :: Arlington Cardinals WC",
        "Jim Soldan :: Frankfort Falcons :: 2",
        "Kurt Hudson :: Redbird WC",
        "Brad Wernsman :: Yorkville WC",
        "David Goforth :: Roxana Roughnecks",
        "Troy Bjork :: Geneseo WC",
        "Curt Bee :: Lanphier-Southeast WC :: 4",
        "Rich Mennella :: Indian Prairie WC",
        "Kevin Dunn :: Vittum Cats :: 5",
        "Tim Combes :: Dolton Park Jr. Falcons",
        "Tad Tyler :: East Moline WC",
        "Brady Arview :: Roxana Roughnecks",
        "Dan Gilbert :: Tinley Park Bulldogs :: 1",
        "Theo Hodges :: Oak Park River Forest WC",
        "Mark Green :: Naperville Patriots",
    ],
    80: [
        "Darby Waggoner :: Lawrence County WC",
        "Jerrett Bernahl :: Geneseo WC",
        "Eric Siebert :: Illinois Valley WC :: 2",
        "Sean Duggan :: St. Tarcissus Raiders",
        "Jason Lemonier :: Tinley Park Bulldogs",
        "Dan Walters :: Panther Wrestling Club",
        "Douglas Sawyer :: Villa Lombard WC :: 5",
        "Mike Prall :: Round Lake P.D. Spartans",
        "Jason Schnell :: Moline Spartans",
        "Randall Pierce :: Chanute Rockets",
        "Kevin Ryan :: Colts WC :: 4",
        "Pat O'Donnell :: Oak Forest Warriors",
        "Bobby McKinney :: Forman WC :: 6",
        "Steve Mitchell :: Roxana Roughnecks",
        "Mick Helms :: Blackhawk WC",
        "Curt Bellone :: Orland Park Pioneers",
        "Michael Powell :: Oak Park River Forest WC",
        "Darrin Thomason :: Bismarck-Henning WC",
        "Jared Gratz :: Harvard WC",
        "William Graham :: Villa Lombard WC :: 3",
        "Brad Chasteen :: Edwardsville WC",
        "Keith Snyder :: Panther Wrestling Club :: 1",
        "Juston Nobiling :: Redbird WC",
        "Ryan Radosh :: Arlington Cardinals WC",
    ],
    85: [
        "Eric Carter :: Roxana Jr. High Vikings",
        "Mike Schomig :: Wheaton P.D. Falcons",
        "Brian Brummitt :: Crossface WC",
        "Erin Johnson :: Hoopeston-East Lynn Jr. High :: 6",
        "John Rociola :: Colts WC",
        "David Bobee :: Lil' Reaper WC",
        "Mike Torres :: Vittum Cats :: 3",
        "Marc Molzek :: Geneseo WC",
        "Devin Sullivan :: Naperville Patriots",
        "Josh Mattio :: Rich Wrestling LTD",
        "Martin Sanchez :: Belvidere Bandits YMCA WC :: 2",
        "Chris White :: Panther Wrestling Club",
        "Tony Villarreal :: Medinah Lancers WC",
        "Cole Cochran :: Belleville Little Devils",
        "Richard Alexander :: Oak Park River Forest WC",
        "Steve Williams :: Harvey Twisters :: 1",
        "Joe Bee :: Lanphier-Southeast WC",
        "Alfred Rizzo :: Peotone Park District WC",
        "Jeff Day :: Morton Youth WC",
        "Steve Gerstung :: Arlington Cardinals WC :: 5",
        "Nick Milazzo :: Roxana Roughnecks",
        "Mike Mena :: Newman Middle School :: 4",
        "Bucky Randolph :: Oak Forest Warriors",
        "G.R. Ficklin :: Urbana Kids WC",
    ],
    90: [
        "Ryan Smith :: Roxana Jr. High Vikings :: 4",
        "Pat Harder :: LaGrange Lions",
        "Josh Bolin :: Naperville Wrestlers",
        "Terry Cantorna :: Orland Park Pioneers :: 6",
        "Chis Ludwig :: Dundee Highlanders",
        "Brooke Hoerr :: Morton Youth WC",
        "Philip Schwing :: Fisher WC",
        "Chris Seher :: Wheaton P.D. Falcons",
        "Will Rehfeldt :: Vittum Cats",
        "Joseph Williams :: Harvey Twisters :: 1",
        "Calvin DeBoer :: Peoria Razorbacks WC",
        "Chad Easteberg :: Round Lake P.D. Spartans",
        "Dave Regetti :: St. Tarcissus Raiders",
        "Mark Vanhala :: Mascoutah Jr. High",
        "Kevin Ruzic :: Lanphier-Southeast WC",
        "Frank Laccone :: DeKalb WC :: 3",
        "Scott Churlin :: Rich Wrestling LTD",
        "Mike Eierman :: Colts WC :: 2",
        "John Virnich :: St. Charles J.H. WC",
        "Phil Benjamin :: Catlin WC :: 5",
        "Randy Deeke :: Belleville Little Devils",
        "Shay Cordes :: East Moline WC",
        "Alvin Jones :: Harvey Twisters",
        "Derek Cedillo :: Tinley Park Bulldogs",
    ],
    95: [
        "Scott Schwab :: Belleville Little Devils",
        "Alex Strobl :: Arlington Cardinals WC",
        "Tony Lepore :: Oak Forest Warriors",
        "Nick Gryga :: Panther Wrestling Club :: 5",
        "Kevin Greaney :: Eisenhower Jr. High",
        "Eric Mathey :: Sycamore WC",
        "Peter Stanley :: Mattoon WC :: 1",
        "David Bradford :: Oak Forest Warriors",
        "Mario Castellanos :: Bensenville Bulldogs",
        "G.W. Fuhr :: Rockridge Jr. High :: 4",
        "Ray Callahan :: DeKalb WC",
        "Tim Gits :: Medinah Lancers WC",
        "Tom Buenik :: Vittum Cats :: 3",
        "Scott Wilson :: Granite City Coolidge WC",
        "John Lieb :: Fisher WC",
        "Oswaldo Quintanilla :: Tomcat WC",
        "Doug Griffith :: Lan-Oak Park District",
        "Jason Wright :: Rockridge Jr. High",
        "Quentin Reidy :: Tinley Park Bulldogs",
        "J.D. Graham :: Mattoon WC",
        "Matt Fischer :: Roxana Roughnecks",
        "Kelly Hamill :: Belvidere Bandits YMCA WC :: 2",
        "Tim Kanke :: Geneseo WC",
        "Terry Dantzler :: Harvey Twisters :: 6",
    ],
    100: [
        "Steven Brito :: Roxana Jr. High Vikings :: 4",
        "Elias Martinez :: Bloomington Jr. High",
        "Renard Williams :: Harvey Twisters",
        "Eric Petruchuis :: Sycamore WC",
        "Herbert House :: Oak Park River Forest WC :: 5",
        "Andy Freverl :: Morton Youth WC",
        "Paul Blaha :: Frankfort Falcons :: 1",
        "David Schultz :: Panther Wrestling Club",
        "Eric Johnson :: Bismarck-Henning WC",
        "Scott Benson :: Naperville Wrestlers",
        "Dan Naab :: Jordan WC",
        "Scott Aronson :: Oak Park River Forest WC",
        "Jason Williams :: Urbana Kids WC",
        "Tim Pate :: Centralia WC",
        "Neal Franzen :: Oak Forest Warriors",
        "Will Lepsi :: Vittum Cats :: 3",
        "Tony Pavlak :: Belvidere Bandits YMCA WC",
        "Tommy Knight :: Wheaton P.D. Falcons",
        "Mike Derro :: Panther Wrestling Club :: 2",
        "Mark Bushell :: Indian Trail Jr. High",
        "Derek Baugh :: Edwardsville WC",
        "Jayson Querciagrossa :: Crossface WC :: 6",
        "John Comstock :: Geneva Vikings",
        "John Doke :: DeKalb WC",
    ],
    105: [
        "Tracy West :: Bethalto Boys Club",
        "Rob Felstead :: Oak Forest Warriors :: 4",
        "Dennis Demoss :: Harvard WC",
        "Jeff Wallace :: Geneseo WC :: 2",
        "Joey Yager :: Urbana Kids WC",
        "Jason Kuefler :: Naperville Warriors",
        "Robert O'Connor :: Oak Lawn PD :: 6",
        "Mike Cliffe :: DeKalb WC",
        "Marcus Gunaka :: Tinley Park Bulldogs",
        "Mark Gabriel :: Vittum Cats",
        "Rocky Rovella :: Carol Stream P.D.",
        "Kasey Alexander :: Mattoon WC",
        "Jerimy Chambers :: Frankfort Falcons :: 3",
        "Jonn Ross :: Belleville Little Devils",
        "Bo O'Rourke :: Colts WC",
        "Shawn Vaughn :: Catlin WC",
        "Jeff Lee :: Bartonville Blue Crew",
        "Dennis Boggess :: Arlington Cardinals WC",
        "Cass Lundgren :: DeKalb WC :: 1",
        "Dennis Kamykowski :: Panther Wrestling Club",
        "Russell Sheppard :: Murphysboro Jr. High",
        "John Rodriguez :: J-Hawk WC",
        "Eric Anderson :: Vittum Cats",
        "Mike Devos :: Morton Youth WC :: 5",
    ],
    111: [
        "Brian Kohring :: Murphysboro Jr. High",
        "Jason Bever :: Colts WC",
        "Troy Copeland :: Geneseo WC :: 2",
        "Tom Garcia :: Wheaton P.D. Falcons",
        "Zane Seipler :: Rich Wrestling LTD",
        "Terry King :: Oak Park River Forest WC",
        "Ray Pena :: Elgin Matt Rats WC :: 4",
        "Dan Rohman :: Metamora Kids WC",
        "Andre Davis :: Harvey Twisters :: 6",
        "Charlie Hayes :: Westville Jr. High",
        "Derek Walker :: Oak Park River Forest WC",
        "James Macdermaid :: Indian Trail Jr. High",
        "Terrell Sandifer :: Harvey Twisters :: 1",
        "James Davis :: Belleville Little Devils",
        "Jeff Hale :: Dixon WC",
        "Andy Bednarczyk :: Tinley Park Bulldogs :: 3",
        "Ralph Wilson :: Tomcat WC",
        "Steve Owens :: Mt. Zion WC",
        "Steve McDonnell :: Moline Wildcats :: 5",
        "John Rizzo :: Woodstock Cardinals",
        None,
        "Dean Boggess :: Arlington Cardinals WC",
        "Ryan Digby :: Georgetown WC",
        "Ochein Wilson :: Naperville Warhawks",
    ],
    118: [
        "Scott Ventimiglia :: Roxana Roughnecks :: 5",
        "Jason Smith :: Sycamore WC",
        "Ryan Beatty :: Eisenhower Jr. High",
        "Mike Ahrens :: LaGrange Lions :: 3",
        "Dan Minet :: Panther Wrestling Club",
        "Duane Parks :: Bradley Bourbonnais WC",
        "Christopher Ireland :: Moline Wildcats :: 1",
        "Chris Milligan :: Geneva Vikings",
        "David Garza :: Belvidere Bandits YMCA WC",
        "Curt Ivins :: Indian Trail Jr. High",
        "John Miller :: Westville Jr. High",
        "Mike Modzelewski :: Panther Wrestling Club",
        "Matt Sell :: DeKalb WC :: 2",
        "Jason Ward :: Murphysboro Jr. High",
        "Chuck Blascyzyk :: Geneseo WC",
        "Lewis Ledet :: Harvey Twisters",
        "Ken Stephens :: Rams WC",
        "Bret Geijer :: Tinley Park Bulldogs",
        "Patrick Mahoney :: Villa Lombard WC :: 4",
        "John King :: Rockridge Jr. High",
        "Travis Stockstill :: Bethalto Boys Club",
        "Priest Wilson :: Georgetown WC :: 6",
        "Tom Manzella :: Tinley Park Bulldogs",
        "Robert Salyers :: Franklin Park Raiders",
    ],
    125: [
        "Gary Davis :: Bethalto Boys Club :: 6",
        "Justin Medina :: Moline Spartans",
        "Shawn Miller :: Bensenville Bulldogs",
        "Jon Pritchett :: Georgetown WC",
        "Drew Mikkelson :: Lil' Reaper WC",
        "Jimmy Tesch :: Frankfort Falcons",
        "Matt Klausner :: Blackhawk WC",
        "Jason Clifton :: Matburns Wrestling Club",
        "Troy Christopherson :: Geneseo WC :: 4",
        "Jim Czajkowski :: Panther Wrestling Club :: 1",
        "Joe Platt :: Indian Trail Jr. High",
        "Brian Davis :: Yorkville WC",
        "Kenton Hitchcock :: Rockridge Jr. High",
        "Scott Borders :: Herrin Raiders",
        "Bob Profeta :: Naperville Wrestlers :: 5",
        "Brian Jensen :: Sycamore WC",
        "Ben Smaga :: Bloomington Jr. High",
        "Jeremy Cary :: Dolton Park Jr. Falcons",
        "Pat Ahrens :: LaGrange Lions :: 2",
        "Mark Back :: Wheaton P.D. Falcons :: 3",
        "Robbie Purcell :: Murphysboro Jr. High",
        "David Vanderwall :: Oak Forest Warriors",
        "Dave Salinas :: Dolton Park Jr. Falcons",
        "Fred Hasbargen :: Hoopeston-East Lynn Jr. High",
    ],
    135: [
        "Richard Carlile :: Bethalto Boys Club",
        "Joseph Lamantia :: Eisenhower Jr. High :: 2",
        "Curt Miller :: Hoopeston-East Lynn Jr. High",
        "Timothy Fix :: Indian Trail Jr. High",
        "Denny Royce :: Moline Wildcats",
        "Larry Parham :: Dolton Park Jr. Falcons",
        "Mike Barcena :: Vittum Cats :: 4",
        "Mitch Page :: Gibson City Youth WC",
        "Bil Baffa :: Villa Lombard WC",
        "Dan Limon :: Lil' Reaper WC :: 5",
        "Roger Langland :: Crestwood Colts WC",
        "Brad Wood :: Metamora Kids WC :: 6",
        "Bryan Rebhan :: Naperville Warhawks :: 1",
        "Tom Moss :: Granite City Grigsby WC",
        "Ed Koleff :: LaGrange Lions",
        "Tim Mack :: Rockridge Jr. High",
        "Arron Mudroch :: Tinley Park Bulldogs",
        "Steve Wood :: Harvard WC",
        "Brad Gardner :: Lanphier-Southeast WC :: 3",
        "Jason Cloherty :: Franklin Park Raiders",
        "David Stout :: Granite City Grigsby WC",
        "John Giuntoli :: Oak Lawn PD",
        "Jacob Pritchett :: Elgin Matt Rats WC",
        "Steve Petrokovitch :: Oak Forest Warriors",
    ],
    145: [
        "Douglas Neumeyer :: Belleville Little Devils",
        "Keith Hermansen :: Lemont Bears WC",
        "Tony O'Daniel :: Bloomington Jr. High",
        "Carlos Flores :: Dolton Park Jr. Falcons :: 6",
        "Doug Seehase :: DeKalb WC :: 1",
        "Vern Huff :: Bartonville Blue Crew",
        "Rob Kellermann :: Arlington Cardinals WC",
        "Tom Ames :: Westville Jr. High",
        "Wayne McDaniel :: Indian Trail Jr. High",
        "Tosh Gibbs :: Naperville Patriots :: 4",
        "Tim Koester :: Rockridge Jr. High",
        "Aaron Seim :: DeKalb WC",
        "Alex Cortez :: Lockport Grapplers WC :: 2",
        "Marty Avant :: Mascoutah Jr. High",
        "Mark Mucha :: Franklin Park Raiders",
        "Bret Gautcher :: Sycamore WC :: 3",
        "Bryan Barham :: Crestwood Colts WC",
        "Anthony Marre :: Carol Stream P.D.",
        "Mark Hussar :: Catlin WC :: 5",
        "Matt Moran :: LaGrange Lions",
        "Bret Bievenue :: Bethalto Boys Club",
        "Dave Burbridge :: Geneseo WC",
        "Dan Hannon :: Naperville Patriots",
        "Tim Faley :: Panther Wrestling Club",
    ],
    155: [
        "Bobby Peterson :: Cahokia WC South",
        "Jamie Morris :: Dolton Park Jr. Falcons",
        "Doug Raiser :: Frankfort Falcons",
        "Russ Bannister :: DeKalb WC :: 2",
        "Carl Sebree :: Turk WC",
        "Mike Staffeldt :: Indian Prairie WC",
        "Steve Davis :: Unity Youth WC :: 4",
        "Clint Rafac :: Indian Trail Jr. High",
        "Michael Block :: Panther Wrestling Club",
        "Rovon Jones :: Matburns Wrestling Club :: 6",
        "Gregory Zimmerman :: Villa Lombard WC",
        None,
        "Tyron Washington :: Crestwood Colts WC",
        "Bill Klein :: Mascoutah Jr. High",
        "Marc Jones :: Bloomington Jr. High",
        "Charlie Vedder :: Turk WC :: 3",
        "Bill Sullivan :: Dundee Highlanders :: 5",
        "Jason Nicolls :: LaGrange Lions",
        "George Hollendoner :: Tinley Park Bulldogs :: 1",
        "Travis Smith :: Unity Youth WC",
        "Eric Jerman :: Wood River Marooners",
        "Garett Marquis :: St. Charles J.H. WC",
        "Norbert Buza :: Vittum Cats",
        "Jerry Carlson :: Harlem-Franklin Boys Club",
    ],
    170: [
        "Matt Alli :: Centralia WC",
        "Bill Little :: Dundee Highlanders :: 6",
        None,
        "Brad Kastor :: Geneseo WC :: 2",
        "Eric Evans :: Jefferson Wolverines",
        "Rich Dongus :: Rams WC",
        "Curt Koch :: Lemont Bears WC :: 3",
        "Tin Flynn :: Dolton Park Jr. Falcons",
        "Ryan Wiggins :: DeKalb WC",
        "Jonn Menges :: Bismarck-Henning WC",
        "Jason Owen :: Matburns Wrestling Club",
        "Jeff Sonntag :: Wheaton P.D. Falcons",
        "Doni Swick :: Sycamore WC",
        "Mark Cotter :: Granite City Grigsby WC",
        "Rich Hartman :: Lockport Grapplers WC",
        "Mike Rivera :: J-Hawk WC :: 4",
        "Denzil Batlin :: Moline Spartans :: 5",
        "Tim Caryl :: Mt. Zion WC",
        "James Quarles :: Harvey Twisters :: 1",
        "Colen Bersamin :: Rich Wrestling LTD",
        "Randy Hamilton :: Mascoutah Jr. High",
        "Chuck Vassos :: Arlington Cardinals WC",
        "Thomas Peach :: Georgetown WC",
        "Matt Laughlin :: Jordan WC",
    ],
    185: [
        "Harvie Link, Jr. :: Belleville Little Devils :: 4",
        "Matt Yancick :: Morton Youth WC",
        None,
        "Jerry Vaughan :: Jefferson Wolverines",
        "George Vassos :: Arlington Cardinals WC",
        None,
        "Patrick McDonald :: Harvey Twisters :: 1",
        None,
        "Bill Keltner :: Bartonville Blue Crew",
        "Brian Hand :: Lockport Grapplers WC",
        "David Vaughn :: Bloomington Jr. High",
        "Greg Stec :: LaGrange Lions :: 6",
        "Jason Lewis :: Moline Wildcats :: 3",
        "Matt Cripps :: Murphysboro Jr. High",
        "Erik Whitehead :: Lan-Oak Park District",
        "Hector Figueroa :: Vittum Cats :: 5",
        "Marc Scott :: J-Hawk WC",
        None,
        "Chuck Biyant :: Sycamore WC",
        "Rick Bielema :: Crestwood Colts WC",
        "Howard Dean, III :: Centralia WC",
        "Juan Molina :: Unity Youth WC :: 2",
        "Bryon Koepke :: Rich Wrestling LTD",
        None,
    ],
    275: [
        "Tom Campbell :: Edwardsville WC",
        "Erik Siecynski :: Naperville Wrestlers",
        "Brent Lindenfelser :: Turk WC",
        "Delira Humberto :: Rams WC :: 6",
        "Tom Theonnes :: Bloomington Jr. High",
        None,
        "Curis Tomac :: Lil' Reaper WC :: 3",
        None,
        "Jason Rogers :: Eisenhower Jr. High",
        "Rodd Nesbitt :: Harvey Twisters :: 1",
        "David Wetzel :: Oak Forest Warriors",
        "Rick Feuerhammer :: Gibson City Youth WC",
        "Terence Durkin :: Eisenhower Jr. High :: 4",
        "Kevin Sanders :: Bethalto Boys Club",
        "Toby Mason :: Belvidere Bandits YMCA WC",
        "Gary Cole :: Bismarck-Henning WC :: 2",
        "Mark Kwon :: St. Tarcissus Raiders",
        "Kareem Roberts :: Hazel Crest Jr. Hawks",
        "Travis Leopard :: Rockridge Jr. High",
        "Michael Adams :: H.P. Little Giant WC :: 5",
        "Stan Barnes :: Edwardsville WC",
        "Fredrick Prueter :: Indian Trail Jr. High",
        "John Davis :: St. Bedes WC",
        "Alex Fuentes :: Rams WC",
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "Harvey Twisters": 248.0,
    "Vittum Cats": 165.0,
    "DeKalb WC": 137.5,
    "Geneseo WC": 111.0,
    "Arlington Cardinals WC": 106.0,
    "Panther Wrestling Club": 105.0,
    "Colts WC": 101.0,
    "Tinley Park Bulldogs": 95.0,
    "Villa Lombard WC": 89.0,
    "Frankfort Falcons": 78.0,
    "Moline Wildcats": 75.0,
    "Belvidere Bandits YMCA WC": 71.5,
    "LaGrange Lions": 68.0,
    "Rich Wrestling LTD": 60.5,
    "Dolton Park Jr. Falcons": 58.0,
    "Lil' Reaper WC": 54.5,
    "Eisenhower Jr. High": 53.5,
    "Forman WC": 45.5,
    "Lanphier-Southeast WC": 45.0,
    "Wheaton P.D. Falcons": 45.0,
    "Roxana Jr. High Vikings": 43.0,
    "Unity Youth WC": 43.0,
    "Oak Forest Warriors": 42.0,
    "Oak Park River Forest WC": 41.5,
    "Mattoon WC": 40.0,
    "Orland Park Pioneers": 40.0,
    "Sycamore WC": 40.0,
    "Lan-Oak Park District": 37.0,
    "Dundee Highlanders": 36.5,
    "Turk WC": 33.5,
    "Catlin WC": 33.0,
    "Newman Middle School": 33.0,
    "Rockridge Jr. High": 33.0,
    "Belleville Little Devils": 32.0,
    "Naperville Warhawks": 32.0,
    "Medinah Lancers WC": 31.5,
    "Lemont Bears WC": 31.0,
    "Moline Spartans": 27.5,
    "Bismarck-Henning WC": 26.0,
    "Elgin Matt Rats WC": 25.5,
    "Lockport Grapplers WC": 24.0,
    "Morton Youth WC": 23.5,
    "J-Hawk WC": 23.0,
    "Illinois Valley WC": 22.0,
    "Roxana Roughnecks": 21.5,
    "Naperville Wrestlers": 20.5,
    "Naperville Patriots": 19.0,
    "Rams WC": 17.5,
    "H.P. Little Giant WC": 16.0,
    "Matburns Wrestling Club": 16.0,
    "Crossface WC": 15.0,
    "Danville YMCA WC": 13.5,
    "Oak Lawn PD": 13.0,
    "Centralia WC": 12.0,
    "Dixon WC": 12.0,
    "Georgetown WC": 12.0,
    "Mascoutah Jr. High": 12.0,
    "Westville Jr. High": 12.0,
    "Harvard WC": 11.0,
    "Hoopeston-East Lynn Jr. High": 11.0,
    "Bloomington Jr. High": 10.5,
    "Jordan WC": 10.5,
    "Bethalto Boys Club": 10.0,
    "Round Lake P.D. Spartans": 10.0,
    "Crestwood Colts WC": 8.0,
    "Granite City Grigsby WC": 8.0,
    "Woodstock Cardinals": 8.0,
    "Cahokia WC South": 7.0,
    "Harlem-Franklin Boys Club": 6.5,
    "St. Charles J.H. WC": 6.0,
    "Yorkville WC": 6.0,
    "Bartonville Blue Crew": 4.0,
    "Blackhawk WC": 4.0,
    "Carol Stream P.D.": 4.0,
    "Fisher WC": 4.0,
    "Franklin Park Raiders": 4.0,
    "Gibson City Youth WC": 4.0,
    "Jefferson Wolverines": 4.0,
    "Mt. Zion WC": 4.0,
    "St. Tarcissus Raiders": 4.0,
    "Urbana Kids WC": 4.0,
    "Lawrence County WC": 3.0,
    "Murphysboro Jr. High": 3.0,
    "Rosemont Cobras": 3.0,
    "Tomcat WC": 2.5,
    "Geneva Vikings": 2.5,
    "Chillicothe WC": 2.0,
    "East Moline WC": 2.0,
    "Hickory Hills Park District": 2.0,
    "Naperville Warriors": 2.0,
    "Wood River Marooners": 2.0,
}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    ("Harvie Link, Jr.", "Belleville Little Devils"): bracket_utils.Competitor(
        full_name="Harvie Link, Jr.",
        first_name="Harvie",
        last_name="Link",
        team_full="Belleville Little Devils",
    ),
    ("Howard Dean, III", "Centralia WC"): bracket_utils.Competitor(
        full_name="Howard Dean, III",
        first_name="Howard",
        last_name="Dean",
        team_full="Centralia WC",
    ),
}


def _get_bout_numbers() -> dict[bracket_utils.MatchSlot, int]:
    return {
        "championship_r32_02": 1,
        "championship_r32_04": 2,
        "championship_r32_06": 3,
        "championship_r32_08": 4,
        "championship_r32_10": 5,
        "championship_r32_12": 6,
        "championship_r32_14": 7,
        "championship_r32_16": 8,
        "consolation_fifth_place": 35,
        "consolation_third_place": 36,
        "championship_first_place": 37,
    }


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, score=score)
        )

    weight_classes: list[bracket_utils.WeightClass] = []
    for weight, competitors in _SENIOR_COMPETITORS.items():
        bout_numbers = _get_bout_numbers()
        weight_class = bracket_utils.weight_class_from_competitors(
            "senior",
            weight,
            competitors,
            _SENIOR_TEAM_REPLACE,
            _NAME_EXCEPTIONS,
            bout_numbers,
        )
        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1987.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
