# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils
import manual_entry

_HERE = pathlib.Path(__file__).resolve().parent
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    60: [
        "Adam Wason :: TIGERTOWN TANGLERS",
        "Amador Estrada :: ROUND LAKE SPARTANS",
        "Anthony Doughty :: JR. BISON WC",
        "Anthony Opiola :: DOLTON PARK FALCONS",
        "Bob Catalano :: LANPHIER-SPRINGFIELD WRESTLING",
        "Brenden Joyce :: TOMCAT WC",
        "Chad Karlen :: ROUND LAKE SPARTANS",
        "Eugene Sacco :: FRANKLIN PARK RAIDERS",
        "Frank Stanke :: MAINE TOWNSHIP EAGLES",
        "Grant Hoerr :: CHILLICOTHE WC",
        "John Murphy :: LOCKPORT GRAPPLERS WC",
        "Justin Henry :: BELLEVILLE LITTLE DEVILS",
        "Kenny Chrisman :: DOLTON PARK FALCONS",
        "Leonard Bowens :: HARVEY PARK DISTRICT TWISTERS",
        "Michael Mathews :: NAPERVILLE PATRIOTS WRESTLING",
        "Michael Murphy Jr. :: LOCKPORT GRAPPLERS WC",
        "Raymond Keeler :: DOLTON PARK FALCONS",
        "Rick McDonald :: CROSSFACE WC",
        "Roy Pierce :: SPARTANS WC",
        "Ryan Rumfelt :: BETHALTO BOYS CLUB BULLS",
        "Steve Wernsman :: YORKVILLE WC",
        "Todd Combes :: DOLTON PARK FALCONS",
        "Tony Skinner :: WESTVILLE JR. HIGH",
        "Vince Chambliss :: CATLIN YOUTH WC",
    ],
    64: [
        "Adam Jones :: PEORIA RAZORBACKS YOUTH WC",
        "Archie Griffin :: OAK PARK RIVER FOREST WARHAWKS",
        "Brad Prunty :: MACOMB YMCA KIDS WRESTLING",
        "Brad Vermillion :: DUNDEE HIGHLANDERS",
        "Brian Comstock :: ST. CHARLES WC",
        "Brian Wilson :: DUNDEE HIGHLANDERS",
        "Chris Bonati :: DUNDEE HIGHLANDERS",
        "Daniel Forystek :: THORNWOOD KIDS WC",
        "David Douglas :: HARVEY PARK DISTRICT TWISTERS",
        "Eric Henry :: REDBIRD WC",
        "Gerry Hilton :: THORNWOOD KIDS WC",
        "Jason Malmstrom :: OSWEGO PANTHERS",
        "Jerry Clemeniz :: GENESEO WC",
        "Juan Salgado :: JR. BISON WC",
        "Matt Goldstein :: LITTLE GIANTS WC",
        "Mike Smith :: BETHALTO BOYS CLUB BULLS",
        "Moses Reed :: DANVILLE WC",
        "Nicholas Delisle :: RAIDER WC",
        "Pat Gaskin :: ST. BARNABAS / CHRIST THE KING",
        "Patrick Wrona :: DOLTON PARK FALCONS",
        "Paul Garbis :: INDIAN PRAIRIE TRAILBLAZERS",
        "Ronnie Dalluge :: MT. ZION WC",
        "Ryan De Lira :: DOLTON PARK FALCONS",
        "Sean Hastings :: VITTUM CATS",
    ],
    68: [
        "Aaron Gilson :: ST. CHARLES WC",
        "Adam Dyche :: AURORA J-HAWKS",
        "Ben Black :: HINSDALE RED DEVIL WC",
        "Brian Hastings :: VITTUM CATS",
        "Chris Tompson :: CUMBERLAND COUNTY WC",
        "Chris Traversa :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Craig Lorek :: JR. BISON WC",
        "Danny Borland :: BLUE CREW WRESTLING CLUB",
        "Francisco Bermudez :: LOCKPORT GRAPPLERS WC",
        "Ike Sullivan :: BETHALTO BOYS CLUB BULLS",
        "J.C. Gaunt :: GOLDEN EAGLES",
        "Jason Lau :: VITTUM CATS",
        "Jim Aberle :: ROUND LAKE SPARTANS",
        "Joel Howard :: NAPERVILLE PATRIOTS WRESTLING",
        "Lawan Gray :: OAK PARK RIVER FOREST WARHAWKS",
        "Lucas Alt :: HOOPESTON-EAST LYNN JR. HIGH",
        "Marc Zehr :: ARLINGTON CARDINALS WC",
        "Matt Nelson :: CHILLICOTHE WC",
        "Michael Bondi :: DUNDEE HIGHLANDERS",
        "Mike Nelson :: REDBIRD WC",
        "Milton Blakely :: HARVEY PARK DISTRICT TWISTERS",
        "Phillip J. Foster :: NEWMAN BLUE DEVILS",
        "Ryan Mason :: SYCAMORE WC",
        "Tim Donohoo :: BETHALTO BOYS CLUB BULLS",
    ],
    72: [
        "Alan Cartwright :: OAK PARK RIVER FOREST WARHAWKS",
        "Berry Chapman :: ROUND LAKE SPARTANS",
        "Bill Kucinski :: VITTUM CATS",
        "Billy Bryant :: BETHALTO BOYS CLUB BULLS",
        "Brad Becker :: BETHALTO BOYS CLUB BULLS",
        "Brian Joseph :: GENEVA PARK DISTRICT",
        "Chris Yourgalite :: HOOPESTON-EAST LYNN JR. HIGH",
        "Craig Gillum :: METAMORA KIDS WC",
        "Ian Penzato :: VILLA-LOMBARD COUGARS",
        "Jacob Doody :: ST. BARNABAS / CHRIST THE KING",
        "Jim Gahagan :: VITTUM CATS",
        "Jim Jones :: ROUND LAKE SPARTANS",
        "John Heathcott :: EDWARDSVILLE",
        "Justin Dyer :: ANTIOCH UPPER GRADE",
        "Kevin Wilson :: MATTOON WC",
        "Luke Ewanio :: ROSEMONT COBRAS WRESTLING",
        "Matthew Wegner :: WARRIOR WC (NILES)",
        "Michael Galvin :: FORMAN WC",
        "Nick Hoehn :: TINLEY PARK BULLDOGS",
        "Scooter Gregory :: OSWEGO COUGARS",
        "Scott Ginger :: REDBIRD WC",
        "Tim Glover :: MORTON YOUTH WRESTLING",
        "Tommy Lee :: OAK FOREST WARRIORS",
        "Tony Davis :: HARVEY PARK DISTRICT TWISTERS",
    ],
    77: [
        "Alan Wilson :: DUNDEE HIGHLANDERS",
        "Andrew Blickensderfer :: MT. ZION WC",
        "Andrew Omalley :: ST. BARNABAS / CHRIST THE KING",
        "Blake Hoerr :: CHILLICOTHE WC",
        "David Kabbe :: NAPERVILLE WARRIORS",
        "Don Bermudez :: LOCKPORT GRAPPLERS WC",
        "Durand Womack :: HARVEY PARK DISTRICT TWISTERS",
        "Jared Camer :: MUSTANG WC",
        "Jason Christeson :: BETHALTO BOYS CLUB BULLS",
        "Jeff Wilson :: MT. ZION WC",
        "Jim Brasher :: VITTUM CATS",
        "John Kopecky :: ROSEMONT COBRAS WRESTLING",
        "Justin Henry :: WEST CHICAGO WILDCATS P.D.",
        "Kevin Milligan :: VILLA-LOMBARD COUGARS",
        "Marc Wegner :: WARRIOR WC (NILES)",
        "Mike Harrington :: ROUND LAKE SPARTANS",
        "Mike Hasty :: MORTON YOUTH WRESTLING",
        "Philip Thorne :: OAK FOREST WARRIORS",
        "Robby Pyfer :: HARLEM-PARK BOYS CLUB",
        "Thomas Grennan :: NEWMAN BLUE DEVILS",
        "Tim Vediz :: EDWARDSVILLE",
        "Tony Niebur :: REDBIRD WC",
        "Travis Zimmerman :: BETHALTO BOYS CLUB BULLS",
        "William Tyler :: OAK PARK RIVER FOREST WARHAWKS",
    ],
    82: [
        "Bradley Schnowske :: GENESEO WC",
        "Chris Donohoo :: ROXANA VIKINGS",
        "Derek Starr :: HINSDALE RED DEVIL WC",
        "Griff Powell :: ARLINGTON CARDINALS WC",
        "Jake Griffin :: OAK FOREST WARRIORS",
        "Jason Heefner :: REDBIRD WC",
        "Jason Pero :: HARVEY PARK DISTRICT TWISTERS",
        "Javier Quintanilla :: TOMCAT WC",
        "Jon Bergen :: CHILLICOTHE WC",
        "Jon Swanson :: MT. ZION WC",
        "Josh Inch :: GENESEO WC",
        "Luke Rives :: BETHALTO BOYS CLUB BULLS",
        "Mark Schaefer :: WHEATON-WARRENVILLE WC",
        "Michael Shields :: BELLEVILLE LITTLE DEVILS",
        "Mike Oneill :: TINLEY PARK BULLDOGS",
        "Patrick Sheahan :: ST. BARNABAS / CHRIST THE KING",
        "Rafael Avila :: BELVIDERE YMCA BANDITS",
        "Reginald Wright :: OAK PARK RIVER FOREST WARHAWKS",
        "Richard Root :: LANPHIER-SPRINGFIELD WRESTLING",
        "Robert Meek :: LEMONT WC",
        "Roberto Rodriguez :: HARLEM-PARK BOYS CLUB",
        "Ryan Duggan :: ST. TARCISSUS RAIDERS",
        "Tim Ottolson :: PANTHER WC",
        "Ty Powers :: HARLEM-PARK BOYS CLUB",
    ],
    87: [
        "Aaron Ehle :: HARLEM-PARK BOYS CLUB",
        "Andrew Shandor :: REDBIRD WC",
        "Anuj Maniar :: MEADE JR. WC",
        "Gregory Voegtle :: BELLEVILLE LITTLE DEVILS",
        "Jeff Swanson :: MORTON YOUTH WRESTLING",
        "John Rogers :: TRI-CITY BRAVES",
        "Josh Griffin :: OAK FOREST WARRIORS",
        "Karl Hofbauer :: OAK FOREST WARRIORS",
        "Mark Bybee :: VITTUM CATS",
        "Mark McMenimen :: CROSSFACE WC",
        "Mark Pishotta :: ROSEMONT COBRAS WRESTLING",
        "Michael Brucker :: GEORGETOWN WC",
        "Mike Pryor :: BETHALTO BOYS CLUB BULLS",
        "Richard Berendson :: WEST CHICAGO WILDCATS P.D.",
        "Robbie Cox :: BELVIDERE YMCA BANDITS",
        "Ronnie Hansen :: EDWARDSVILLE",
        "Shaun Bouback :: BELVIDERE YMCA BANDITS",
        "Steve Marvin :: DANVILLE WC",
        "Steve Wallace :: BLACKHAWK WC",
        "Steven Craig :: FRANKLIN PARK RAIDERS",
        "Steven Molinari :: VILLA-LOMBARD COUGARS",
        "Terry Obrien :: PANTHER WC",
        "Tim Gaskin :: ST. BARNABAS / CHRIST THE KING",
        "Tyler Hurry :: RIVERDALE JR. HIGH WC",
    ],
    93: [
        "Andrew Heilemeier :: DAKOTA MATT RATS",
        "Bob Johnson :: WARHAWK WC",
        "Brian Davis :: NEWMAN BLUE DEVILS",
        "Bryon Krummelbein :: BETHALTO BOYS CLUB BULLS",
        "Chad Hawkins :: BISMARCK-HENNING WRESTLING",
        "Dan Collins :: ARLINGTON CARDINALS WC",
        "Danny Otero :: GORDON TECH RAMS WC CHICAGO",
        "Eric Scroggins :: AURORA J-HAWKS",
        "Eric Tempel :: UNITY YOUTH",
        "James Crnich :: OAK FOREST WARRIORS",
        "Jason Eierman :: MUSTANG WC",
        "Joseph Opiola :: DOLTON PARK FALCONS",
        "Karmen Bradshaw :: HARVEY PARK DISTRICT TWISTERS",
        "Ken Biala :: VILLA-LOMBARD COUGARS",
        "Kyle Bollinger :: TRIMPE JUNIOR HIGH",
        "Leon Ramsey :: AURORA J-HAWKS",
        "Mark Jones :: HARVARD WC",
        "Matthew Webster :: PEORIA RAZORBACKS YOUTH WC",
        "Michael Banfield :: TRIMPE JUNIOR HIGH",
        "Ryan Lee :: ROSEMONT COBRAS WRESTLING",
        "Stephen Stanley :: MATTOON WC",
        "TJ Watts :: FORMAN WC",
        "Timothy Donnahue :: PANTHER WC",
        "Timothy Miller :: PLAINFIELD INDIAN TRAIL WILDCATS",
    ],
    99: [
        "Ben Gerdes :: ORLAND PARK PIONEERS",
        "Ben Niles :: YORKVILLE WC",
        "Ben Sollars :: HOOPESTON-EAST LYNN JR. HIGH",
        "Brody Rude :: NEWMAN BLUE DEVILS",
        "Danny Javanovic :: DOLTON PARK FALCONS",
        "David Hoenig :: HICKORY HILLS PARK DISTRICT",
        "Dino Kokkines :: PALATINE P.D. SUNDLING",
        "Jarvis Wardlow :: OAK PARK RIVER FOREST WARHAWKS",
        "Jason Osterhoff :: ARGENTA-OREANA WC",
        "Jermaine White :: OAK PARK RIVER FOREST WARHAWKS",
        "Jerry Swift :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Jose Barrera :: BELVIDERE YMCA BANDITS",
        "Jose Villarreal :: LIL' REAPER",
        "Matt Longton :: ELGIN GRAPPLERS",
        "Michael Overby :: WEST FRANKFORT WRESTLING",
        "Mike Greenfield :: BELLEVILLE LITTLE DEVILS",
        "Randall Richardson :: METAMORA KIDS WC",
        "Richie Marmolejo :: WEST CHICAGO WILDCATS P.D.",
        "Robert Serio :: CAROL STREAM P.D. PANTHERS",
        "Scott Benjamin :: CATLIN YOUTH WC",
        "Shane Zorbrist :: GRANITE CITY WC COOLIDGE",
        "Steve Torres :: VITTUM CATS",
        "Timothy Williams :: HARVEY PARK DISTRICT TWISTERS",
        "Tony Didonato :: PEKIN BOY'S CLUB",
    ],
    105: [
        "Arean Arechiga :: THORNWOOD KIDS WC",
        "Bob Remily :: HARLEM-PARK BOYS CLUB",
        "Charles Crescenzo :: LINCOLN WAY AREA WRESTLING",
        "Chris Carlisle :: TRIMPE JUNIOR HIGH",
        "Chuck Powell :: HOOPESTON-EAST LYNN JR. HIGH",
        "Curtis Owen :: FRANKLIN PARK RAIDERS",
        "Cyril Strezo :: DOLTON PARK FALCONS",
        "Drek Santiago :: AURORA J-HAWKS",
        "Eric Griffin :: RIVERDALE JR. HIGH WC",
        "Frank Lamie :: BRADLEY BOURBONNAIS WC",
        "Jason Coleman :: ST. CHARLES WC",
        "Jeremy Christeson :: BETHALTO BOYS CLUB BULLS",
        "Joe Kalous :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Jon Clauson :: ILLINI BLUFFS WC",
        "Joseph Brauer :: PANTHER WC",
        "Matt Becker :: ELGIN GRAPPLERS",
        "Matt Ferguson :: BELLEVILLE LITTLE DEVILS",
        "Matt Goncher :: BLACKHAWK WC",
        "Michael Rosengrant :: WARRIOR WC (NILES)",
        "Ricky Avila :: BELVIDERE YMCA BANDITS",
        "Ryan Ewanio :: ROSEMONT COBRAS WRESTLING",
        "Sam Watts :: FORMAN WC",
        "Thomas Combes :: DOLTON PARK FALCONS",
        "Troy Brigham :: GEORGETOWN WC",
    ],
    112: [
        "Aaron Jacobs :: MURPHYSBORO JR. HIGH",
        "Aaron Mihaljevich :: CALUMET MEMORIAL PARK DISTRICT",
        "Ben Ancona :: GOLDEN EAGLES",
        "Brock Baer :: ELGIN GRAPPLERS",
        "Charles Damptz :: JEFFERSON WOLVERINES",
        "Chris Papanek :: MEADE JR. WC",
        "Clayton Reed :: UNITY YOUTH",
        "Dan Schmidt :: MOLINE TIGERS",
        "David Rivera :: DOLTON PARK FALCONS",
        "Edward Rivera :: AURORA J-HAWKS",
        "Jason Miller :: HOOPESTON-EAST LYNN JR. HIGH",
        "Jeremy Neufeld :: OAK FOREST WARRIORS",
        "Jesse Carmack :: BELLEVILLE LITTLE DEVILS",
        "Joe Minott :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Joe Pierce :: ADDAMS JR. HIGH SCHOOL W.C.",
        "Kristian Wahlgren :: TIGERTOWN TANGLERS",
        "Manuel Villarreal :: ARLINGTON CARDINALS WC",
        "Mike Bertoni :: VITTUM CATS",
        "Richard Weber :: ANTIOCH UPPER GRADE",
        "Rick Babb :: CHILLICOTHE WC",
        "Ryan Seloover :: DUNDEE HIGHLANDERS",
        "Steve Carroll :: DOLTON PARK FALCONS",
        "Tim Forgey :: DECATUR WC",
        "Tom Hisey :: WEST CHICAGO WILDCATS P.D.",
    ],
    119: [
        "Adam Witsken :: BETHALTO BOYS CLUB BULLS",
        "Andy Royce :: MOLINE TIGERS",
        "Ben Palmer :: HARVARD WC",
        "Brett Gautcher :: SYCAMORE WC",
        "Brian Martin :: EDWARDSVILLE",
        "Clint Clevenger :: BRADLEY BOURBONNAIS WC",
        "Daman Montello :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "David Gierke :: FRANKLIN PARK RAIDERS",
        "Issac Hampton :: CALUMET MEMORIAL PARK DISTRICT",
        "Jim Dieringer :: ARLINGTON CARDINALS WC",
        "Jim Leduc :: INDIAN PRAIRIE TRAILBLAZERS",
        "Jon Bussert :: RIVERDALE JR. HIGH WC",
        "Josh Pearson :: TRI-CITY BRAVES",
        "Joshua Clark :: CHILLICOTHE WC",
        "Kenneth Mills :: DOLTON PARK FALCONS",
        "Marcos Navarro :: GORDON TECH RAMS WC CHICAGO",
        "Mare Hornsby :: ELGIN MATT RATS",
        "Matt Berg :: ARGENTA-OREANA WC",
        "Michael Murdough :: ST. CHARLES WC",
        "Ron Stonitsch :: CRESTWOOD COLTS WC",
        "Ruben Saldana :: TOMCAT WC",
        "Ryan Casey :: ST. BARNABAS / CHRIST THE KING",
        "Ryan Reinhart :: UNITY YOUTH",
        "Travis Kassing :: BELLEVILLE LITTLE DEVILS",
    ],
    127: [
        "Brandon Presern :: FRANKLIN PARK RAIDERS",
        "Brett Mason :: WEST FRANKFORT WRESTLING",
        "Brian McCollum :: HARLEM-PARK BOYS CLUB",
        "Bryan Medlin :: MORTON YOUTH WRESTLING",
        "Colin Thompson :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Craig Padgett :: CRESTWOOD COLTS WC",
        "Daniel Moynihan :: ARLINGTON CARDINALS WC",
        "Ernie Slavik :: ANTIOCH UPPER GRADE",
        "Gerardo Quintanilla :: TOMCAT WC",
        "Jeff Defauw :: GENESEO WC",
        "Lance Douglas :: MARQUART MIDDLE JR. HIGH",
        "Leslie Whittake :: BELLEVILLE LITTLE DEVILS",
        "Matt Frego :: NAPERVILLE LANCERS",
        "Matt McDonnell :: NEWMAN BLUE DEVILS",
        "Mike Powell :: OAK PARK RIVER FOREST WARHAWKS",
        "Robert Porter :: GRANITE CITY WC COOLIDGE",
        "Ryan Daprile :: LIONS WC",
        "Shane York :: HOOPESTON-EAST LYNN JR. HIGH",
        "Shawn Stafford :: HICKORY HILLS PARK DISTRICT",
        "Shay Hawkins :: RICH WRESTLING LTD.",
        "Tim Angsten :: TINLEY PARK BULLDOGS",
        "Tim Davis :: ARGENTA-OREANA WC",
        "Todd Madden :: SYCAMORE WC",
        "Willie Morris :: DANVILLE WC",
    ],
    135: [
        "Austin Collins :: FRANKLIN PARK RAIDERS",
        "Bill Schaack :: CRESTWOOD COLTS WC",
        "Brent Rogers :: EDWARDSVILLE",
        "Brian Proffitt :: EDWARDSVILLE",
        "C.J. Protsman :: MACOMB YMCA KIDS WRESTLING",
        "Cody Lewis :: CUMBERLAND COUNTY WC",
        "David Migut :: HICKORY HILLS PARK DISTRICT",
        "Dean Bielawa :: ARLINGTON CARDINALS WC",
        "Denny Hartwig :: OAK FOREST WARRIORS",
        "Jason Yarber :: GRANITE CITY WC COOLIDGE",
        "Jeffrey Garretson :: STREATOR JUNIOR BULLDOGS",
        "Joshua Thalman :: KNIGHTS WC",
        "Kevin Singletary :: ORLAND PARK PIONEERS",
        "Khamla Sounthala :: MARQUART MIDDLE JR. HIGH",
        "Kirk Gill :: DOLTON PARK FALCONS",
        "Matt Hayes :: ELGIN MATT RATS",
        "Mike Etzkorn :: LEMONT WC",
        "Scott Borota :: HARLEM-PARK BOYS CLUB",
        "Shane Hudnall :: GENESEO WC",
        "Shane Richards :: OAKWOOD WC",
        "Steve Bailey :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Steve Pawlak :: VILLA-LOMBARD COUGARS",
        "Steven Froelich :: MEADE JR. WC",
        "William York :: GEORGETOWN WC",
    ],
    144: [
        "Brandon Odaniel :: ORLAND PARK PIONEERS",
        "Chris Timmons :: HOOPESTON-EAST LYNN JR. HIGH",
        "Dave Cardin :: METAMORA KIDS WC",
        "Derek Meadows :: TAYLORVILLE WC",
        "Dino Cece :: HINSDALE RED DEVIL WC",
        "Eric Chappel :: CARBONDALE WC",
        "Jacob Csiszer :: LIL' REAPER",
        "Jason Salley :: EISENHOWER JR. HIGH WC",
        "Jeff Witter :: GRANITE CITY WC GRIGSBY",
        "Jeremy Judd :: LIL' REAPER",
        "Kori Hooe :: JOLIET BOYS CLUB COBRAS",
        "Lenny Walker :: LEMONT WC",
        "Matt Burdette :: PEKIN BOY'S CLUB",
        "Matt Carison :: NAPERVILLE PATRIOTS WRESTLING",
        "Michael Burlack :: CAROL STREAM P.D. PANTHERS",
        "Mike Chance :: PEORIA RAZORBACKS YOUTH WC",
        "Mike Clark :: PALATINE P.D. CHARGERS",
        "Ray Todd Guzak :: CRESTWOOD COLTS WC",
        "Robert Carlson :: ORLAND PARK PIONEERS",
        "Robert Wright :: WESTVILLE JR. HIGH",
        "Ryan Beivenue :: TRIMPE JUNIOR HIGH",
        "Ryan Pape :: FRANKLIN PARK RAIDERS",
        "Sean Pruden :: WOODSTOCK CARDINAL WRESTLING",
        "Tony Volini :: HINSDALE RED DEVIL WC",
    ],
    153: [
        "Aaron Wright :: TRIAD WC",
        "Bob Nelson :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Brandon Dahlke :: AURORA J-HAWKS",
        "Brian Billett :: HICKORY HILLS PARK DISTRICT",
        "Brian Dill :: CENTRALIA WC",
        "Clifton Oliviel :: TRI-CITY BRAVES",
        "Curtis Berry :: TRI-CITY BRAVES",
        "Dan Green :: DAKOTA MATT RATS",
        "David Hanchrr :: WARRIOR WC (NILES)",
        "Dean Phillips :: JR. BISON WC",
        "Jason Dillingham :: UNITY YOUTH",
        "Jason Finks :: KNIGHTS WC",
        "Jason Slavicek :: LEMONT WC",
        "Jeff Harrington :: INDIAN PRAIRIE TRAILBLAZERS",
        "Jessie Jr. Whitton :: EL PASO WRESTLING",
        "John Rupprecht :: GENESEO WC",
        "Jose Medina :: GORDON TECH RAMS WC CHICAGO",
        "Joshua Slaten :: WOODSTOCK CARDINAL WRESTLING",
        "Kevin Powers :: DOLTON PARK FALCONS",
        "Matthew Beeler :: MATTOON WC",
        "Ryan Ahring :: EDWARDSVILLE",
        "Scott Reed :: TIGERTOWN TANGLERS",
        "Tommy McHarry :: UNITY YOUTH",
        "William Arthur :: VITTUM CATS",
    ],
    163: [
        "Andy Donaldson :: MEADE JR. WC",
        "Brian Smith :: TIGERTOWN TANGLERS",
        "Brian Woodley :: DAKOTA MATT RATS",
        "Chris Williams :: INDIAN PRAIRIE PIONEERS",
        "D.J. Brigham :: TIGERTOWN TANGLERS",
        "Dan Volpentesta :: LITTLE GIANTS WC",
        "Floyd Smith :: RICH WRESTLING LTD.",
        "Ilija Dragisic :: JR. FALCON WRESTLING",
        "Jason Tebbe :: HIGHLAND JUNIOR BULLDOGS",
        "Jeff Chandler :: HOOPESTON-EAST LYNN JR. HIGH",
        "Jeff Heavrin :: OAK PARK RIVER FOREST WARHAWKS",
        "John Koitz :: HARVARD WC",
        "John Sherrill :: MURPHYSBORO JR. HIGH",
        "Lewis Lang :: RICH WRESTLING LTD.",
        "Michael Acord :: WESTVILLE JR. HIGH",
        "Michael Smith :: DAKOTA MATT RATS",
        "Nathan Kincade :: TRIMPE JUNIOR HIGH",
        "PJ McEnroe :: BLACKHAWK WC",
        "Paul Naumowicz :: PANTHER WC",
        "Philip Buck :: CROSSFACE WC",
        "Ray Jebsen :: TINLEY PARK BULLDOGS",
        "Richard Hunt :: DOLTON PARK FALCONS",
        "Scott Wulff :: OSWEGO PANTHERS",
        "Sean Denton :: BRADLEY BOURBONNAIS WC",
    ],
    173: [
        "Chris McCay :: HOOPESTON-EAST LYNN JR. HIGH",
        "Chuck Morin :: INDIAN PRAIRIE TRAILBLAZERS",
        "Douglas Roderick :: BISMARCK-HENNING WRESTLING",
        "Glen Humphrey :: AURORA J-HAWKS",
        "Jason Middleton :: GRANITE CITY WC GRIGSBY",
        "Jon Danao :: MARQUART MIDDLE JR. HIGH",
        "Jose Saucedo :: HARVARD WC",
        "Keith Heiy :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Kelly Feltes :: TRIMPE JUNIOR HIGH",
        "Ken Keltnee :: BLUE CREW WRESTLING CLUB",
        "Ken Robinson :: ST. CHARLES WC",
        "Kris Hermansen :: LEMONT WC",
        "Larry Fong :: MEADE JR. WC",
        "Mark Conmy :: PALATINE P.D. CHARGERS",
        "Matthew Weidner :: GIBSON CITY YOUTH WRESTLING",
        "Mike Shea :: ANTIOCH UPPER GRADE",
        "Phillip Grandfield :: MT. ZION WC",
        "Pip Gray :: TRI-CITY BRAVES",
        "Roy Vix :: CAROL STREAM P.D. PANTHERS",
        "Scott Owen :: FRANKLIN PARK RAIDERS",
        "Sheamus Fergus :: MATBURNS WC",
    ],
    185: [
        "Andy Sutt :: GOLDEN EAGLES",
        "Brian Washington :: DOLTON PARK FALCONS",
        "Charlie Ellis :: CALUMET MEMORIAL PARK DISTRICT",
        "Chris Hagg :: ANTIOCH UPPER GRADE",
        "David Meroni :: NAPERVILLE PATRIOTS WRESTLING",
        "David Miller :: AURORA J-HAWKS",
        "David Yokley :: UNITY YOUTH",
        "Don Madenis :: HARVARD WC",
        "James Choate :: LIL' REAPER",
        "Jeffrey Rohde :: YORKVILLE WC",
        "Jeremy Harter :: BISMARCK-HENNING WRESTLING",
        "Jim Witte :: ADDAMS JR. HIGH SCHOOL W.C.",
        "John Haar :: BELLEVILLE LITTLE DEVILS",
        "Johnathan Rutledge :: JR. BISON WC",
        "Johnny Jaworski :: OAK FOREST WARRIORS",
        "Kyle Feltes :: TRIMPE JUNIOR HIGH",
        "L.T. Garrett :: HOOPESTON-EAST LYNN JR. HIGH",
        "Mark Harvey :: MT. ZION WC",
        "Matt Riney :: RIVERDALE JR. HIGH WC",
        "Nathan Shelton :: AURORA J-HAWKS",
        "Neil Dicka NN :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Nicholas Fulara :: ST. TARCISSUS RAIDERS",
        "Peter Wildermuth :: RIVERDALE JR. HIGH WC",
        "Steve Ritter :: RAIDER WC",
    ],
    275: [
        "Albert Licka :: CAROL STREAM P.D. PANTHERS",
        "Armenoius Griham :: URBANA KIDS WC",
        "Brett George :: FRANKLIN PARK RAIDERS",
        "Cameron Randolf :: HARVEY PARK DISTRICT TWISTERS",
        "Cory Martin :: DELAVAN MAT WRATS",
        "Fred Larson :: MOLINE TIGERS",
        "Jeff Sticht :: BETHALTO BOYS CLUB BULLS",
        "Jerry Jontry :: ARGENTA-OREANA WC",
        "Joe De Voss Jr. :: RIVERDALE JR. HIGH WC",
        "John Bettasso :: ANTIOCH UPPER GRADE",
        "Jon Jordan :: MT. ZION WC",
        "Mark Prehar :: LITTLE GIANTS WC",
        "Matt Bolandis :: GRANITE CITY WC COOLIDGE",
        "Miguel Carreno :: LIL' REAPER",
        "Mike Johnson :: TRI-CITY BRAVES",
        "Patrick Parham :: TRI-CITY BRAVES",
        "Peter Marx :: EISENHOWER JR. HIGH WC",
        "Raymond Holden :: PLAINFIELD INDIAN TRAIL WILDCATS",
        "Richard Reynolds :: AURORA J-HAWKS",
        "Rick Starr :: CENTRALIA WC",
        "Seneca Carey :: DOLTON PARK FALCONS",
        "Spyros Fetsis :: MATBURNS WC",
        "Ted Stec :: LIONS WC",
        "Tommy Rush :: AURORA J-HAWKS",
    ],
}
_SENIOR_PLACERS: dict[int, list[bracket_utils.Placer]] = {
    64: [
        bracket_utils.Placer(name="Matt Goldstein", team="Little Giants WC"),
        bracket_utils.Placer(
            name="David Douglas", team="Harvey Park District Twisters"
        ),
        bracket_utils.Placer(name="Sean Hastings", team="Vittum Cats"),
        bracket_utils.Placer(name="Chris Bonati", team="Dundee Highlanders"),
        bracket_utils.Placer(name="Gerry Hilton", team="Thornwood Kids WC"),
        bracket_utils.Placer(name="Ryan DeLira", team="Dolton Park Falcons"),
    ],
    68: [
        bracket_utils.Placer(name="Marc Zehr", team="Arlington Cardinals"),
        bracket_utils.Placer(name="Francisco Bermudez", team="Lockport Grapplers WC"),
        bracket_utils.Placer(name="Danny Borland", team="Blue Crew WC"),
        bracket_utils.Placer(name="Jim Aberle", team="Round Lake Spartans"),
        bracket_utils.Placer(
            name="Milton Blakely", team="Harvey Park District Twisters"
        ),
        bracket_utils.Placer(name="Joel Howard", team="Naperville Patriots WC"),
    ],
    72: [
        bracket_utils.Placer(name="Tony Davis", team="Harvey Park District Twisters"),
        bracket_utils.Placer(name="Jim Gahagan", team="Vittum Cats"),
        bracket_utils.Placer(name="Matthew Wegner", team="Warrior WC Niles"),
        bracket_utils.Placer(name="Alan Cartwright", team="OPRF Warhawks"),
        bracket_utils.Placer(name="Tommy Lee", team="Oak Forest Warriors"),
        bracket_utils.Placer(name="Tim Glover", team="Morton Youth Wrestling"),
    ],
    77: [
        bracket_utils.Placer(name="Don Bermudez", team="Lockport Grapplers WC"),
        bracket_utils.Placer(name="Thomas Grennan", team="Newman Blue Devils"),
        bracket_utils.Placer(name="Blake Hoerr", team="Chillicothe Wrestling"),
        bracket_utils.Placer(
            name="Durand Womack", team="Harvey Park District Twisters"
        ),
        bracket_utils.Placer(name="Jim Brasher", team="Vittum Cats"),
        bracket_utils.Placer(name="Andrew O'Malley", team="St. Barnabas"),
    ],
    82: [
        bracket_utils.Placer(name="Jason Pero", team="Harvey Park District Twisters"),
        bracket_utils.Placer(name="Javier Quintanilla", team="Tomcat WC"),
        bracket_utils.Placer(name="Bradley Schnowske", team="Geneseo WC"),
        bracket_utils.Placer(name="Patrick Sheahan", team="St. Barnabas"),
        bracket_utils.Placer(name="Rafael Avila", team="Belvidere YMCA Bandits"),
        bracket_utils.Placer(name="Reginald Wright", team="OPRF Warhawks"),
    ],
    87: [
        bracket_utils.Placer(name="Tyler Hurry", team="Riverdale Jr. High WC"),
        bracket_utils.Placer(name="Mark Bybee", team="Vittum Cats"),
        bracket_utils.Placer(name="Terry O'Brien", team="Panther WC"),
        bracket_utils.Placer(name="Ronnie Hansen", team="Edwardsville"),
        bracket_utils.Placer(name="Mark Pishotta", team="Rosemont Cobras WC"),
        bracket_utils.Placer(name="Robbie Cox", team="Belvidere YMCA Bandits"),
    ],
    93: [
        bracket_utils.Placer(name="Dan Collins", team="Arlington Cardinals"),
        bracket_utils.Placer(name="James Crnich", team="Oak Forest Warriors"),
        bracket_utils.Placer(name="Joseph Opiola", team="Dolton Park Falcons"),
        bracket_utils.Placer(name="Stephen Stanley", team="Mattoon WC"),
        bracket_utils.Placer(name="Ken Biala", team="Villa-Lombard Cougars"),
        bracket_utils.Placer(
            name="Timothy Miller", team="Plainfield Indian Trail Wrest."
        ),
    ],
    99: [
        bracket_utils.Placer(
            name="Timothy Williams", team="Harvey Park District Twisters"
        ),
        bracket_utils.Placer(name="Ben Gerdes", team="Orland Park Pioneers"),
        bracket_utils.Placer(name="Scott Benjamin", team="Catlin Youth WC"),
        bracket_utils.Placer(name="Danny Jovanovic", team="Dolton Park Falcons"),
        bracket_utils.Placer(name="Jermaine White", team="OPRF Warhawks"),
        bracket_utils.Placer(name="Brody Rude", team="Newman Blue Devils"),
    ],
    105: [
        bracket_utils.Placer(name="Thomas Combes", team="Dolton Park Falcons"),
        bracket_utils.Placer(name="Sam Watts", team="Foreman WC"),
        bracket_utils.Placer(name="Curtis Owen", team="Franklin Park Raiders"),
        bracket_utils.Placer(name="Ryan Ewanio", team="Rosemont Cobras WC"),
        bracket_utils.Placer(name="Bob Remily", team="Harlem Park Boys Club"),
        bracket_utils.Placer(name="Aren Arechiga", team="Thornwood Kids WC"),
    ],
    112: [
        bracket_utils.Placer(name="Manuel Villarreal", team="Arlington Cardinals"),
        bracket_utils.Placer(name="Kristian Wahlgren", team="Tigertown Tanglers"),
        bracket_utils.Placer(name="Jeremy Neufeld", team="Oak Forest Warriors"),
        bracket_utils.Placer(name="Dan Schmidt", team="Moline Tigers"),
        bracket_utils.Placer(
            name="Aaron Mihaljevich.", team="Cal. Mem. Pk. Dist. Wolv."
        ),
        bracket_utils.Placer(name="Chris Papanek", team="Mead Jr. WC"),
    ],
    119: [
        bracket_utils.Placer(name="Ron Stonitsch", team="Crestwood Colts WC"),
        bracket_utils.Placer(name="Ryan Casey", team="St. Barnabas"),
        bracket_utils.Placer(name="Ruben Saldana", team="Tomcat WC"),
        bracket_utils.Placer(name="Ryan Reinhart", team="Unity Youth"),
        bracket_utils.Placer(name="Jim Leduc", team="Indian Prairie Trailblazers"),
        bracket_utils.Placer(name="Brian Martin", team="Edwardsville"),
    ],
    127: [
        bracket_utils.Placer(name="Gerardo Quintanilia", team="Tomcat WC"),
        bracket_utils.Placer(name="Matt McDonnell", team="Newman Blue Devils"),
        bracket_utils.Placer(name="Mike Powell", team="Oak Park River Forest Warhawks"),
        bracket_utils.Placer(name="Willie Morris", team="Danville WC"),
        bracket_utils.Placer(
            name="Colin Thompson", team="Plainfield Indian Tr. Wrest."
        ),
        bracket_utils.Placer(name="Jeff Defauw", team="Geneseo WC"),
    ],
    135: [
        bracket_utils.Placer(name="Denny Hartwig", team="Oak Forest Warriors"),
        bracket_utils.Placer(name="Kevin Singletary", team="Orland Park Pioneers"),
        bracket_utils.Placer(name="Austin Collins", team="Franklin Park Raiders"),
        bracket_utils.Placer(name="C.J. Protsman", team="Macomb YMCA Kids Wrestling"),
        bracket_utils.Placer(
            name="Steve Bailey", team="Plainfield Indian Trail Wrestling"
        ),
        bracket_utils.Placer(name="Mike Etzkorn", team="Lemont WC"),
    ],
    144: [
        bracket_utils.Placer(name="Ryan Pape", team="Franklin Park Raiders"),
        bracket_utils.Placer(name="Chris Timmons", team="Hoopeston East Lynn Jr. High"),
        bracket_utils.Placer(name="Ryan Beivenue", team="Trimpe Junior High"),
        bracket_utils.Placer(name="Jeremy Judd", team="Lil Reaper"),
        bracket_utils.Placer(name="Dave Cardin", team="Metamora Kids WC"),
        bracket_utils.Placer(name="RayTodd Guzak", team="Crestwood Colts WC"),
    ],
    153: [
        bracket_utils.Placer(name="Jose Medina", team="Gordon Tech Rams WC Chicago"),
        bracket_utils.Placer(name="Matthew Beeler", team="Mattoon WC"),
        bracket_utils.Placer(name="John Rupprecht", team="Geneseo WC"),
        bracket_utils.Placer(name="Brandon Dahlke", team="Aurora J-Hawks"),
        bracket_utils.Placer(name="Dean Phillips", team="Bison WC B"),
        bracket_utils.Placer(name="Brian Dill", team="Centralia WC"),
    ],
    163: [
        bracket_utils.Placer(name="Andy Donaldson", team="Mead Hr. WC"),
        bracket_utils.Placer(name="Michael Acord", team="Westville Jr. High"),
        bracket_utils.Placer(name="Scott Wulff", team="Oswego Panthers"),
        bracket_utils.Placer(name="Ray Jebsen", team="Tinley Park Bulldogs"),
        bracket_utils.Placer(name="Chris Williams", team="Indian Prairie Pioneers"),
        bracket_utils.Placer(name="John Sherrill", team="Murphysboro Jr. High"),
    ],
    173: [
        bracket_utils.Placer(name="Ken Robinson", team="St. Charles WC"),
        bracket_utils.Placer(name="Glen Humphrey", team="Aurora J-Hawks"),
        bracket_utils.Placer(name="Larry Fong", team="Mead Jr. WC"),
        bracket_utils.Placer(name="Chris McCay", team="Hoopeston East Lynn Jr. High"),
        bracket_utils.Placer(name="Chuck Morin", team="Indian Prairie Trailblazers"),
        bracket_utils.Placer(name="Matthew Weidner", team="Gibson City Youth Wrest."),
    ],
    185: [
        bracket_utils.Placer(name="Mark Harvey", team="Mt. Zion WC"),
        bracket_utils.Placer(name="Nathan Shelton", team="Aurora J-Hawks"),
        bracket_utils.Placer(name="Don Madenis", team="Harvard WC"),
        bracket_utils.Placer(name="L.T. Garrett", team="Hoopeston East Lynn Jr. High"),
        bracket_utils.Placer(name="Brian Washington", team="Dolton Park Falcons"),
        bracket_utils.Placer(name="Jeffrey Rohde", team="Yorkville WC"),
    ],
    275: [
        bracket_utils.Placer(name="Peter Marx", team="Eisenhower Jr. High WC"),
        bracket_utils.Placer(name="Jerry Jontry", team="Argenta/Oreana WC"),
        bracket_utils.Placer(name="Mike Johnson", team="Tri-City Braves"),
        bracket_utils.Placer(
            name="Cameron Randolph", team="Harvey Park District Twisters"
        ),
        bracket_utils.Placer(name="Richard Reynolds", team="Aurora J-Hawks"),
        bracket_utils.Placer(name="Patrick Parham", team="Tri-City Braves"),
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {
    "Harvey Park District Twisters": 195.0,
    "Dolton Park Falcons": 143.5,
    "Vittum Cats": 103.5,
    "Aurora J-Hawks": 102.0,
    "Oak Forest Warriors": 101.5,
    "Arlington Cardinals WC": 93.0,
    "Franklin Park Raiders": 83.5,
    "Oak Park River Forest Warhawks": 82.5,
    "Tomcat WC": 80.5,
    "Lockport Grapplers Wrestling": 80.0,
    "Geneseo WC": 68.0,
    "Newman Blue Devils": 66.5,
    "Mead Jr. High": 66.0,  # Was `Mead Jr. WC` in the program
    "Plainfield Indian Trail Wrestling": 64.0,
    "St. Barnabas/Christ The King": 59.0,
    "Tri-City Braves": 57.5,
    "Hoopeston E. Lynn Jr. High": 56.0,
    "Orland Park Pioneers": 54.5,
    "Argenta/Oreana WC": 42.0,
    "Rosemont Cobras WC": 41.0,
    "Crestwood Colts WC": 40.5,
    "Mattoon WC": 40.5,
    "Edwardsville": 39.0,
    "Indian Prairie Trailblazers": 39.0,
    "Round Lake Spartans": 39.0,
    "Thornwood Kids WC": 36.5,
    "Catlin Youth WC": 36.0,
    "Lemont WC": 36.0,
    "Mt. Zion WC": 36.0,
    "Forman WC": 34.0,
    "St. Charles WC": 33.0,
    "Gordon Tech Rams WC Chicago": 33.0,
    "Naperville Patriots Wrestling": 32.0,
    "Westville Jr. High": 31.0,
    "Belleville Little Devils": 31.0,
    "Riverdale Jr. High WC": 31.0,
    "Warrior WC Niles": 31.0,
    "Eisenhower Jr. High": 30.0,  # Was `Eisenhower Jr. High WC` in the program
    "Unity Youth": 29.0,
    "Tinley Park Bulldogs": 28.5,
    "Belvidere YMCA Bandits": 28.0,
    "Little Giants WC": 28.0,
    "Oswego Panthers": 28.0,
    "Jr. Bison WC": 27.0,
    "Panthers WC": 26.0,
    "Antioch Upper Grade School": 24.0,
    "Tigertown Tanglers": 24.0,
    "Bismarck-Henning Wrestling": 23.5,
    "Trimpe Junior High": 23.0,
    "Dundee Highlanders": 22.0,
    "Harlem-Park Boys Club": 21.0,
    "Moline Tigers": 21.0,
    "Harvard WC": 20.0,
    "Villa-Lombard Cougars": 20.0,
    "Yorkville WC": 20.0,
    "Carol Stream Park Dist": 17.5,
    "Blue Crew WC": 17.0,
    "Calumet Memorial PD": 17.0,
    "Chillicothe Wrestling": 17.0,
    "Gibson City Youth Wrestling": 17.0,
    "Lil Reaper": 17.0,
    "Blackhawk WC": 16.0,
    "Marquardt Middle Jr. High": 16.0,
    "Murphysboro Jr. High": 16.0,
    "Centralia WC": 15.0,
    "Indian Prairie Pioneers": 15.0,
    "Bethalto Boys Club Bulls": 14.0,
    "Granite City WC Coolidge": 14.0,
    "Macomb YMCA Kids Wrestling": 14.0,
    "Morton Youth Wrestling": 14.0,
    "Carbondale WC": 12.0,
    "Danville WC": 12.0,
    "Rich Wrestling LTD": 12.0,
    "Metamora Kids WC": 11.0,
    "West Chicago Wildcats PD": 11.0,
    "Dakota Matt Rats": 10.0,
    "Redbird WC": 10.0,
    "Streator Junior Bulldogs": 10.0,
    "Bradley-Bourbonnais": 9.0,
    "Addams Jr. High School WC": 7.0,
    "Hinsdale Red Devil WC": 7.0,
    "Mustang WC": 7.0,
    "Elgin Matt Rats": 6.0,
    "Hickory Hills Park District": 6.0,
    "Knights Wrestling lub": 6.0,
    "Woodstock Cardinal Wrestling": 6.0,
    "Geneva Park Dist": 5.0,
    "Decatur WC": 4.0,
    "Jr. Falcon Wrestling": 4.0,
    "Naperville Warriors": 4.0,
    "Spartans WC": 4.0,
    "St. Tarcissus Raiders": 4.0,
    "Sycamore WC": 4.0,
    "Taylorville WC": 4.0,
    "Urbana Kids WC": 4.0,
    "Granite City WC Grigsby": 3.5,
    "Jr. Bison WC (2)": 3.0,
    "Palatine PD Sundling": 3.0,
    "Pekin Boy's Club": 3.0,
    "Elgin Grapplers": 2.0,
    "Highland Junior Bulldogs": 2.0,
    "Illini Bluffs WC": 2.0,
    "Joliet Boy's Club Cobras": 2.0,
    "Lions WC": 2.0,
}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    ("Michael Murphy, Jr", "Lockport Grap."): bracket_utils.Competitor(
        full_name="Michael Murphy, Jr",
        first_name="Michael",
        last_name="Murphy",
        team_full="Lockport Grap.",
        team_acronym=None,
    ),
}


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    weight_classes = manual_entry.load_manual_entries(
        _HERE.parent, 1990, _NAME_EXCEPTIONS
    )
    for weight, placers in _SENIOR_PLACERS.items():
        weight_class = bracket_utils.create_weight_class_from_placers(
            "senior", weight, placers, _SENIOR_TEAM_REPLACE
        )
        if weight == 60:
            _, _, match_5th = weight_class.matches
            match_5th.top_competitor.full_name = "Michael Murphy Jr."
        if weight == 64:
            _, _, match_5th = weight_class.matches
            match_5th.bottom_competitor.full_name = "Ryan De Lira"
            match_5th.bottom_competitor.last_name = "De Lira"
        if weight == 144:
            _, _, match_5th = weight_class.matches
            match_5th.bottom_competitor.full_name = "Ray Todd Guzak"
            match_5th.bottom_competitor.first_name = "Ray Todd"
        if weight == 153:
            _, _, match_5th = weight_class.matches
            match_5th.bottom_competitor.full_name = "Dean Phillips Jr."

        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1990.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
