# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils
import manual_entry

_HERE = pathlib.Path(__file__).resolve().parent
_NOVICE_TEAM_SCORES: dict[str, float] = {}
_SENIOR_TEAM_REPLACE: dict[str, str] = {}
_SENIOR_COMPETITORS: dict[int, list[str | None]] = {
    70: [
        "KWANDRICK SUMLER :: ROCKFORD WRESTLING CLUB",
        None,
        None,
        "TIM HAYES :: JR. GOLDEN EAGLES WC :: 6",
        None,
        None,
        "ZACHARY BERMAN :: LITTLE CELTIC WRESTLING CLUB :: 1",
        None,
        None,
        "DANE SHAW :: EDWARDSVILLE WRESTLING :: 2",
        None,
        None,
        "JUSTIN GREY :: TINLEY PARK BULLDOGS :: 3",
        None,
        None,
        "PATRICK KENNEDY :: HUSKIES WRESTLING CLUB :: 5",
        None,
        None,
        "KURTIS HARTWIG :: HARVARD WRESTLING CLUB :: 4",
        None,
        None,
        None,
        None,
        None,
    ],
    74: [
        "ADAM HARRISON :: ROXANA WRESTLING",
        None,
        "NEIL PAVELA :: BEARS WRESTLING CLUB",
        "TONY EMMA :: WHEATON MONROE EAGLES :: 3",
        None,
        None,
        "RYAN KIMBERLIN :: BRADLEY-BOURBONNAIS :: 2",
        "TIM BLEDSOE :: OSWEGO PANTHERS WC",
        None,
        "MATTHEW WILLIAMS :: ROCK ISLAND WRESTLING CLUB",
        "RHETT GOTLUND :: BEARS WRESTLING CLUB :: 5",
        None,
        "BRIAN DYER :: FOX VALLEY WC :: 1",
        None,
        None,
        "CLARK ASKAM :: JR. ROCKET WRESTLING CLUB",
        "STEVE SCREMENTI :: LITTLE CELTIC WRESTLING CLUB :: 4",
        None,
        "MICHAEL RZAB JR. :: TINLEY PARK BULLDOGS",
        None,
        None,
        "ROBERT LOFTUS :: YORKVILLE WRESTLING CLUB :: 6",
        "LEE DOYLE :: VANDALIA JR WRESTLING",
        None,
    ],
    79: [
        "JOSH JOHNSON :: HARLEM COUGARS",
        "DAN DATAVS :: WOLFPACK WRESTLING CLUB",
        "MATTHEW ADAMS :: CHILLI DAWGS WRESTLING",
        "BRYAN PICKARD :: EDISON PANTHERS",
        "BILLY VANDOM :: WEST FRANKFORT REDBIRDS",
        "BRIAN TAYLOR :: TIGERTOWN TANGLERS :: 4",
        "KEVIN MCNICHOLAS :: VITTUM CATS WRESTLING CLUB :: 6",
        "STEVE LOFTUS :: GENESEO WC",
        None,
        "CHARLIE MANNING :: ORLAND PARK PIONEERS :: 2",
        "RICKY WOOD :: MORTON YOUTH WRESTLING",
        "BRANDON HARRISON :: METRO STALLIONS",
        "PAT BARTH :: MORTON YOUTH WRESTLING :: 1",
        "KEVIN GAGAN :: LITTLE CELTIC WRESTLING CLUB",
        None,
        "TERRANCE J. MIDDENDORF :: MT. VERNON LIONS WRESTLING",
        "TIM GARRISON :: EDISON PANTHERS",
        None,
        "JEREMY WILSON :: OAKWOOD WRESTLING CLUB",
        "JOSEPH SOJKA :: TINLEY PARK BULLDOGS :: 5",
        "DUSTIN MARMITT :: HUSKIES WRESTLING CLUB",
        "RYAN GIULANO :: WOLFPACK WRESTLING CLUB :: 3",
        "KYLE WOLFGRAM :: HARLEM COUGARS",
        None,
    ],
    84: [
        "KEVIN KENNEDY :: ORLAND PARK PIONEERS :: 1",
        "DOUG BAETHKE :: ELGIN LARKIN ROYALS",
        "CHARLIE MANN :: DUNDEE HIGHLANDERS",
        "JEREMY LAUBSCHER :: EAST ALTON RAMS",
        "TRAVIS STARK :: MATTOON YOUTH WRESTLING",
        "JUSTIN STEVE :: LASALLE PERU CRUNCHING CAVS",
        "MARTIN MCNICHOLAS :: VITTUM CATS WRESTLING CLUB :: 4",
        "JOSH TRACY :: HARVARD WRESTLING CLUB",
        "KYLE HAUN :: WESTVILLE YOUTH WC",
        "DAVID WISENAUER :: EDISON PANTHERS :: 6",
        "ZACK DURHAM :: ROCK ISLAND WRESTLING CLUB",
        "KEVIN CUKIERSKI :: MAINE EAGLES WRESTLING",
        "JONATHAN MICHL :: JORDAN / SETON WRESTLING :: 2",
        "TIM FINEGAN :: BRONCO WRESTLING CLUB",
        "BRETT SMETANA :: BEARS WRESTLING CLUB",
        "DANIEL THOMPSON :: CHARGER KIDS WRESTLING :: 5",
        "JOSHUA REUSCHER :: MURPHYSBORO MIDDLE",
        "MATTHEW MUTHART :: LITTLE CELTIC WRESTLING CLUB",
        "BRIAN ALLEN :: ROCKFORD WRESTLING CLUB",
        "CASEY CARRINO :: SENECA IRISH CADETS",
        "MARK SNYDER :: HUSKIES WRESTLING CLUB",
        "JOSEPH HOPKINS :: VILLA-LOMBARD COUGARS :: 3",
        "CHRISTOPHER SOJKA :: TINLEY PARK BULLDOGS",
        "DOUG WATTERS :: LITCHFIELD WRESTLING CLUB",
    ],
    89: [
        "RYAN KLINGER :: OAK LAWN P.D. WILDCATS",
        "KEVIN DUNNE :: ORLAND PARK PIONEERS :: 6",
        "MATTHEW FAULKNER :: FREEPORT BOYS AND GIRLS",
        "TYLER LUDWIG :: WHEATON MONROE EAGLES :: 2",
        "JONATHAN HOWE :: HERRIN JR. WRESTLING",
        "MICHAEL WHITE :: LITTLE CELTIC WRESTLING CLUB",
        "NATHAN WANGELIN :: TIGERTOWN TANGLERS :: 3",
        "JAMIE DALCOLLO :: DURAND-PECATONICA YOUTH",
        "CHRIS MCLEAN :: EDWARDSVILLE WRESTLING",
        "JOEL FRAZIER :: WESTVILLE YOUTH WC",
        "MATT WEGER :: BRADLEY-BOURBONNAIS",
        "STEVEN WOECKER :: ROCK ISLAND WRESTLING CLUB",
        "DAN KUNZER :: LITTLE CELTIC WRESTLING CLUB :: 1",
        "SETH MARMION :: CHARGER KIDS WRESTLING",
        "ROBERT MEYERS :: EAST MOLINE WRESTLING CLUB",
        "ZACHARY HARRIS :: BELLEVILLE LITTLE DEVILS",
        "STEVEN EVANS :: HUSKIES WRESTLING CLUB",
        "MATTHEW POLI :: VITTUM CATS WRESTLING CLUB",
        "MATTHEW ANDERSON :: HARLEM COUGARS",
        "ANTHONY BROWN :: TINLEY PARK BULLDOGS :: 4",
        "ANDY MCCALLA :: HOOPESTON AREA WRESTLING",
        "CHARLES ATCHISON :: VILLA-LOMBARD COUGARS :: 5",
        "LARAMIE STORM :: TIGERTOWN TANGLERS",
        "TYLER WINTERS :: BATAVIA PINNERS WC",
    ],
    95: [
        "ADAM HALL :: MT. VERNON LIONS WRESTLING",
        "CHRIS ZANONI :: HARLEM COUGARS",
        "STEVEN SCOTT :: ROCK ISLAND WRESTLING CLUB",
        "MIKE GRIMES :: BRONCO WRESTLING CLUB",
        "BRIAN ROSSETTI :: WOLFPACK WRESTLING CLUB",
        "MIKE OGANEKU :: BADGER WRESTLING CLUB :: 6",
        "DONNY REYNOLDS :: LITTLE CELTIC WRESTLING CLUB :: 1",
        "GREG CLODFELTER :: TIGERTOWN TANGLERS",
        "CHRIS PIHA :: VILLA-LOMBARD COUGARS",
        "ETHAN ROUSH :: MT. ZION WRESTLING CLUB",
        "LUKE JONES :: TINLEY PARK BULLDOGS :: 4",
        "NICK ENDERLE :: HARLEM COUGARS",
        "BRIAN DALY :: VITTUM CATS WRESTLING CLUB :: 3",
        "ANDREW FRUHLING :: SJO YOUTH WRESTLING",
        "CLAY WEIER :: BELLEVILLE LITTLE DEVILS",
        "JEFF KROCKO :: DUNDEE HIGHLANDERS :: 5",
        "CHRIS LOUISE :: FOX VALLEY WC-HILL",
        "JACOB STOUT :: LITTLE CELTIC WRESTLING CLUB",
        "JONATHON GAPINSKI :: LASALLE PERU CRUNCHING CAVS",
        "GEORGE KAPPAS :: PLAINFIELD WRESTLING CLUB :: 2",
        "JOSHUA BLACKBURN :: UNITY WRESTLING CLUB",
        "MATTHEW ATKINS :: VILLA-LOMBARD COUGARS",
        "KYLE BOESER :: EDWARDSVILLE WRESTLING",
        "KYLE HAMMERSLEY :: HINSDALE RED DEVIL WC",
    ],
    101: [
        "JUSTIN BEER :: LITTLE CELTIC WRESTLING CLUB :: 2",
        "GREGORY GOODLETTE :: STREAMWOOD WC",
        "JAKOB BOTTOMS :: BETHALTO / JR. HIGH",
        "ADAM BULLOCK :: BISMARCK-HENNING",
        "ELIZABETH BRUSA :: GLENBARD EAST JR. RAMS",
        "JACOB MEKEEL :: STERLING NEWMAN JR.",
        "BOB BOHACZYK :: BADGER WRESTLING CLUB :: 6",
        "JOEY ASHCRAFT :: EAST MOLINE WRESTLING CLUB",
        "MATT WELLNER :: PLAINFIELD WOLVES WC",
        "JASON PERDUE :: OREGON-MT. MORRIS :: 3",
        "JASON GROVER :: JR. MAROON'S WRESTLING",
        "MATTHEW STENNETT :: HUSKIES WRESTLING CLUB",
        "COLT LEE :: MURPHYSBORO MIDDLE",
        "J.D. HUBERT :: SJO YOUTH WRESTLING",
        "BILL BREHENY :: OAK LAWN P.D. WILDCATS",
        "RUBEN VILLARREAL :: FOX VALLEY WC :: 1",
        "MATTHEW PLUMMER :: HONONEGAH KIDS WRESTLING",
        "MICHAEL PILA :: ORLAND PARK PIONEERS",
        "RYAN DEVRIENDT :: SHERRARD JR. WRESTLING",
        "JOSH OSTER :: BEARS WRESTLING CLUB :: 5",
        "MICHAEL GARVIN :: DAKOTA WRESTLING CLUB",
        "MICHAEL GORANSON :: WOLFPACK WRESTLING CLUB",
        "JOHN SILOSKI :: PLAINFIELD WRESTLING CLUB :: 4",
        "JOSH RUPPRECHT :: PONTIAC PYTHONS WC",
    ],
    108: [
        "JOHN DECEAULT :: TINLEY PARK BULLDOGS :: 3",
        "JOE SALADINO :: RAMS WRESTLING CLUB",
        "GRANT NEWHOUSE :: ORLAND PARK PIONEERS",
        "JOSHUA BEDNAREK :: WOODSTOCK PANTHERS",
        "CHASE PITTMAN :: BISMARCK-HENNING",
        "MIKE KERR :: EAST MOLINE WRESTLING CLUB",
        "AARON RUJAWITZ :: BELLEVILLE LITTLE DEVILS :: 1",
        "KEITH WITALKA :: LASALLE PERU CRUNCHING CAVS",
        "CICO SANCHEZ :: WOLFPACK WRESTLING CLUB",
        "DREW WEIMER :: FOX VALLEY WC :: 5",
        "DAVID EARLY :: YORKVILLE WRESTLING CLUB",
        "NICHOLAS BROWN :: SJO YOUTH WRESTLING",
        "JIM CREMEENS :: PLAINFIELD WRESTLING CLUB",
        "MIKE TURNMIRE :: HARLEM COUGARS :: 4",
        "NICK HUEBNER :: BETHALTO / JR. HIGH",
        "JOHN LITCHFIELD :: SJO YOUTH WRESTLING :: 6",
        "TIM QUIRK :: HINSDALE RED DEVIL WC",
        "SAMUEL KUNTZ :: VITTUM CATS WRESTLING CLUB",
        "KEVIN AMY :: JR. ROCKET WRESTLING CLUB",
        "DAVID TERRY :: MURPHYSBORO MIDDLE",
        "CHRIS GENSLINGER :: FOX VALLEY WC",
        "SEAN WELCH :: VILLA-LOMBARD COUGARS :: 2",
        "ANTHONY CASTILLO :: BADGER WRESTLING CLUB",
        "RICHIE COOPER :: ROCKFORD WRESTLING CLUB",
    ],
    115: [
        "STEVE LOFTON :: HUSKIES WRESTLING CLUB :: 4",
        "JOEL DENNIS :: ROCK ISLAND WRESTLING CLUB",
        "RORY MCGINNIS :: OAK LAWN P.D. WILDCATS",
        "CHRIS MCCLELLAN :: PONTIAC PYTHONS WC",
        "TRAVIS CHERRY :: VILLA-LOMBARD COUGARS",
        "DANNY FINNEY :: LITTLE CELTIC WRESTLING CLUB :: 6",
        "DUSTY CARPENTER :: BELLEVILLE LITTLE DEVILS :: 2",
        "SERGIO FLORES :: TINLEY PARK BULLDOGS",
        "ROCKY DRAGONETTI :: WOLFPACK WRESTLING CLUB",
        "DAVID KAYS :: BELVIDERE BANDITS",
        "MIKE KEAVENY :: ORLAND PARK PIONEERS",
        "STEVE PETERSON :: METAMORA KIDS WRESTLING",
        "MIKE KLIMEK :: ORLAND PARK PIONEERS",
        "BENJAMIN RIECHERT :: RICHMOND WRESTLING CLUB",
        "PAT LOUISE :: FOX VALLEY WC-HILL",
        "LAMBROS FOTOS :: EAST MOLINE WRESTLING CLUB :: 1",
        "HEATH SCHULTZ :: WESTVILLE YOUTH WC",
        "THOMAS J. MIDDENDORF :: MT. VERNON LIONS WRESTLING",
        "BRYAN HARNEY :: VITTUM CATS WRESTLING CLUB :: 5",
        "DOUGLAS KUEHN :: VANDALIA JR WRESTLING",
        "AARON THOR :: ROCKFORD WRESTLING CLUB",
        "CHAD ISACSON :: VILLA-LOMBARD COUGARS :: 3",
        "SCOTT ANDRIANO :: FOX VALLEY WC",
        "MARCUS HINKLE :: BISMARCK-HENNING",
    ],
    122: [
        "JIM PRESTON :: ORLAND PARK PIONEERS :: 5",
        "VINCE DEMAREST :: GIANTS WRESTLING CLUB",
        "GRANT ARTHUR :: OAK LAWN P.D. WILDCATS",
        "JIMMY KIM :: TAZEWELL YOUTH WC :: 4",
        "LUCAS SWANBORG :: ROCKFORD WRESTLING CLUB",
        "DUSTIN EARNHEART :: WEST FRANKFORT REDBIRDS",
        "MARK MENDOZA :: FOX VALLEY WC :: 2",
        "KEVIN TOBOLA :: TINLEY PARK BULLDOGS",
        "COLT MAYER :: DAKOTA WRESTLING CLUB",
        "ERIC AQUINO :: WESTVILLE YOUTH WC",
        "MIKE MEIER :: BELLEVILLE LITTLE DEVILS",
        "JAMES DENK :: WOLFPACK WRESTLING CLUB",
        "STEVE RYAN :: BELLEVILLE LITTLE DEVILS",
        "CHRIS MILLER :: CHENOA WRESTLING CLUB",
        "MANNY GARCIA :: HUSKIES WRESTLING CLUB",
        "MATT WINTERHALTER :: DAKOTA WRESTLING CLUB :: 3",
        'DREW PULLEN :: YOUNG ZIPS "Y" WRESTLING :: 6',
        "JOE LENAHAN :: LITTLE CELTIC WRESTLING CLUB",
        "SEAN PHILLIPS :: TINLEY PARK BULLDOGS",
        "BRANDON ROSCH :: PLAINFIELD WRESTLING CLUB",
        "JC HAGEN :: MATTOON YOUTH WRESTLING",
        "MIKE MALIZZIO :: VILLA-LOMBARD COUGARS :: 1",
        "JASON SHOWALTER :: WHEATON BULLDOGS",
        "KENNY ROBERTSON :: METAMORA KIDS WRESTLING",
    ],
    130: [
        "KYLE JOHNSON :: SJO YOUTH WRESTLING :: 2",
        "PATRICK MALONEY :: WOLFPACK WRESTLING CLUB",
        "MIKE BAILEY :: BRADLEY-BOURBONNAIS",
        "PETER STRAUS :: WOODSTOCK PANTHERS",
        "CHAD MIRUS :: OAK LAWN P.D. WILDCATS",
        "JACOB GRECO :: EDWARDSVILLE WRESTLING",
        "NICK VANSOMEREN :: WHEATON BULLDOGS",
        "TRAVIS NAVICKAS :: HIGHLAND BULLDOG JR.",
        "JACOB KOPECKY :: MAINE EAGLES WRESTLING",
        "DANNY BURK :: METAMORA KIDS WRESTLING :: 3",
        "WALTER CZERWINSKI :: PLAINFIELD WRESTLING CLUB",
        "AARON GUISINGER :: TINLEY PARK BULLDOGS :: 5",
        "MICHAEL CIABATTONI :: BELLEVILLE LITTLE DEVILS :: 1",
        "JED VEACH :: FARMINGTON WRESTLING CLUB",
        "CHARLIE GOUGH :: HINSDALE RED DEVIL WC",
        "ROBERT PALUMBO :: OAK LAWN P.D. WILDCATS :: 4",
        "MIKE GRIFFEN :: HARVARD WRESTLING CLUB",
        "RICHARD COX :: A-O KIDS WRESTLING",
        "SEAN CUMBEE :: LITTLE CELTIC WRESTLING CLUB",
        "ERIC VARI :: FOX VALLEY WC",
        "NICK HOLLIS :: POLO WRESTLING CLUB :: 6",
        "JACOB SHURPIT :: ELGIN LARKIN ROYALS",
        "JOSH INMAN :: HOOPESTON AREA WRESTLING",
        "JUSTIN KEMPHER :: GENESEO WC",
    ],
    138: [
        "THOMAS TOVELLO :: VILLA PARK YOUNG WARRIORS",
        "JEFF JOHNSON :: BELVIDERE BANDITS",
        "JOE AARONSON :: ROCKFORD WRESTLING CLUB",
        "EVAN MCCALLISTER :: RIVERBEND / FULTON WC :: 5",
        "RYAN RUBEL :: WOLFPACK WRESTLING CLUB",
        "MICHAEL JOHNSON :: SJO YOUTH WRESTLING",
        "KRIS ROBERTS :: MARION WRESTLING CLUB :: 3",
        "ROY STACY :: LITTLE CELTIC WRESTLING CLUB",
        "MICHAEL VITALE :: FRANKLIN PARK RAIDERS",
        "TOM TREADWAY :: BEARS WRESTLING CLUB :: 1",
        "BOBBY ORMAN :: MATTOON YOUTH WRESTLING",
        "DUANE HALL :: HARLEM COUGARS",
        "BEN BAKER :: CHARGER KIDS WRESTLING :: 6",
        "DANNY BROWN :: TINLEY PARK BULLDOGS :: 2",
        "MARCO EUFRASIO :: VILLA PARK YOUNG WARRIORS",
        "KEVIN STOTT :: HARVARD WRESTLING CLUB",
        "ERIC SLOCUM :: ERIE MIDDLE SCHOOL WRESTLING CLUB",
        "MICHAEL WADE :: BELLEVILLE LITTLE DEVILS",
        "STEVEN ZBACNIK :: PLAINFIELD WOLVES WC",
        "BRYAN CINCOSKI :: ROXANA WRESTLING",
        "JOHN MCGLYNN :: MUSTANG WRESTLING CLUB",
        "KEITH FOSTER :: VILLA-LOMBARD COUGARS",
        "CHRIS JENSEN :: FOX VALLEY WC",
        "ADAM LOWE :: JR. ROCKET WRESTLING CLUB :: 4",
    ],
    147: [
        "RYAN CLAY :: VANDALIA JR WRESTLING",
        "RONALD GAGNEPAIN :: MAINE EAGLES WRESTLING",
        "DAVID ORTIZ JR. :: LAKEVIEW MITEY CATS",
        "NIALL CAMPBELL :: BEARS WRESTLING CLUB :: 5",
        "ROBERT POWELL :: ERIE MIDDLE SCHOOL WRESTLING CLUB",
        "CHUY QUINTANILLA :: FOX VALLEY WC",
        "ERIC MOORE :: A-O KIDS WRESTLING",
        "ANDY CVENGROS :: WHEATON MONROE EAGLES :: 2",
        "DONALD ESQUIVEL :: ELGIN LARKIN ROYALS",
        "MITCH HILDEN :: BELVIDERE BANDITS :: 3",
        "LUKE OLZSTA :: LITTLE CELTIC WRESTLING CLUB",
        "JAKE ANDERSON :: RIVERDALE JR. HIGH WC",
        "NICK METCALF :: VILLA PARK YOUNG WARRIORS :: 1",
        "JAMES EARLYWINE :: DAKOTA WRESTLING CLUB :: 6",
        "RASHAD STEWERT :: CHARGER KIDS WRESTLING",
        "NICK PYSZKA :: LASALLE PERU CRUNCHING CAVS",
        "CLINT PADGETT :: COLTS & BRAVES WRESTLING",
        "CHISTOPHER MCCANN :: MURPHYSBORO MIDDLE",
        "CHRISTOPHER MARKELZ :: LITTLE CELTIC WRESTLING CLUB :: 4",
        "BRIAN MILLER :: MATTOON YOUTH WRESTLING",
        "KENNETH VINGUA :: OAK LAWN P.D. WILDCATS",
        "KEVIN KOSNIK :: VILLA-LOMBARD COUGARS",
        "AARON ENGELKE :: EDWARDSVILLE WRESTLING",
        "DANIEL RUSSELL :: RICHMOND WRESTLING CLUB",
    ],
    156: [
        "STEVEN ZANONI :: HARLEM COUGARS :: 1",
        "ZACHARY ADAMS :: VILLA-LOMBARD COUGARS",
        "TERRY BURNER :: CENTRALIA WRESTLING CLUB :: 5",
        "BROOKS SWANSON :: JR. ROCKET WRESTLING CLUB",
        "BRAD DEGRAVE :: GENESEO WC",
        "PATRICK REDMOND :: WHEATON MONROE EAGLES",
        "SHANE SMITH :: HOOPESTON AREA WRESTLING",
        "EIL ESPINOZA :: EDISON PANTHERS",
        "EDGAR OSORIO :: LAKEVIEW MITEY CATS",
        "NICHOLAS ORLANDO :: BEARS WRESTLING CLUB :: 3",
        "ZAC FAGER :: MURPHYSBORO MIDDLE",
        "MATT ANDERSON :: WHEATON BULLDOGS",
        "RUBEN HERNANDEZ :: FOX VALLEY WC :: 6",
        "MICHAEL KING :: COLTS & BRAVES WRESTLING",
        "TIM AXE :: MT. ZION WRESTLING CLUB",
        "ROBERT RAPP :: BRADLEY-BOURBONNAIS",
        "TOM RICHMOND :: MORRISON STALLIONS :: 4",
        "DERRICK LISTER :: HARLEM COUGARS",
        "COREY FORD :: BELLEVILLE LITTLE DEVILS :: 2",
        "BRAD KIMBALL :: STILLMAN VALLEY CARDINALS",
        "NATHANIEL ROTH :: BEARS WRESTLING CLUB",
        "ANTHONY SCRIVANI :: VILLA-LOMBARD COUGARS",
        "MICHAEL MESSENGER :: A-O KIDS WRESTLING",
        "RANDY CULBERTSON :: GALESBURG JR. STREAKS",
    ],
    166: [
        "TYLER CLENDENEN :: A-O KIDS WRESTLING",
        "CHRISTIAN MCDONALD :: RAMS WRESTLING CLUB",
        "JASON WILLIAMS :: BELLEVILLE LITTLE DEVILS",
        "RASHAWN THURMAN :: COLTS & BRAVES WRESTLING :: 1",
        "MARIO CARAEVO :: ROCK ISLAND WRESTLING CLUB",
        "STEVE MAGINITY :: CRYSTAL LAKE WIZARDS :: 3",
        "PHIL SINETOS :: FOX VALLEY WC :: 5",
        "JEREMY WARREN :: ROXANA WRESTLING",
        "BEN MCLAREN :: MORTON YOUTH WRESTLING",
        "ELDRICK SMITH :: EUREKA KIDS WRESTLING CLUB",
        "ERIC NEYER :: HONONEGAH KIDS WRESTLING",
        "BLAKE WITHERS :: URBANA KIDS CLUB",
        "JOEL POWERS :: ROCKFORD WRESTLING CLUB :: 2",
        "JACK NELSON :: EDISON PANTHERS",
        "JARED CURRIE :: NAPERVILLE WRESTLING",
        "ADAM POSSIN :: GENESEO WC",
        "MICHAEL PELKOWSKI :: BADGER WRESTLING CLUB :: 4",
        "LANCE SCHAEFER :: MT. ZION WRESTLING CLUB",
        "CHRIS JAMES :: MURPHYSBORO MIDDLE",
        "TONY RUGGIERO :: OSWEGO COUGARS",
        "NICHOLAS PAOLILLI :: TINLEY PARK BULLDOGS",
        "ROBERTO MARTINEZ :: VILLA-LOMBARD COUGARS :: 6",
        "ZACH MIKALIK :: BISMARCK-HENNING",
        "BOBBY FISHER :: HARVARD WRESTLING CLUB",
    ],
    177: [
        "JUAN APONTE :: FOX VALLEY WC :: 2",
        "SHAWN STEVERS :: EAST MOLINE WRESTLING CLUB",
        "CHRIS MIDGETT :: JR. MAROON'S WRESTLING",
        "ERIC STRAIT :: SENECA IRISH CADETS :: 5",
        "SCOTT FESTIN :: BEARS WRESTLING CLUB",
        "CODY HUDDLESTON :: CHENOA WRESTLING CLUB",
        "JIMMY SCHRIMSHER :: JR. GOLDEN EAGLES WC :: 4",
        "JOSEPH DOWNS :: WARRENSBURG WRESTLING",
        "JUSTIN VOLPE :: MARENGO WRESTLING CLUB",
        "ZACHARY SCHROEDER :: CHILLI DAWGS WRESTLING",
        "KASON WILLIAMS :: BELLEVILLE LITTLE DEVILS",
        "DESMOND KNUSKA :: ST. BARNABAS SHARKS",
        "CALEB BRIDGES :: SPRINGFIELD SENATORS",
        "ADAM EICH :: MENDOTA YOUTH WRESTLING",
        "MATT HAMLIN :: HARVARD WRESTLING CLUB",
        "TOM SMITH :: MUSTANG WRESTLING CLUB :: 1",
        "JOSHUA RUNGE :: LITTLE CELTIC WRESTLING CLUB",
        "ALEXANDER WOOD :: CENTRALIA WRESTLING CLUB",
        "ARTHUR LANGSTON :: VANDALIA JR WRESTLING",
        "ANDY MEADIE :: HARVARD WRESTLING CLUB",
        "LUKE WARNER :: LITTLE REDBIRDS WRESTLING",
        "DEREK BURGER :: MAINE EAGLES WRESTLING",
        "DANIEL KUNDINGER :: GLENBARD EAST JR. RAMS :: 3",
        "KEVIN RUSH :: THE JACKSONVILLE WC :: 6",
    ],
    189: [
        "JACOB COY :: VILLA-LOMBARD COUGARS",
        None,
        None,
        "KYLE CROTTY :: ROXANA WRESTLING :: 5",
        None,
        "CHRIS FLORES :: EDISON PANTHERS",
        "GEORGE MASKA :: GALESBURG JR. STREAKS",
        "JAY GILLETTE :: FOX VALLEY WC :: 3",
        None,
        "DAVID JILES :: BADGER WRESTLING CLUB :: 2",
        None,
        None,
        "ELJUN WATSON :: ROCKFORD WRESTLING CLUB :: 6",
        "DAN INBODEN :: JR. MAROON'S WRESTLING",
        "CHRIS SCHERTZ :: METAMORA KIDS WRESTLING",
        "MURPHY MAHALIK :: LITTLE CELTIC WRESTLING CLUB :: 4",
        "DAN TOMASEK :: MUSTANG WRESTLING CLUB",
        None,
        "MIKE BEHNKE :: VILLA PARK YOUNG WARRIORS :: 1",
        "FRANK VALLE JR. :: LASALLE PERU CRUNCHING CAVS",
        None,
        "ADAM WAITE :: WOLFPACK WRESTLING CLUB",
        None,
        "GREG BOSWORTH :: CARBONDALE WRESTLING CLUB",
    ],
    275: [
        "DAVID BENNETT :: HARLEM COUGARS :: 1",
        "JEFF MANN :: BEARS WRESTLING CLUB",
        "JUSTIN MILLER :: BATAVIA PINNERS WC",
        "ROBBIE COOK :: TAYLORVILLE WC",
        "PATRICK LESHER :: VILLA-LOMBARD COUGARS",
        "MATT MULDER :: GENESEO WC",
        "JOSH WURTSBAUGH :: MATTOON YOUTH WRESTLING :: 5",
        "A.J. SIMIONE :: WHEATON MONROE EAGLES",
        "JESSE RODRIGUEZ :: FRANKLIN PARK RAIDERS",
        "NATHAN STREET :: VANDALIA JR WRESTLING :: 3",
        "CLAY REVEAL :: RIVERDALE JR. HIGH WC",
        "JACQUES LARUE :: COLTS & BRAVES WRESTLING",
        "THILIPPE SHERROD :: EAST MOLINE WRESTLING CLUB",
        "JUSTIN KLITZING :: VANDALIA JR WRESTLING :: 6",
        "NICHOLAS YARBER :: BELLEVILLE LITTLE DEVILS",
        "DAN SCHMIDT :: TINLEY PARK BULLDOGS",
        "ISREAL BAUTISTA :: LAKEVIEW MITEY CATS",
        "JESSE MANNING :: A-O KIDS WRESTLING :: 4",
        "MATTHEW RICHARDS :: EDISON PANTHERS",
        "BEN BRADFIELD :: BISMARCK-HENNING",
        "RYAN WALSH :: EDWARDSVILLE WRESTLING",
        "RON PENA :: ELGIN LARKIN ROYALS",
        "JEFF HALL :: ROCKFORD WRESTLING CLUB :: 2",
        "CHRIS MARTIN :: ROCK ISLAND WRESTLING CLUB",
    ],
}
_SENIOR_TEAM_SCORES: dict[str, float] = {}
_NAME_EXCEPTIONS: dict[tuple[str, str], bracket_utils.Competitor] = {
    ("M RILEY KRUEGER", "PLAINFIELD WOLVES WC"): bracket_utils.Competitor(
        full_name="M RILEY KRUEGER",
        first_name="RILEY",
        last_name="KRUEGER",
        team_full="PLAINFIELD WOLVES WC",
        team_acronym=None,
    ),
    ("TERRY HOLCOMB JR.", "MIDWEST CENTRAL YOUTH"): bracket_utils.Competitor(
        full_name="TERRY HOLCOMB JR.",
        first_name="TERRY",
        last_name="HOLCOMB",
        team_full="MIDWEST CENTRAL YOUTH",
        team_acronym=None,
    ),
    ("ANDREW P. LUKANICH", "VITTUM CATS WRESTLING CLUB"): bracket_utils.Competitor(
        full_name="ANDREW P. LUKANICH",
        first_name="ANDREW",
        last_name="LUKANICH",
        team_full="VITTUM CATS WRESTLING CLUB",
        team_acronym=None,
    ),
    ("BUDDY DEL CAMPO", "RAMS WRESTLING CLUB"): bracket_utils.Competitor(
        full_name="BUDDY DEL CAMPO",
        first_name="BUDDY",
        last_name="DEL CAMPO",
        team_full="RAMS WRESTLING CLUB",
        team_acronym=None,
    ),
    ("RYAN ST. JOSEPH", "CRYSTAL LAKE WIZARDS"): bracket_utils.Competitor(
        full_name="RYAN ST. JOSEPH",
        first_name="RYAN",
        last_name="ST. JOSEPH",
        team_full="CRYSTAL LAKE WIZARDS",
        team_acronym=None,
    ),
    ("JONATHAN LA MANTIA", "VILLA-LOMBARD COUGARS"): bracket_utils.Competitor(
        full_name="JONATHAN LA MANTIA",
        first_name="JONATHAN",
        last_name="LA MANTIA",
        team_full="VILLA-LOMBARD COUGARS",
        team_acronym=None,
    ),
    ("MICHAEL RZAB JR.", "TINLEY PARK BULLDOGS"): bracket_utils.Competitor(
        full_name="MICHAEL RZAB JR.",
        first_name="MICHAEL",
        last_name="RZAB",
        team_full="TINLEY PARK BULLDOGS",
        team_acronym=None,
    ),
    ("TERRANCE J. MIDDENDORF", "MT. VERNON LIONS WRESTLING"): bracket_utils.Competitor(
        full_name="TERRANCE J. MIDDENDORF",
        first_name="TERRANCE",
        last_name="MIDDENDORF",
        team_full="MT. VERNON LIONS WRESTLING",
        team_acronym=None,
    ),
    ("THOMAS J. MIDDENDORF", "MT. VERNON LIONS WRESTLING"): bracket_utils.Competitor(
        full_name="THOMAS J. MIDDENDORF",
        first_name="THOMAS",
        last_name="MIDDENDORF",
        team_full="MT. VERNON LIONS WRESTLING",
        team_acronym=None,
    ),
    ("DAVID ORTIZ JR.", "LAKEVIEW MITEY CATS"): bracket_utils.Competitor(
        full_name="DAVID ORTIZ JR.",
        first_name="DAVID",
        last_name="ORTIZ",
        team_full="LAKEVIEW MITEY CATS",
        team_acronym=None,
    ),
    ("FRANK VALLE JR.", "LASALLE PERU CRUNCHING CAVS"): bracket_utils.Competitor(
        full_name="FRANK VALLE JR.",
        first_name="FRANK",
        last_name="VALLE",
        team_full="LASALLE PERU CRUNCHING CAVS",
        team_acronym=None,
    ),
}
_BOUT_NUMBER_INPUTS: dict[tuple[bracket_utils.Division, int], tuple[int, int]] = {
    ("senior", 70): (2, 1047),
    ("senior", 74): (18, 1050),
    ("senior", 79): (34, 1053),
    ("senior", 84): (50, 1056),
    ("senior", 89): (66, 1059),
    ("senior", 95): (82, 1062),
    ("senior", 101): (98, 1065),
    ("senior", 108): (114, 1068),
    ("senior", 115): (130, 1071),
    ("senior", 122): (146, 1074),
    ("senior", 130): (162, 1077),
    ("senior", 138): (178, 1080),
    ("senior", 147): (194, 1083),
    ("senior", 156): (210, 1086),
    ("senior", 166): (226, 1089),
    ("senior", 177): (242, 1092),
    ("senior", 189): (258, 1095),
    ("senior", 275): (274, 1098),
}


def _get_bout_numbers(
    division: bracket_utils.Division, weight: int
) -> dict[bracket_utils.MatchSlot, int]:
    key = (division, weight)
    entry = _BOUT_NUMBER_INPUTS.get(key)
    if entry is None:
        return {}

    first_pigtail, first_place = entry
    return {
        "championship_r32_02": first_pigtail,
        "championship_r32_04": first_pigtail + 1,
        "championship_r32_06": first_pigtail + 4,
        "championship_r32_08": first_pigtail + 5,
        "championship_r32_10": first_pigtail + 8,
        "championship_r32_12": first_pigtail + 9,
        "championship_r32_14": first_pigtail + 12,
        "championship_r32_16": first_pigtail + 13,
        "consolation_fifth_place": first_place - 2,
        "consolation_third_place": first_place - 1,
        "championship_first_place": first_place,
    }


def main():
    team_scores: dict[bracket_utils.Division, list[bracket_utils.TeamScore]] = {}
    team_scores["novice"] = []
    for team_name, score in _NOVICE_TEAM_SCORES.items():
        team_scores["novice"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    team_scores["senior"] = []
    for team_name, score in _SENIOR_TEAM_SCORES.items():
        team_scores["senior"].append(
            bracket_utils.TeamScore(team=team_name, acronym=None, score=score)
        )

    weight_classes = manual_entry.load_manual_entries(
        _HERE.parent, 1998, _NAME_EXCEPTIONS
    )

    for weight, competitors in _SENIOR_COMPETITORS.items():
        bout_numbers = _get_bout_numbers("senior", weight)
        weight_class = bracket_utils.weight_class_from_competitors(
            "senior",
            weight,
            competitors,
            _SENIOR_TEAM_REPLACE,
            _NAME_EXCEPTIONS,
            bout_numbers,
        )
        weight_classes.append(weight_class)

    extracted = bracket_utils.ExtractedTournament(
        weight_classes=weight_classes, team_scores=team_scores, deductions=[]
    )
    extracted.sort()
    with open(_HERE / "extracted.1998.json", "w") as file_obj:
        file_obj.write(extracted.model_dump_json(indent=2))
        file_obj.write("\n")


if __name__ == "__main__":
    main()
