# Copyright (c) 2025 - Present. IKWF History. All rights reserved.

import pathlib

import bracket_utils
import extract_2002 as extract_this_year

HERE = pathlib.Path(__file__).resolve().parent
TOURNAMENT_ID = 33
TEAM_SCORE_ID_START = 269
TEAM_ACRONYM_MAPPING = extract_this_year.TEAM_ACRONYM_MAPPING
NOVICE_TEAM_ACRONYM_MAPPING = extract_this_year.NOVICE_TEAM_ACRONYM_MAPPING
SENIOR_TEAM_ACRONYM_MAPPING = extract_this_year.SENIOR_TEAM_ACRONYM_MAPPING
TEAM_NAME_MAPPING: dict[str, int] = {
    "A-J JR. WILDCATS": 4,
    "ACES WC": 3,
    "ARGENTA/OREANA KIDS CLUB": 8,
    "ARLINGTON CARDINALS": 9,
    "BADGER WC": 14,
    "BARTLETT HAWK WC": 16,
    "BATAVIA PINNERS": 10005,
    "BELLEVILLE LITTLE DEVILS": 23,
    "BELVIDERE BANDITS": 24,
    "BENTON JR. WC": 26,
    "BETHALTO BULLS WC": 10006,
    "BISMARCK-HENNING WC": 28,
    "BISON WC": 126,
    "BLACKHAWK WC": 30,
    "BLOOMINGTON RAIDER WC": 32,
    "BOYS & GIRLS CLUB OF PEKIN": 319,
    "BRAWLERS WC": 39,
    "BRONCO WRESTLING": 41,
    "CAMP POINT CENTRAL": 50,
    "CARBONDALE WC": 53,
    "CARLINVILLE KIDS WC": 54,
    "CARY JR TROJAN MATMEN": 59,
    "CENTRAL WC": 10010,
    "CHAMPAIGN KIDS WRESTLING": 65,
    "CHARLESTON WC": 69,
    "CHENOA MAT CATS": 10011,
    "CHILLICOTHE WC": 10014,
    "CROSSFACE WRESTLING": 10018,
    "CRYSTAL LAKE WIZARDS": 89,
    "CUMBERLAND YOUTH WC": 90,
    "DAKOTA WC": 92,
    "DEKALB WC": 96,
    "DIXON WC": 98,
    "DOWNERS GROVE COUGARS": 100,
    "DUNDEE HIGHLANDERS": 102,
    "DURAND-PECATONICA CARNIVORES": 10020,
    "EAST MOLINE PANTHER PINNERS": 10164,
    "EDWARDSVILLE WC": 110,
    "EFFINGHAM YOUTH WC": 111,
    "ELMHURST JR. DUKES": 10024,
    "EUREKA KIDS WC": 117,
    "FALCON WC": 124,
    "FALCON YOUTH WC": 123,
    "FISHER WC": 130,
    "FORD HEIGHTS FALCONS": 10029,
    "FOX VALLEY WC": 134,
    "GALESBURG JR STREAKS": 10030,
    "GENERALS": 10144,
    "GENESEO WC": 10033,
    "GENEVA WC": 10034,
    "GLADIATORS": 10038,
    "GLEN ELLYN DUNGEON WC": 10039,
    "GLENBARD EAST JR RAMS": 147,
    "GRANITE CITY JR WARRIORS": 10040,
    "HARLEM COUGARS": 10041,
    "HARVEY TWISTERS": 162,
    "HIGHLAND BULLDOG JR WC": 168,
    "HILLSBORO JR TOPPERS": 170,
    "HILLTOPPERS WC": 10044,
    "HINSDALE RED DEVIL WC": 171,
    "HOMEWOOD-FLOSSMOOR CATS": 10165,
    "HONONEGAH KIDS WC": 173,
    "HOOPESTON AREA WC": 174,
    "HUSKIES WC": 10145,
    "ILLINI BLUFFS WC": 181,
    "JACKSONVILLE WC": 189,
    "JOLIET BOYS CLUB COBRAS": 10047,
    "JR. COUGAR WC": 196,
    "JR. GOLDEN EAGLES": 10050,
    "JR. MAROON WC": 538,
    "JR. PANTHERS WRESTLING": 198,
    "JR. ROCKET WRESTLING": 10052,
    "JR. SENTINELS": 10054,
    "JUNIOR PIRATE WC": 201,
    "KISHWAUKEE WC": 10056,
    "KNIGHTS WRESTLING": 206,
    "L-P CRUNCHING CAVS": 241,
    "LAKE VIEW JR WILDCATS": 10159,
    "LAKELAND PREDATORS": 10057,
    "LAN-OAK P.D. LITTLE REBELS": 10171,
    "LANCER WC": 216,
    "LARKIN JR. ROYALS WC": 10170,
    "LAWRENCE COUNTY WC": 217,
    "LEMONT BEARS WC": 219,
    "LIL' ROUGHNECKS": 10059,
    "LIL' STORM YOUTH WRESTLING": 10060,
    "LINCOLN-WAY WC": 227,
    "LIONS WC": 229,
    "LITTLE BOILER WC": 232,
    "LITTLE CELTIC WC": 233,
    "LITTLE REDBIRD WC": 10065,
    "LOCKPORT GATORS WC": 10068,
    "MACOMB LITTLE BOMBERS": 243,
    "MAINE EAGLES WC": 245,
    "MANTENO JR PANTHERS": 247,
    "MARENGO WC": 248,
    "MARTINEZ FOX VALLEY ELITE WC": 250,
    "MATTOON YOUTH WC": 252,
    "METAMORA KIDS WC": 262,
    "MIDWEST CENTRAL YOUTH": 263,
    "MOLINE WC": 268,
    "MORTON LITTLE MUSTANGS": 271,
    "MT. VERNON LIONS": 275,
    "MT. ZION WC": 276,
    "MURPHYSBORO WRESTLING": 278,
    "MUSTANG WC": 279,
    "NAPERVILLE WC": 281,
    "NORTHSHORE GATORS": 10074,
    "NOTRE DAME": 295,
    "OAK FOREST WARRIORS": 297,
    "OAK LAWN P.D. WILDCATS": 10075,
    "OAKWOOD WC": 299,
    "OPRF LITTLE HUSKIE WC": 235,
    "ORLAND PARK PIONEERS": 306,
    "OSWEGO PANTHERS": 10076,
    "PALATINE PANTHERS WC": 10078,
    "PANTHER CUB WC": 10079,
    "PANTHER WC": 346,
    "PLAINFIELD WC": 326,
    "PLT PROPHETS WC": 10127,
    "POLO WC": 327,
    "PONTIAC PYTHONS": 10082,
    "PONY EXPRESS WC": 10154,
    "RAIDER WC": 10084,
    "RAMS WC": 236,
    "RICH RATTLERS WC": 349,
    "RIVERBEND WC": 354,
    "ROCK ISLAND JR. ROCKS": 361,
    "ROCKFORD WC": 364,
    "ROUND LAKE BAD BOYZ": 10169,
    "ROXANA KIDS WRESTING CLUB": 371,
    "SAUKEE YOUTH WC": 376,
    "SAVANNA REDHAWKS": 10089,
    "SCHAUMBURG JR. SAXONS": 10053,
    "SHARKS WC": 381,
    "SHEPARD WRESTLING": 10168,
    "SJO SPARTAN WC": 402,
    "SOUTHERN ILLINOIS EAGLES": 10092,
    "SPRINGFIELD CAPITALS": 397,
    "ST. CHARLES WC": 400,
    "STERLING NEWMAN JR COMETS": 10098,
    "STILLMAN VALLEY WC": 407,
    "SYCAMORE WC": 418,
    "T-BIRD/RAIDER WRESTLING": 10099,
    "TAYLORVILLE WC": 420,
    "TAZEWELL COUNTY KIDZ WC": 10135,
    "TEAM WEST WOLVES": 10101,
    "TEAM XPRESS": 10167,
    "TIGER WC": 10103,
    "TIGERTOWN TANGLERS": 441,
    "TINLEY PARK BULLDOGS": 443,
    "TOMCAT WC": 448,
    "TRIAD KNIGHTS": 452,
    "UNITY WC": 457,
    "VANDALIA JR WRESTLING": 461,
    "VILLA LOMBARD COUGARS": 10109,
    "VITTUM CATS": 466,
    "WARRENSBURG WC": 468,
    "WAUBONSIE WC": 473,
    "WAUKEGAN TAKEDOWN": 10166,
    "WEST FRANKFORT JR. WC": 478,
    "WESTVILLE YOUTH WC": 482,
    "WHEATON BULLDOGS": 10120,
    "WHEATON FRANKLIN WC": 10113,
    "WHEATON MONROE EAGLES": 10114,
    "WOLFPAK WC": 490,
    "WRESTLING FACTORY": 10115,
    "YORKVILLE WC": 497,
}
NOVICE_EXTRA_TEAM_SCORES: dict[str, float] = {
    "A-J JR. WILDCATS": 0.0,
    "ACES WC": 0.0,
    "BLOOMINGTON RAIDER WC": 0.0,
    "BRONCO WRESTLING": 0.0,
    "CAMP POINT CENTRAL": 0.0,
    "CARLINVILLE KIDS WC": 0.0,
    "CENTRAL WC": 0.0,
    "DURAND-PECATONICA CARNIVORES": 0.0,
    "ELMHURST JR. DUKES": 0.0,
    "GALESBURG JR STREAKS": 0.0,
    "GENERALS": 0.0,
    "GENEVA WC": 0.0,
    "HILLSBORO JR TOPPERS": 0.0,
    "HILLTOPPERS WC": 0.0,
    "ILLINI BLUFFS WC": 0.0,
    "JR. COUGAR WC": 0.0,
    "JR. ROCKET WRESTLING": 0.0,
    "JUNIOR PIRATE WC": 0.0,
    "KISHWAUKEE WC": 0.0,
    "LAKE VIEW JR WILDCATS": 0.0,
    "LANCER WC": 0.0,
    "LARKIN JR. ROYALS WC": 0.0,
    "LIL' ROUGHNECKS": 0.0,
    "MANTENO JR PANTHERS": 0.0,
    "METAMORA KIDS WC": 0.0,
    "NORTHSHORE GATORS": 0.0,
    "NOTRE DAME": 0.0,
    "RIVERBEND WC": 0.0,
    "SHARKS WC": 0.0,
    "SHEPARD WRESTLING": 0.0,
    "TAYLORVILLE WC": 0.0,
    "TAZEWELL COUNTY KIDZ WC": 0.0,
    "TEAM WEST WOLVES": 0.0,
    "WARRENSBURG WC": 0.0,
    "WAUBONSIE WC": 0.0,
    "WESTVILLE YOUTH WC": 0.0,
    "WHEATON BULLDOGS": 0.0,
    ########################################
    "LIONS WC": -1.0,
}
SENIOR_EXTRA_TEAM_SCORES: dict[str, float] = {
    "BENTON JR. WC": 0.0,
    "CROSSFACE WRESTLING": 0.0,
    "DOWNERS GROVE COUGARS": 0.0,
    "FALCON YOUTH WC": 0.0,
    "FORD HEIGHTS FALCONS": 0.0,
    "GLENBARD EAST JR RAMS": 0.0,
    "HOMEWOOD-FLOSSMOOR CATS": 0.0,
    "JR. MAROON WC": 0.0,
    "KISHWAUKEE WC": 0.0,
    "LAKE VIEW JR WILDCATS": 0.0,
    "LAKELAND PREDATORS": 0.0,
    "LANCER WC": 0.0,
    "LITTLE REDBIRD WC": 0.0,
    "MACOMB LITTLE BOMBERS": 0.0,
    "MAINE EAGLES WC": 0.0,
    "MANTENO JR PANTHERS": 0.0,
    "PLT PROPHETS WC": 0.0,
    "RAIDER WC": 0.0,
    "RAMS WC": 0.0,
    "ROCK ISLAND JR. ROCKS": 0.0,
    "ROUND LAKE BAD BOYZ": 0.0,
    "SAUKEE YOUTH WC": 0.0,
    "SAVANNA REDHAWKS": 0.0,
    "TEAM WEST WOLVES": 0.0,
    "TIGERTOWN TANGLERS": 0.0,
    "TRIAD KNIGHTS": 0.0,
    "WHEATON FRANKLIN WC": 0.0,
    ########################################
    "BARTLETT HAWK WC": -1.0,
    "CARBONDALE WC": -1.0,
    "KNIGHTS WRESTLING": -1.0,
    "ST. CHARLES WC": -1.0,
}
BRACKET_ID_MAPPING: dict[tuple[bracket_utils.Division, int], int] = {
    ("novice", 62): 69,
    ("novice", 66): 70,
    ("novice", 70): 71,
    ("novice", 74): 72,
    ("novice", 79): 73,
    ("novice", 84): 74,
    ("novice", 89): 75,
    ("novice", 95): 76,
    ("novice", 101): 77,
    ("novice", 108): 78,
    ("novice", 115): 79,
    ("novice", 122): 80,
    ("novice", 130): 81,
    ("novice", 147): 82,
    ("novice", 166): 83,
    ("novice", 215): 84,
    ("senior", 70): 85,
    ("senior", 74): 86,
    ("senior", 79): 87,
    ("senior", 84): 88,
    ("senior", 89): 89,
    ("senior", 95): 90,
    ("senior", 101): 91,
    ("senior", 108): 92,
    ("senior", 115): 93,
    ("senior", 122): 94,
    ("senior", 130): 95,
    ("senior", 138): 96,
    ("senior", 147): 97,
    ("senior", 156): 98,
    ("senior", 166): 99,
    ("senior", 177): 100,
    ("senior", 189): 101,
    ("senior", 215): 102,
    ("senior", 275): 103,
}


def main():
    with open(HERE / "extracted.2002.json") as file_obj:
        extracted = bracket_utils.ExtractedTournament.model_validate_json(
            file_obj.read()
        )

    weight_classes = extracted.weight_classes
    bracket_utils.validate_acronym_mapping_names(
        weight_classes,
        (
            TEAM_ACRONYM_MAPPING,
            NOVICE_TEAM_ACRONYM_MAPPING,
            SENIOR_TEAM_ACRONYM_MAPPING,
        ),
        (NOVICE_EXTRA_TEAM_SCORES, SENIOR_EXTRA_TEAM_SCORES),
        TEAM_NAME_MAPPING,
    )
    unclassified = sorted(
        name for name, team_id in TEAM_NAME_MAPPING.items() if team_id < 0
    )
    if unclassified:
        raise ValueError("Some teams are unclassified", unclassified)

    bracket_utils.validate_acronym_mappings_divisions(
        weight_classes,
        TEAM_ACRONYM_MAPPING,
        NOVICE_TEAM_ACRONYM_MAPPING,
        SENIOR_TEAM_ACRONYM_MAPPING,
    )

    # NOTE: We just do team score **matching** for validation (but do not use
    #       the outputs).
    bracket_utils.team_scores_for_sql(
        "novice",
        TOURNAMENT_ID,
        extracted,
        TEAM_ACRONYM_MAPPING,
        NOVICE_TEAM_ACRONYM_MAPPING,
        TEAM_NAME_MAPPING,
        NOVICE_EXTRA_TEAM_SCORES,
    )
    bracket_utils.team_scores_for_sql(
        "senior",
        TOURNAMENT_ID,
        extracted,
        TEAM_ACRONYM_MAPPING,
        SENIOR_TEAM_ACRONYM_MAPPING,
        TEAM_NAME_MAPPING,
        SENIOR_EXTRA_TEAM_SCORES,
    )

    start_id = 1795
    mapped_competitors = bracket_utils.get_competitors_for_sql(
        start_id,
        weight_classes,
        TEAM_ACRONYM_MAPPING,
        NOVICE_TEAM_ACRONYM_MAPPING,
        SENIOR_TEAM_ACRONYM_MAPPING,
        TEAM_NAME_MAPPING,
    )

    start_id = 3237
    bracket_utils.get_matches_for_sql(
        start_id,
        weight_classes,
        mapped_competitors.team_competitor_by_info,
        BRACKET_ID_MAPPING,
    )

    start_id = 492
    bracket_utils.tournament_team_sql(
        start_id,
        TOURNAMENT_ID,
        TEAM_ACRONYM_MAPPING,
        NOVICE_TEAM_ACRONYM_MAPPING,
        SENIOR_TEAM_ACRONYM_MAPPING,
        TEAM_NAME_MAPPING,
    )


if __name__ == "__main__":
    main()
